### ISSUE TITLE
Change wording of error message

### ISSUE THREAD

**Issue by jcoffland** [FoldingAtHome/fah-issues#1054]
| Trac | Data |
| --: | :-- |
| Ticket | 1054 |
| Reported by | @bb30994 |
| Status | closed |
| Component | FAHClient |
| Priority | 5 |
| Milestone | v7.3.11 |

FAHClient writes frightening messages to the log when WEBControl terminates.  When FAHControl is terminated, the messages are much more benign.  Let's try to not frighten the novice users when it's a "normal" condition.

'''15:36:20:4:127.0.0.1:New Web connection
15:36:30:WARNING:Exception: 8:127.0.0.1: Send error: 10053: An established connection was aborted by the software in your host machine.'''

**Comment by bb30994** [comment]
Apparently this has gotten un-fixed.  We're getting reports asking what the message means and how they can correct the problem.

**Comment by bb30994** [comment]
00:05:54:WU02:FS01:0x21:Folding@home GPU Core21 Folding@home Core
00:05:54:WU02:FS01:0x21:Version 0.0.18
00:05:59:WU01:FS01:Upload 91.90%
00:06:00:ERROR:Receive error: 10053: An established connection was aborted by the software in your host machine.
00:06:00:WU01:FS01:Upload complete
00:06:00:WU01:FS01:Server responded WORK_ACK (400)
00:06:00:WU01:FS01:Final credit estimate, 14825.00 points
00:06:00:WU01:FS01:Cleaning up
00:06:02:WU02:FS01:0x21:Completed 0 out of 5000000 steps (0%)
00:06:02:WU02:FS01:0x21:Temperature control disabled. Requirements: single Nvidia GPU, tmax must be < 110 and twait >= 900
00:06:16:ERROR:Receive error: 10053: An established connection was aborted by the software in your host machine.
00:06:32:ERROR:Receive error: 10053: An established connection was aborted by the software in your host machine.
00:06:48:ERROR:Receive error: 10053: An established connection was aborted by the software in your host machine.
00:07:04:ERROR:Receive error: 10053: An established connection was aborted by the software in your host machine.
00:07:20:ERROR:Receive error: 10053: An established connection was aborted by the software in your host machine.
00:07:36:ERROR:Receive error: 10053: An established connection was aborted by the software in your host machine.
00:07:52:ERROR:Receive error: 10053: An established connection was aborted by the software in your host machine.
00:08:08:ERROR:Receive error: 10053: An established connection was aborted by the software in your host machine.
00:08:24:ERROR:Receive error: 10053: An established connection was aborted by the software in your host machine.
00:08:24:WU02:FS01:0x21:Completed 50000 out of 5000000 steps (1%)
00:08:40:ERROR:Receive error: 10053: An established connection was aborted by the software in your host machine.
00:08:56:ERROR:Receive error: 10053: An established connection was aborted by the software in your host machine.
00:09:12:ERROR:Receive error: 10053: An established connection was aborted by the software in your host machine.
00:09:28:ERROR:Receive error: 10053: An established connection was aborted by the software in your host machine.
00:09:44:ERROR:Receive error: 10053: An established connection was aborted by the software in your host machine.
00:10:00:ERROR:Receive error: 10053: An established connection was aborted by the software in your host machine.
00:10:16:ERROR:Receive error: 10053: An established connection was aborted by the software in your host machine.
00:10:32:ERROR:Receive error: 10053: An established connection was aborted by the software in your host machine.
00:10:47:WU02:FS01:0x21:Completed 100000 out of 5000000 steps (2%)
00:10:48:ERROR:Receive error: 10053: An established connection was aborted by the software in your host machine.
00:11:04:ERROR:Receive error: 10053: An established connection was aborted by the software in your host machine.

**Comment by bb30994** [comment]
Apparently this has gotten un-fixed -- or there's another cause for the message. We're getting reports asking what the message means and how they can correct the problem.

Please re-open this ticket.
