### ISSUE TITLE
GPU WUs get hung and client does not notice.

### ISSUE THREAD

**Issue by jcoffland** [FoldingAtHome/fah-issues#1121]
| Trac | Data |
| --: | :-- |
| Ticket | 1121 |
| Reported by | @bb30994 |
| Status | closed |
| Component | FAHClient |
| Priority | 5 |

This is probably a duplicate of the original #768 whish NEEDSMOREINFORMATION but I did not get an Unstable Machine error.  My GPU simply quit progressing.  Shouldn't the client be smart enough to recognize the Core is hung?

You did try to fix this once but it can be looked at as a core issue (why doesn't the core have a logitcal timeout?) AND a client issue (why have we reached 99.99% without getting any updates since 40%?)  I suspect that no progress has been made on either front.

The progress bar seen in FAHControl before the client was restarted said 99.99% but I don't have a picture of it.  After restarting, it still shows 99.99% and will until the next checkpoint is reached, when is successfully resets the progress to 38%.  

In the attached screengrab called 99.99%, the previous log shows the GPU quit making progress until about a day ago. (shown on the right). After restarting, the new log and FAHControl showing the (now obsolete) 99.99% are on the left.

Waiting another 15 minutes, you can see in the screengrab called 40% that progress has resumed and FAHControl now knows what's happening.  This also demonstrates that pausing and resuming the FahCore successfully fixes the problem.

I currently have no explanation as to what happend soon after 04:17 on 2014-03-04 but I'll update the ticket if I learn anything more about the GPU status.

Most of FAHClient's/FAHControl's behavior can be explained based on the information it is (not) getting, but there's no "reasonableness" test being applied.

(Getting the FAHCore fixed needs to be a high priority, too.)

**Comment by bb30994** [comment]
I don't remember reading about stall-detection-enabled=true.

Nevertheless, what's wrong with true being the default?
