### ISSUE TITLE
Highlight Matching WU When Slot Is Selected

### ISSUE THREAD

**Issue by jcoffland** [FoldingAtHome/fah-issues#1127]
| Trac | Data |
| --: | :-- |
| Ticket | 1127 |
| Reported by | @PantherX |
| Status | new |
| Component | FAHControl |
| Priority | 5 |

Normally, when you select a Slot, the crossponding WU is automatically highlighted. However, it doesn't happen in these cases:

Case 1 -> A Paused Slot is selected which doesn't have any WU associated with it
Case 2 -> Slots where no WUs have been downloaded
Case 3 -> Changing from the local client to remote client and back to local

In all the above cases, the first WU is selected regardless of what Slot is selected.

It would be great if the associated WU is always highlighted with the Slot. If no WU is present, make sure that nothing is displayed in the Selected Work Unit Panel

**Comment by informatorius** [comment]
https://github.com/FoldingAtHome/fah-control/pull/24

**Comment by jcoffland** [comment]
Fixed thanks to PR #24 from @informatorius.
