### ISSUE TITLE
Windows won't sleep

### ISSUE THREAD

**Issue by kbernhagen** [FoldingAtHome/fah-issues#1175]
There are multiple threads on foldingfoum reporting this, if one feels like searching.

Problem is that the Win API used to disable system sleep is strictly per-thread.

Only one thread (on Windows), preferably the main thread, should be toggling system sleep enabled.

Currently, a random worker thread disables sleep, and a random thread tries to re-enable sleep, which does not work if it is a different thread (likely, as there are 8 worker threads by default). Over time with multiple toggling is that half the worker threads will have sleep disabled, so Win will never sleep.

The quick easy solution is to move sleep toggle code from worker thread loop to a new method, eg ClientApp::updateSystemSleepEnabled(), and call that only from the main thread loop.

For OSX, the CFRunLoop will need to only run for a few seconds at a time to service the update.
In OSXNotifications::update(), instead of CFRunLoopRun(), it could be CFRunLoopRunInMode(kCFRunLoopDefaultMode, 5.0, false).
The main thread loop throttle should also be ifndef APPLE, because the thread sleeps in CFRunLoopRun.

A better solution long term is to have the Win Message loop always active, and post a custom Win message from worker threads that will be serviced by a main message loop callback whenever the sleep setting is actually changed. Currently, there is up to a .25 second delay responding to mouse down for the SysTray icon menu, which can be seen in the menu appearing wherever the mouse pointer is instead of over tray icon.

**Comment by jcoffland** [comment]
Does the above change solve the problem?

**Comment by kbernhagen** [comment]
No. You need the other two changes mentioned in second to last paragraph for it to work on OSX.

Currently, by design, OSXNotifications::update() does not return until a worker thread is exiting and calls CFRunLoopStop. The change would have update() return every 5 seconds.
The main thread loop throttle is not needed nor desirable on OSX.

**Comment by jcoffland** [comment]
Ok, I understand now.  Would you be willing to submit PR for this?

**Comment by kbernhagen** [comment]
Sure.

On Jan 6, 2017, at 2:41 PM, Joseph Coffland <notifications@github.com> wrote:

Ok, I understand now. Would you be willing to submit PR for this?

**Comment by informatorius** [comment]
I don't know if this is the same problem but when I set disable-sleep-when-active=false in Advanced Control slot expert options then send Windows to sleep works again.

**Comment by bb30994** [comment]
Please report this on foldingforum.org, along with your system configuration from the log..
It's not an Issue that I remember hearing about and I don't use that setting.  I think I heard that something in that area had been changed recently, so we need to know which version of FAHClient you're running.


Bruce
-
-
-


---------- Original Message ----------

**Comment by informatorius** [comment]
I meant that thread taking about Windows go to sleep with a GPU slot.
https://foldingforum.org/viewtopic.php?f=96&t=29324&p=290037&hilit=sleep+windows#p290037
If this is not that issue just ignore me.

**Comment by kbernhagen** [comment]
I believe this issue was fixed a long time ago in v7.
