### ISSUE TITLE
0xa7 adds multiple ``-nt #`` arguments when reducing thread count

### ISSUE THREAD

**Issue by bb30994** [FoldingAtHome/fah-issues#1179]
I was successfully running with CPU:6. I wanted to reduce it so I updated the slot and here's what happened: (edited for brevity)

I happened to choose 5 threads which turned out to be something the client prohibits.  I would have been willing to accept CPU:4 instead of CPU:5, but the current software creates an unnecessary error.

When the client adjusts the number of threads specified, DO NOT insert -nt a second time. That' crashes a perfectly good WU.

    21:26:58:WU03:FS00:0xa7:Caught signal SIGINT(2) on PID 20329
    21:26:58:WU03:FS00:0xa7:Exiting, please wait. . .
    21:27:00:WU03:FS00:0xa7:Folding@home Core Shutdown: INTERRUPTED
    21:27:00:WU03:FS00:FahCore returned: INTERRUPTED (102 = 0x66)
    21:27:01:WU03:FS00:Starting
    21:27:01:WARNING:WU03:FS00:Changed SMP threads from 6 to 5 this can cause some work units to fail
    21:27:01:WU03:FS00:Running FahCore: /usr/bin/FAHCoreWrapper /var/lib/fahclient/cores/fahwebx.stanford.edu/cores/Linux/AMD64/beta/Core_a7.fah/FahCore_a7 -dir 03 -suffix 01 -version 704 -lifeline 2516 -checkpoint 15 -np 5
    21:27:01:WU03:FS00:FahCore 0xa7 started
    21:27:01:WU03:FS00:0xa7:************************** Gromacs Folding@home Core ***************************
    21:27:01:WU03:FS00:0xa7:       Type: 0xa7
    21:27:01:WU03:FS00:0xa7:       Args: -dir 03 -suffix 01 -version 704 -lifeline 21098 -checkpoint 15 -np
    21:27:01:WU03:FS00:0xa7:             5
    21:27:01:WU03:FS00:0xa7:     Config: <none>
    21:27:01:WU03:FS00:0xa7:************************************ Build *************************************
    21:27:01:WU03:FS00:0xa7:    Version: 0.0.11
    21:27:01:WU03:FS00:0xa7: Repository: Git
    21:27:01:WU03:FS00:0xa7:   Revision: 957bd90e68d95ddcf1594dc15ff6c64cc4555146
    21:27:01:WU03:FS00:0xa7:     Branch: master
    21:27:01:WU03:FS00:0xa7:       Bits: 64
    21:27:01:WU03:FS00:0xa7:       Mode: Release
    21:27:01:WU03:FS00:0xa7:       SIMD: sse2
    21:27:01:WU03:FS00:0xa7:************************************ System ************************************
    21:27:01:WU03:FS00:0xa7:        CPU: Intel(R) Core(TM) i7 CPU 920 @ 2.67GHz
    21:27:01:WU03:FS00:0xa7:     CPU ID: GenuineIntel Family 6 Model 26 Stepping 4
    21:27:01:WU03:FS00:0xa7:       CPUs: 8
    21:27:01:WU03:FS00:0xa7:     Memory: 5.82GiB
    21:27:01:WU03:FS00:0xa7:Free Memory: 2.79GiB
    21:27:01:WU03:FS00:0xa7:    Threads: POSIX_THREADS
    21:27:01:WU03:FS00:0xa7: OS Version: 3.13
    21:27:01:WU03:FS00:0xa7:        CWD: /var/lib/fahclient/work
    21:27:01:WU03:FS00:0xa7:         OS: Linux 3.13.0-107-generic x86_64
    21:27:01:WU03:FS00:0xa7:    OS Arch: AMD64
    21:27:01:WU03:FS00:0xa7:********************************************************************************
    21:27:01:WU03:FS00:0xa7:Project: 13800 (Run 0, Clone 95, Gen 17)
    21:27:01:WU03:FS00:0xa7:Reducing thread count from 5 to 4 to avoid domain decomposition by a prime number > 3
    21:27:01:WU03:FS00:0xa7:Calling: mdrun -s frame17.tpr -o frame17.trr -x frame17.xtc -cpi state.cpt -cpt 15 -nt 4 -nt 4
    21:27:01:WU03:FS00:0xa7:ERROR:-------------------------------------------------------
    21:27:01:WU03:FS00:0xa7:ERROR:Program GROMACS, VERSION 5.0.4-20160919-669094a-unknown
    21:27:01:WU03:FS00:0xa7:ERROR:Source code file: /host/debian-testing-64bit-core-a7-sse-release/gromacs-core/build/gromacs/src/gromacs/commandline/pargs.cpp, line: 680
    21:27:01:WU03:FS00:0xa7:ERROR:
    21:27:01:WU03:FS00:0xa7:ERROR:Fatal error:
    21:27:01:WU03:FS00:0xa7:ERROR:Double command line argument -nt
    21:27:01:WU03:FS00:0xa7:ERROR:
    21:27:10:WU03:FS00:0xa7:Completed 164470 out of 250000 steps (65%)
    21:27:12:WU03:FS00:0xa7:Folding@home Core Shutdown: BAD_WORK_UNIT
    21:27:12:WARNING:WU03:FS00:FahCore returned: BAD_WORK_UNIT (114 = 0x72)

**Comment by jcoffland** [comment]
That's a bad one.  I'm surprised we didn't find this sooner.  Fortunately it was easy to fix.

**Comment by bb30994** [comment]
There was a previous report asking why their call to FAHCore said -np 4 twice.  Since it didn't cause any problems, I ignored it.  I'll bet Core_a4 allowed repeated parameter strings but the newer GROMACS doesn't.  It's also possible that "... -np4 -np 4..." is accepted whereas "... np5 -np4..." is not.


Bruce
-
-
-


---------- Original Message ----------
