### ISSUE TITLE
Due to limitations in FAHClient's API, log parsing is still employed

### ISSUE THREAD

**Issue by bb30994** [FoldingAtHome/fah-issues#1183]
(An edited quote)

> ... the API is not yet rich enough to replace log parsing as it doesn't deliver all relevant information from a  FAHCore's log. 
>e.g. core version, Bad States or the general reason for failures.

**Comment by jcoffland** [comment]
There will always be additional features that people want so an issue as broad as this could never be closed.  If you have specific feature requests open issues for them.

**Comment by jcoffland** [comment]
There will always be additional features that people want so an issue as broad as this could never be closed.  If you have specific feature requests open issues for them.

**Comment by bb30994** [comment]
Are these not specific enough:
* core version, 
* Bad States  
* the general reason for failures.

**Comment by jcoffland** [comment]
no
