### ISSUE TITLE
Links from FAHControl are broken.

### ISSUE THREAD

**Issue by bb30994** [FoldingAtHome/fah-issues#1189]
When looking at Selected WU in FAHClient,. IP addresses are given for the WS and CS associated with that WU. When clicking on an address (such as 140.163.4.232), a 404 message says The requested URL /logs/140.163.4.232.log.html was not found on this server.

Where have the server logs been hidden? Does this need to be fixed in the client or is this something that needs to be fixed on the server.
![capture0](https://cloud.githubusercontent.com/assets/5483435/24668842/00c41192-191d-11e7-9766-bee7386fad47.PNG)

**Comment by informatorius** [comment]
Looks like the server status page path changed with a subpath pybeta added
http://fah-web.stanford.edu/serverstat.html => http://fah-web.stanford.edu/pybeta/serverstat.html

But the logs subfolder does not have such redirect, so this fails
http://fah-web.stanford.edu/logs/171.67.108.160.log.html

This works:
http://fah-web.stanford.edu/pybeta/logs/171.67.108.160.log.html

Is this a server config issue that /logs/ should redirect to /pybeta/logs/ ?

**Comment by bb30994** [comment]
This is further complicated by the as yet incomplete update to serverstat which is now in a "new" subpath
http://fah-web.stanford.edu/pybeta/new/serverstat.html but I trust this will somehow all be resolved when the newest version is completed.   (It still has a number of incomplete changes.)

**Comment by informatorius** [comment]
Looks like a new homepage is coming https://foldingathome.org/ so this may solve these link issues too

**Comment by jcoffland** [comment]
This problem is eliminated in the upcoming beta v7.4.17.
