### ISSUE TITLE
FAHControl (Windows) memory leak ... grows to fill virtual memory

### ISSUE THREAD

**Issue by bb30994** [FoldingAtHome/fah-issues#1192]
(I though this had been reported but I can't find it.  It's still true in 7.4.16)

**Comment by jcoffland** [comment]
I don't know.  Was there a forum post to go with this?

**Comment by bb30994** [comment]
07:57 AM	69.6
02:00 PM	116.0
03:06 PM	134.6
11:17 PM	268.6
10:33 AM	452.5
12:33 PM	484.6

https://foldingforum.org/viewtopic.php?f=96&t=29242&p=289414#p289414
https://foldingforum.org/viewtopic.php?f=104&t=29601
https://foldingforum.org/viewtopic.php?f=104&t=29899&p=294710#p294701
https://foldingforum.org/viewtopic.php?f=96&t=29921&p=289172#p289172
https://foldingforum.org/viewtopic.php?f=96&t=29242&p=289414#p289414
(and others)

**Comment by informatorius** [comment]
Looks like python has a garbage collector. So maybe it is not a memory leak but the gc just decides to not release the memory yet and a gc.collect() could help to enforce it? Or it can at least show which objects cannot be collected.

**Comment by informatorius** [comment]
This is how I build using Glade Gtk+ 2.24.23 on Windows:
1) Download GladeGtk+2: http://ftp.gnome.org/pub/GNOME/binaries/win32/glade/3.8/
2) unzip to C:\GladeGtk+2
3) open cmd shell
4) set path=C:\GladeGtk+2;%path%
5) cd to folder fah-control
6) python setup.py build
7) gui\FAHControl.exe
=> nearly no mem leak

**Comment by jcoffland** [comment]
Awesome.   That's what I thought was wrong.  I'll build with the newer gtk.  Thanks for figuring this out!

**Comment by informatorius** [comment]
Mem usage on Windows 7 64bit after 12 hours (running 2 GPU slots):

**FahControl build with Glade Gtk+** 
initial mem: 20.740 KB
after 12 hours: 22.776 KB
=> mem leak = 122 KB per month

**FAHClient 7.4.16 beta** 
initial mem: 13.320 KB
after 12 hours:  34.640 KB
=> mem leak = 1279 kb per month

So both leak seem acceptable.

**Comment by jcoffland** [comment]
@informatorius, I installed GladeGtk+2 3.8.5 as you suggested above.  Unfortunately, it had no effect on the FAHControl build.  You mention pygtk 2.24.23.  Where did you find this version?

**Comment by jcoffland** [comment]
I think we are getting hit by this bug: https://stackoverflow.com/questions/16366845/working-around-a-big-memory-leak-in-gtk-when-redrawing-a-label

**Comment by informatorius** [comment]
Inside the C:\Program Files (x86)\Glade Gtk+2\bin folder there is the libgtk-win32-2.0-0.dll 2.24.23 and all other dlls. I see in my tutorial step 6) I made a mistake. It needs to be "python setup.py install" to get the dlls copied to the fah-control folder.

**Comment by informatorius** [comment]
It is solved.
