### ISSUE TITLE
"bad" WU just keeps getting reassigned. (Deserializes forever)

### ISSUE THREAD

**Issue by bb30994** [FoldingAtHome/fah-issues#1199]
I'm not sure if this needs to be fixed in FAHClient or in the FAHCore.  You guys can sort that out.
https://foldingathome.slack.com/messages/C10TQ0PUG/

The WUs keep getting assigned and get "stuck" so the WS cannot get a count of failures so it cannot suspend the WU.  Moreover the Mod transaction that supposedly suspends the WUs doesn't seem to actually suspend that trajectory.

**Comment by bb30994** [comment]
The last message in both of the logs is that it starts deserializing ... and then nothing else.

```
Project: 13207 (Run 45, Clone 0, Gen 120)
Unit: 0x0000004bab436c66579598b865438b01
CPU: 0x00000000000000000000000000000000
Machine: 1
Reading tar file core.xml
Reading tar file integrator.xml
Reading tar file state.xml
Reading tar file system.xml
Digital signatures verified
*************************** Core21 Folding@home Core ***************************
       Type: 33
       Core: Core21
    Website: http://folding.stanford.edu/
  Copyright: (c) 2009-2014 Stanford University
     Author: Yutong Zhao <yutong.zhao@stanford.edu>
       Args: -dir 02 -suffix 01 -version 704 -lifeline 10430 -checkpoint 15
             -gpu-vendor nvidia -gpu 0 -gpu-vendor=nvidia -noclean
     Config: <none>
************************************ Build *************************************
    Version: 0.0.17
       Date: Dec 18 2015
       Time: 22:48:55
 Repository: Git
   Revision: 99a324d4be70589b0a127080bb7fdfe05cc4597f
     Branch: HEAD
   Compiler: GNU 4.4.7 20120313 (Red Hat 4.4.7-16)
    Options: -std=gnu++98 -O3 -funroll-loops -mfpmath=sse -ffast-math
             -fno-unsafe-math-optimizations -msse2
   Platform: linux2 4.1.13-boot2docker
       Bits: 64
       Mode: Release
************************************ System ************************************
        CPU: Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz
     CPU ID: GenuineIntel Family 6 Model 42 Stepping 7
       CPUs: 8
     Memory: 7.77GiB
Free Memory: 2.12GiB
    Threads: POSIX_THREADS
 OS Version: 4.4
Has Battery: false
 On Battery: false
 UTC Offset: -5
        PID: 10434
        CWD: /var/lib/fahclient/work
         OS: Linux 4.4.0-38-generic x86_64
    OS Arch: AMD64
       GPUs: 0
       CUDA: Not detected
     OpenCL: Not detected
********************************************************************************
Folding@home GPU Core21 Folding@home Core
Version 0.0.17
[1] compatible platform(s):
  -- 0 --
  PROFILE = FULL_PROFILE
  VERSION = OpenCL 1.2 CUDA 8.0.0
  NAME = NVIDIA CUDA
  VENDOR = NVIDIA Corporation

(2) device(s) found on platform 0:
  -- 0 --
  DEVICE_NAME = GeForce GTX 750 Ti
  DEVICE_VENDOR = NVIDIA Corporation
  DEVICE_VERSION = OpenCL 1.2 CUDA

  -- 1 --
  DEVICE_NAME = GeForce GTX 750 Ti
  DEVICE_VENDOR = NVIDIA Corporation
  DEVICE_VERSION = OpenCL 1.2 CUDA

[ Entering Init ]
  Launch time: 2016-10-11T11:59:57Z
  Arguments passed: -dir 02 -suffix 01 -version 704 -lifeline 10430 -checkpoint 15 -gpu-vendor nvidia -gpu 0 -gpu-vendor=nvidia -noclean 
  For testState comparison of CPU and GPU, will use:
    forceTolerance: 5 kJ/mol/nm
    energyTolerance: 10 kJ/mol
[ Leaving  Init ]
[ Entering Main ]
  Reading core settings...
  Total number of steps: 2000000
  XTC write frequency: 200000
  Checkpoint write frequency: 200000 (10%)
  Number of frames per WU: 10
[ Initializing Core Contexts ]
  Using platform OpenCL
  Looking for vendor: nvidia...found on platformId 0
  Setting platform precision to single
  Deserializing System...
    Found: 67367 atoms, 9 forces.
  Deserializing State...
```

**Comment by bb30994** [comment]
Why doesn't the script that supposed to stop bad WUs from recirculating work?  Is is possible that when an on-the-fly WU actually expires, that it resumes the trajectory in spite of the script having suspended that trajectory?

**Comment by jcoffland** [comment]
I don't get this issue.  If the WU hangs the client should kill it eventually.  Is this not happening?  If the WU just hangs forever how does it get reassigned?

**Comment by bb30994** [comment]
The issue is that the SERVER keeps resurrecting this WU after it has been distributed to many, many people.  It's a server issue, not a client issue.  

This _might_ be a case where the project owner is issuing some command that restarts all suspended WUs but even that redistribution should be limited by the number of failures exceeding the assigned limit.  It has been discussed in #13200 several times and it seems to be limited to TWO specific WUs.

**Comment by jcoffland** [comment]
So the client hangs?  It should time out eventually and fail the WU.  Does the WS continue to issue the same gen?

**Comment by bb30994** [comment]
Yes.  

The WS's failure counter doesn't work and the Mod transaction that supposedly suspends the thread doesn't work.  The server just keeps sending the same WU out again and again.

**Comment by PantherX** [comment]
Please note that I have split this issue into two components:
Server: https://github.com/FoldingAtHome/fah-issues/issues/1497
FahCore_21: https://github.com/FoldingAtHome/fah-issues/issues/1498

I will close this issue and migrate it to a new label.
