### ISSUE TITLE
FAHCore_a7 will not run in a virtualized environment

### ISSUE THREAD

**Issue by bb30994** [FoldingAtHome/fah-issues#1200]
FAHCore_a7 utilizes the RDTSCP instruction, causing an exception in a virtualized environment.
https://foldingforum.org/viewtopic.php?f=89&t=30053

Is this instruction essential to FAH or can Core_A7 be recompiled with a VM friendly timer to avoid this limitation?   FAHCore_a4 will run virtualized.

**Comment by jcoffland** [comment]
Gromacs requires this instruction so we cannot support running 0xa7 in a VM.

**Comment by jcoffland** [comment]
Should be fixed in v0.0.16.
