### ISSUE TITLE
When setting FahControl slider to medium only one cpu thread is freed

### ISSUE THREAD

**Issue by informatorius** [FoldingAtHome/fah-issues#1203]
When setting FahControl slider to medium, only one cpu thread is freed. On a 16 thread cpu that means on medium the cpu slot is still folding on 15 threads. Expected behavior is 3/4 of threads are used only, that is 12 threads in my example. http://folding.stanford.edu/faqs/fah-v7/v7-introduction/web-control/folding-power-slider/

**Comment by jcoffland** [comment]
This is the intended behavior.  LIGHT mode will use at most half the CPUs.
