### ISSUE TITLE
WARNING:...Size of positions xxxx does not match topology yyyy

### ISSUE THREAD

**Issue by bb30994** [FoldingAtHome/fah-issues#1204]
Repeated warning messages in FAHclient's log. **Size of positions xxxx does not match topology yyyy**

This reportedly does not indicate a problem for the results that are being produced..

Who should be taking some action(s) indicated by the messages? ... or should the message simply be suppressed?

**Comment by jcoffland** [comment]
This is caused by the visualization code.  I need logs with PRCG info to debug this.

**Comment by bb30994** [comment]
```
16:23:52:WU03:FS01:0x21:Project: 9431 (Run 1551, Clone 4, Gen 74)
16:23:52:WU03:FS01:0x21:Unit: 0x00000055ab436c9d586fdd40d9af9ff3
16:23:52:WU03:FS01:0x21:CPU: 0x00000000000000000000000000000000
16:23:52:WU03:FS01:0x21:Folding@home GPU Core21 Folding@home Core
16:23:52:WU03:FS01:0x21:Version 0.0.18
16:24:00:WU03:FS01:0x21:Completed 0 out of 6250000 steps (0%)
16:24:00:WU03:FS01:0x21:Temperature control disabled. Requirements: single Nvidia GPU, tmax must be < 110 and twait >= 900
16:36:10:WARNING:FS01:Size of positions 376 does not match topology 364
16:39:05:WU03:FS01:0x21:Completed 62500 out of 6250000 steps (1%)
16:48:16:WARNING:FS01:Size of positions 376 does not match topology 364
16:54:15:WU03:FS01:0x21:Completed 125000 out of 6250000 steps (2%)
```

**Comment by bb30994** [comment]
`18:15:22:WU02:FS02:0x21:Project: 13208 (Run 12, Clone 2, Gen 154)
18:15:22:WU02:FS02:0x21:Unit: 0x00000050ab436c66579d2e18e81016f8
18:15:22:WU02:FS02:0x21:Folding@home GPU Core21 Folding@home Core
18:15:22:WU02:FS02:0x21:Version 0.0.18
18:15:22:WU02:FS02:0x21:  Found a checkpoint file
18:15:23:WARNING:FS02:Size of positions 27474 does not match topology 19
18:15:23:WARNING:FS02:Size of positions 27474 does not match topology 19
18:17:33:WU02:FS02:0x21:Completed 400000 out of 2000000 steps (20%)
18:25:55:WU02:FS02:0x21:Completed 420000 out of 2000000 steps (21%)
18:34:13:WU02:FS02:0x21:Completed 440000 out of 2000000 steps (22%)
18:42:31:WU02:FS02:0x21:Completed 460000 out of 2000000 steps (23%)
18:50:49:WU02:FS02:0x21:Completed 480000 out of 2000000 steps (24%)
18:59:05:WU02:FS02:0x21:Completed 500000 out of 2000000 steps (25%)
19:07:23:WU02:FS02:0x21:Completed 520000 out of 2000000 steps (26%)
19:15:39:WU02:FS02:0x21:Completed 540000 out of 2000000 steps (27%)
19:23:57:WU02:FS02:0x21:Completed 560000 out of 2000000 steps (28%)
19:32:13:WU02:FS02:0x21:Completed 580000 out of 2000000 steps (29%)
19:40:31:WU02:FS02:0x21:Completed 600000 out of 2000000 steps (30%)
19:40:47:WARNING:FS02:Size of positions 27474 does not match topology 19
19:48:59:WU02:FS02:0x21:Completed 620000 out of 2000000 steps (31%)`

**Comment by jcoffland** [comment]
This warning is not critical.  I believe it is caused by 0x21 not filtering out the waters correctly.  What it means is that the topology (list of atomic bonds) does not match the positions (list of atom positions).  A difference such as that between 376 and 364 is not a huge deal.  Likely the visualization will still be intact.  27,474 positions with a topology size of 19 is a problem for the visualization.  There will be a lot of unconnected atoms floating around.

The problem here is in 0x21's code for outputting the visualization data.

**Comment by bb30994** [comment]
I believe we have an update to FAHCore_21 that fixes this problem.  It has been "beta" for a long, long time.  What does it take to get that version released?

**Comment by jcoffland** [comment]
Refer this to @jchodera  and @peastman.

**Comment by ProDigit** [comment]
Same error here:
`01:11:26:WARNING:FS00:Size of positions 5845 does not match topology 5844
01:18:11:WARNING:FS00:Size of positions 5845 does not match topology 5844
01:24:55:WARNING:FS00:Size of positions 5845 does not match topology 5844
01:31:40:WARNING:FS00:Size of positions 5845 does not match topology 5844
01:38:25:WARNING:FS00:Size of positions 5845 does not match topology 5844
01:45:10:WARNING:FS00:Size of positions 5845 does not match topology 5844
01:51:54:WARNING:FS00:Size of positions 5845 does not match topology 5844
01:58:39:WARNING:FS00:Size of positions 5845 does not match topology 5844
02:05:24:WARNING:FS00:Size of positions 5845 does not match topology 5844
02:12:09:WARNING:FS00:Size of positions 5845 does not match topology 5844
02:18:54:WARNING:FS00:Size of positions 5845 does not match topology 5844
02:25:39:WARNING:FS00:Size of positions 5845 does not match topology 5844
02:32:24:WARNING:FS00:Size of positions 5845 does not match topology 5844
02:39:09:WARNING:FS00:Size of positions 5845 does not match topology 5844
02:45:54:WARNING:FS00:Size of positions 5845 does not match topology 5844
02:52:39:WARNING:FS00:Size of positions 5845 does not match topology 5844
02:59:24:WARNING:FS00:Size of positions 5845 does not match topology 5844
03:06:09:WARNING:FS00:Size of positions 5845 does not match topology 5844
03:19:42:WARNING:FS00:Size of positions 5845 does not match topology 5844
03:26:27:WARNING:FS00:Size of positions 5845 does not match topology 5844
03:33:11:WARNING:FS00:Size of positions 5845 does not match topology 5844
03:39:55:WARNING:FS00:Size of positions 5845 does not match topology 5844
03:46:40:WARNING:FS00:Size of positions 5845 does not match topology 5844
03:53:24:WARNING:FS00:Size of positions 5845 does not match topology 5844
04:00:08:WARNING:FS00:Size of positions 5845 does not match topology 5844
04:06:53:WARNING:FS00:Size of positions 5845 does not match topology 5844
04:13:37:WARNING:FS00:Size of positions 5845 does not match topology 5844
04:20:22:WARNING:FS00:Size of positions 5845 does not match topology 5844
04:27:06:WARNING:FS00:Size of positions 5845 does not match topology 5844
04:33:51:WARNING:FS00:Size of positions 5845 does not match topology 5844
04:40:35:WARNING:FS00:Size of positions 5845 does not match topology 5844
04:47:20:WARNING:FS00:Size of positions 5845 does not match topology 5844
`

**Comment by ProDigit** [comment]
This is the first error you'll notice when you're overclocking close to the limit. 
Once you overclock GPU more than this, errors occur, and WU batches fail.
Dial down a few Mhz on the overclock.

**Comment by bb30994** [comment]
No, I do not beleive this is an overclocking error.  It's actually related to the bond count of atoms with an unexpected characteristic as Joseph has suggested.

I seem to remember that it has been fixed in a later version of the FAHCore.

**Comment by ProDigit** [comment]
The issue is repeatable.
And yes, bonds give errors due to erroneous calculations due to overclocking.
RTX cards overclocked past ~ 100Mhz will show these errors. Below the threshold will not show the error anymore.

**Comment by RealLaugh** [comment]
@ProDigit I am using an RTX card with power limit dialed down to 77% and temp limit at 68 C so I am clocking around 1785MHz and seeing WARNING:FS01:Size of positions 2073 does not match topology 2067 for project 11719.

In general I am trying to debug why this card BSODs at the moment after around 1h-2h of folding on stock setteings (I'm not looking to OC, just want this card for F@H so accuracy is way more important).

Do you think that I should also underclock the core clock manually and see if the errors go away? The errors don't bother me, just interested.

**Comment by ProDigit** [comment]
It may have been coincidence, that for days in a row, I get no topology issues, but the moment I do overclock, I get them again...
I've read about early RTX cards, mainly 2080, with bad vram. Could also be overclocked too high at one point on the vram and damaged.

**Comment by pcowley** [comment]
This is the first time I have seen this error but it is obviously still there. Is there an updated core_21 I should download?

 Here is the log:
run:0 clone:2666 gen:141 core:0x21 unit:0x000000c28ca304e75bbce9dfb2324d6c
19:38:21:WU01:FS00:Uploading 7.02MiB to 140.163.4.231
19:38:21:WU01:FS00:Connecting to 140.163.4.231:8080
19:38:21:WU00:FS00:Starting
19:38:21:WU00:FS00:Running FahCore: /usr/bin/FAHCoreWrapper /var/lib/fahclient/cores/cores.foldingathome.org/Linux/AMD64/NVIDIA/Fermi/Core_21.fah/FahCore_21 -dir 00 -suffix 01 -version 705 -lifeline 2209 -checkpoint 15 -gpu-vendor nvidia -opencl-device 0 -cuda-device 0 -gpu 0
19:38:21:WU00:FS00:Started FahCore on PID 5564
19:38:21:WU00:FS00:Core PID:5568
19:38:21:WU00:FS00:FahCore 0x21 started
19:38:21:WU00:FS00:0x21:*********************** Log Started 2019-05-19T19:38:21Z ***********************
19:38:21:WU00:FS00:0x21:Project: 14179 (Run 36, Clone 7, Gen 33)
19:38:21:WU00:FS00:0x21:Unit: 0x0000002c0002894c5cb38745f22b5fa6
19:38:21:WU00:FS00:0x21:CPU: 0x00000000000000000000000000000000
19:38:21:WU00:FS00:0x21:Machine: 0
19:38:21:WU00:FS00:0x21:Reading tar file core.xml
19:38:21:WU00:FS00:0x21:Reading tar file integrator.xml
19:38:21:WU00:FS00:0x21:Reading tar file state.xml
19:38:21:WU00:FS00:0x21:Reading tar file system.xml
19:38:21:WU00:FS00:0x21:Digital signatures verified
19:38:21:WU00:FS00:0x21:Folding@home GPU Core21 Folding@home Core
19:38:21:WU00:FS00:0x21:Version 0.0.18
19:38:23:WU00:FS00:0x21:Completed 0 out of 25000000 steps (0%)
19:38:23:WU00:FS00:0x21:Temperature control disabled. Requirements: single Nvidia GPU, tmax must be < 110 and twait >= 900
19:38:27:WU01:FS00:Upload 26.71%
19:38:33:WU01:FS00:Upload 93.48%
19:38:35:WU01:FS00:Upload complete
19:38:35:WU01:FS00:Server responded WORK_ACK (400)
19:38:35:WU01:FS00:Final credit estimate, 35298.00 points
19:38:35:WU01:FS00:Cleaning up
19:40:43:WU00:FS00:0x21:Completed 250000 out of 25000000 steps (1%)
19:40:48:WARNING:FS00:Size of positions 294 does not match topology 24
19:43:04:WU00:FS00:0x21:Completed 500000 out of 25000000 steps (2%)
19:43:09:WARNING:FS00:Size of positions 294 does not match topology 24
19:45:24:WU00:FS00:0x21:Completed 750000 out of 25000000 steps (3%)
19:45:29:WARNING:FS00:Size of positions 294 does not match topology 24
19:47:42:WU00:FS00:0x21:Completed 1000000 out of 25000000 steps (4%)
19:47:48:WARNING:FS00:Size of positions 294 does not match topology 24
19:50:01:WU00:FS00:0x21:Completed 1250000 out of 25000000 steps (5%)
19:50:06:WARNING:FS00:Size of positions 294 does not match topology 24
19:52:20:WU00:FS00:0x21:Completed 1500000 out of 25000000 steps (6%)
19:52:25:WARNING:FS00:Size of positions 294 does not match topology 24
19:54:38:WU00:FS00:0x21:Completed 1750000 out of 25000000 steps (7%)
19:54:44:WARNING:FS00:Size of positions 294 does not match topology 24
19:56:57:WU00:FS00:0x21:Completed 2000000 out of 25000000 steps (8%)
19:57:02:WARNING:FS00:Size of positions 294 does not match topology 24
19:59:17:WU00:FS00:0x21:Completed 2250000 out of 25000000 steps (9%)
19:59:22:WARNING:FS00:Size of positions 294 does not match topology 24
20:01:37:WU00:FS00:0x21:Completed 2500000 out of 25000000 steps (10%)
20:01:42:WARNING:FS00:Size of positions 294 does not match topology 24
20:03:55:WU00:FS00:0x21:Completed 2750000 out of 25000000 steps (11%)
20:04:01:WARNING:FS00:Size of positions 294 does not match topology 24
20:06:14:WU00:FS00:0x21:Completed 3000000 out of 25000000 steps (12%)
20:06:19:WARNING:FS00:Size of positions 294 does not match topology 24
20:08:32:WU00:FS00:0x21:Completed 3250000 out of 25000000 steps (13%)
20:08:38:WARNING:FS00:Size of positions 294 does not match topology 24
20:10:51:WU00:FS00:0x21:Completed 3500000 out of 25000000 steps (14%)
20:10:56:WARNING:FS00:Size of positions 294 does not match topology 24
20:13:09:WU00:FS00:0x21:Completed 3750000 out of 25000000 steps (15%)
20:13:14:WARNING:FS00:Size of positions 294 does not match topology 24
20:15:27:WU00:FS00:0x21:Completed 4000000 out of 25000000 steps (16%)
20:15:32:WARNING:FS00:Size of positions 294 does not match topology 24
20:17:45:WU00:FS00:0x21:Completed 4250000 out of 25000000 steps (17%)
20:17:50:WARNING:FS00:Size of positions 294 does not match topology 24
20:20:03:WU00:FS00:0x21:Completed 4500000 out of 25000000 steps (18%)
20:20:08:WARNING:FS00:Size of positions 294 does not match topology 24
20:22:22:WU00:FS00:0x21:Completed 4750000 out of 25000000 steps (19%)
20:22:27:WARNING:FS00:Size of positions 294 does not match topology 24
20:24:40:WU00:FS00:0x21:Completed 5000000 out of 25000000 steps (20%)
20:24:45:WARNING:FS00:Size of positions 294 does not match topology 24
20:26:58:WU00:FS00:0x21:Completed 5250000 out of 25000000 steps (21%)
20:27:04:WARNING:FS00:Size of positions 294 does not match topology 24
20:29:18:WU00:FS00:0x21:Completed 5500000 out of 25000000 steps (22%)

Cheers
Pete

**Comment by bb30994** [comment]
It's not a bad WU.  The message only appears in a few projects. The error, itself, does not alter the results and should be ignored.

I have seen it disappear due to some change in the project.  It can also be ignored by a change to the code in FAHClient that supports FAHViewer.  I suspect that change will be incorporated in the next revision to FAHClient, but many such updates generally wait until there's a more serious issue that needs to be fixed.

**Comment by pcowley** [comment]
Hi Bruce

Thanks for that.

It did just say it was a warning. Shortly after I posted the results the
client actually gave up, called it bad and pulled down a new work unit and
that started fine. So there is obviously some mechanism already in the
client to handle this situation to a degree.

Cheers
Pete

**Comment by bb30994** [comment]
FAHCore_21, V0.0.20 fixed this issue and is currently being distributed to all Windows clients.  For some reason, V0.0.18 is still being downloaded for Linux clients running Advanced or FAH.

**Comment by pcowley** [comment]
Hi Bruce

Thanks for that.  I was wondering what was happening.
The issue only happens infrequently so not a big deal.

Having said that, I'm sure the later version will eventually be made
available for Linux clients at some stage and I assume when it is it will
download automatically (or am I being overly optimistic?)

Thanks for you quick replies.

Cheers
Pete

**Comment by sombraguerrero** [comment]
Am I misunderstanding something here? I am running the Windows client with no slot configs right now at all, and all my WUs have still been coming back with version .18 all weekend long. Is the rollout still in progress?

**Comment by jchodera** [comment]
> FAHCore_21, V0.0.20 fixed this issue and is currently being distributed to all Windows clients. For some reason, V0.0.18 is still being downloaded for Linux clients running Advanced or FAH.

That's very odd. We're looking into this.

**Comment by jchodera** [comment]
@bb30994: It looks like we never fully rolled out 0.0.20 because we didn't have enough reports that it had fixed this issue. The 0.0.20 test builds are still available here:

http://www.choderalab.org/core21

If you could give these a try and see if it fixes your issue, that would be awesome. If so, @jcoffland can roll these out to full FAH.

**Comment by jcoffland** [comment]
So it looks like 0.0.20 was rolled out to beta but not public release.  I've rolled it out to public release.

**Comment by bb30994** [comment]
Thanks


Bruce
-
-
-


---------- Original Message ----------

**Comment by pcowley** [comment]
Hi everyone

After my current work unit was completed, I deleted core 0.0.18 and
restarted the Linux client - it DID download core 0.0.20 this time!  Great
job. Thanks!
I will keep you posted if I see any more position warning messages.

Of note though with core 0.0.18 was that even though the positions was a
warning message, the client gave up after 25 warnings in a row and called
the work unit BAD.  So that might also be something to consider for other
possible warning messages.

Cheers
Pete

**Comment by bb30994** [comment]
The automatic distribution of v0.0.20 will happen whenever individual Donors receive a WU from a project that REQUIRES 0.0.20.  Inasmuch as V0.0.18 gives correct answers, there are no project that have been updated to require 0.0.20, and that couldn't happen until the Linus version was available for download.  New clients will download the latest version, and manually deleting the old version will accomplish the same thing.  That's a bit of a nuisance that you shouldn't have to do, but right now that's the only option until a suitable project is available.

Project 14179 gave you the messages?  That's a good candidate to be updated to require 0.0.20.

**Comment by jcoffland** [comment]
I emailed all of the project managers asking them to update the core version requirement on their projects.
