### ISSUE TITLE
When there's a port 80 timeout problem, the client does not attempt to connect to the CS.

### ISSUE THREAD

**Issue by bb30994** [FoldingAtHome/fah-issues#1210]
> 15:02:44:WU00:FS00:Uploading 4.26MiB to 155.247.166.219
> 15:02:44:WU00:FS00:Connecting to 155.247.166.219:8080
> 15:02:46:WARNING:WU00:FS00:WorkServer connection failed on port 8080 trying 80
> 15:02:46:WU00:FS00:Connecting to 155.247.166.219:80
> 15:03:07:WARNING:WU00:FS00:Exception: Failed to send results to work server: Failed to connect to 155.247.166.219:80: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

This is NOT followed by an attempt to connect to the CS 155.247.166.220:8080

**Comment by sombraguerrero** [comment]
The work server in question reports version 9.1.0 when accessed through TCP8080. As of posting this, it is still timing out on TCP80.

**Comment by jcoffland** [comment]
Most likely the CS was not enabled for this WU.  This can happen if the client gets assigned a WU before the WS has contacted the CS.  Reopen this if this continues to occur.
