### ISSUE TITLE
Windows installer causes a corrupt installation unless "just for me" is selected.

### ISSUE THREAD

**Issue by bb30994** [FoldingAtHome/fah-issues#1211]
FAH uses two directories: One where work files (etc.) are R/W and one where *exe are found.  When FAHClient and FAHControl (etc.) are not in sync,, storage of WUs, config, etc. cause various problems.  The startup scripts must properly set the local directory to a suitable R/W location, no matter what is in effect when the script is invoked.

This also means that the script(s) MUST be used.  e.g.-starting by double clicking FAHClient or FAHControl leads to unpredictable results.  This also can be caused if the user selects an alternate directory.

When installing "for everyone" failures will happen when started by another user.

Other examples can be found here: https://foldingforum.org/viewtopic.php?f=61&t=30181

**Comment by jcoffland** [comment]
Option removed in beta v7.4.18.
