### ISSUE TITLE
OMP_NUM_THREADS (AVX)

### ISSUE THREAD

**Issue by bb30994** [FoldingAtHome/fah-issues#1213]
This is just a reminder that we need a fix either in FAHCore_a7 or elsewhere so that AVX knows how many threads to use.

The Windows FAHCore_a7 crashes with
0xC0000028 STATUS_BAD_STACK = An invalid or unaligned stack was encountered during an unwind operation.

18:45:00:WU00:FS00:0xa7:ERROR:Fatal error:
18:45:00:WU00:FS00:0xa7:ERROR:More than 1 OpenMP thread requested, but Gromacs was compiled without OpenMP support

Faulting application name: FahCore_a7.exe, version: 0.0.0.0, time stamp: 0x57e1e600
Faulting module name: ntdll.dll, version: 10.0.15063.608, time stamp: 0x8274fd8b
Exception code: 0xc0000028
Fault offset: 0x0000000000004b90
Faulting process id: 0x4834
Faulting application start time: 0x01d342a962ca70b6
Faulting application path: C:\ProgramData\FAHClient\cores\fahwebx.stanford.ed u\cores\Win32\AMD64\AVX\Core_a7.fah\FahCore_a7.exe
Faulting module path: C:\WINDOWS\SYSTEM32\ntdll.dll

See also https://foldingforum.org/viewtopic.php?p=289619
and https://foldingforum.org/viewtopic.php?f=96&t=30339

**Comment by jcoffland** [comment]
I fixed this once but the fix caused a more serious problem.  I've got a new solution for Gromacs core v0.0.15.
