### ISSUE TITLE
same enumeration problem as #1161

### ISSUE THREAD

**Issue by nickgabby** [FoldingAtHome/fah-issues#1226]
Hi

I have been folding for some years now as Montague-Cripps. I am running into the same enumeration problem as in fah-issue #1161.

I have two nvidia GTX 1080TI cards in the same machine idling at the moment because they have recently started conflicting.  The log for one slot shows:

> *********************** Log Started 2018-04-28T21:24:48Z ***********************
21:25:00:WU01:FS01:Connecting to 171.67.108.45:8080
21:25:00:WU01:FS01:Connecting to 171.67.108.45:80
21:25:01:WU01:FS01:Assigned to work server 140.163.4.231
21:25:01:WU01:FS01:Requesting new work unit for slot 01: READY gpu:0:GP102 [GeForce GTX 1080 Ti] 11380 from 140.163.4.231
21:25:01:WU01:FS01:Connecting to 140.163.4.231:8080
21:25:02:WU01:FS01:Downloading 16.51MiB
21:25:08:WU01:FS01:Download 5.30%
21:25:14:WU01:FS01:Download 12.11%
21:25:20:WU01:FS01:Download 21.96%
21:25:26:WU01:FS01:Download 51.86%
21:25:32:WU01:FS01:Download 80.64%
21:25:35:WU01:FS01:Download complete
21:25:35:WU01:FS01:Received Unit: id:01 state:DOWNLOAD error:NO_ERROR project:11713 run:25 clone:207 gen:15 core:0x21 unit:0x000000148ca304e75adf7e2c5ac19fe1
21:25:40:WU01:FS01:Starting
21:25:40:ERROR:WU01:FS01:Failed to start core: OpenCL device matching slot 1 not found, try setting 'opencl-index' manually
21:25:40:WU01:FS01:Starting
21:25:40:ERROR:WU01:FS01:Failed to start core: OpenCL device matching slot 1 not found, try setting 'opencl-index' manually
21:26:41:WU01:FS01:Starting
21:26:41:ERROR:WU01:FS01:Failed to start core: OpenCL device matching slot 1 not found, try setting 'opencl-index' manually
21:35:04:WU01:FS01:Starting
21:35:04:ERROR:WU01:FS01:Failed to start core: OpenCL device matching slot 1 not found, try setting 'opencl-index' manually
21:36:41:WU01:FS01:Starting
21:36:41:ERROR:WU01:FS01:Failed to start core: OpenCL device matching slot 1 not found, try setting 'opencl-index' manually
21:39:18:WU01:FS01:Starting
21:39:18:ERROR:WU01:FS01:Failed to start core: OpenCL device matching slot 1 not found, try setting 'opencl-index' manually
21:39:18:WU01:FS01:Sending unit results: id:01 state:SEND error:FAILED project:11713 run:25 clone:207 gen:15 core:0x21 unit:0x000000148ca304e75adf7e2c5ac19fe1
21:39:18:WU01:FS01:Connecting to 140.163.4.231:8080
21:39:19:WU01:FS01:Server responded WORK_ACK (400)
21:39:19:WU01:FS01:Cleaning up
21:48:56:WU01:FS02:Connecting to 171.67.108.45:80
21:48:57:WU01:FS02:Assigned to work server 155.247.166.219
21:48:57:WU01:FS02:Requesting new work unit for slot 02: READY gpu:1:GP102 [GeForce GTX 1080 Ti] 11380 from 155.247.166.219
21:48:57:WU01:FS02:Connecting to 155.247.166.219:8080
21:48:59:WU01:FS02:Downloading 903.88KiB
21:49:03:WU01:FS02:Download complete
21:49:03:WU01:FS02:Received Unit: id:01 state:DOWNLOAD error:NO_ERROR project:13782 run:219 clone:2 gen:170 core:0x21 unit:0x000000b90002894b5a78cee907b19146
21:49:03:WU01:FS02:Starting
21:49:03:ERROR:WU01:FS02:Failed to start core: OpenCL device matching slot 2 not found, try setting 'opencl-index' manually
21:49:03:WU01:FS02:Starting
21:49:03:ERROR:WU01:FS02:Failed to start core: OpenCL device matching slot 2 not found, try setting 'opencl-index' manually
21:50:03:WU01:FS02:Starting
21:50:03:ERROR:WU01:FS02:Failed to start core: OpenCL device matching slot 2 not found, try setting 'opencl-index' manually
21:51:41:WU01:FS02:Starting
21:51:41:ERROR:WU01:FS02:Failed to start core: OpenCL device matching slot 2 not found, try setting 'opencl-index' manually
21:54:18:WU01:FS02:Starting
21:54:18:ERROR:WU01:FS02:Failed to start core: OpenCL device matching slot 2 not found, try setting 'opencl-index' manually
21:58:32:WU01:FS02:Starting
21:58:32:ERROR:WU01:FS02:Failed to start core: OpenCL device matching slot 2 not found, try setting 'opencl-index' manually
21:58:32:WU01:FS02:Sending unit results: id:01 state:SEND error:FAILED project:13782 run:219 clone:2 gen:170 core:0x21 unit:0x000000b90002894b5a78cee907b19146
21:58:32:WU01:FS02:Connecting to 155.247.166.219:8080
21:58:33:WU01:FS02:Server responded WORK_ACK (400)
21:58:33:WU01:FS02:Cleaning up

The same goes for the other slot:

> *********************** Log Started 2018-04-28T21:24:48Z ***********************
21:39:19:WU03:FS01:Connecting to 171.67.108.45:80
21:39:20:WU03:FS01:Assigned to work server 140.163.4.231
21:39:20:WU03:FS01:Requesting new work unit for slot 01: READY gpu:0:GP102 [GeForce GTX 1080 Ti] 11380 from 140.163.4.231
21:39:20:WU03:FS01:Connecting to 140.163.4.231:8080
21:39:21:WU03:FS01:Downloading 16.52MiB
21:39:27:WU03:FS01:Download 17.03%
21:39:33:WU03:FS01:Download 42.76%
21:39:39:WU03:FS01:Download 99.89%
21:39:40:WU03:FS01:Download complete
21:39:40:WU03:FS01:Received Unit: id:03 state:DOWNLOAD error:NO_ERROR project:11713 run:26 clone:168 gen:19 core:0x21 unit:0x000000158ca304e75adf7ea2add466b1
21:39:40:WU03:FS01:Starting
21:39:40:ERROR:WU03:FS01:Failed to start core: OpenCL device matching slot 1 not found, try setting 'opencl-index' manually
21:39:40:WU03:FS01:Starting
21:39:40:ERROR:WU03:FS01:Failed to start core: OpenCL device matching slot 1 not found, try setting 'opencl-index' manually
21:40:40:WU03:FS01:Starting
21:40:40:ERROR:WU03:FS01:Failed to start core: OpenCL device matching slot 1 not found, try setting 'opencl-index' manually
21:42:18:WU03:FS01:Starting
21:42:18:ERROR:WU03:FS01:Failed to start core: OpenCL device matching slot 1 not found, try setting 'opencl-index' manually
21:44:55:WU03:FS01:Starting
21:44:55:ERROR:WU03:FS01:Failed to start core: OpenCL device matching slot 1 not found, try setting 'opencl-index' manually
21:49:09:WU03:FS01:Starting
21:49:09:ERROR:WU03:FS01:Failed to start core: OpenCL device matching slot 1 not found, try setting 'opencl-index' manually
21:49:09:WU03:FS01:Sending unit results: id:03 state:SEND error:FAILED project:11713 run:26 clone:168 gen:19 core:0x21 unit:0x000000158ca304e75adf7ea2add466b1
21:49:09:WU03:FS01:Connecting to 140.163.4.231:8080
21:49:10:WU03:FS01:Server responded WORK_ACK (400)
21:49:10:WU03:FS01:Cleaning up
21:58:32:WU03:FS02:Connecting to 171.67.108.45:80
21:58:33:WU03:FS02:Assigned to work server 155.247.166.219
21:58:33:WU03:FS02:Requesting new work unit for slot 02: READY gpu:1:GP102 [GeForce GTX 1080 Ti] 11380 from 155.247.166.219
21:58:33:WU03:FS02:Connecting to 155.247.166.219:8080
21:58:35:WU03:FS02:Downloading 903.82KiB
21:58:38:WU03:FS02:Download complete
21:58:38:WU03:FS02:Received Unit: id:03 state:DOWNLOAD error:NO_ERROR project:13783 run:907 clone:1 gen:188 core:0x21 unit:0x000000cf0002894b5a833ff30cf3fe9d
21:58:38:WU03:FS02:Starting
21:58:38:ERROR:WU03:FS02:Failed to start core: OpenCL device matching slot 2 not found, try setting 'opencl-index' manually
21:58:39:WU03:FS02:Starting
21:58:39:ERROR:WU03:FS02:Failed to start core: OpenCL device matching slot 2 not found, try setting 'opencl-index' manually
21:59:39:WU03:FS02:Starting
21:59:39:ERROR:WU03:FS02:Failed to start core: OpenCL device matching slot 2 not found, try setting 'opencl-index' manually
22:01:16:WU03:FS02:Starting
22:01:16:ERROR:WU03:FS02:Failed to start core: OpenCL device matching slot 2 not found, try setting 'opencl-index' manually

The system info is as follows:

> *********************** Log Started 2018-04-28T21:24:48Z ***********************
21:24:48:************************* Folding@home Client *************************
21:24:48:        Website: http://folding.stanford.edu/
21:24:48:      Copyright: (c) 2009-2016 Stanford University
21:24:48:         Author: Joseph Coffland <joseph@cauldrondevelopment.com>
21:24:48:           Args: --open-web-control
21:24:48:         Config: <none>
21:24:48:******************************** Build ********************************
21:24:48:        Version: 7.4.16
21:24:48:           Date: Jan 6 2017
21:24:48:           Time: 00:25:14
21:24:48:     Repository: Git
21:24:48:       Revision: a9e9e27dc2ee6ff01398c439677bc27f6cb74032
21:24:48:         Branch: master
21:24:48:       Compiler: Visual C++ 2008
21:24:48:        Options: /TP /nologo /EHa /wd4297 /wd4103 /Ox -arch:SSE /MT
21:24:48:       Platform: win32 10
21:24:48:           Bits: 32
21:24:48:           Mode: Release
21:24:48:******************************* System ********************************
21:24:48:            CPU: Intel(R) Core(TM) i5-8600K CPU @ 3.60GHz
21:24:48:         CPU ID: GenuineIntel Family 6 Model 158 Stepping 10
21:24:48:           CPUs: 6
21:24:48:         Memory: 15.88GiB
21:24:48:    Free Memory: 11.30GiB
21:24:48:        Threads: WINDOWS_THREADS
21:24:48:     OS Version: 6.2
21:24:48:    Has Battery: false
21:24:48:     On Battery: false
21:24:48:     UTC Offset: 12
21:24:48:            PID: 15676
21:24:48:            CWD: C:\Users\nickm\AppData\Roaming\FAHClient
21:24:48:             OS: Windows 10 Pro
21:24:48:        OS Arch: AMD64
21:24:48:           GPUs: 0
21:24:48:  CUDA Device 0: Platform:0 Device:0 Bus:1 Slot:0 Compute:6.1 Driver:9.2
21:24:48:  CUDA Device 1: Platform:0 Device:1 Bus:2 Slot:0 Compute:6.1 Driver:9.2
21:24:48:OpenCL Device 0: Platform:0 Device:0 Bus:NA Slot:NA Compute:2.1 Driver:23.20
21:24:48:  Win32 Service: false
21:24:48:***********************************************************************
21:24:48:<config>
21:24:48:  
21:24:48:</config>
21:24:48:Connecting to assign-GPU.stanford.edu:80
21:24:49:Updated GPUs.txt
21:24:49:Read GPUs.txt
21:24:49:Trying to access database...
21:24:49:Successfully acquired database lock
21:24:49:Enabled folding slot 00: PAUSED cpu:3 (not configured)
21:24:49:Enabled folding slot 01: PAUSED gpu:0:GP102 [GeForce GTX 1080 Ti] 11380 (not configured)
21:24:49:Enabled folding slot 02: PAUSED gpu:1:GP102 [GeForce GTX 1080 Ti] 11380 (not configured)
21:24:59:Set client configured
21:24:59:WU00:FS00:Connecting to 171.67.108.45:8080
21:25:00:WU01:FS01:Connecting to 171.67.108.45:8080
21:25:00:WU02:FS02:Connecting to 171.67.108.45:8080
21:25:00:WU00:FS00:Connecting to 171.67.108.45:8080
21:25:00:WU01:FS01:Connecting to 171.67.108.45:80
21:25:00:WU02:FS02:Connecting to 171.67.108.45:80
21:25:01:WU00:FS00:Assigned to work server 171.67.108.158
21:25:01:WU00:FS00:Requesting new work unit for slot 00: READY cpu:4 from 171.67.108.158
21:25:01:WU00:FS00:Connecting to 171.67.108.158:8080
21:25:01:WU01:FS01:Assigned to work server 140.163.4.231
21:25:01:WU01:FS01:Requesting new work unit for slot 01: READY gpu:0:GP102 [GeForce GTX 1080 Ti] 11380 from 140.163.4.231
21:25:01:WU01:FS01:Connecting to 140.163.4.231:8080
21:25:01:WU02:FS02:Assigned to work server 140.163.4.231
21:25:01:WU02:FS02:Requesting new work unit for slot 02: READY gpu:1:GP102 [GeForce GTX 1080 Ti] 11380 from 140.163.4.231
21:25:01:WU02:FS02:Connecting to 140.163.4.231:8080
21:25:02:WU01:FS01:Downloading 16.51MiB

The CPU slot is the only one to work.  

So far, I have tried:

- re-installing FAH - several times in the hope that the cards will be properly identified
- re-booting a gazillion times
- altering the opencl-index to 0 and 1 respectively, but these new values don't seem to stick 
- updating my Windows 10 installation (now at 1709 build 16299.402) and updating to the newest nvidia driver (397.31)

This issue only started last week after the assignment server problems.  That issue was solved for me only after: 

- pausing Malwarebyte's real-time protection layers (as that seemed to be obstructing downloads of new WUs), and
- creating exceptions in Windows Defender for fahcontrol and fahclient

I can't see a ready way to solve this and return to full folding.  Any suggestions would be most welcome.

Let me know if you need any further info

Cheers

Nick

**Comment by jcoffland** [comment]
I'm not sure how to solve this.  It appears that your GPUs are supported and detected by the client but the 0x21 core fails to detect them.  Since this is a client configuration issue you should take your problem to the foldingforum.org.  They will likely be able to better help you there.

**Comment by nickgabby** [comment]
Thanks - I have logged an issue with FAH forum at https://foldingforum.org/viewtopic.php?f=18&t=30766&start=15.  Cheers, Nick

**Comment by informatorius** [comment]
It was a driver issue, nvidia 397.31 is evil. Can be closed.

**Comment by jcoffland** [comment]
thanks!
