### ISSUE TITLE
Beta 7.5.0 [FAHControl]: System Info tab not pulling config.xml path upon reload after changes applied

### ISSUE THREAD

**Issue by sombraguerrero** [FoldingAtHome/fah-issues#1229]
![image](https://user-images.githubusercontent.com/24618934/40290241-5cc4548a-5c82-11e8-9e36-bf683cb6be77.png)

**Comment by sombraguerrero** [comment]
Other notes: I installed the client and the data directory to an alternate drive (D:) and I am not running it as a service since I also do GPU folding.

**Comment by jcoffland** [comment]
Is this a problem only in v7.5.0?  I don't understand how to reproduce this.  Can you list the steps?

**Comment by sombraguerrero** [comment]
You know, I think now that I'm re-evaluating it, it's simply that FAHControl doesn't populate the path upon the very first (initial) run of the client, which I suppose would kind of make sense. After I restarted the client, which I didn't do until the following day, the path was there just fine.

**Comment by jcoffland** [comment]
So yeah, on the first run there may not be a ``config.xml``.  Is this really a bug?  If it is please provide the exact steps to reproduce it.  Otherwise, let me know if I can close this.

**Comment by sombraguerrero** [comment]
Yeah, it's probably okay to close this. It's just me being nit-picky. I'm just used to QA'ing that way. The question, I guess is if immediately after the client has run for the first time, and the file is saved, should Control update in real time to display the path? Probably not worth caring about or the effort to code.
