### ISSUE TITLE
sudo prefered over su in Linux install docs.

### ISSUE THREAD

**Issue by RheaAyase** [FoldingAtHome/fah-issues#1231]
_I've not found docs to be open source so I can't fix it, if is please direct me to the right place..._

Page: <https://folding.stanford.edu/support/faq/installation-guides/linux/manual-installation-advanced/>

* All the occurrences of `su -c 'rpm -i ...` are wrong, user should never acquire root privileges that way... Please replace with `sudo rpm .......`
* It's `Red Hat Enterprise Linux 6.x` (or `RHEL 6.x`) and not `Red Hat 6.x`

**Comment by jcoffland** [comment]
"Dangerously wrong" is a bit hyperbolic.  Those commands do exactly the same thing and ``su`` is no more dangerous than ``sudo``.  Running a shell as root is arguably more dangerous.  But ok, ``sudo`` is more appropriate.

**Comment by jcoffland** [comment]
I've updated the instructions here: https://foldingathome.org/support/faq/installation-guides/linux/manual-installation-advanced/  Note that folding.stanford.edu is no longer being updated and will be redirected to foldingathome.org soon.  Thanks for the report.
