### ISSUE TITLE
Use systemd services on Linux.

### ISSUE THREAD

**Issue by RheaAyase** [FoldingAtHome/fah-issues#1232]
Systemd services would be highly preferred to the useless initd ones as vast majority of Linux distributions use systemd and merely provide somewhat wobbly backwards compatibility.

**Comment by dmc5179** [comment]
We have a systemd service written and installed by our ansible playbooks:


https://github.com/ajacocks/fah

**Comment by RheaAyase** [comment]
Duplicate of what? I can't see one on this topic what so ever.

**Comment by cinderblock** [comment]
If this is true, why is the official installer still creating `/etc/init.d/FAHClient`?
