### ISSUE TITLE
Stats API returns HTML

### ISSUE THREAD

**Issue by oroszwj** [FoldingAtHome/fah-issues#1234]
In a recent update, the stats api began returning HTML formatted data instead of machine readable JSON. This is breaking my tracking application and may also be breaking the web control (which no longer shows identity or points)

**Comment by oroszwj** [comment]
In a recent update, the stats api began returning HTML formatted data instead of machine readable JSON.  This is breaking my tracking application and may also be breaking the web control (which no longer shows identity or points)

**Comment by jcoffland** [comment]
Which URL are you using?

**Comment by sombraguerrero** [comment]
http://folding.stanford.edu/stats/api/donor/1780372
I seem to be getting a redirect to an old news post:
https://foldingathome.org/2011/11/09/donor-advisorary-board-dab/1780372/

**Comment by oroszwj** [comment]
I've tested all of the GET API URL's listed on and all of them return the same HTML as non-api URL for interactive browsing.  Of particular interest for my application:
http://folding.stanford.edu/stats/api/team/223518 returns the same as http://folding.stanford.edu/stats/team/223518

**Comment by oroszwj** [comment]
Apologies, having re-read the API docs, it seems the entrypoint URL has moved to https://stats.foldingathome.org/.  The updated URL is functioning as intended.

**Comment by sombraguerrero** [comment]
What I see happening even after updating the entry point is that it's returning the HTML document that reflects the Angular driven stats page. If I review the HAR output in the dev console of a browser, I see that the GET call to retrieve the JSON arrays is happening much later, after the rest of the webpage load completes. So I bring this back to, is this a user problem in the API invocation, or did the order of operations get scrambled around when the entry point changed?

**Comment by jcoffland** [comment]
@sombraguerrero  I think you still don't have they API entry point right.  It's https://stats.foldingathome.org/api/  There's no Angular involved here, BTW.

**Comment by sombraguerrero** [comment]
Oh! "stats" is no longer part of the path, I see. Thanks!

**Comment by jcoffland** [comment]
I've now also fixed the redirect.
