### ISSUE TITLE
JSON API broken

### ISSUE THREAD

**Issue by bls1999** [FoldingAtHome/fah-issues#1235]
The JSON API for stats lookup is broken. All it does is redirect to the search GUI. Click any of the links on [this page](https://stats.foldingathome.org/api) to see what I'm talking about.

**Comment by sombraguerrero** [comment]
I posted about this on the forums too. It's not *technically* totally broken. The problem is that the JSON data is getting retrieved in a separate GET call that's happening AFTER the stats page loads, so something probably happened when they transitioned to https://stats.foldingathome.org.

**Comment by jcoffland** [comment]
It's fixed now.  The problem was in the documentation.  The examples were pointing to the wrong place.
