### ISSUE TITLE
FAHControl doesn't open the project description

### ISSUE THREAD

**Issue by bb30994** [FoldingAtHome/fah-issues#1237]
Clicking on the project number in FAHControl doesn't open the project description.

The project link needs to go to https://apps.foldingathome.org/project.py?p=####

links to the WS and CS don't work either, but I'm not sure what they're supposed to do.

**Comment by ahoyJS** [comment]
This seems broken again - at least in the Debian/Ubuntu version. Clicking on the "Project" link does nothing. And right clicking it does not copy the URL. (WS and CS links work: they open Firefox with the donor credits.)

**Comment by shorttack** [comment]
Closed: fixed in 7.5.2. Duplicates #48.

**Comment by shorttack** [comment]
> Where can I get 7.5.2 from? <
[https://foldingathome.org/beta/](url)

**Comment by ahoyJS** [comment]
> > Where can I get 7.5.2 from? <
> > [https://foldingathome.org/beta/](url)

Thanks!!
