### ISSUE TITLE
Failed to read from stream, Update Core in 7.5.1

### ISSUE THREAD

**Issue by SwiftTG** [FoldingAtHome/fah-issues#1241]
Log from FAHClient.exe via Command Prompt:
```
00:35:07:************************* Folding@home Client *************************
00:35:07:      Website: https://foldingathome.org/
00:35:07:    Copyright: (c) 2009-2018 foldingathome.org
00:35:07:       Author: Joseph Coffland <joseph@cauldrondevelopment.com>
00:35:07:         Args:
00:35:07:       Config: <none>
00:35:07:******************************** Build ********************************
00:35:07:      Version: 7.5.1
00:35:07:         Date: May 11 2018
00:35:07:         Time: 13:06:32
00:35:07:   Repository: Git
00:35:07:     Revision: 4705bf53c635f88b8fe85af7675557e15d491ff0
00:35:07:       Branch: master
00:35:07:     Compiler: Visual C++ 2008
00:35:07:      Options: /TP /nologo /EHa /wd4297 /wd4103 /Ox /MT
00:35:07:     Platform: win32 10
00:35:07:         Bits: 32
00:35:07:         Mode: Release
00:35:07:******************************* System ********************************
00:35:07:          CPU: Intel(R) Xeon(R) CPU E5520 @ 2.27GHz
00:35:07:       CPU ID: GenuineIntel Family 6 Model 26 Stepping 5
00:35:07:         CPUs: 16
00:35:07:       Memory: 31.99GiB
00:35:07:  Free Memory: 28.39GiB
00:35:07:      Threads: WINDOWS_THREADS
00:35:07:   OS Version: 6.2
00:35:07:  Has Battery: false
00:35:07:   On Battery: false
00:35:07:   UTC Offset: -4
00:35:07:          PID: 7952
00:35:07:          CWD: C:\Windows\system32
00:35:07:           OS: Windows 10 Pro
00:35:07:      OS Arch: AMD64
00:35:07:         GPUs: 0
00:35:07:         CUDA: Not detected: Failed to open dynamic library 'nvcuda.dll': The
00:35:07:               specified module could not be found.
00:35:07:
00:35:07:       OpenCL: Not detected: clGetPlatformIDs() returned -1001
00:35:07:Win32 Service: false
00:35:07:***********************************************************************
00:35:07:<config>
00:35:07:  <!-- Folding Slots -->
00:35:07:</config>
00:35:07:Connecting to assign1.foldingathome.org:8080
00:35:07:Updated GPUs.txt
00:35:07:Read GPUs.txt
00:35:07:Trying to access database...
00:35:07:Successfully acquired database lock
00:35:07:Enabled folding slot 00: PAUSED cpu:15 (not configured)
00:36:08:Saving configuration to config.xml
00:36:08:<config>
00:36:08:  <!-- Folding Slots -->
00:36:08:  <slot id='0' type='CPU'/>
00:36:08:</config>
00:36:08:Set client configured
00:36:08:WU00:FS00:Connecting to 65.254.110.245:8080
00:36:08:WU00:FS00:Connecting to 65.254.110.245:8080
00:36:09:WU00:FS00:Assigned to work server 155.247.166.219
00:36:09:WU00:FS00:Requesting new work unit for slot 00: READY cpu:15 from 155.247.166.219
00:36:09:WU00:FS00:Connecting to 155.247.166.219:8080
00:36:09:WU00:FS00:Downloading 484.92KiB
00:36:11:WU00:FS00:Download complete
00:36:11:WU00:FS00:Received Unit: id:00 state:DOWNLOAD error:NO_ERROR project:14058 run:11 clone:37 gen:0 core:0xa7 unit:0x000000000002894b5aeb6034af1a78c8
00:36:11:WU00:FS00:Downloading core from http://cores.foldingathome.org/Win32/AMD64/Core_a7.fah
00:36:11:WU00:FS00:Connecting to cores.foldingathome.org:80
00:37:11:ERROR:WU00:FS00:Exception: Failed to read stream
00:37:11:WU00:FS00:Downloading core from http://cores.foldingathome.org/Win32/AMD64/Core_a7.fah
00:37:11:WU00:FS00:Connecting to cores.foldingathome.org:80
00:38:11:ERROR:WU00:FS00:Exception: Failed to read stream
00:38:11:ERROR:Receive error: 10053: An established connection was aborted by the software in your host machine.
00:38:14:Saving configuration to config.xml
00:38:14:<config>
00:38:14:  <!-- Network -->
00:38:14:  <proxy v=':8080'/>
00:38:14:
00:38:14:  <!-- User Information -->
00:38:14:  <user v='winsrv-ag'/>
00:38:14:
00:38:14:  <!-- Folding Slots -->
00:38:14:  <slot id='0' type='CPU'/>
00:38:14:</config>
00:38:48:WU00:FS00:Downloading core from http://cores.foldingathome.org/Win32/AMD64/Core_a7.fah
00:38:48:WU00:FS00:Connecting to cores.foldingathome.org:80
00:39:48:ERROR:WU00:FS00:Exception: Failed to read stream
00:39:49:Saving configuration to config.xml
00:39:49:<config>
00:39:49:  <!-- Network -->
00:39:49:  <proxy v=':8080'/>
00:39:49:
00:39:49:  <!-- User Information -->
00:39:49:  <user v='winsrv-ag'/>
00:39:49:
00:39:49:  <!-- Folding Slots -->
00:39:49:  <slot id='0' type='CPU'/>
00:39:49:</config>
00:39:50:ERROR:Receive error: 10053: An established connection was aborted by the software in your host machine.
00:41:25:WU00:FS00:Downloading core from http://cores.foldingathome.org/Win32/AMD64/Core_a7.fah
00:41:25:WU00:FS00:Connecting to cores.foldingathome.org:80
00:42:26:ERROR:WU00:FS00:Exception: Failed to read stream
00:42:27:ERROR:Receive error: 10053: An established connection was aborted by the software in your host machine.
00:45:40:WU00:FS00:Downloading core from http://cores.foldingathome.org/Win32/AMD64/Core_a7.fah
00:45:40:WU00:FS00:Connecting to cores.foldingathome.org:80
00:46:40:ERROR:WU00:FS00:Exception: Failed to read stream
```
Using a retired server (DELL PowerEdge R710). Was working this morning, got Update Core dialogue when I checked back just an hour before this post. So it kept cycling from Updating to Update Core. When I checked the FAHClient.exe in CMD, I saw the Failed to read from stream error. This hasn't happened in the past few days and I have also tried removing the FahCore file to allow it to update it to the newest version to no avail. Is it a server-side issue  cores.foldingathome.org:80?

**Comment by bb30994** [comment]
This is a direct result of actions forced by Microsoft's WindowsUpdate.  See the duplicate issue #1212.

Whenever Microsoft updates your video drivers, they remove the NVidia supplied drivers for CUDA and OpenCL, preventing FAHClient from running on your GPU.  After they do that, you have to reinstall the current driver from nvidia.com/  (Actually probably from https://www.geforce.com/drivers)

For most systems, you cannot prevent WindowsUpdate from doing this other than by by installing a newer version before Microsoft decides they need to do it..

**Comment by SwiftTG** [comment]
@bb30994 Thanks for the direction and very helpful information, but,I am not running a Nvidia GPU,, This is a R710 Server. I'm using the Xeon CPUs to do the Folding.

**Comment by bb30994** [comment]
OK.  Wrong answer.

Correct answer: Please visit foldingforum.org which is the support site for FAH.

Second probable right answer: Your firewall is blocking FAHClient from connecting to the internet and messages from it have been disabled (oi ignored).  Reconfigure the firewall with an exception allowing FAHClient.ext to connect to the internet.

**Comment by SwiftTG** [comment]
I believe I already added the firewall exception, but with my luck it’s worth a shot to review and fix. thanks!

**Comment by informatorius** [comment]
https://foldingforum.org/viewtopic.php?f=106&t=30846&start=30

**Comment by jcoffland** [comment]
@informatorius  provide a synopsis of the forum contents rather than just a link.  It's a huge pain to read through the forum posts to try to figure out the essence of the problem.  That information needs to be right here in the issue.

**Comment by informatorius** [comment]
I see. The problem may have occured on first rolloff FAHclient 7.5.1 because all clients needed to download the cores from new website location and bandwidth or max concurrent connections to the server maybe was limited. This should be solved now. Single people still had problems because of firewall or router settings maybe in conflict with new client or new website location.

**Comment by bb30994** [comment]
Aha.  I see the problem.
@SwiftTG said
>I'm using the Xeon CPUs to do the Folding.

FAH supports NVidia and ATI GPUs.  Intel GPUs are not supported.  You'll note that near the top of the log you posted it says

> GPUs: 0
> CUDA: Not detected: Failed to open dynamic library 'nvcuda.dll': The  specified module could not be found.
> OpenCL: Not detected: clGetPlatformIDs() returned -1001

When you installed FAHClient it would have configured a single slot for your CPU.  Manually adding a GPU slot is not supported as there is no FAHCore that has been compiled to use OpenCL on an Intel iGPU.  Please install a supported GPU or fold with your CPU only.

**Comment by bb30994** [comment]
the message "Failed to read stream" is actually correct, but not the least informative.  FAHClient is written so that if foldingathome does decide to support Intel iGPUs, FAHClient will work but since that's not the case, all it knows is that it cannot find an appropriate FAHCore to download.

Perhaps if the client detects  GPUs: 0 it should skip any attempts to fold with a GPU, preventing the download attempt with a more enlightening message -- but that's an enhancement for some future version of FAHClient.

**Comment by shorttack** [comment]
Closed: shelf life past due.
