### ISSUE TITLE
Is there a setting to disable Temperature Control?

### ISSUE THREAD

**Issue by bb30994** [FoldingAtHome/fah-issues#1242]
On a system with more than one GPU, there always are messages:

> 01:23:20:WU01:FS02:0x21:Temperature control disabled. Requirements: single Nvidia GPU, tmax must be < 110 and twait >= 900
> 01:23:20:WU04:FS01:0x21:Temperature control disabled. Requirements: single Nvidia GPU, tmax must be < 110 and twait >= 900

How can I tell FAHCore_21 not to bother trying to enable Temperature Control because I already know it isn't going to work?

**Comment by jcoffland** [comment]
You can't.
