### ISSUE TITLE
CXXABI 1.3.9 not found in libstdc++so.6 on Linux 

### ISSUE THREAD

**Issue by bb30994** [FoldingAtHome/fah-issues#1252]
Same issue as https://github.com/FoldingAtHome/fah-issues/issues/1147 except now a LATER version  of CXXABI is required by FAHCore_a7.

(I'm not allowed to re-open that issue.)

**Comment by bb30994** [comment]
Can the appropriate version of GLIBCXX be statically linked?  
Can it be incorporated into the FAHCore distribution package?

**Comment by shorttack** [comment]
closed: Ubuntu 14 deprecated
