### ISSUE TITLE
[Question] FAHClient automated (and testing) install

### ISSUE THREAD

**Issue by MichaIng** [FoldingAtHome/fah-issues#1255]
Hey there,

we worked on the [DietPi](https://github.com/Fourdee/DietPi) Debian based distro to include Folding@Home with our software offer.

DietPi aims to offer automated and well pre-configured software, so that the necessary manual config steps for end users are minimal. In this case we pre-configure the official `.deb` package via `debconf-set-selections` to e.g. add a default (anonymous) user name, our DietPi team and implement the service in a way, that by default the web UI can be accessed remotely, as most of our users use DietPi for headless servers.

_______________

All of this is working just fine now. I was just wondering, as during our test installs and the need to enable autostart currently (https://github.com/FoldingAtHome/fah-issues/issues/1193) on every test install a work unit is received and started to process, which we of course for testing only never finish. I guess the work unit is then reserved for this particular client, thus an unnecessary delay for this research occurs? Is it somehow possible to sign out for a work unit, so another client can directly start working on it? Or is this done automatically when uninstalling the client (guess this would be hard to achieve)?

Not sure if this is a real issue on your/the researchers side, if there are anyway always more opened WUs than clients to work on. But in case it would make sense e.g. to not automatically start with a WU on first start, but leave it to the user to receive the first WU. And second to allow signing out a WU, if for some reasons one can't finish the job. Even better if this could be done automatically, when the client is uninstalled.

**€: Just read a bid through the FAQ and found that you chose the deadline/expiration times accordingly to assure research progress. However I guess as unfinished WU always create a certain delay, it should be kept as low as possible and I still think a way to opt out manually from a WU would be beneficial.**

______________

Next is the default user. We currently use "DietPi" for this. Of course users will mostly directly change this. But as one could create a passkey for this user name and thus break access for all others, it would make sense to create a passkey our end (and preconfigure it) for this default user. But I am not sure if this somehow breaks your intentions with passkeys. I found otherwise default to be "Anonymous" (at least on Windows desktop installs?). Would this be the better choice and is it unallowed to receive a passkey for this user?

**Comment by MichaIng** [comment]
> FAHClient --dump

Ah nice, I will add this to our uninstall code.

Not sure if it's possible to add such commands to `.deb` and/or `.rpm` package (pre-)uninstall steps, or if this is already the case, but it would help to reduce research delays if users for some reason decide to remove the client while usually a work unit is currently assigned.

**Comment by bb30994** [comment]
The FAH EULA prohibits donors from obtaining FAH software from unauthorized sources and I'm afraid you'd fall into that category.  The .deb and .rpm provide all the necessary steps to begin folding.  You MAY begin folding as Anonymous for Team 0 or you may choose your own name and team.  That option is built into the code provided by FAH.  I do recommend that each person make those changes for themselves and add a passkey, but that not essential.  It doesn't change the science you complete, only the accounting of the points you can earn.

FAHClient should start automatically after a brief pause.  

The FAHClient service is just that, a service that is expected to run continuously.  If you wish to stop processing, you can suspend the worker threads (FAHCore_xx)  by using FAHControl (if you have a GUI) or by telnet commands to the service.  Then FAHClient will remain idle until you choose to resume processing.

**Comment by MichaIng** [comment]
@bb30994 
> The FAH EULA prohibits donors from obtaining FAH software from unauthorized sources and I'm afraid you'd fall into that category.

We do not offer FAH from a different source, but use the official .deb package: https://github.com/Fourdee/DietPi/blob/testing/dietpi/dietpi-software#L3886-L3911

We just provide a GUI to allow users choose FAH and have an automated install without interactive steps needed, so you can as well install images on multiple machines non-interactively and have FAH installed and running on all of them automatically.

> If you wish to stop processing, you can suspend the worker threads

As said, I was just caring about started but not finished WUs. Preventing autostart of work units and allowing to check out from a work unit (FAHClient --dump) just allows to reduce those, when devs or end users test or try out FAH.

**Comment by ProDigit** [comment]
ARM Currently doesn't make sense, but that doesn't mean they never will.
They are extremely power efficient. The moment ARM will start implementing 32 core CPUs, FAH should start to take notice!

**Comment by ronlaws86** [comment]
Can I resurrect this one in 2020? :) Big ARM Based server farms run ARM core counts in the 64+ range, Pi4 is a Cortex A72 and can turn out Work units on BOINC at the same rate as FAH does on my laptop, turnaround typically 1 day or less. it's worth re-visiting this with current hardware no?
[`This thread](https://www.raspberrypi.org/forums/viewtopic.php?f=67&t=194952) is worth pointout out for running OpenCL against the VideoCore IV  (Pi3) - https://github.com/doe300/VC4CL

Pi4 is the next gen VideoCore which has more compute power.

**Comment by MichaIng** [comment]
@ronlaws86 
The initial issue wasn't about ARM support btw, so I suggest to open a new one or better contribute to a related discussion in the forums, e.g. https://foldingforum.org/viewtopic.php?p=320319#p320319
