### ISSUE TITLE
Incomplete rewrite of https://apps.foldingathome.org/team

### ISSUE THREAD

**Issue by bb30994** [FoldingAtHome/fah-issues#1260]
Apparently teams have been created with no emails (I can't check that theory) so the Reset Code REQUEST function is inadequate.

Does this mean that the team was never registered? ... or was the email lost somewhere?  What happens when the REQUEST cannot be sent.

Suggestion: When it cannot be sent, an email should be sent to someone who can manage this error.

**Comment by bb30994** [comment]
According to the guy I'm dealing with, no email was required for his team 85 as well as older teams (and perhaps later teams).  That was before my time, so I'm not sure what the rules were then.  I didn't found my team, so I'm not sure when the rules changed.

**Comment by shorttack** [comment]
Closed: too old
