### ISSUE TITLE
Linux GPU detection in the cloud

### ISSUE THREAD

**Issue by informatorius** [FoldingAtHome/fah-issues#1262]
When I rent a Linux GPU machine in the cloud then FAH sometimes creates wrong GPU slots initially. The config is special as in HW there may be shown more GPUs than OpenCL slots are available. Current behavior is for every GPU device the FahClient creates a FAH GPU slots. Expected behavior: Only for each OpenCL device FAH creates a GPU slot.

See logfile below where GPUs:3 detected in HW but only 2 OpenCL devices available. FAH creates 1 CPU slot and 3 GPU slots. But expected are 1 CPU slot and 2 GPU slots.
```
22:21:50:INFO(1):Read GPUs.txt
22:21:51:************************* Folding@home Client *************************
22:21:51:        Website: https://foldingathome.org/
22:21:51:      Copyright: (c) 2009-2018 foldingathome.org
22:21:51:         Author: Joseph Coffland <joseph@cauldrondevelopment.com>
22:21:51:           Args:
22:21:51:         Config: /etc/init.d/config.xml
22:21:51:******************************** Build ********************************
22:21:51:        Version: 7.5.1
22:21:51:           Date: May 11 2018
22:21:51:           Time: 19:59:04
22:21:51:     Repository: Git
22:21:51:       Revision: 4705bf53c635f88b8fe85af7675557e15d491ff0
22:21:51:         Branch: master
22:21:51:       Compiler: GNU 6.3.0 20170516
22:21:51:        Options: -std=gnu++98 -O3 -funroll-loops
22:21:51:       Platform: linux2 4.14.0-3-amd64
22:21:51:           Bits: 64
22:21:51:           Mode: Release
22:21:51:******************************* System ********************************
22:21:51:            CPU: Intel(R) Celeron(R) CPU G1840 @ 2.80GHz
22:21:51:         CPU ID: GenuineIntel Family 6 Model 60 Stepping 3
22:21:51:           CPUs: 2
22:21:51:         Memory: 3.79GiB
22:21:51:    Free Memory: 990.56MiB
22:21:51:        Threads: POSIX_THREADS
22:21:51:     OS Version: 4.15
22:21:51:    Has Battery: false
22:21:51:     On Battery: false
22:21:51:     UTC Offset: 0
22:21:51:            PID: 375
22:21:51:            CWD: /etc/init.d
22:21:51:             OS: Linux 4.15.0-29-generic x86_64
22:21:51:        OS Arch: AMD64
22:21:51:           GPUs: 3
22:21:51:          GPU 0: Bus:1 Slot:0 Func:0 NVIDIA:7 GP102 [GeForce GTX 1080 Ti] 11380
22:21:51:          GPU 1: Bus:2 Slot:0 Func:0 NVIDIA:7 GP102 [GeForce GTX 1080 Ti] 11380
22:21:51:          GPU 2: Bus:3 Slot:0 Func:0 NVIDIA:7 GP102 [GeForce GTX 1080 Ti] 11380
22:21:51:  CUDA Device 0: Platform:0 Device:0 Bus:2 Slot:0 Compute:6.1 Driver:10.0
22:21:51:  CUDA Device 1: Platform:0 Device:1 Bus:3 Slot:0 Compute:6.1 Driver:10.0
22:21:51:OpenCL Device 0: Platform:0 Device:0 Bus:2 Slot:0 Compute:1.2 Driver:410.78
22:21:51:OpenCL Device 1: Platform:0 Device:1 Bus:3 Slot:0 Compute:1.2 Driver:410.78
22:21:51:***********************************************************************
22:21:51:<config>
22:21:51:  <!-- Folding Slots -->
22:21:51:  <slot id='0' type='CPU'/>
22:21:51:  <slot id='1' type='GPU'/>
22:21:51:  <slot id='2' type='GPU'/>
22:21:51:  <slot id='3' type='GPU'/>
22:21:51:</config>
```

**Comment by bb30994** [comment]
FAH has created one CPU slot and 3 GPU slots.  That part is consistent.

I'm going to GUESS that your cloud contract allows you to use 2 GPUs even though the hardware detection finds for 3 devices.  If something like that is going on, you can manually remove slot 3 and everthing would be consistent.   Otherwise, you may be able to configure one more slot for the extra GPU. 

Both of the GPUs that have been enabled are treated as two devices, an OpenCL device (compute 1.2) and a CUDA device (compute 6.1) which would also be consistent.  FAH doesn't currently use CUDA devices.

**Comment by informatorius** [comment]
So if I have a GPU which does not support OpenCL then FAH automatically creates a GPU slot which then fails? Shouldn't it only create GPU slots for GPUs which support OpenCL? Then I would expect only 2 GPU slots created for Device 0 and Device 1. (I know how to manually fix it.)

**Comment by jcoffland** [comment]
This will be handled correctly in the next release of the client.

**Comment by bb30994** [comment]
By "handled correctly" I presume it will look something like this:
>22:21:51:           GPUs: 2
>22:21:51:          GPU 0: Bus:1 Slot:0 Func:0 NVIDIA: ...
>22:21:51:          GPU 1: Bus:2 Slot:0 Func:0 NVIDIA: ...
>22:21:51:    (unsupported) GPU *: Bus:3 Slot:0 Func:0 NVIDIA: ...
>22:21:51:  CUDA Device 0: Platform:0 Device:0 Bus:2 Slot:0 Compute:6.1 Driver:10.0
>22:21:51:  CUDA Device 1: Platform:0 Device:1 Bus:3 Slot:0 Compute:6.1 Driver:10.0
>22:21:51:OpenCL Device 0: Platform:0 Device:0 Bus:2 Slot:0 Compute:1.2 Driver:410.78
>22:21:51:OpenCL Device 1: Platform:0 Device:1 Bus:3 Slot:0 Compute:1.2 Driver:410.78
>22:21:51:***********************************************************************

or it might look like this:

>22:21:51:           GPUs: 2
>22:21:51:          GPU 0: Bus:1 Slot:0 Func:0 AMD: ...
>22:21:51:          GPU 1: Bus:2 Slot:0 Func:0 AMD: ...
>22:21:51:OpenCL Device 0: Platform:0 Device:0 Bus:2 Slot:0 Compute:1.2 Driver:410.78
>22:21:51:OpenCL Device 1: Platform:0 Device:1 Bus:3 Slot:0 Compute:1.2 Driver:410.78
>22:21:51:***********************************************************************

I wonder if we'll ever see something like this if OpenCL drivers are not present

>22:21:51:           GPUs: 2
>22:21:51:          GPU 0: Bus:1 Slot:0 Func:0 NVIDIA: ...
>22:21:51:          GPU 1: Bus:2 Slot:0 Func:0 NVIDIA: ...
>22:21:51:  CUDA Device 0: Platform:0 Device:0 Bus:2 Slot:0 Compute:6.1 Driver:10.0
>22:21:51:  CUDA Device 1: Platform:0 Device:1 Bus:3 Slot:0 Compute:6.1 Driver:10.0

**Comment by shorttack** [comment]
> This will be handled correctly in the next release of the client.

@informatorius iIf you're still interested in this issue, please try your cloud GPU configuration with the latest beta at [https://foldingathome.org/beta/](url) and report issues back here. In the meantime, I'm closing this old issue.
