### ISSUE TITLE
bother sony for the FAH code?

### ISSUE THREAD

**Issue by JazzMaster** [FoldingAtHome/fah-issues#1266]
with recent accomplishments (not everyone likes hacking teams) PS3 up thru 4.80 are now able to be fully unlocked with some effort. 

This brings back Cell processing- albeit SONY, I believe, had the shards running- not FaH. 
(to answer someone)

cost per unit make PS3 worth it - even today compared 10 years later to GPU/RX GPU prices(in mine/fold mode). POWER arch are still a bit more- recently the TALON II has come out.

It makes sense- although the tools may have some residual bad code- to open this up again- if there is interest. I think SONY stopped- despite thermal issues(there are fan mods)-much like otherOS- that they "didnt want people doing this". I think WE should decide, not big industry. The mod works. I side-stepped from 4.80. I installed lubuntu to USB thumb.

Its limited-compared to a normal PC- but it runs. 

FAH is either a PUPpyLinux mod for SONY- or a OtherOS application. We need to figure out which and let the "team responsible for opening the door" get this to work.
PKG format is used once the mod is installed. I dont know if its debain-style or not.

I do know that SONY uses Puppy Linux (modified) for its OS-much like how Slitaz works on the PC.

Anyone up for a challenge?

**Comment by bb30994** [comment]
I hate to be negative about this idea, but I doubt that FAH-Development will put any effort into the PS3 client.  Personally, I have an unused PS3 but the hardware is terribly inefficient in terms of Watts/WU and/or Watts/PPD and I it's almost more effective to buy an electric heater for that room.  ;)

You're welcome to open a topic on foldingforum.org where interested parties can discuss the necessary steps to get it working. https://foldingforum.org/viewforum.php?f=89.  ... and I wish you luck.

**Comment by ProDigit** [comment]
Ticket can be closed off.
Sony PS3 performs about the same as a dual core Celeron CPU. This hardware is on the decline.

Nothing can be done with the software, though it might be interesting to request a transfer of the rights of the Android client to FAH, to further develop it for upcoming ARM systems (especially with eye on arm based GPU servers, or arm based deep learning chipsets, as there may be a major shift happening from x86 to arm in the near future).

**Comment by bb30994** [comment]
The ARM/Android client should be covered in a different ticket.  It's worth transferring the rights -- and perhaps even make it into a semi-open-software project.  A new PlayStation (PS5) is on the horizon but not worth supporting -- it's a dying concept (dead?)..  

The Android/iPhone platforms are worth supporting.
