### ISSUE TITLE
error: 10053 when using viewer

### ISSUE THREAD

**Issue by bb30994** [FoldingAtHome/fah-issues#1269]
This error was reported on Foldingforum.org.  It was solved by replacing viewer 7.5.1 with the older 7.4.4

**Comment by informatorius** [comment]
With GPU FAHCore_22 beta p11733 using older 7.4.4 proteinviewer.exe with FahClient 7.5.1 even shows protein for GPU work unit again.

**Comment by shorttack** [comment]
@bb30994 Is this an issue with the latest beta 7.6.x viewer?

**Comment by shorttack** [comment]
Closed: 7.5.1 had viewer problems. Fixed in 7.6.6. See #1283 and #1369.
