### ISSUE TITLE
Enhancement: Allow FAHControl to parse previous logs

### ISSUE THREAD

**Issue by bb30994** [FoldingAtHome/fah-issues#1272]
FAHControl provides a well-developed viewer for FAH's public log.  It can filter for errors/look at the log of a chosen slot/look at the log of an individual WU.

These capabilities would be useful in scanning previous logs which are stored in ./logs.  Adding an option to list and select from the contents of ./logs would be a simple enhancement to FAHControl which would facilitate finding out when and why FAH crashed (after FAH has been restarted).

**Comment by ProDigit** [comment]
A link should be provided in Fahcontrol, that will either open older logs with the OS native text editor, or to the location of the log files.

Many Linux and windows leeks have problems locating the log files.

**Comment by shorttack** [comment]
This enhancement would keep users from the bowels of the Linux or Windows directory structure.

**Comment by shorttack** [comment]
Closed: merged to create #1448
