### ISSUE TITLE
FahControl freeze when GPU slot not available

### ISSUE THREAD

**Issue by informatorius** [FoldingAtHome/fah-issues#1274]
When FAH is configured to use 2 GPU slots but there is only one GPU available then starting FAHcontrol shows an error message and freezes. So it is not possible to remove the wrong GPU slot. Expected behavior: FahControl does not freeze and wrong GPU slot can be removed.

Error message: "iter should be a GTKTreeIter"

FahClient 7.5.1 on Windows 7

https://foldingforum.org/viewtopic.php?f=106&t=31464

![FahControl_error](https://user-images.githubusercontent.com/6989214/54764697-90833000-4bf8-11e9-960b-9ce2f9061d5c.PNG)
![FahControl_error2](https://user-images.githubusercontent.com/6989214/54764703-92e58a00-4bf8-11e9-8fd1-4da6ecacd53c.PNG)

**Comment by bb30994** [comment]
It's clear that when there's a slot defined and no GPU is present, the client doesn't know what to do and it's unfortunate that it doesn't give you the option to edit the configuration.  How about allowing the client to continue with a message that reads
 
> Option "gpu-index" has no default and cannot be set
> Slot deleted.

**Comment by informatorius** [comment]
FAHcontrol should not change configuration itself but just don't freeze, so user can change the config.
FAHclient also ignores the faulty slot.

**Comment by bb30994** [comment]
You have created an impossible situation.  Your configuration says that you have one slot (a GPU slot) but you have zero supported GPUs.  What's FAH supposed to do?  

FAH might be able to start if you had a functional CPU slot, allowing you to reconfigure a GPU slot, but that, too, gives FAHClient more authority to discard the present config.

Reinstall FAHClient.  It might be smart enough to discard the defective config, but I doubt it.  The only option I can think of is to reinitialize a default configuration.

**Comment by ProDigit** [comment]
Fahcontrol should give the option to adjust the slots, or reset to default value of CPU only in that moment. It's dependency on an internet connection, prevents anyone from adjusting those parameters, both in windows and Linux.
It's a small fix, I suggest switching to higher priority, unless the new Control app/program will have this fixed.
