### ISSUE TITLE
nacl web client should use https now as google chrome browser warns about that

### ISSUE THREAD

**Issue by informatorius** [FoldingAtHome/fah-issues#1275]
nacl web client should use https now as google chrome browser warn about that so users dont get scared about unsecure connection.

Current url http://nacl.foldingathome.org/
Expected url https://nacl.foldingathome.org/
using ssl certificate from https://foldingathome.org/

https://foldingforum.org/viewtopic.php?f=95&t=31476

**Comment by jcoffland** [comment]
NaCl issues should be filed here: https://github.com/FoldingAtHome/fah-nacl-client/issues

There are two things preventing us from using HTTPS for NaCl:

 1. None of our WS have proper SSL certificates.
 2. We don't use hostnames for WS in F@H and you need a hostname to use an SSL cert.

**Comment by informatorius** [comment]
I see but cannot the WS stay non SSL but only the front page be SSL?
https://nacl.foldingathome.org/
Because the users only see connection to the front page not secure and not connections to the WS.
So the users do not get scared anymore in chrome browser.

**Comment by jcoffland** [comment]
No, because then the browser will block the http connection to the WS and it won't work at all.

**Comment by ProDigit** [comment]
NaCl Will be discontinued. Can be closed off.
