### ISSUE TITLE
FAHClient reports incorrect points for the first 10 WUs.

### ISSUE THREAD

**Issue by bb30994** [FoldingAtHome/fah-issues#1276]
> 6:10:26:WU00:FS00:Upload complete
> 06:10:26:WU00:FS00:Server responded WORK_ACK (400)
> 06:10:26:WU00:FS00:Final credit estimate, 2076.00 points
>
> But it got me 207 points.
FAHClient should check the QRB eligibility ... or if that's not feasible, calculate both (such as a message that says
> Final credit estimate, 207 points (baseline) or 2076.00 points with bonus points.

**Comment by ProDigit** [comment]
First 10 WUs are without bonus points. Close issue.
