### ISSUE TITLE
Will there be a new FAHbench version with FahCore22?

### ISSUE THREAD

**Issue by informatorius** [FoldingAtHome/fah-issues#1277]
Will there be a new FAHbench version with FahCore22?

**Comment by bb30994** [comment]
Before that can be answered, FAHCore_22 needs to be released and there are still things to be fixed.

**Comment by PantherX** [comment]
Based on this information: https://foldingforum.org/viewtopic.php?p=324826#p324826
I would suggest that this issue can be closed :)
