### ISSUE TITLE
Linux FAH_installer needs updates for Ubuntu 18.10 

### ISSUE THREAD

**Issue by bb30994** [FoldingAtHome/fah-issues#1278]
Quoting a report from FoldingForum:
[Ubuntu18.10.txt](https://github.com/FoldingAtHome/fah-issues/files/3061632/Ubuntu18.10.txt)

**Comment by ProDigit** [comment]
Works fine in Ubuntu 18.10.

**Comment by fcole90** [comment]
I created some patched packages to support FAHControl in Focal: https://github.com/fcole90/fah-control/releases/tag/7.5.1-1_focal_1

**Comment by dmc5179** [comment]
We are installing and running on 18.04

https://github.com/ajacocks/fah
