### ISSUE TITLE
Provide support for shorter WUs

### ISSUE THREAD

**Issue by bb30994** [FoldingAtHome/fah-issues#1282]
Provide a new user-managed setting for **wu-size = {short/medium/normal}** based on expected processing time ... perhaps even replacing **max-packet-size** which is unused.

- [ ] With summer coming I will need to switch off my folding computers during several months because during the day the temperature is way too high.

- [ ] It would therefore be great to have a --wu-size small/medium/normal option to be able to ask for smaller WUs that could be completed during the night, when the temperature is lower. (Btw the max-packet-size option isn't OK as the WU completion time is not at all related to the packet size).

NOTE: The FINISH function will still be required to avoid inactive time for the WU.

**Comment by bb30994** [comment]
For donors with Air Conditioning limitations,  The only way to get CPU projects that can be completed overnight is to run NaCl rather than FAHCore_a7 or _a4.  If FAH really wants to emphasize those FAHCore_a* projects over the NaCl projects before the end of summer, this suggestion needs to be expedited.

**Comment by ProDigit** [comment]
NaCl is going to be discontinued.

**Comment by shorttack** [comment]
Closed: control enhancement
