### ISSUE TITLE
OS Stats not updating.

### ISSUE THREAD

**Issue by bb30994** [FoldingAtHome/fah-issues#1284]
See https://foldingforum.org/viewtopic.php?f=18&t=31069 for more information.

Does the OS Stats page have to be updated manually?  It seems that somebody has put a date on the table that changes regularly without actually collecting new data and that's a bad idea.

**Comment by shorttack** [comment]
This is a stats issue

**Comment by shorttack** [comment]
Closed: worksforme The current stats page at [https://stats.foldingathome.org/os](url) shows 2.4 petacycles, matching the press release this week. I'm assuming whatever problem from 2018 got fixed and the case was not closed.
