### ISSUE TITLE
WU up/download polling for less stable networks

### ISSUE THREAD

**Issue by ProDigit** [FoldingAtHome/fah-issues#1286]
Seems like fah stops down/uploading WUs after a few tries, and only tries again, when the next WU is finished and ready for upload.

Perhaps when no connection can be made, a ping can be triggered to a known site (like eg:google.com) at a regular interval?
If google.com responds, the client can try to ping the fah servers again.
If Google doesn't respond, re-ping every 5 minutes.
Network downs, slow and overcrowded networks, is still an issue in many areas, and waiting to upload until another WU is ready, wastes too much time.

**Comment by NuovaApe** [comment]
Implementing ping programmatically on Windows at least requires the app to run as Administrator to access the "raw socket" needed to do ping. That's a huge ask, especially within work places where users are locked down. I don't even give myself admin rights on my home PC for security concerns.

The Windows ping command line tool is a trusted app and doesn't need admin, but different OS's will have different ping screen outputs to screen scrape - a real pain to support.

If a network is overwhelmed the best thing to do is hold off for a while. Increasing the probing when it's already struggling is counterproductive and may prolong the problem.

**Comment by ProDigit** [comment]
Ping doesn't require admin rights of sorts at all.
The simple command in terminal or cmd.exe works without admin rights.
Not to mention, that fah already had ping built in, to call on the fah servers.
All it needs is an additional static address, like that of Google

**Comment by bb30994** [comment]
This is closely related to at least one aspect of https://github.com/FoldingAtHome/fah-issues/issues/1254

**Comment by ProDigit** [comment]
If ping is too hard to do, then use the procedure you currently use to contact the FAH servers, but on a more regular interval.
After a WU finished, and fah wasn't able to contact the server, keep retrying every 5 minutes.

It's not going to overload FAH servers when the cause is a downed wifi network, or a temporary network collision causing the fah servers to be unreachable.

Just as long as the client doesn't end up in a loop bug, where the client keeps successfully connecting to the server, and aborts, it should require almost no modifications.

**Comment by shorttack** [comment]
Closed: known issue
