### ISSUE TITLE
Ubuntu "portable" command line and directory structure?

### ISSUE THREAD

**Issue by muiaao** [FoldingAtHome/fah-issues#1287]
Is it possible to have a single command line to start FAH in Ubuntu with all executable and data in one single directory? 

For example:

./fahclient --exec-path xxx --data-path xxx --config xxx

so that I can just download my own package and run in ubuntu without installation?

**Comment by jcoffland** [comment]
Just run ``FAHClient`` in a directory containing a ``config.xml`` file.  No need to pass any extra options.

**Comment by muiaao** [comment]
Error: 

...FahCore returned: FAILED_3 (255 = 0xff)

[log-20190628-042438.txt](https://github.com/FoldingAtHome/fah-issues/files/3337560/log-20190628-042438.txt)

Also,
dan@fah:~/FAH/cores/cores.foldingathome.org/Linux/AMD64/ATI/R600/Core_21.fah$ ls -la
total 8140
drwxr-xr-x 2 root root    4096 6月  28 12:03 .
drwxr-xr-x 3 root root    4096 6月  28 12:03 ..
-rwxr-xr-x 1 root root 8324816 6月  28 12:03 FahCore_21
dan@fah:~/FAH/cores/cores.foldingathome.org/Linux/AMD64/ATI/R600/Core_21.fah$

**Comment by jcoffland** [comment]
Please report this at foldingform.org.  They can help you there.
