### ISSUE TITLE
FAHControl for Windows does not follow its links

### ISSUE THREAD

**Issue by bb30994** [FoldingAtHome/fah-issues#1288]

**Comment by bb30994** [comment]
In earlier versions of FAHControl for Windows, the project number and server IP used to open a browser window giving information about the WU or the Server.  This capability was broken by v7.5.1

**Comment by Sandman192** [comment]
Work Server and Collection Server IP numbers does nothing when clicking on it any more.

**Comment by waded** [comment]
I opened a more detailed version of this issue (specific to the project button) as https://github.com/FoldingAtHome/fah-control/issues/48.

**Comment by shorttack** [comment]
closed: duplicate #48
