### ISSUE TITLE
Optimus/Enduro automatic switching kills FAH

### ISSUE THREAD

**Issue by bb30994** [FoldingAtHome/fah-issues#1294]
https://www.geforce.com/hardware/technology/optimus/technology

Not surprisingly, when a Laptop with an NVidia GPU and an Intel iGPU spontaneously disables the NV GPU and enables the iGPU, the FAHCore crashes.  Does anybody know enough about this technology to configure a FAH-reliable system?

**Comment by bb30994** [comment]
Can FAHCore_22 be made smart enough to keep the GPU configured or otherwise cope with the activation of the iGPU?

**Comment by bb30994** [comment]
MORE DETAILS: 
Most recent laptops are being provided with a pair of switchable GPUs which switch between the integrated GPU and a discrete GPU, providing two choices of video performance and power savings. 

Apparently, when FAHClient starts, it detects only the one which is active at the time. and if the BIOS decides to switch later, it (not surprisingly) this caused any GPU FAHCore which may be active to crash.
 
AMD has called it Enduro and it is similar to Nvidia's Optimus.   In general, the iGPU is not supported, but the dGPU may be -- mostly depending on whether it supports mixed precision or not.

I'm not sure whether FAHClient can detect this hardware configuration during initialization ... or what the FAHCore can do about the loss of it's active GPU -- such as reporting it in the log and eventually backing up to the previous checkpoint.

**Comment by shorttack** [comment]
Closed: Windows enhancement to detect loss of dGPU when switched to iGPU.
