### ISSUE TITLE
Suggestion: Change default value of next-unit-percentage to 100

### ISSUE THREAD

**Issue by bb30994** [FoldingAtHome/fah-issues#1296]
The function of the **next-unit-percentage** was important  in the days of dial-up-modems, but _nobody_ has one any more.  Rather than changing code to remove that function (just in case somebody needs it) how about simply changing the default value to 100.  I run all my machines that way have not found anything wrong with that setting.

When there are two WUs queued on a single slot there's a risk (albeit low) of something like this happening., https://foldingforum.org/viewtopic.php?f=19&t=31863.  Changing the default removes that risk.

In fact it will probably minimize a problem similar to the topic described here https://github.com/FoldingAtHome/fah-issues/issues/1042

(See also https://github.com/FoldingAtHome/fah-issues/issues/486)

**Comment by bollix47** [comment]
I'm afraid I have to disagree with the suggestion of changing the default to 100.  Using 100 would mean sometimes the upload will start before the download finishes and that does cause problem which can & has caused 'stuck' downloads/uploads.  All of mine are set to default (99%) and they work well ... I'm sure most folders are using it that way as many may not even know about that option.

**Comment by bb30994** [comment]
Thanks for the comment bollix47.  

I do understand that FAHClient can be relatively intolerant of communications errors.  (There are several other tickets discussing such problems.)  I certainly don't want to increase the likelihood of those events.  

My experience has been different that yours, even when the download finishes after the upload is started -- which, in my case, is quite common.   Let's see if we can categorize the errors you're seeing which I somehow am avoiding.  Full-duplex communications "should" work ... and often does, but it's still not universally reliable. 

Whatever default is applicable, the other option will still be available.
