### ISSUE TITLE
WorkServers should notify the client when a WU is identified as FAULTY.

### ISSUE THREAD

**Issue by bb30994** [FoldingAtHome/fah-issues#1297]
Recently, a number of WUs were corrupted but the results were not identified as corrupt by FAHClient.  The WUs were either uploaded or the WU was abandoned before the upload was completed.

Example:```

21:09:57:WU02:FS01:0x21:Folding@home Core Shutdown: FINISHED_UNIT
21:09:57:WU02:FS01:FahCore returned: FINISHED_UNIT (100 = 0x64)
21:09:57:WU02:FS01:Sending unit results: id:02 state:SEND error:NO_ERROR project:14225 run:48 clone:1 gen:24 core:0x21 unit:0x0000002480fccb0a5d6545dbf5b1623c
21:09:57:WU02:FS01:Uploading 160.33MiB to 128.252.203.10
21:09:57:WU02:FS01:Connecting to 128.252.203.10:8080
21:10:17:WU02:FS01:Upload 0.12%
21:10:17:WARNING:WU02:FS01:Exception: Failed to send results to work server: Transfer failed
21:10:17:WU02:FS01:Trying to send results to collection server
21:10:17:WU02:FS01:Uploading 160.33MiB to 155.247.166.219
21:10:17:WU02:FS01:Connecting to 155.247.166.219:8080
21:10:17:ERROR:WU02:FS01:Exception: Transfer failed
```
FAHClient should be a message displayed by FAHClient giving whatever information is available.
Maybe that's a simple as
**Corrupt WU.  160.33MiB is too big.**

(If appropriate) delete the local copy of the WU.

I believe the older WS code did perform notification functions like this.

**Comment by shorttack** [comment]
This happened when there were collection server problems which caused WUs to get screwed up in comms. Happened to me that week.
