### ISSUE TITLE
How to copy FAH config info to text clipboard for use in support requests?

### ISSUE THREAD

**Issue by bulrush15** [FoldingAtHome/fah-issues#1302]
* I'm on windows 10 with FAH client 7.5.1. 

In Advanced view, on System Info tab, I'd like to be able to copy all the text shown so I can paste it into a text editor or into a website post to help with troubleshooting. I right clicked on several areas of the tab including the tab itself but found now right-click menu at all. 

A screenshot of the info is one hack but I'd prefer a text version of this information.

**Comment by jcoffland** [comment]
The same information is in the log.  Go to the log tab on the main window of FAHControl and you can cut and paste the system info from there.

**Comment by bulrush15** [comment]
Ok, thanks.
