### ISSUE TITLE
Enable low priority WUs, for when internet is down

### ISSUE THREAD

**Issue by ProDigit** [FoldingAtHome/fah-issues#1305]
I really believe we should get an option on downloading 1 WU per 2GPUs, and 1WU per <10CPU cores, that's a low priority WU that gets processed in a time when the servers are down, there are internet connection issues, or other...

I think one low priority WU could prevent a system from stalling completely, and with recent fah server outages, something we really should implement!

**Comment by bb30994** [comment]
FAH doesn't really have low priority WUs.  Every WU has a deadline and its value declines for every minute elapses between when it's downloaded until the result is returned (hence the QRB).  When a WU is delayed, the future Gens of that trajectory are all delayed.

When a server is down, FAH expects to have other servers which can distribute assignments to your particular configuration.

The recent capacity problems with servers at temple.edu are being addressed.  Additional servers are expected to be delivered soon, and in the meantime, various manual adjustments are being made.  See the discussion here: https://foldingforum.org/viewtopic.php?f=18&t=31876&start=165#p309915

**Comment by dmc5179** [comment]
@ProDigit Perhaps try the 'next-unit-percentage' option. The option supports a value as low as 90%. Depending on the size of the WU and how fast your GPUs are the time from 90% to 100% could be significant. You would essentially be sitting on a WU so your QRB would suffer as @bb30994 mentioned.

**Comment by bb30994** [comment]
Think of an atomic trajectory as an athletic relay race.  When a runner completes his segment of the course, he passes the baton to the next runner and the race proceeds.  There was a definite starting point and time and your team has to reach the finish point to qualify as having completed the race.  There is no such thing as a low-priority runner or a low-priority segment of the course.  Folding is a serial process.

**Comment by shorttack** [comment]
No action necessary.
