### ISSUE TITLE
Some GROMACS domain composition errors cause an infinite loop

### ISSUE THREAD

**Issue by bb30994** [FoldingAtHome/fah-issues#1307]
See more detailed log posted at https://foldingforum.org/viewtopic.php?f=19&t=32015#p310162 

> 11:16:19:WU00:FS00:0xa7:ERROR:Fatal error:
> 11:16:19:WU00:FS00:0xa7:ERROR:There is no domain decomposition for 10 ranks that is compatible with the given box and a minimum cell size of 1.45733 nm 

which leads to a restart of the same WU with the same parameters:
> 11:16:24:WU00:FS00:0xa7:WARNING:Unexpected exit from science code
> ...
> 11:16:24:WU00:FS00:FahCore returned: INTERRUPTED (102 = 0x66)
> 11:17:19:WU00:FS00:Starting

(FAHClient doesn't recognize the error as important enough to either change something or prepare to dump the WU after a few retries.)

Search foldingforum for "details on the domain decomposition" for a number of similar cases.

**Comment by marco44** [comment]
I'm having this exact same error

**Comment by marco44** [comment]
Reducing the amount of cores available made it run. That was on an AMD 3900x, so 24 threads available. Running the job on only 6 threads, I could complete it.

**Comment by DeeGeeFi** [comment]
Yeah, the bug isn't fixed yet. I still get it from time to time. Either deleting the workunit or changing number of cores/threads for slot helps. I'm running my 3950x with two separate CPU slots, 16 and 14 threads assigned for them.

**Comment by bb30994** [comment]
Unfortunately, the number of cores allocated depends mostly on the CPU that happens to be in the machine that is assigned the project as well as the characteristics of the particular project.  The Project Owner can exclude assignments to specific hardware but project beta testing doesn't systematically test with all possible numbers of threads.

The project owner needs to be notified of the exact problem.

**Comment by shorttack** [comment]
This should be taken to [foldingforum.org](url) related to the specific work unit.
