### ISSUE TITLE
Unhandled Windows exception

### ISSUE THREAD

**Issue by bb30994** [FoldingAtHome/fah-issues#1310]
It is not unreasonable for Windows to get a shut down reuqest while FAH is running.  This used to shut down semi-silently.  Now  I get the following in the logs
  **(Core 0x22)**
02:21:39:WARNING:WU02:FS03:FahCore crashed with Windows unhandled exception code 0x40010004, searching for this code online may provide more information
02:21:39:WARNING:WU02:FS03:FahCore returned: UNKNOWN_ENUM (1073807364 = 0x40010004)
  **(Core 0xa7)**
02:21:38:WARNING:WU03:FS00:FahCore crashed with Windows unhandled exception code 0x40010004, searching for this code online may provide more information
02:21:38:WARNING:WU03:FS00:FahCore returned: UNKNOWN_ENUM (1073807364 = 0x40010004)
but the WU restarts and produces a second error.
02:21:41:WU03:FS00:FahCore 0xa7 started
02:21:42:WARNING:WU03:FS00:FahCore returned an unknown error code which probably indicates that it crashed
02:21:42:WARNING:WU03:FS00:FahCore returned: UNKNOWN_ENUM (-1073741205 = 0xc000026b)

It would seem that the exception  handler could be trained to intercept these errors and deal with them with a simple messaged like "FAH is shutting down due to a requested Windows Shutdown"

**Comment by shorttack** [comment]
Closed: duplicate #1314
