### ISSUE TITLE
Web Control Sleeping on F@H Web-base.

### ISSUE THREAD

**Issue by Sandman192** [FoldingAtHome/fah-issues#1311]
Is it really necessary to have Sleeping mode on a F@H Web-base?

If so the give us an option to lengthen the timer and/or turn of Sleeping.

**Comment by bb30994** [comment]
Sleeping mode is managed by your OS.  You'll find the timer in the configuration panels for your OS -- and almost everybody turns it off.

By default, FAH disables that OS action since FAH is expected to run any time the OS is running.

**Comment by Sandman192** [comment]
I don't follow. The F@H Web-base. that grays out the browser window. Not the sleep mode in Windows power manger.

**Comment by bb30994** [comment]
Oh, I guess you're talking about the IP connection between FAHClient and the web browser.  Maybe it times out after a period of inactivity.

**Comment by Sandman192** [comment]
> Oh, I guess you're talking about the IP connection between FAHClient and the web browser. Maybe it times out after a period of inactivity.

Yes, and only 30 secs of inactivity. And again why?

I just want F@H developers to respond on why and if there going to have it stop doing that. Plus, it's random if it's going to work or not under Chrome.

**Comment by jcoffland** [comment]
It times out because the Web interface sends periodic queries to our servers.  We cannot have 1000s of clients hitting our servers when no one is paying attention.  Moving the mouse over the Web page resets the timer.

**Comment by Sandman192** [comment]
> It times out because the Web interface sends periodic queries to our servers. We cannot have 1000s of clients hitting our servers when no one is paying attention. Moving the mouse over the Web page resets the timer.

The web interface does not send queries to a server. That's not how it works. It's a web-based hitting my local client. Now if I want to check my computer from far away that I need the internet then ya it should go to sleep. Not when it's local not to sleep.

Note: I can still bring up the web-based without the internet and it will still monitor the client. That's how you know it's not going to a server from the internet. True the client can't upload or download work.

I just don't like the web-based going to sleep every 30 secs.

**Comment by shorttack** [comment]
Closed: no action.
