### ISSUE TITLE
FAH gave up downloading and wouldn't try where it left off or clean up and try to get new work again..

### ISSUE THREAD

**Issue by Sandman192** [FoldingAtHome/fah-issues#1312]
Internet is bad right now but it's still up because I can still browse the web, just very slowly and FAH just gave up.
I'll restart FAH to fix the problem. And yes FAH started downloading new work rather than where it left off and is working fine.
_WU02_ stopped a long time ago at 6.43% and _WU00_ at 95.42%. The reason why it's not showing it finishes.

### The point is FAH should have a backoff timer and try again later.

2 WU here trying to Download and 1 _WU03_ Uploaded and download went fine.

> 11:24:31:WU02:FS01:Connecting to 140.163.4.241:8080
> 11:24:34:WU02:FS01:Downloading 11.66MiB
> 11:25:18:WU02:FS01:Download 0.54%
> 11:25:25:WU02:FS01:Download 1.61%
> 11:25:31:WU02:FS01:Download 2.68%
> 11:25:48:WU00:FS00:0xa7:Completed 30000 out of 125000 steps (24%)
> 11:25:53:WU02:FS01:Download 4.29%
> 11:26:00:WU02:FS01:Download 5.36%
> **11:26:15:_WU02_:FS01:Download 6.43%** <--Never finshed and GPU 1 not running because of no work.
> 11:27:31:WU00:FS00:0xa7:Completed 31250 out of 125000 steps (25%)
> ******************************* Date: 2020-02-16 *******************************
> 11:28:20:WU01:FS02:0x21:Completed 21500000 out of 25000000 steps (86%)
> 11:29:16:WU00:FS00:0xa7:Completed 32500 out of 125000 steps (26%)
> 11:31:02:WU00:FS00:0xa7:Completed 33750 out of 125000 steps (27%)
> 11:32:46:WU00:FS00:0xa7:Completed 35000 out of 125000 steps (28%)
> 11:33:56:WU01:FS02:0x21:Completed 21750000 out of 25000000 steps (87%)
> 11:34:31:WU00:FS00:0xa7:Completed 36250 out of 125000 steps (29%)
> 11:36:14:WU00:FS00:0xa7:Completed 37500 out of 125000 steps (30%)
> 11:37:58:WU00:FS00:0xa7:Completed 38750 out of 125000 steps (31%)
> 11:39:32:WU01:FS02:0x21:Completed 22000000 out of 25000000 steps (88%)
> 11:39:43:WU00:FS00:0xa7:Completed 40000 out of 125000 steps (32%)
> 11:41:26:WU00:FS00:0xa7:Completed 41250 out of 125000 steps (33%)
> 11:43:10:WU00:FS00:0xa7:Completed 42500 out of 125000 steps (34%)
> 11:44:57:WU00:FS00:0xa7:Completed 43750 out of 125000 steps (35%)
> 11:45:09:WU01:FS02:0x21:Completed 22250000 out of 25000000 steps (89%)
> 11:46:45:WU00:FS00:0xa7:Completed 45000 out of 125000 steps (36%)
> 11:48:33:WU00:FS00:0xa7:Completed 46250 out of 125000 steps (37%)
> 11:50:23:WU00:FS00:0xa7:Completed 47500 out of 125000 steps (38%)
> 11:50:45:WU01:FS02:0x21:Completed 22500000 out of 25000000 steps (90%)
> 11:52:10:WU00:FS00:0xa7:Completed 48750 out of 125000 steps (39%)
> 11:54:01:WU00:FS00:0xa7:Completed 50000 out of 125000 steps (40%)
> 11:55:48:WU00:FS00:0xa7:Completed 51250 out of 125000 steps (41%)
> 11:56:21:WU01:FS02:0x21:Completed 22750000 out of 25000000 steps (91%)
> 11:57:35:WU00:FS00:0xa7:Completed 52500 out of 125000 steps (42%)
> 11:59:24:WU00:FS00:0xa7:Completed 53750 out of 125000 steps (43%)
> 12:01:14:WU00:FS00:0xa7:Completed 55000 out of 125000 steps (44%)
> 12:01:58:WU01:FS02:0x21:Completed 23000000 out of 25000000 steps (92%)
> 12:03:04:WU00:FS00:0xa7:Completed 56250 out of 125000 steps (45%)
> 12:04:53:WU00:FS00:0xa7:Completed 57500 out of 125000 steps (46%)
> 12:06:42:WU00:FS00:0xa7:Completed 58750 out of 125000 steps (47%)
> 12:07:33:WU01:FS02:0x21:Completed 23250000 out of 25000000 steps (93%)
> 12:08:31:WU00:FS00:0xa7:Completed 60000 out of 125000 steps (48%)
> 12:10:18:WU00:FS00:0xa7:Completed 61250 out of 125000 steps (49%)
> 12:12:04:WU00:FS00:0xa7:Completed 62500 out of 125000 steps (50%)
> 12:13:09:WU01:FS02:0x21:Completed 23500000 out of 25000000 steps (94%)
> 12:13:51:WU00:FS00:0xa7:Completed 63750 out of 125000 steps (51%)
> 12:15:39:WU00:FS00:0xa7:Completed 65000 out of 125000 steps (52%)
> 12:17:26:WU00:FS00:0xa7:Completed 66250 out of 125000 steps (53%)
> 12:18:45:WU01:FS02:0x21:Completed 23750000 out of 25000000 steps (95%)

Edit so much out because it was so long.
> 22:40:41:WU01:FS00:Upload 3.57%
> 22:40:44:WU00:FS02:Download 75.05%
> 22:40:48:WU01:FS00:Upload 5.95%
> 22:40:51:WU00:FS02:Download 76.12%
> 22:40:54:WU01:FS00:Upload 8.93%
> 22:41:00:WU00:FS02:Download 77.20%
> 22:41:00:WU01:FS00:Upload 11.91%
> 22:41:07:WU01:FS00:Upload 13.70%
> 22:41:09:WU00:FS02:Download 78.27%
> 22:41:14:WU01:FS00:Upload 17.27%
> 22:41:15:WU00:FS02:Download 78.80%
> 22:41:21:WU01:FS00:Upload 19.05%
> 22:41:22:WU00:FS02:Download 79.88%
> 22:41:27:WU01:FS00:Upload 22.63%
> 22:41:33:WU01:FS00:Upload 24.41%
> 22:41:39:WU01:FS00:Upload 27.39%
> 22:41:42:WU00:FS02:Download 80.41%
> 22:41:46:WU01:FS00:Upload 28.58%
> 22:41:52:WU01:FS00:Upload 32.75%
> 22:41:53:WU00:FS02:Download 81.48%
> 22:42:01:WU01:FS00:Upload 35.13%
> 22:42:07:WU01:FS00:Upload 38.11%
> 22:42:13:WU01:FS00:Upload 39.30%
> 22:42:20:WU01:FS00:Upload 42.87%
> **22:42:23:_WU03_:FS00:0xa7:Completed 1250 out of 125000 steps (1%)** <-- Aparently download just fine. Sorry I loast the log when it finshed downloading when I restarted FAH Client.
> 22:42:29:WU01:FS00:Upload 45.25%
> 22:42:33:WU00:FS02:Download 82.56%
> 22:42:36:WU01:FS00:Upload 49.42%
> 22:42:41:WU00:FS02:Download 84.16%
> 22:42:42:WU01:FS00:Upload 51.80%
> 22:42:48:WU01:FS00:Upload 54.19%
> 22:42:51:WU00:FS02:Download 84.70%
> 22:42:56:WU01:FS00:Upload 57.16%
> 22:42:57:WU00:FS02:Download 85.77%
> 22:43:02:WU01:FS00:Upload 60.74%
> 22:43:03:WU00:FS02:Download 86.31%
> 22:43:10:WU01:FS00:Upload 62.52%
> 22:43:11:WU00:FS02:Download 87.38%
> 22:43:17:WU01:FS00:Upload 65.50%
> 22:43:21:WU00:FS02:Download 88.45%
> 22:43:23:WU01:FS00:Upload 67.88%
> 22:43:27:WU00:FS02:Download 88.99%
> 22:43:34:WU01:FS00:Upload 69.67%
> 22:43:35:WU00:FS02:Download 89.53%
> 22:43:40:WU01:FS00:Upload 72.65%
> 22:43:45:WU00:FS02:Download 90.06%
> 22:43:46:WU01:FS00:Upload 74.43%
> 22:43:51:WU00:FS02:Download 90.60%
> 22:43:52:WU01:FS00:Upload 77.41%
> 22:43:58:WU01:FS00:Upload 80.39%
> 22:44:00:WU00:FS02:Download 94.35%
> 22:44:06:WU01:FS00:Upload 82.77%
> 22:44:11:WU00:FS02:Download 94.89%
> 22:44:13:WU03:FS00:0xa7:Completed 2500 out of 125000 steps (2%)
> 22:44:15:WU01:FS00:Upload 83.96%
> 22:44:22:WU01:FS00:Upload 88.72%
> **22:44:31:_WU00_:FS02:Download 95.42%** <--Never finshed and GPU 2 not running because of no work.
> 22:44:34:WU01:FS00:Upload 91.11%
> 22:44:41:WU01:FS00:Upload 95.87%
> 22:44:48:WU01:FS00:Upload 97.06%
> **22:44:56:_WU01_:FS00:Upload 100.00%** <--Just fine
> 22:45:02:WU01:FS00:Upload complete
> 22:45:02:WU01:FS00:Server responded WORK_ACK (400)
> 22:45:02:WU01:FS00:Final credit estimate, 4988.00 points
> 22:45:02:WU01:FS00:Cleaning up
> 22:45:59:WU03:FS00:0xa7:Completed 3750 out of 125000 steps (3%)
> 22:47:45:WU03:FS00:0xa7:Completed 5000 out of 125000 steps (4%)
> 22:49:27:WU03:FS00:0xa7:Completed 6250 out of 125000 steps (5%)

**Comment by Sandman192** [comment]
2nd-time FAH failed to completely download work. Failed yesterday and now it's today and got no work. Restarted FAH and got new work. Back to normal.
Poor internet... Yes. FAH not retrying... Definitely. Eather it needs a retry the same work or start over with a backoff in minutes timer.
As you can see in the log. It started on the 27th at 03:18 and now it's the 28th.

> 21:11:54:WU02:FS01:Cleaning up
> ******************************* Date: 2020-02-27 *******************************
> 03:18:45:WU02:FS02:Connecting to 65.254.110.245:8080
> 03:18:48:WU02:FS02:Assigned to work server 140.163.4.241
> 03:18:48:WU02:FS02:Requesting new work unit for slot 02: RUNNING gpu:1:GM204 [GeForce GTX 980] 4612 from 140.163.4.241
> 03:18:48:WU02:FS02:Connecting to 140.163.4.241:8080
> 03:18:49:WU02:FS02:Downloading 11.65MiB
> 03:18:55:WU02:FS02:Download 0.54%
> 03:19:05:WU02:FS02:Download 1.61%
> 03:19:17:WU02:FS02:Download 2.68%
> 03:19:26:WU02:FS02:Download 3.75%
> 03:19:33:WU02:FS02:Download 4.29%
> 03:19:41:WU02:FS02:Download 5.36%
> 03:19:47:WU02:FS02:Download 8.04%
> 03:20:01:WU02:FS02:Download 10.73%
> 03:20:09:WU02:FS02:Download 11.80%
> 03:20:17:WU02:FS02:Download 12.87%
> 03:20:23:WU02:FS02:Download 13.41%
> 03:20:32:WU02:FS02:Download 15.02%
> 03:20:41:WU02:FS02:Download 16.09%
> 03:20:47:WU02:FS02:Download 17.70%
> 03:20:58:WU02:FS02:Download 20.92%
> 03:21:04:WU02:FS02:Download 24.13%
> 03:21:12:WU02:FS02:Download 24.67%
> 03:21:27:WU02:FS02:Download 25.21%
> 03:21:36:WU02:FS02:Download 25.74%
> 03:21:47:WU02:FS02:Download 26.28%
> 03:21:57:WU02:FS02:Download 26.82%
> 03:22:08:WU02:FS02:Download 27.89%
> 03:22:18:WU02:FS02:Download 28.96%
> 03:22:27:WU02:FS02:Download 30.03%
> 03:22:33:WU02:FS02:Download 33.79%
> 03:22:39:WU02:FS02:Download 54.17%
> 03:22:52:WU02:FS02:Download 62.21%
> 03:23:06:WU02:FS02:Download 62.75%
> 03:23:37:WU02:FS02:Download 63.28%
> 03:24:12:WU02:FS02:Download 63.82%
> 03:24:25:WU02:FS02:Download 64.36%
> 03:24:31:WU02:FS02:Download 64.89%
> 03:24:37:WU02:FS02:Download 65.43%
> 03:24:45:WU02:FS02:Download 65.97%
> 03:24:59:WU02:FS02:Download 67.04%
> 03:25:07:WU02:FS02:Download 67.57%
> 03:25:14:WU02:FS02:Download 69.18%
> 03:25:22:WU02:FS02:Download 70.26%
> 03:25:28:WU02:FS02:Download 70.79%
> 03:25:42:WU02:FS02:Download 71.86%
> 03:25:53:WU02:FS02:Download 76.69%
> 03:26:00:WU02:FS02:Download 77.76%
> 03:26:06:WU02:FS02:Download 78.30%
> 03:26:12:WU02:FS02:Download 78.84%
> 03:26:20:WU02:FS02:Download 79.91%
> 03:26:29:WU02:FS02:Download 80.45%
> 03:26:37:WU02:FS02:Download 81.52%
> 03:26:48:WU02:FS02:Download 82.59%
> 03:27:00:WU02:FS02:Download 83.13%
> 03:27:10:WU02:FS02:Download 83.66%
> 03:27:24:WU02:FS02:Download 84.20%
> 03:27:33:WU02:FS02:Download 84.74%
> 03:27:39:WU02:FS02:Download 85.81%
> 03:27:47:WU02:FS02:Download 86.88%
> 03:28:01:WU02:FS02:Download 87.42%
> 03:28:08:WU02:FS02:Download 88.49%
> 03:28:15:WU02:FS02:Download 89.56%
> 03:28:25:WU02:FS02:Download 91.17%
> 03:28:36:WU02:FS02:Download 92.24%
> 03:28:56:WU02:FS02:Download 92.78%
> 03:29:08:WU02:FS02:Download 93.85%
> 03:29:19:WU02:FS02:Download 94.39%
> 03:29:28:WU02:FS02:Download 94.93% **<--Fail**
> ******************************* Date: 2020-02-28 *******************************

**Comment by bb30994** [comment]
This is apparently a duplicate of an unfixed problem #983 which was identified long ago.

**Comment by Sandman192** [comment]
It's been reported in Feb 2013 and still no fix. WOW!
