### ISSUE TITLE
Shutdown processing for Core_a7/CoreWrapper

### ISSUE THREAD

**Issue by bb30994** [FoldingAtHome/fah-issues#1313]
When a Windows Shutdown is initiated, all active processes are notified of the pending shutdown and given a period of time to clean up their files.  I've noticed that FAHCore_a7 does not process that information correctly.  After the wait interval expires, Windows forces the remaining processes to die.  This may or may not leave corrupted files  (needing a sync process).  This increases the probability of a GURU MEDITATION error.

If I manually pause all A7 WUs, the shutdown does not leave corrupted files.

Why can't a7 (or it's wrapper) manage these files correctly when the shutdown warning is issued?

See also https://foldingforum.org/viewtopic.php?f=106&t=32011&p=310002#p310002 and #1289.

January is history.  When can we beta-test those pending changes?

**Comment by shorttack** [comment]
Closed: duplicate #1314
