### ISSUE TITLE
Taking out a second video card and F@H goes crazy.

### ISSUE THREAD

**Issue by Sandman192** [FoldingAtHome/fah-issues#1317]
I toke out my second video card for varies reasons and folding not only give me an error it locks me out on changing anything in the main window and the config window.

It ran my CPU and main GPU just fine for a while and after a day my main GPU stops crunching. And the CPU and after that.

### Not asking for a fix since I'll reinstall F@H when I can. Locking out of settings is very strange.

The error I'm getting...

> On client "local" 127.xxx.xxx.xxx:xxxxx:
> Option 'gpu-index' has no default and is not set.
> iter should be a GtkTreelter

All folding "SLOTS" are empty.
In "WORK QUEUE", I've got ID 00, Status Downloading with 0.00% Progress and ETA Credit Unknown.
And ID 04, Status "blank" and stuck at 87.00% Progress and ETA 1 hours 57 mins and credit 17508 ALL GRADE OUT.
Even clicking "About" got me the popout window but can't even click on the 3 links in the about window.

**Comment by shorttack** [comment]
The proper way to yank a gpu is to remove the gpu from the config in FAHcontrol first. Then you can power down and remove the card. To fix this now, edit the FAH config.xml file and remove the GPU1 line so that FAH thinks you only have one gpu card. [You are not the first. I've done it myself.]
