### ISSUE TITLE
Snap package of FAH

### ISSUE THREAD

**Issue by fcole90** [FoldingAtHome/fah-issues#1319]
Hi, it would be very nice to have FAH as a snap, to be rapidly redistributable on many platforms, besides just Ubuntu and Fedora, and facilitating the package maintenance. However, I can't find the client available anywhere. Would it be fine to use the client that comes from the deb packages (the snap can run on top of a minimal Ubuntu 18.04 stack).

A discussion was also started here: [https://forum.snapcraft.io/t/a-snap-of-folding-at-home-against-covid19/16021](https://forum.snapcraft.io/t/a-snap-of-folding-at-home-against-covid19/16021)

**Comment by juanro49** [comment]
It's a great idea, other optios is a flatpak package

**Comment by fcole90** [comment]
Sure, that too :+1:

**Comment by fcole90** [comment]
Hi, we have a testing snap with some parts working, and some not. More info [here](https://forum.snapcraft.io/t/a-snap-of-folding-at-home-against-covid19/16021/13?u=fcole90).

If your system supports snap you can install it with: `snap install folding-at-home-fcole90 --edge`

I named it appending my username in order to reserve the proper folding-at-home name if FAH people want to use it to publish it. Please, let me know if you eventually intend to.

**Comment by fcole90** [comment]
Hi, I released the snap to the stable channel. So far it can only use CPUs, I have some problems letting it detect OpenCL. Nevertheless it is possible to compute, I got a job assigned and it seem to be working mostly well. 

If you want to test it, it is now available on the snap store.

[![Get it from the Snap Store](https://snapcraft.io/static/images/badges/en/snap-store-black.svg)](https://snapcraft.io/folding-at-home-fcole90)

**Comment by fcole90** [comment]
Hi, we are having some problem with the client not finding libOpenCL.so
The package contains a symlink to libOpenCL.so.1 provided by `ocl-icd-libopencl1`
```
ln -s usr/lib/x86_64-linux-gnu/libOpenCL.so usr/lib/x86_64-linux-gnu/libOpenCL.so1
```
It also has access to nvidia drivers:
```
$ snap run --shell folding-at-home.FAHClient  # run shell inside the snap sandbox 
$ cat /etc/OpenCL/vendors/nvidia.icd 
libnvidia-opencl.so.1
$ ls /var/lib/snapd/hostfs/usr/lib/x86_64-linux-gnu/libnvidia-opencl.so.1
/var/lib/snapd/hostfs/usr/lib/x86_64-linux-gnu/libnvidia-opencl.so.1
```

Where does the client expects to find libOpenCL.so? And how does it detect it?

**Comment by fcole90** [comment]
There was actually some issue with the library path, the snap is hence almost ready.

**Comment by shorttack** [comment]
Join the conversation at [Q&A about unsupported distros of Linux

https://foldingforum.org/viewforum.php?f=89](url)
