### ISSUE TITLE
Android client

### ISSUE THREAD

**Issue by darkdragon-001** [FoldingAtHome/fah-issues#1321]
Please create a new Android client since the old one [is discontinued](https://foldingathome.org/2018/02/02/android-client-overhaul/).

**Comment by IzzySoft** [comment]
And when doing so, please leave the Twitter SDK and Fabric out, for privacy reasons. That's not needed for the purpose. If people want to tweet whatever, they can use Android's built-in share functionality :wink:

Ideally, make the app fully FOSS and available at [F-Droid](https://f-droid.org/) :heart_eyes:

Thanks! :green_heart:

**Comment by user8446** [comment]
If this can be put on the shortlist all of the Android TV devices with high end GPU's can be put to work also like the NVIDIA Shield

**Comment by shorttack** [comment]
Closed: Android client enhancement request has been made before.

**Comment by IzzySoft** [comment]
When referring to "before": may we kindly ask to link to it? The link bel… oops, above is an issue created *after* – and doesn't have the "before" link either. I see no open issue mentioning Android – but neither an Android client available (so you cannot mean a solved issue). :confused:

**Comment by talregev** [comment]
How it complicated that you will come back to boinc? Already have a client in android, and you will not need to develop it from zero.

**Comment by user8446** [comment]
@IzzySoft 
They are probably referring to the fork from the old Sony application: https://github.com/FoldingAtHome/FAHAndroid

**Comment by IzzySoft** [comment]
Thanks @user8446 – I didn't know of the fork! But that one is archived, with its last commit in 6/2017, so it cannot be the one they actively develop now.

Would be nice to have an official word – and an issue kept open until its solved. Closing with just "has been asked before" sounds a bit like "and we said no" (no offense meant). Guess we all understand if priorities are somewhere else these days; but getting it closed without details is pretty much discouraging.

**Comment by user8446** [comment]
Completely agree

**Comment by PantherX** [comment]
Based on historical knowledge, new clients/platforms that are under development are generally not announced at all. There are no ETA's no updates just silence. Out of the blue, there's an announcement of new client/platform. Reason is that if the deadline of X was given and couldn't be met due to changing priorities, it causes issue.

The last official word is that the overhaul of the back-end is required before relaunching the Android Client: https://foldingforum.org/viewtopic.php?f=100&t=30663

**Comment by IzzySoft** [comment]
An ETA is one thing we didn't even ask for (yet). And open-source software doesn't just pop up out of the blue, it's usually developed – openly. Always best to let the users participate as early as possible – after all, they are the ones who will use it in the end. Decisions are adjusted more easily in the early phase, so if one values its users, that's where they should be included.

Thanks for the link to the forum @PantherX. So the new Android client was announced being in the works more than 2 years ago – and the last comment on that thread was made in 5/2018. Not that much convincing at all. To be honest: with 2 years silence and issues asking for a comment closed without information, this rather seems dead to me.

> In October 2017 we announced […] the open sourcing of the Folding@Home Android client

Notice the word "open"? That also means "visible".

> But we will keep you posted.

Yepp. That was in 2/2018. Since then no post, no news. It's dead, Jim?

**Comment by PantherX** [comment]
There's still hope for Android -> https://github.com/FoldingAtHome/fah-issues/issues/1358#issuecomment-613439667

**Comment by IzzySoft** [comment]
Thanks @PantherX – that killed my last hope:

> Android is under consideration

Almost 3 years after the initial announcement, it still is "under consideration" (not "in development", not even "in planning"). So I'd be surprised if something pops up before 2030. But then, I like positive surprises :wink:

@shorttack don't get me wrong. Explicit thanks for the clear words – so at least we know where we stand. And I certainly agree if you say you have to focus on other demands currently. Besides, if you'd leave one of those issues open, you might have less others to close as duplicates :wink:

**Comment by user8446** [comment]
I just checked and the Sony version is up on APKMirror: https://www.apkmirror.com/apk/sony-mobile-communications/foldinghome/foldinghome-1-00-61-release/#whatsnew

I installed it and it works and it switched to "contributing time" as soon as your battery is over 98%, on WiFi, and a charger plugged in. I didn't have time to let it run long enough to see if the "contribution details" populates though... maybe others can test also

**Comment by IzzySoft** [comment]
I certainly won't install it, thanks to the trackers it brings along (see my first post above), sorry @user8446.

**Comment by user8446** [comment]
At least on the latest version 1.00.61 that I linked there are only two trackers in that APK. Facebook & Google Analytics... how many installs are there, what type device, that sort of thing. Nothing intrusive because there aren't any permissions requested. It's also open source.

**Comment by IzzySoft** [comment]
Pardon me: "Facebook" and "nothing intrusive" in the same paragraph – I'm out. An app doesn't need *any* permissions to access quite sensitive details. Just take a look at [PrivacyBreacher](https://apt.izzysoft.de/fdroid/index/apk/io.nandandesai.privacybreacher) if you need a show-case for a tiny part of that.

Any module contained in an app has access to everything the app itself has access to, because it's part of it. Neither the Facebook SDK nor Google Analytics are "open source" – they are proprietary modules the dev has not much control over. So just because the dev did not explicitly tell FB/GA to collect X, it doesn't mean they don't do that on their own. And sorry, they do. And usually *before* the user is asked for consent.

Saying "nothing intrusive because there aren't any permissions requested" is like saying "that man cannot be dangerous because he has no weapons". Greetings from Chuck Norris :wink:

**Comment by user8446** [comment]
Like you I prefer open source also, but the truth is you just can't get everything open source or not have some influence from big tech - at least to be able to live a normal life. 
Github is owned by MS but you are still using it. Android is developed by Google but you obviously have an Android device. I bet you also have an Amazon, Facebook, and Twitter account also.

Here's something you may or may not know... unless you have an alternative ROM on your phone and stripped out google play services, even if you installed zero apps - go to https://takeout.google.com/ and download your "Android Device Configuration Service" and you'll see everything is already known about your device anyway. 

If you feel facebook or google knowing you run F&H on your mobile device is so bad that you won't be helping the researchers find a COVID-19 treatment then that's your decision and opinion.

As a side note until an Android dev forks the project and makes it more privacy preserving, AppCloner can anonymize device IMEI, ESN, Android ID on devices.

**Comment by IzzySoft** [comment]
We're getting slightly off-topic here, but to shortly answer your questions: I've moved almost all my projects to Codeberg.org (the last two will follow as soon as time permits). My Android devices run custom ROMs without GApps. And no, I don't have Facebook, Twitter, Instagram want whatsnot accounts (find me in the Fediverse instead). And I don't use a Google account (so nothing to "takeout" there). I don't use Play Store either (but F-Droid instead). The F@H client runs on multiple of my machines, if you wonder if I "won't be helping" (~100k credits with ~60 WUs per week). And I still think I'm "able to live a normal life" :wink: So: sorry, but you've lost that bet :rofl:

Thanks for the side note, that might help some! But how does that anonymize IMEI & Co? According to its description (and especially the video) it just creates a clone of an app (by re-installing it using a different package name). What you'd rather want is [Shelter](https://f-droid.org/packages/net.typeblog.shelter/) then, which isolates apps in separate "sandboxes".

Maybe someone would even be able to fork that dead Android project and just compile it w/o those SDKs, if the app still works and gets WUs which are accepted. I'd even offer to host it in [my F-Droid repo](https://apt.izzysoft.de/fdroid) then.

**Comment by user8446** [comment]
To be able to function only on FOSS... impressive

What  AppCloner does is clone the app and fakes the device identity to that app: https://twitter.com/AppCloner/status/1235612260061646850

I agree it would be great if an Android dev could fork it and remove those trackers. I wish that was my skill set. 

Thanks for offering to host... hopefully the right person will see that.

**Comment by IzzySoft** [comment]
> To be able to function only on FOSS

That would be the goal, yeah – hence my repo in addition to F-Droids, to extend the selection for all similar minded. I still use few proprietary apps from sources I trust though, such as Titanium Backup (got the Pro directly from Jöel, so no Google License Check).

> https://nitter.net/AppCloner/status/1235612260061646850

Wow, that's cool indeed! And the app itself [has no trackers](https://reports.exodus-privacy.eu.org/en/reports/125646/)!

And yes, my hosting offer stands – waiting for the app…

**Comment by TPS** [comment]
Sadly, the closest app I can find that functions on my devices is [DreamLab](https://play.google.com/store/apps/details?id=au.com.vodafone.dreamlabapp) — I've run the old Android F@H client, but it has no real evidence of proper use (idle cores are all I see), & BOINC is too complicated (diverse failing logins).

**Comment by IzzySoft** [comment]
Well, and DreamLab comes [with multiple trackers](https://reports.exodus-privacy.eu.org/en/reports/134484/). I'll never understand why one needs multiple analytics modules (here: 3 of them). And if an app's primary purpose is to serve a good cause like this, ad modules are also misplaced. This, together with the fact it's not even mentioned (neither in the app description nor on the page they point to), in my eyes disqualifies DreamLab. Being proprietary and thus not available outside the "walled gardens" adds to that.

That said, were there a FOSS F@H app, I'd certainly install that on all my Android devices and let it fold whenever they are connected to a power source (an option to start folding when connected and pause when disconnected would be great for this). Would probably help me moving up from the top 8% to the top 5% of "folders" :smile:

**Comment by talregev** [comment]
@TPS I didn't understand what the problem with BOINC?
What device you have and android version on it?

**Comment by user8446** [comment]
All,
[World Community Grid](https://www.worldcommunitygrid.org/) now has their Covid-19 folding project up. You can contribute through BOINC [(no trackers)](https://reports.exodus-privacy.eu.org/en/reports/edu.berkeley.boinc/latest/) . You can fine tune it to have it only run when charging, percent of processor used, etc. So now I have the PC's running F&H and World Community Grid running on all the android devices.

**Comment by talregev** [comment]
For boinc Covid-19 support you have several projects:
- WCG: https://www.worldcommunitygrid.org/
- Rosseta@Home: https://boinc.bakerlab.org/
- Ibercivis BOINC: https://boinc.ibercivis.es/

Feel free to add more.

**Comment by user8446** [comment]
I could never get Rosetta@Home to work. It would error out saying out of RAM on every device tried, even of 4gb devices. Bug reports posted in their forum were no help.

**Comment by talregev** [comment]
It say yellow warning about ram. but after a while when it have a task, it give you.

**Comment by darkdragon-001** [comment]
To me it seemed that the first batch of tasks required more RAM. The latest batches worked for me without problems. They just don't seem to have that many ARM tasks for the many smartphone and raspberry pi users.

Does anyone know where I can find information about Open Science principles for the BOINC projects? If I donate my processing power, I want the results to be freely available for everyone.

**Comment by talregev** [comment]
You can try to ask it on boinc discord channel:
Discord: https://discord.com/
https://discord.gg/WsKUsBZ

**Comment by TPS** [comment]
> @TPS I didn't understand what the problem with BOINC?
> What device you have and android version on it? 

@talregev Diverse problems also, on multiple devices.   Mostly, it's just not worth establishing more individual accounts for each cause 1's interested in, but, many times, over multiple manufacturer's, I'd download & attempt, but get nowhere, w/ some problems like those others had above.  Dreamlab, on the devices I tried, is simply install & run.

**Comment by talregev** [comment]
Can you tell me what the problems? 
Most of the problems we solve in the master, and we support now armv7 device with android 4.1 and above. 
If you have many devices like me and you want to add many projects it really handle to use account manger. 
I am using https://www.boincstats.com/bam/.
If you want I can send you unofficial apk from the master.

**Comment by darkdragon-001** [comment]
Account managers are definitely the right way to go. Just waiting for account managers to be able to delete accounts (see BOINC/boinc#2507). Single account deletion is possible already ([Wiki](https://boinc.berkeley.edu/trac/wiki/RightToErasure), [Github](https://github.com/BOINC/boinc/pull/2472)).

**Comment by darkdragon-001** [comment]
> You can try to ask it on boinc discord channel:
> https://discord.gg/WsKUsBZ

I [just asked](https://discord.com/channels/605398931479724074/605398932067188768/726572603166425188). Thanks for the hint!
