### ISSUE TITLE
Package the client also for opensuse

### ISSUE THREAD

**Issue by SchoolGuy** [FoldingAtHome/fah-issues#1323]
Hi guys, I wanted to contribute with my GPU but since I run opensuse there is no client available. If I install the unsigned package with broken dependencies it runs into the following issue.

````
FAHClient: error while loading shared libraries: libssl.so.10: cannot open shared object file: No such file or directory
````

**Comment by SchoolGuy** [comment]
The opensuse wiki entry which is available is also dead because apparently the link to the zip is dead: https://en.opensuse.org/Folding@Home

**Comment by Mirppc** [comment]
It is strange.  I got Folding@Home running on one of my leap 15.1 machines with no issues.  Tried installing it on another and ran into the same issues as above.  

Staticly linked both libcrypto.so.1.0.0 and libcrypto.so.1.1 to libcrypto.so.10 as well as libssl.so.1.0.0 and libssl.so.1.1 to libssl.so.10 to even more strangeness.

Redacted@Redacted:/usr/lib64> FAHClient 
FAHClient: /usr/lib64/libssl.so.10: version libssl.so.10' not found (required by FAHClient)
FAHClient: /usr/lib64/libcrypto.so.10: version OPENSSL_1.0.1_EC' not found (required by FAHClient)
FAHClient: /usr/lib64/libcrypto.so.10: version `libcrypto.so.10' not found (required by FAHClient)

This is highly perplexing as i have it working just fine on one machine using the redhat RPM's.

**Comment by andreaswachowski** [comment]
I was able to get it to work on OpenSUSE Tumbleweed by installing the openssl-libs package from Fedora. Specifically, I installed openssl-libs-1.0.1k-13.fc22.x86_64 from https://apps.fedoraproject.org/packages/openssl/builds/ (direct link to that version https://koji.fedoraproject.org/koji/buildinfo?buildID=667727 ). I haven't tried other versions, just tried to find the latest 1.0.1.

I used `rpm -i --nodeps` to ignore the missing dependencies. The client now runs just fine and accepts both CPU (Intel Core i7-6700T) and GPU (Nvidia GTX 970) tasks.

**Comment by Mirppc** [comment]
That solution conflicts with the already existing openssl 1.0 that is installed on my system which is 1.0.2p.  @andreaswachowski  so your workaround is not a valid one in the majority of cases.

**Comment by SchoolGuy** [comment]
Guys installing Redhat Packages on a SUSE system is not a real solution. That is like building a BMW engine into a VW. It may work with 100 of modifications but you will never know if it worked completely except you know how to build a car. There is a reason why you build packages for different distros and not one package for all. In the Open Build Service you would be able to build with one specfile for all distros (also via debbuild you would build for Debian/Ubuntu).

Also please remember that not every Linux-User is a 10+ years Senior Linux Distribution Architect how knows how to get around this.

**Comment by Mirppc** [comment]
> Guys installing Redhat Packages on a SUSE system is not a real solution. That is like building a BMW engine into a VW. It may work with 100 of modifications but you will never know if it worked completely except you know how to build a car. There is a reason why you build packages for different distros and not one package for all. In the Open Build Service you would be able to build with one specfile for all distros (also via debbuild you would build for Debian/Ubuntu).
> 
> Also please remember that not every Linux-User is a 10+ years Senior Linux Distribution Architect how knows how to get around this.

This is exactly why i linked the Openssl 1.0.1 built for Opensuse.  It is not the correct and good coice as it will cause issues with the more secure 1.0.2 and 1.1 that is the default.

To corilate with @SchoolGuy  and something that has been bashed into my head by the opensuse community is "DONT MIX SYSTEM PACKAGES FROM OTHER DISTROS!" Anonymous Opensuse Member 2007

And to updated it is is not suggested to mix older opensuse packages as well hence why i made the above repo i linked.  It was branched off a much older repo for a EOL version of Opensuse.  I made sure it builds for several version.  Do i recommend it in this case. NO

**Comment by shorttack** [comment]
Join the conversation: Q&A about unsupported distros of Linux
[](https://foldingforum.org/viewforum.php?f=89)

**Comment by Mirppc** [comment]
Why dont you link to it here then instead of just telling us to go to some mysterious Q&A.

**Comment by SchoolGuy** [comment]
@shorttack This was neither resolved or it was explained why you don't do this. So please do so instead of just closing.

**Comment by andreaswachowski** [comment]
@shorttack I have to agree with @Mirppc and @SchoolGuy . Presumably (?!) you are referring us to https://foldingforum.org/viewforum.php?f=89 , but we'd like a properly packaged build for opensuse, since the available packages are not working. We are not hunting for workarounds (if I gave that impression above, that wasn't my intent). Github seems the proper place to raise this, if not, then please justify.

**Comment by Mirppc** [comment]
Redhat and other supported distros should be dropping openssl 1.0.1 like a bleeding heart... Oh yeah, that is one of the vulnerabilities of openssl1.0.1.

**Comment by SchoolGuy** [comment]
And there is even more problems when using FAH on opensuse: https://foldingforum.org/viewtopic.php?f=89&t=31637

**Comment by Mirppc** [comment]
I followed that and got nowhere. Hence why I am here.

**Comment by PantherX** [comment]
It's my understanding that officially, only the following platforms are supported:

- Debian
- Mint
- Ubuntu
- Redhat
- Centos
- Fedora

Thus, openSUSE is unsupported. However, if any one of the above packages could work on openSUSE but not now then it might be a bug fix which may be considered.

**Comment by SchoolGuy** [comment]
@PantherX You can build for openSUSE with minimal adoptions via a cross distro specfile. There is a good tutorial for that: https://en.opensuse.org/openSUSE:Build_Service_cross_distribution_howto

In the forum linked by @andreaswachowski you see that people are trying to use openSUSE since 12.3 which was back in 2013, so there is an audience which wants to use the client on it.

P.S.: I guess you mean above instead of Redhat RHEL. Because otherwise Redhat would mean you support ClearOS for example, as well as the one you listed.
P.P.S.: I would volunteer to maintain the package build for openSUSE, depending on how you build your packages exaclty.

**Comment by PantherX** [comment]
@SchoolGuy 
Thanks for the link and your offer! However, I will leave it up to the @FoldingAtHome/client-dev  to comment on this further. :)

**Comment by Mirppc** [comment]
It should not be that difficult either using the Open Build Service too as the RHEL packages can be built against that while the SUSE ones can be built on SUSE, then take the deb and have it build across the multitude of Debian like distributions.  I cannot begin to say how much of a pain it was to get FAH working on PopOS 19.10 (ubuntu Eoan based).  

On another note i am glad there is so much dissatisfaction with the way that @shorttack dealt with this issue.

**Comment by SchoolGuy** [comment]
Are you really hardcoded depending on that openssl version? - https://github.com/FoldingAtHome/docker-core-linux-build-environment/blob/master/Dockerfile

I am now even more confused.

**Comment by shorttack** [comment]
> It's my understanding that officially, only the following platforms are supported:

Debian
Mint
Ubuntu
Redhat
Centos
Fedora
Thus, openSUSE is unsupported.

openSUSE is not a supported version. Support for unsupported Linux distros is at foldingforum.org. The request here for openSUSE is labeled as a Linux Enhancement request. Thanks for your interest.
