### ISSUE TITLE
FAHClient only use one core per time?

### ISSUE THREAD

**Issue by juanro49** [FoldingAtHome/fah-issues#1324]
Hi, I'm playing around with the FAHClient configuration with FAHControl and I've noticed that even though I have selected to use multiple cores, it only uses one at a time. Is there any way that instead of using just one at 100% you can use multi-core at 50% for example?

![imagen](https://user-images.githubusercontent.com/11600804/77006494-d9340d00-6962-11ea-9c11-0d58c5c8981f.png)

**Comment by juanro49** [comment]
With cpu-usage tag in config.xml, we can limit cpu usage, for example, to limit at 75% cpu usage, we neet to add this tag in config.xml <cpu-usage v='75'/>

Now we have to see if it can be enabled to use multiple cores at once.

**Comment by juanro49** [comment]
I reinstalled FAHClient with option system service enabled (Start launch yes), and now it use multicore correctly.

If we launch FAHClient from terminal, it use only one core.

**Comment by dmc5179** [comment]
@juanro49 Launching from terminal vs the GUI should not result in different outcomes. Would it be possible to run it in a terminal and then do:

```
ps -eaf | grep -i fah
```

Then stop the client running in the terminal, start it from the GUI, and run the ps command in the terminal again. This should reveal if different options are being passed to the fahclient binary depending on who starts it.

**Comment by PantherX** [comment]
Please note that if you need help with setup, you can visit the official F@H Forum for support: https://foldingforum.org/index.php

**Comment by tomek3001** [comment]
> 
> 
> With cpu-usage tag in config.xml, we can limit cpu usage, for example, to limit at 75% cpu usage, we neet to add this tag in config.xml <cpu-usage v='75'/> (for gpu, use gpu-usage)
> 
> Now we have to see if it can be enabled to use multiple cores at once.

where can I find config.xml?

**Comment by PantherX** [comment]
> 
> 
> > With cpu-usage tag in config.xml, we can limit cpu usage, for example, to limit at 75% cpu usage, we neet to add this tag in config.xml  (for gpu, use gpu-usage)
> > Now we have to see if it can be enabled to use multiple cores at once.
> 
> where can I find config.xml?

On Windows, assuming default installation, it is in either of these two locations:
%AppData%\FAHClient
%ProgramData%\FAHClient
