### ISSUE TITLE
How to reverse proxy the web control panel?

### ISSUE THREAD

**Issue by virtadpt** [FoldingAtHome/fah-issues#1325]
Hi.  I've got the FAH client running on one of my machines.  I would like to reverse proxy the web panel (localhost:7369) through Nginx, so I don't have to SSH into the machine and set up a local port forward.  I've made it as far as proxying http://localhost:7369/ (the basedir) and http://localhost:7369/images:
```
location /fah {
    proxy_set_header Host $http_host;
    proxy_pass http://localhost:7396/;
}

# Yes, I know this really should be /fah/images - one step at a time.
location /images {
    proxy_pass http://localhost:7396/images/;
}
```
However, when I try to proxy /js the control panel goes into an endless load/refresh loop.  The page never finishes loading and I have to stop it manually.  This does not seem to affect FAHclient doing its thing, though.  Here's what I tried:
```
# Yes, I know this really should be /fah/js.
location /js {
    proxy_pass http://localhost:7396/js/;
}
```
I've been searching for about a week now and haven't found any signs that someone's done this before.  Can you help?

**Comment by shorttack** [comment]
@virtadpt This forum is for reporting bugs, enhancements and issues with the FAH software. The folks at [https://foldingforum.org/index.php](url) are best suited to help you with your proxy script. I suggest you copy your post there.
-Issues Team-
