### ISSUE TITLE
FAH not detect OpenCL

### ISSUE THREAD

**Issue by mrdev023** [FoldingAtHome/fah-issues#1328]
FAH not detect OpenCL in fedora with nvidia driver because the library is name libOpenCL.so.1 and not libOpenCL.so.

I found workaround for this problem with this command 
```sh
$ sudo ln -s /usr/lib64/libOpenCL.so.1 /usr/lib64/libOpenCL.so 
``` 

Is not possible to fix that ?

I'm try negativo17 and fedora fusion repo.

**Comment by dmc5179** [comment]
@mrdev023 The fahclient v7.5.1 sometimes has issues detecting the card if there is more than one openCL provider. We ran into this issue on Fedora as well and I had to remove a couple of packages. I'm looking for the thread now. We also had folks try v7.4 with success and not have to remove any packages. Try an older client version, or perhaps the new 7.6.2

**Comment by shorttack** [comment]
Version 7.6.x is in beta and can be found at [https://foldingathome.org/beta/](url). Please try the beta and if that does not work, report another issue report here mentioning "FAH not detect OpenCL #1328". Thanks.
_Issue Support Team _
