### ISSUE TITLE
ERROR:WU00:FS00:Exception: Failed reading core package header.

### ISSUE THREAD

**Issue by MrKingofRome** [FoldingAtHome/fah-issues#1329]
So i have the following problems, on my GPU Slot (Project 11760) i get the following Message in the log:

12:58:23:WU00:FS00:Downloading core from http://cores.foldingathome.org/v7/win/64bit/Core_22.fah
12:58:23:WU00:FS00:Connecting to cores.foldingathome.org:80
12:58:23:ERROR:WU00:FS00:Exception: Failed reading core package header.

and i cant find anything what causes it, and how i could solve the error.

And on the CPU Slot ( Project showed 0):

13:00:34:WU01:FS01:Connecting to 65.254.110.245:8080
13:00:35:WARNING:WU01:FS01:Failed to get assignment from '65.254.110.245:8080': No WUs available for this configuration
13:00:35:WU01:FS01:Connecting to 18.218.241.186:80
13:00:35:WARNING:WU01:FS01:Failed to get assignment from '18.218.241.186:80': No WUs available for this configuration
13:00:35:ERROR:WU01:FS01:Exception: Could not get an assignment

but i think that is just because there are not enough WU available for the CPU

EDIT#1:

After a reboot my CPU gets the same Massage:

13:13:51:WU01:FS01:Downloading core from http://cores.foldingathome.org/v7/win/64bit/avx/Core_a7.fah
13:13:51:WU01:FS01:Connecting to cores.foldingathome.org:80
13:13:57:ERROR:WU01:FS01:Exception: Failed reading core package header.

Now both are waiting on FahCore Update

Greetings from Germany

**Comment by shorttack** [comment]
@MrKingofRome Are you still having this issue? Your problem occurred during a period of unprecedented increases in folding network traffic volume. If you are still having this problem, reply and I will reopen the case. Let me also suggest you join the discussion at [https://foldingforum.org/index.php](url) where operating issues are solved.
