### ISSUE TITLE
Automatic Pause Function

### ISSUE THREAD

**Issue by jokarl3000** [FoldingAtHome/fah-issues#1330]
Hi!

I think it could be useful if the folding @ home program would have an automatic stop function after a finished job, or that you could choose how many projects hours you want to spend under a day. Then I could go safely sleeping knowing that it's not running 24/7 causing large electrical bills. :)

**Comment by sopex** [comment]
The first is already implemented you just press the "Finish" button and F@H finishes the current job and then stops.

**Comment by jonstacks** [comment]
This seems like it might have functionality in common with #639.

**Comment by shorttack** [comment]
> functionality in common with #639. <

Note Folding@Home stops on the Finish command when done. This suggestion and #639 passed on as enhancements.
