### ISSUE TITLE
Please support FreeBSD

### ISSUE THREAD

**Issue by dyeske** [FoldingAtHome/fah-issues#1334]
After looking at the client it appears that FreeBSD could be supported. The ctypes call could be changed to use something more portable or FreeBSD specific instead of prctl(). This could be made into a FreeBSD port probably starting with the command line client first.  Then glade support could be fixed later.  I have created about 40 FreeBSD ports.

**Comment by shorttack** [comment]
The folding project has limited volunteer resources, so we cannot take on another OS. We support six popular versions of Linux. Please visit Q&A about unsupported distros of Linux/Unix at [https://foldingforum.org/viewforum.php?f=89](url)
