### ISSUE TITLE
Please create pure web client

### ISSUE THREAD

**Issue by dyeske** [FoldingAtHome/fah-issues#1335]
The pure web client could do mathematical calculations on systems where the user might not have the skills or access to install software.  It should support common desktop browsers.

This could start with something simple like mathjs https://mathjs.org  or MathML https://www.w3.org/Math/whatIsMathML.html or Crunch http://crunch.js.org?

**Comment by shorttack** [comment]
Folding@Home used the NACL code in Google Chrome to run folding inside the Chrome browser. It was difficult to maintain, and did not work on non-Chromium browser. Support was dropped last year. Thanks for your suggestion.
