### ISSUE TITLE
Missing source code

### ISSUE THREAD

**Issue by paulmenzel** [FoldingAtHome/fah-issues#1338]
Where can I access the source code for fahclient, mentioned on the [Start folding page](https://foldingathome.org/start-folding/)?

`usr/share/doc/fahclient/README.md` from March 2018 in the [Debian package][1] mentions https://github.com/FoldingAtHome/fah-client, but that project is not available anymore (404 returned by GitHub).

Having the source, would allow people to easily adapt it to their environment, like asked for in
https://github.com/FoldingAtHome/coronavirus/issues/49. Additionally, a lot of organizations do not allow to run arbitrary binary blobs.

[1]: https://download.foldingathome.org/releases/public/release/fahclient/debian-stable-64bit/v7.5/fahclient_7.5.1_amd64.deb

**Comment by dmc5179** [comment]
@paulmenzel The F@H team has put forth the position that if people could see the code then they could cheat the system and the science would then be unreliable. I don't think that's a compelling argument long term and has likely contributed to a slower pace of SW development.

**Comment by paulmenzel** [comment]
@shorttack, can this please be documented somewhere visible to save people from looking for the source in vain?

PS: If it’s possible to cheat the system, hiding the source won’t help, and the system shouldn’t be trusted.

**Comment by shorttack** [comment]
@paulmenzel Yes, I will document that parts of the project are not open source. BTW I understand that the FAHcontrol will be open sourced at some point.
