### ISSUE TITLE
AMD OpenCL Error initializing context: clCreateCommandQueue (-6)

### ISSUE THREAD

**Issue by Lovett1991** [FoldingAtHome/fah-issues#1342]
Don't seem to be able to run any WU's on my GPU...
System
```
19:09:37:******************************* System ********************************
19:09:37:            CPU: Intel(R) Pentium(R) CPU G3258 @ 3.20GHz
19:09:37:         CPU ID: GenuineIntel Family 6 Model 60 Stepping 3
19:09:37:           CPUs: 2
19:09:37:         Memory: 7.71GiB
19:09:37:    Free Memory: 7.37GiB
19:09:37:        Threads: POSIX_THREADS
19:09:37:     OS Version: 5.4
19:09:37:    Has Battery: false
19:09:37:     On Battery: false
19:09:37:     UTC Offset: 1
19:09:37:            PID: 858
19:09:37:            CWD: /opt/fah
19:09:37:             OS: Linux 5.4.28-1-MANJARO x86_64
19:09:37:        OS Arch: AMD64
19:09:37:           GPUs: 1
19:09:37:          GPU 0: Bus:1 Slot:0 Func:0 AMD:5 R575A [Radeon R7 250X/HD 7700/8760]
19:09:37:           CUDA: Not detected: Failed to open dynamic library 'libcuda.so':
19:09:37:                 libcuda.so: cannot open shared object file: No such file or
19:09:37:                 directory
19:09:37:OpenCL Device 0: Platform:0 Device:0 Bus:NA Slot:NA Compute:1.1 Driver:19.3
19:09:37:OpenCL Device 1: Platform:1 Device:0 Bus:1 Slot:0 Compute:1.2 Driver:3004.6
19:09:37:***********************************************************************
```

Logs,

```
/opt/fah/logs/log-20200329-190937.txt:16:22:45:WU02:FS01:Requesting new work unit for slot 01: READY gpu:0:R575A [Radeon R7 250X/HD 7700/8760] from 128.252.203.10
/opt/fah/logs/log-20200329-190937.txt:16:22:45:WU02:FS01:Connecting to 128.252.203.10:8080
/opt/fah/logs/log-20200329-190937.txt:16:23:54:WU02:FS01:Downloading 50.74MiB
/opt/fah/logs/log-20200329-190937.txt:16:24:00:WU02:FS01:Download 9.85%
/opt/fah/logs/log-20200329-190937.txt:16:24:06:WU02:FS01:Download 21.31%
/opt/fah/logs/log-20200329-190937.txt:16:24:12:WU02:FS01:Download 29.56%
/opt/fah/logs/log-20200329-190937.txt:16:24:18:WU02:FS01:Download 38.93%
/opt/fah/logs/log-20200329-190937.txt:16:24:24:WU02:FS01:Download 51.61%
/opt/fah/logs/log-20200329-190937.txt:16:24:30:WU02:FS01:Download 64.80%
/opt/fah/logs/log-20200329-190937.txt:16:24:36:WU02:FS01:Download 77.98%
/opt/fah/logs/log-20200329-190937.txt:16:24:42:WU02:FS01:Download 94.24%
/opt/fah/logs/log-20200329-190937.txt:16:24:44:WU02:FS01:Download complete
/opt/fah/logs/log-20200329-190937.txt:16:24:44:WU02:FS01:Received Unit: id:02 state:DOWNLOAD error:NO_ERROR project:11762 run:0 clone:7780 gen:12 core:0x22 unit:0x0000001880fccb0a5e7113d265405335
/opt/fah/logs/log-20200329-190937.txt:16:24:44:WU02:FS01:Starting
/opt/fah/logs/log-20200329-190937.txt:16:24:44:WU02:FS01:Running FahCore: /opt/fah/FAHCoreWrapper /opt/fah/cores/cores.foldingathome.org/v7/lin/64bit/Core_22.fah/FahCore_22 -dir 02 -suffix 01 -version 705 -lifeline 856 -checkpoint 15 -gpu-vendor amd -opencl-platform 1 -opencl-device 0 -gpu 0
/opt/fah/logs/log-20200329-190937.txt:16:24:44:WU02:FS01:Started FahCore on PID 1796
/opt/fah/logs/log-20200329-190937.txt:16:24:44:WU02:FS01:Core PID:1800
/opt/fah/logs/log-20200329-190937.txt:16:24:44:WU02:FS01:FahCore 0x22 started
/opt/fah/logs/log-20200329-190937.txt:16:24:44:WU02:FS01:0x22:*********************** Log Started 2020-03-29T16:24:44Z ***********************
/opt/fah/logs/log-20200329-190937.txt:16:24:44:WU02:FS01:0x22:*************************** Core22 Folding@home Core ***************************
/opt/fah/logs/log-20200329-190937.txt:16:24:44:WU02:FS01:0x22:       Type: 0x22
/opt/fah/logs/log-20200329-190937.txt:16:24:44:WU02:FS01:0x22:       Core: Core22
/opt/fah/logs/log-20200329-190937.txt:16:24:44:WU02:FS01:0x22:    Website: https://foldingathome.org/
/opt/fah/logs/log-20200329-190937.txt:16:24:44:WU02:FS01:0x22:  Copyright: (c) 2009-2018 foldingathome.org
/opt/fah/logs/log-20200329-190937.txt:16:24:44:WU02:FS01:0x22:     Author: John Chodera <john.chodera@choderalab.org> and Rafal Wiewiora
/opt/fah/logs/log-20200329-190937.txt:16:24:44:WU02:FS01:0x22:             <rafal.wiewiora@choderalab.org>
/opt/fah/logs/log-20200329-190937.txt:16:24:44:WU02:FS01:0x22:       Args: -dir 02 -suffix 01 -version 705 -lifeline 1796 -checkpoint 15
/opt/fah/logs/log-20200329-190937.txt:16:24:44:WU02:FS01:0x22:             -gpu-vendor amd -opencl-platform 1 -opencl-device 0 -gpu 0
/opt/fah/logs/log-20200329-190937.txt:16:24:44:WU02:FS01:0x22:     Config: <none>
/opt/fah/logs/log-20200329-190937.txt:16:24:44:WU02:FS01:0x22:************************************ Build *************************************
/opt/fah/logs/log-20200329-190937.txt:16:24:44:WU02:FS01:0x22:    Version: 0.0.2
/opt/fah/logs/log-20200329-190937.txt:16:24:44:WU02:FS01:0x22:       Date: Dec 6 2019
/opt/fah/logs/log-20200329-190937.txt:16:24:44:WU02:FS01:0x22:       Time: 21:20:17
/opt/fah/logs/log-20200329-190937.txt:16:24:44:WU02:FS01:0x22: Repository: Git
/opt/fah/logs/log-20200329-190937.txt:16:24:44:WU02:FS01:0x22:   Revision: f87d92b58abdf7e6bf2e173cfbc4dc3e837c7042
/opt/fah/logs/log-20200329-190937.txt:16:24:44:WU02:FS01:0x22:     Branch: core22
/opt/fah/logs/log-20200329-190937.txt:16:24:44:WU02:FS01:0x22:   Compiler: GNU 4.8.2 20140120 (Red Hat 4.8.2-15)
/opt/fah/logs/log-20200329-190937.txt:16:24:44:WU02:FS01:0x22:    Options: -std=gnu++98 -O3 -funroll-loops
/opt/fah/logs/log-20200329-190937.txt:16:24:44:WU02:FS01:0x22:   Platform: linux2 4.9.87-linuxkit-aufs
/opt/fah/logs/log-20200329-190937.txt:16:24:44:WU02:FS01:0x22:       Bits: 64
/opt/fah/logs/log-20200329-190937.txt:16:24:44:WU02:FS01:0x22:       Mode: Release
/opt/fah/logs/log-20200329-190937.txt:16:24:44:WU02:FS01:0x22:************************************ System ************************************
/opt/fah/logs/log-20200329-190937.txt:16:24:44:WU02:FS01:0x22:        CPU: Intel(R) Pentium(R) CPU G3258 @ 3.20GHz
/opt/fah/logs/log-20200329-190937.txt:16:24:44:WU02:FS01:0x22:     CPU ID: GenuineIntel Family 6 Model 60 Stepping 3
/opt/fah/logs/log-20200329-190937.txt:16:24:44:WU02:FS01:0x22:       CPUs: 2
/opt/fah/logs/log-20200329-190937.txt:16:24:44:WU02:FS01:0x22:     Memory: 7.71GiB
/opt/fah/logs/log-20200329-190937.txt:16:24:44:WU02:FS01:0x22:Free Memory: 5.63GiB
/opt/fah/logs/log-20200329-190937.txt:16:24:44:WU02:FS01:0x22:    Threads: POSIX_THREADS
/opt/fah/logs/log-20200329-190937.txt:16:24:44:WU02:FS01:0x22: OS Version: 5.4
/opt/fah/logs/log-20200329-190937.txt:16:24:44:WU02:FS01:0x22:Has Battery: false
/opt/fah/logs/log-20200329-190937.txt:16:24:44:WU02:FS01:0x22: On Battery: false
/opt/fah/logs/log-20200329-190937.txt:16:24:44:WU02:FS01:0x22: UTC Offset: 1
/opt/fah/logs/log-20200329-190937.txt:16:24:44:WU02:FS01:0x22:        PID: 1800
/opt/fah/logs/log-20200329-190937.txt:16:24:44:WU02:FS01:0x22:        CWD: /opt/fah/work
/opt/fah/logs/log-20200329-190937.txt:16:24:44:WU02:FS01:0x22:         OS: Linux 5.4.28-1-MANJARO x86_64
/opt/fah/logs/log-20200329-190937.txt:16:24:44:WU02:FS01:0x22:    OS Arch: AMD64
/opt/fah/logs/log-20200329-190937.txt:16:24:44:WU02:FS01:0x22:********************************************************************************
/opt/fah/logs/log-20200329-190937.txt:16:24:44:WU02:FS01:0x22:Project: 11762 (Run 0, Clone 7780, Gen 12)
/opt/fah/logs/log-20200329-190937.txt:16:24:44:WU02:FS01:0x22:Unit: 0x0000001880fccb0a5e7113d265405335
/opt/fah/logs/log-20200329-190937.txt:16:24:44:WU02:FS01:0x22:Reading tar file core.xml
/opt/fah/logs/log-20200329-190937.txt:16:24:44:WU02:FS01:0x22:Reading tar file integrator.xml
/opt/fah/logs/log-20200329-190937.txt:16:24:44:WU02:FS01:0x22:Reading tar file state.xml
/opt/fah/logs/log-20200329-190937.txt:16:24:44:WU02:FS01:0x22:Reading tar file system.xml
/opt/fah/logs/log-20200329-190937.txt:16:24:44:WU02:FS01:0x22:Digital signatures verified
/opt/fah/logs/log-20200329-190937.txt:16:24:44:WU02:FS01:0x22:Folding@home GPU Core22 Folding@home Core
/opt/fah/logs/log-20200329-190937.txt:16:24:44:WU02:FS01:0x22:Version 0.0.2
/opt/fah/logs/log-20200329-190937.txt:16:24:48:WU02:FS01:0x22:ERROR:exception: Error initializing context: clCreateCommandQueue (-6)
/opt/fah/logs/log-20200329-190937.txt:16:24:48:WU02:FS01:0x22:Saving result file ../logfile_01.txt
/opt/fah/logs/log-20200329-190937.txt:16:24:48:WU02:FS01:0x22:Saving result file science.log
/opt/fah/logs/log-20200329-190937.txt:16:24:48:WU02:FS01:0x22:Folding@home Core Shutdown: BAD_WORK_UNIT
/opt/fah/logs/log-20200329-190937.txt:16:24:48:WARNING:WU02:FS01:FahCore returned: BAD_WORK_UNIT (114 = 0x72)
/opt/fah/logs/log-20200329-190937.txt:16:24:48:WU02:FS01:Sending unit results: id:02 state:SEND error:FAULTY project:11762 run:0 clone:7780 gen:12 core:0x22 unit:0x0000001880fccb0a5e7113d265405335
```
I've got `opencl-amd` install and `clinfo` shows up as:

```
Number of platforms                               2
  Platform Name                                   Clover
  Platform Vendor                                 Mesa
  Platform Version                                OpenCL 1.1 Mesa 19.3.5
  Platform Profile                                FULL_PROFILE
  Platform Extensions                             cl_khr_icd
  Platform Extensions function suffix             MESA

  Platform Name                                   AMD Accelerated Parallel Processing
  Platform Vendor                                 Advanced Micro Devices, Inc.
  Platform Version                                OpenCL 2.1 AMD-APP (3004.6)
  Platform Profile                                FULL_PROFILE
  Platform Extensions                             cl_khr_icd cl_amd_event_callback cl_amd_offline_devices 
  Platform Host timer resolution                  1ns
  Platform Extensions function suffix             AMD

  Platform Name                                   Clover
Number of devices                                 1
  Device Name                                     AMD Radeon HD 7700 Series (VERDE, DRM 3.35.0, 5.4.28-1-MANJARO, LLVM 9.0.1)
  Device Vendor                                   AMD
  Device Vendor ID                                0x1002
  Device Version                                  OpenCL 1.1 Mesa 19.3.5
  Driver Version                                  19.3.5
  Device OpenCL C Version                         OpenCL C 1.1 
  Device Type                                     GPU
  Device Profile                                  FULL_PROFILE
  Device Available                                Yes
  Compiler Available                              Yes
  Max compute units                               10
  Max clock frequency                             950MHz
  Max work item dimensions                        3
  Max work item sizes                             256x256x256
  Max work group size                             256
  Preferred work group size multiple              64
  Preferred / native vector sizes                 
    char                                                16 / 16      
    short                                                8 / 8       
    int                                                  4 / 4       
    long                                                 2 / 2       
    half                                                 8 / 8        (cl_khr_fp16)
    float                                                4 / 4       
    double                                               2 / 2        (cl_khr_fp64)
  Half-precision Floating-point support           (cl_khr_fp16)
    Denormals                                     No
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 No
    Round to infinity                             No
    IEEE754-2008 fused multiply-add               No
    Support is emulated in software               No
  Single-precision Floating-point support         (core)
    Denormals                                     No
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 No
    Round to infinity                             No
    IEEE754-2008 fused multiply-add               No
    Support is emulated in software               No
    Correctly-rounded divide and sqrt operations  No
  Double-precision Floating-point support         (cl_khr_fp64)
    Denormals                                     Yes
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 Yes
    Round to infinity                             Yes
    IEEE754-2008 fused multiply-add               Yes
    Support is emulated in software               No
  Address bits                                    64, Little-Endian
  Global memory size                              3221225472 (3GiB)
  Error Correction support                        No
  Max memory allocation                           858993459 (819.2MiB)
  Unified memory for Host and Device              No
  Minimum alignment for any data type             128 bytes
  Alignment of base address                       32768 bits (4096 bytes)
  Global Memory cache type                        None
  Image support                                   No
  Local memory type                               Local
  Local memory size                               32768 (32KiB)
  Max number of constant args                     16
  Max constant buffer size                        858993459 (819.2MiB)
  Max size of kernel argument                     1024
  Queue properties                                
    Out-of-order execution                        No
    Profiling                                     Yes
  Profiling timer resolution                      0ns
  Execution capabilities                          
    Run OpenCL kernels                            Yes
    Run native kernels                            No
  Device Extensions                               cl_khr_byte_addressable_store cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_fp64 cl_khr_fp16

  Platform Name                                   AMD Accelerated Parallel Processing
Number of devices                                 1
  Device Name                                     Capeverde
  Device Vendor                                   Advanced Micro Devices, Inc.
  Device Vendor ID                                0x1002
  Device Version                                  OpenCL 1.2 AMD-APP (3004.6)
  Driver Version                                  3004.6
  Device OpenCL C Version                         OpenCL C 1.2 
  Device Type                                     GPU
  Device Board Name (AMD)                         AMD Radeon HD 7700 Series
  Device Topology (AMD)                           PCI-E, 01:00.0
  Device Profile                                  FULL_PROFILE
  Device Available                                Yes
  Compiler Available                              Yes
  Linker Available                                Yes
  Max compute units                               5
  SIMD per compute unit (AMD)                     4
  SIMD width (AMD)                                16
  SIMD instruction width (AMD)                    1
  Max clock frequency                             950MHz
  Graphics IP (AMD)                               6.0
  Device Partition                                (core)
    Max number of sub-devices                     5
    Supported partition types                     None
    Supported affinity domains                    (n/a)
  Max work item dimensions                        3
  Max work item sizes                             1024x1024x1024
  Max work group size                             256
  Preferred work group size (AMD)                 256
  Max work group size (AMD)                       1024
  Preferred work group size multiple              64
  Wavefront width (AMD)                           64
  Preferred / native vector sizes                 
    char                                                 4 / 4       
    short                                                2 / 2       
    int                                                  1 / 1       
    long                                                 1 / 1       
    half                                                 1 / 1        (n/a)
    float                                                1 / 1       
    double                                               1 / 1        (cl_khr_fp64)
  Half-precision Floating-point support           (n/a)
  Single-precision Floating-point support         (core)
    Denormals                                     No
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 Yes
    Round to infinity                             Yes
    IEEE754-2008 fused multiply-add               Yes
    Support is emulated in software               No
    Correctly-rounded divide and sqrt operations  Yes
  Double-precision Floating-point support         (cl_khr_fp64)
    Denormals                                     Yes
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 Yes
    Round to infinity                             Yes
    IEEE754-2008 fused multiply-add               Yes
    Support is emulated in software               No
  Address bits                                    32, Little-Endian
  Global memory size                              416051200 (396.8MiB)
  Global free memory (AMD)                        <printDeviceInfo:78: get number of CL_DEVICE_GLOBAL_FREE_MEMORY_AMD : error -33>
  Global memory channels (AMD)                    4
  Global memory banks per channel (AMD)           16
  Global memory bank width (AMD)                  256 bytes
  Error Correction support                        No
  Max memory allocation                           218059571 (208MiB)
  Unified memory for Host and Device              No
  Minimum alignment for any data type             128 bytes
  Alignment of base address                       2048 bits (256 bytes)
  Global Memory cache type                        Read/Write
  Global Memory cache size                        16384 (16KiB)
  Global Memory cache line size                   64 bytes
  Image support                                   Yes
    Max number of samplers per kernel             16
    Max size for 1D images from buffer            134217728 pixels
    Max 1D or 2D image array size                 2048 images
    Base address alignment for 2D image buffers   256 bytes
    Pitch alignment for 2D image buffers          256 pixels
    Max 2D image size                             16384x16384 pixels
    Max 3D image size                             2048x2048x2048 pixels
    Max number of read image args                 128
    Max number of write image args                8
  Local memory type                               Local
  Local memory size                               32768 (32KiB)
  Local memory syze per CU (AMD)                  65536 (64KiB)
  Local memory banks (AMD)                        32
  Max number of constant args                     8
  Max constant buffer size                        65536 (64KiB)
  Preferred constant buffer size (AMD)            16384 (16KiB)
  Max size of kernel argument                     1024
  Queue properties                                
    Out-of-order execution                        No
    Profiling                                     Yes
  Prefer user sync for interop                    Yes
  Profiling timer resolution                      1ns
  Profiling timer offset since Epoch (AMD)        1585508947944099852ns (Sun Mar 29 20:09:07 2020)
  Execution capabilities                          
    Run OpenCL kernels                            Yes
    Run native kernels                            No
    Thread trace supported (AMD)                  No
    Number of async queues (AMD)                  2
    Max real-time compute queues (AMD)            0
    Max real-time compute units (AMD)             1208989160
    SPIR versions                                 1.2
  printf() buffer size                            4194304 (4MiB)
  Built-in kernels                                (n/a)
  Device Extensions                               cl_khr_fp64 cl_amd_fp64 cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_3d_image_writes cl_khr_byte_addressable_store cl_khr_gl_sharing cl_amd_device_attribute_query cl_amd_vec3 cl_amd_printf cl_amd_media_ops cl_amd_media_ops2 cl_amd_popcnt cl_khr_image2d_from_buffer cl_amd_bus_addressable_memory cl_khr_spir cl_khr_gl_event 


NULL platform behavior
  clGetPlatformInfo(NULL, CL_PLATFORM_NAME, ...)  Clover
  clGetDeviceIDs(NULL, CL_DEVICE_TYPE_ALL, ...)   Success [MESA]
  clCreateContext(NULL, ...) [default]            Success [MESA]
  clCreateContext(NULL, ...) [other]              Success [AMD]
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_DEFAULT)  Success (1)
    Platform Name                                 Clover
    Device Name                                   AMD Radeon HD 7700 Series (VERDE, DRM 3.35.0, 5.4.28-1-MANJARO, LLVM 9.0.1)
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CPU)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_GPU)  Success (1)
    Platform Name                                 Clover
    Device Name                                   AMD Radeon HD 7700 Series (VERDE, DRM 3.35.0, 5.4.28-1-MANJARO, LLVM 9.0.1)
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ACCELERATOR)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CUSTOM)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ALL)  Success (1)
    Platform Name                                 Clover
    Device Name                                   AMD Radeon HD 7700 Series (VERDE, DRM 3.35.0, 5.4.28-1-MANJARO, LLVM 9.0.1)

ICD loader properties
  ICD loader Name                                 OpenCL ICD Loader
  ICD loader Vendor                               OCL Icd free software
  ICD loader Version                              2.2.12
  ICD loader Profile                              OpenCL 2.2
```

I've only found one other person with this issue and there isn't any solutions on the FoldingForums. Is this a problem with the code or is this a problem with my setup?

**Comment by jath03** [comment]
I am having the same problem.  It looks like that function `clCreateCommandQueue` might be depracated in newer opencl versions.  https://community.khronos.org/t/deprecated-clcreatecommandqueue-avoids-profiling/7561  It's a problem between the opencl amdgpu-pro driver and the code, but I'm not sure which side is the issue.  
`clinfo`:

    Number of platforms                               2
      Platform Name                                   AMD Accelerated Parallel Processing
      Platform Vendor                                 Advanced Micro Devices, Inc.
      Platform Version                                OpenCL 2.1 AMD-APP (3004.6)
      Platform Profile                                FULL_PROFILE
      Platform Extensions                             cl_khr_icd cl_amd_event_callback cl_amd_offline_devices 
      Platform Host timer resolution                  1ns
      Platform Extensions function suffix             AMD
    
      Platform Name                                   NVIDIA CUDA
      Platform Vendor                                 NVIDIA Corporation
      Platform Version                                OpenCL 1.2 CUDA 10.2.141
      Platform Profile                                FULL_PROFILE
      Platform Extensions                             cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_fp64 cl_khr_byte_addressable_store cl_khr_icd cl_khr_gl_sharing cl_nv_compiler_options cl_nv_device_attribute_query cl_nv_pragma_unroll cl_nv_copy_opts cl_nv_create_buffer cl_khr_int64_base_atomics cl_khr_int64_extended_atomics
      Platform Extensions function suffix             NV
    
      Platform Name                                   AMD Accelerated Parallel Processing
    Number of devices                                 1
      Device Name                                     Pitcairn
      Device Vendor                                   Advanced Micro Devices, Inc.
      Device Vendor ID                                0x1002
      Device Version                                  OpenCL 1.2 AMD-APP (3004.6)
      Driver Version                                  3004.6
      Device OpenCL C Version                         OpenCL C 1.2 
      Device Type                                     GPU
      Device Board Name (AMD)                         AMD Radeon(TM) HD 8800 Series
      Device Topology (AMD)                           PCI-E, 0a:00.0
      Device Profile                                  FULL_PROFILE
      Device Available                                Yes
      Compiler Available                              Yes
      Linker Available                                Yes
      Max compute units                               10
      SIMD per compute unit (AMD)                     4
      SIMD width (AMD)                                16
      SIMD instruction width (AMD)                    1
      Max clock frequency                             1070MHz
      Graphics IP (AMD)                               6.0
      Device Partition                                (core)
        Max number of sub-devices                     10
        Supported partition types                     None
        Supported affinity domains                    (n/a)
      Max work item dimensions                        3
      Max work item sizes                             1024x1024x1024
      Max work group size                             256
      Preferred work group size (AMD)                 256
      Max work group size (AMD)                       1024
      Preferred work group size multiple              64
      Wavefront width (AMD)                           64
      Preferred / native vector sizes                 
        char                                                 4 / 4       
        short                                                2 / 2       
        int                                                  1 / 1       
        long                                                 1 / 1       
        half                                                 1 / 1        (n/a)
        float                                                1 / 1       
        double                                               1 / 1        (cl_khr_fp64)
      Half-precision Floating-point support           (n/a)
      Single-precision Floating-point support         (core)
        Denormals                                     No
        Infinity and NANs                             Yes
        Round to nearest                              Yes
        Round to zero                                 Yes
        Round to infinity                             Yes
        IEEE754-2008 fused multiply-add               Yes
        Support is emulated in software               No
        Correctly-rounded divide and sqrt operations  Yes
      Double-precision Floating-point support         (cl_khr_fp64)
        Denormals                                     Yes
        Infinity and NANs                             Yes
        Round to nearest                              Yes
        Round to zero                                 Yes
        Round to infinity                             Yes
        IEEE754-2008 fused multiply-add               Yes
        Support is emulated in software               No
      Address bits                                    32, Little-Endian
      Global memory size                              2121617408 (1.976GiB)
      Global free memory (AMD)                        <printDeviceInfo:78: get number of CL_DEVICE_GLOBAL_FREE_MEMORY_AMD : error -33>
      Global memory channels (AMD)                    8
      Global memory banks per channel (AMD)           16
      Global memory bank width (AMD)                  256 bytes
      Error Correction support                        No
      Max memory allocation                           1578780262 (1.47GiB)
      Unified memory for Host and Device              No
      Minimum alignment for any data type             128 bytes
      Alignment of base address                       2048 bits (256 bytes)
      Global Memory cache type                        Read/Write
      Global Memory cache size                        16384 (16KiB)
      Global Memory cache line size                   64 bytes
      Image support                                   Yes
        Max number of samplers per kernel             16
        Max size for 1D images from buffer            134217728 pixels
        Max 1D or 2D image array size                 2048 images
        Base address alignment for 2D image buffers   256 bytes
        Pitch alignment for 2D image buffers          256 pixels
        Max 2D image size                             16384x16384 pixels
        Max 3D image size                             2048x2048x2048 pixels
        Max number of read image args                 128
        Max number of write image args                8
      Local memory type                               Local
      Local memory size                               32768 (32KiB)
      Local memory syze per CU (AMD)                  65536 (64KiB)
      Local memory banks (AMD)                        32
      Max number of constant args                     8
      Max constant buffer size                        65536 (64KiB)
     Preferred constant buffer size (AMD)            16384 (16KiB)
      Max size of kernel argument                     1024
      Queue properties                                
        Out-of-order execution                        No
        Profiling                                     Yes
      Prefer user sync for interop                    Yes
      Profiling timer resolution                      1ns
      Profiling timer offset since Epoch (AMD)        1585688502491863160ns (Tue Mar 31 14:01:42 2020)
      Execution capabilities                          
        Run OpenCL kernels                            Yes
        Run native kernels                            No
        Thread trace supported (AMD)                  No
        Number of async queues (AMD)                  2
        Max real-time compute queues (AMD)            0
        Max real-time compute units (AMD)             0
        SPIR versions                                 1.2
      printf() buffer size                            4194304 (4MiB)
      Built-in kernels                                (n/a)
      Device Extensions                               cl_khr_fp64 cl_amd_fp64 cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_3d_image_writes cl_khr_byte_addressable_store cl_khr_gl_sharing cl_amd_device_attribute_query cl_amd_vec3 cl_amd_printf cl_amd_media_ops cl_amd_media_ops2 cl_amd_popcnt cl_khr_image2d_from_buffer cl_amd_bus_addressable_memory cl_khr_spir cl_khr_gl_event 

      Platform Name                                   NVIDIA CUDA
    Number of devices                                 1
      Device Name                                     GeForce GTX 1660 SUPER
      Device Vendor                                   NVIDIA Corporation
      Device Vendor ID                                0x10de
      Device Version                                  OpenCL 1.2 CUDA
      Driver Version                                  440.64
      Device OpenCL C Version                         OpenCL C 1.2 
      Device Type                                     GPU
      Device Topology (NV)                            PCI-E, 09:00.0
      Device Profile                                  FULL_PROFILE
      Device Available                                Yes
      Compiler Available                              Yes
      Linker Available                                Yes
      Max compute units                               22
      Max clock frequency                             1860MHz
      Compute Capability (NV)                         7.5
      Device Partition                                (core)
        Max number of sub-devices                     1
        Supported partition types                     None
        Supported affinity domains                    (n/a)
      Max work item dimensions                        3
      Max work item sizes                             1024x1024x64
      Max work group size                             1024
      Preferred work group size multiple              32
      Warp size (NV)                                  32
      Preferred / native vector sizes                 
        char                                                 1 / 1       
        short                                                1 / 1       
        int                                                  1 / 1       
        long                                                 1 / 1       
        half                                                 0 / 0        (n/a)
        float                                                1 / 1       
        double                                               1 / 1        (cl_khr_fp64)
      Half-precision Floating-point support           (n/a)
      Single-precision Floating-point support         (core)
        Denormals                                     Yes
        Infinity and NANs                             Yes
        Round to nearest                              Yes
        Round to zero                                 Yes
        Round to infinity                             Yes
        IEEE754-2008 fused multiply-add               Yes
        Support is emulated in software               No
        Correctly-rounded divide and sqrt operations  Yes
      Double-precision Floating-point support         (cl_khr_fp64)
        Denormals                                     Yes
        Infinity and NANs                             Yes
        Round to nearest                              Yes
        Round to zero                                 Yes
        Round to infinity                             Yes
        IEEE754-2008 fused multiply-add               Yes
        Support is emulated in software               No
      Address bits                                    64, Little-Endian
      Global memory size                              6230114304 (5.802GiB)
      Error Correction support                        No
      Max memory allocation                           1557528576 (1.451GiB)
      Unified memory for Host and Device              No
      Integrated memory (NV)                          No
      Minimum alignment for any data type             128 bytes
      Alignment of base address                       4096 bits (512 bytes)
      Global Memory cache type                        Read/Write
      Global Memory cache size                        720896 (704KiB)
      Global Memory cache line size                   128 bytes
      Image support                                   Yes
        Max number of samplers per kernel             32
        Max size for 1D images from buffer            268435456 pixels
        Max 1D or 2D image array size                 2048 images
        Max 2D image size                             32768x32768 pixels
        Max 3D image size                             16384x16384x16384 pixels
        Max number of read image args                 256
        Max number of write image args                32
      Local memory type                               Local
      Local memory size                               49152 (48KiB)
      Registers per block (NV)                        65536
      Max number of constant args                     9
      Max constant buffer size                        65536 (64KiB)
      Max size of kernel argument                     4352 (4.25KiB)
      Queue properties                                
        Out-of-order execution                        Yes
        Profiling                                     Yes
      Prefer user sync for interop                    No
      Profiling timer resolution                      1000ns
     Execution capabilities                          
        Run OpenCL kernels                            Yes
        Run native kernels                            No
        Kernel execution timeout (NV)                 Yes
      Concurrent copy and kernel execution (NV)       Yes
        Number of async copy engines                  3
      printf() buffer size                            1048576 (1024KiB)
      Built-in kernels                                (n/a)
      Device Extensions                               cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_fp64 cl_khr_byte_addressable_store cl_khr_icd cl_khr_gl_sharing cl_nv_compiler_options cl_nv_device_attribute_query cl_nv_pragma_unroll cl_nv_copy_opts cl_nv_create_buffer cl_khr_int64_base_atomics cl_khr_int64_extended_atomics


    NULL platform behavior
      clGetPlatformInfo(NULL, CL_PLATFORM_NAME, ...)  No platform
      clGetDeviceIDs(NULL, CL_DEVICE_TYPE_ALL, ...)   No platform
      clCreateContext(NULL, ...) [default]            No platform
      clCreateContext(NULL, ...) [other]              Success [AMD]
      clCreateContextFromType(NULL, CL_DEVICE_TYPE_DEFAULT)  Success (1)
        Platform Name                                 AMD Accelerated Parallel Processing
        Device Name                                   Pitcairn
      clCreateContextFromType(NULL, CL_DEVICE_TYPE_CPU)  No devices found in platform
      clCreateContextFromType(NULL, CL_DEVICE_TYPE_GPU)  Success (1)
        Platform Name                                 AMD Accelerated Parallel Processing
        Device Name                                   Pitcairn
      clCreateContextFromType(NULL, CL_DEVICE_TYPE_ACCELERATOR)  No devices found in platform
      clCreateContextFromType(NULL, CL_DEVICE_TYPE_CUSTOM)  No devices found in platform
      clCreateContextFromType(NULL, CL_DEVICE_TYPE_ALL)  Success (1)
        Platform Name                                 AMD Accelerated Parallel Processing
        Device Name                                   Pitcairn
            NOTE:   your OpenCL library only supports OpenCL 2.0,
                    but some installed platforms support OpenCL 2.1.
                    Programs using 2.1 features may crash
                    or behave unexpectedly

**Comment by shorttack** [comment]
Please ask this question and seek support at [https://foldingforum.org/viewforum.php?f=81](url)

This issues discussion does not resolve video driver issues. Thanks.
_-Issues Support-_
