### ISSUE TITLE
Username changes creates a new user instead of just a name change 

### ISSUE THREAD

**Issue by user8446** [FoldingAtHome/fah-issues#1345]
I changed my username on my team and noticed that it creates a completely new user with the new username with 0 points and leaves the old name and stats on the team. 

The expected behavior would be to only change the username and keep the same stats and points.

**Comment by shorttack** [comment]
Names are unique and permanent. If you change your name, points start at zero and the new name is treated as a new user. That's not going to change as eighteen years of history are based on that premise.
