### ISSUE TITLE
(Tiny enhancement for) the FINISH option.

### ISSUE THREAD

**Issue by bb30994** [FoldingAtHome/fah-issues#1346]
If I set FINISH, it works exactly like it's supposed to provided the current WU passes 100% where it continues to upload the results and pauses before download the next WU.

Unfortunately, if the current WU has an error and processing is aborted, the FINISH flag is not examined.  The error report is uploaded to the server and A NEW WU IS DOWNLOADED.

Come on:  I told you I did not want a new WU.  You should check the flag before downloading the next WU.

**Comment by shorttack** [comment]
Non-critical defect.
