### ISSUE TITLE
FAHClient general protection fault

### ISSUE THREAD

**Issue by ComiR** [FoldingAtHome/fah-issues#1349]
Using client `fahclient_7.5.1_amd64.deb`.

Right after `sudo service FAHClient start`:
```
kernel: traps: FAHClient[10158] general protection fault ip:7f128310e9bd sp:7fffd0ea83f0 error:0 in libc-2.28.so[7f12830ac000+148000]
FAHClient[10154]: Starting fahclient ... /etc/init.d/FAHClient: Zeile 64: 10158 Speicherzugriffsfehler  $EXEC $OPTS > /dev/null 2> /dev/null
FAHClient[10154]: FAIL
```

**Comment by dmc5179** [comment]
- What version of debian are you running?
- Is this physical or virtual?
- Specs on the machine that this is running on ?

GPFs are often HW faults unrelated to a specific application. Check /var/log/messages and/or dmesg for any other related errors.

**Comment by shorttack** [comment]
Closed: no action taken. Comment back if you think this needs attention and we can identify the exact cause. Thanks.
_-Issues Team-_
