### ISSUE TITLE
Support old amd graphics card (with opencl)

### ISSUE THREAD

**Issue by talregev** [FoldingAtHome/fah-issues#1350]
I have an amd  AMD Radeon™ HD 6770M
Please add support for this driver.

**Comment by muziqaz** [comment]
> I have an amd AMD Radeon™ HD 6770M
> Please add support for this driver.

Folding@home requires cards to have at least minimal Double Precision support.
6770m does not support Double Precision, I'm afraid

**Comment by talregev** [comment]
Thank you for your answer.
Are you one of the developers?

**Comment by muziqaz** [comment]
Hi,
no. Just have been around FAH since 2004.

Thanks

**Comment by talregev** [comment]
I actually have more issues.
First:
The constant refresh on the web browser: #18

Second:
I want you to back again to boinc. 
I already have many android devices just ready to get your project on android. #1358

Third: 
I try your folding@home program, but it crash every couple hours. (Didn't run at least one day). even I finish some of the tasks, I understand I don't want to open it every time. I switch back to boinc on my pc.

**Comment by talregev** [comment]
> If you have other issues, please do not hesitate to join foldingforum.org

It more easy and intuitive to reports bug here as a developer myself.
I will not register in this forum only for bugs. That why folding@home open this repository, and I glad they did.

**Comment by shorttack** [comment]
Issue Support: Your first and second issues are already separately reported and will be acted on there. On your third issue, please try the 64-bit Folding client (not 32-bit) on 64-bit Windows.

This case is closed.

**Comment by talregev** [comment]
> On your third issue, please try the 64-bit Folding client (not 32-bit) on 64-bit Windows.
> 
> This case is closed.
@shorttack 
I guess you never run on windows. Because there isn't folding@home windows 64bit version.
Maybe we should create one? (issue and version).

**Comment by PantherX** [comment]
@talregev 
Regarding Windows, the installer installs FAHClient/FAHControl/FAHViewer. They are all 32-bit applications. However, FAHClient downloads FahCore_XX which is a 64-bit executable. Thus, while the installer installs 32-bit components, the actual work being done by FahCore_XX is 64-bit.

**Comment by talregev** [comment]
> Regarding Windows, the installer installs FAHClient/FAHControl/FAHViewer. They are all 32-bit applications. However, FAHClient downloads FahCore_XX which is a 64-bit executable. Thus, while the installer installs 32-bit components, the actual work being done by FahCore_XX is 64-bit.

Thank you for your answer.
Even if there isn't real necessary people keep asking about folding@home windows client for 64it.
If it not hard, and even absolute not give any new ability I will recommend just for people will not ask.
