### ISSUE TITLE
Does restart required to get available tasks?

### ISSUE THREAD

**Issue by ks1322** [FoldingAtHome/fah-issues#1351]
I have FAHClient installed on Linux.
Normally it is up and running, but at some point it stops with messages in log like this:
```
error:wu00:fs00:exception: could not get an assignment
```
No tasks were available for about several hours. But when I restarted FAHClient the task became available very soon:
```
$ sudo /etc/init.d/FAHClient restart 
Stopping fahclient ... OK
Starting fahclient ... OK
```
This sounds like a bug. Should I always restart FAHClient when there is no tasks available?

**Comment by bb30994** [comment]
Operational support for FAHClient can be obtained at foldingforum.org.

This is not a bug.  Interest in solving the COVAID issues has skyrocketed and FAH servers have been overwhelmed.  In spite increases in server capacity of more that 10x, demand has grown even faster. All of the servers are still bandwidth-limited.

A Stop/start rarely helps, but it's not a bug.

**Comment by dmc5179** [comment]
Agreed, this is not a bug. What you are running into is likely increased wait times each time the client is not able to get a WU. After awhile the wait times can be long. A pause/unpause resets the waits but doesn't guarantee a WU will be assigned.

'''
FAHClient --send-pause
sleep 5
FAHClient --send-unpause
```

**Comment by shorttack** [comment]
Not a functional issue.
