### ISSUE TITLE
Web Control bug reports don't go anywhere

### ISSUE THREAD

**Issue by bb30994** [FoldingAtHome/fah-issues#1353]
If someone reports a bug in the HELP page of the Web Control the reports do not appear here.

**Comment by shorttack** [comment]
Let's document where #webcontrol help reports end up. Hopefully, in a place where they can be acted upon. Otherwise, replace the Help page with a link to [https://github.com/FoldingAtHome/fah-issues/issues/](url) to report the problem.

**Comment by bb30994** [comment]
See also https://apps.foldingathome.org/bugreport.php

This appears to be an incomplete implementation of a feature that might have been useful but it's still up to somebody to make it work or eliminate it.  Let's mark it as an enhancement

**Comment by ffissore** [comment]
Since 7.6.8 the link brings folks on github. This issue can be closed @shorttack
