### ISSUE TITLE
Time series stats API endpoints do not work

### ISSUE THREAD

**Issue by anand-bhat** [FoldingAtHome/fah-issues#1354]
The [time series stats API](https://api.foldingathome.org/#GET-/time-series/:series/:period) doesn't appear to be working.

https://api.foldingathome.org/time-series/as/daily
`{"error":"Table 'ts.daily_as' doesn't exist","status":500}`

https://api.foldingathome.org/time-series/os/weekly
`{"error":"Table 'ts.weekly_os' doesn't exist","status":500}`

**Comment by jcoffland** [comment]
We had to disable the collection of time series data for now.  It did not hold up well with the onslaught of new data.  It will be resurrected when there is more time to work on it again.

**Comment by anand-bhat** [comment]
Thanks.
