### ISSUE TITLE
Add SELinux Support

### ISSUE THREAD

**Issue by dmc5179** [FoldingAtHome/fah-issues#1356]
The F@H Client has web sockets, as well as other features, which present an attack vector. Create an SELinux policy to support enhanced security on systems like RHEL, CentOS, Fedora, and Amazon Linux.

**Comment by dmc5179** [comment]
https://github.com/dmc5179/fah-selinux

**Comment by shorttack** [comment]
dmc5179 has the policy requested.

**Comment by dmc5179** [comment]
@shorttack I was referencing my initial work on SELinux support. I wrote this issue to see if the F@H team wanted to have the SElinux policy under their banner and ownership.

**Comment by shorttack** [comment]
Aha. My new job is to try to clean out the issues queue, which goes back to 2018. I’m trying to get things into the right inbox.
Thanks,
Pete
