### ISSUE TITLE
Website not showing CPU Core Number 

### ISSUE THREAD

**Issue by Guidowr** [FoldingAtHome/fah-issues#1357]
Not exactly a bug - either in Mac or in Win Version 7.6.3 beta the Website is showing for 8 cores for every core=number 1 .... if possible perhaps nice to see exact number of the core..

**Comment by jcoffland** [comment]
Can you provide a screenshot?

**Comment by Guidowr** [comment]
Instead of cpu=1 should be cpu=x

BTW: Installed beta on 9 Mac's (Imac and MacB, no issues so far). Good work!

[image: Bildschirmfoto 2020-04-11 um 09.21.28.png]

**Comment by jcoffland** [comment]
Sorry, the screenshot didn't come through.  You have to attached it on the GitHub issue page.  Attaching it to your email doesn't work.

**Comment by Guidowr** [comment]
![unnamed](https://user-images.githubusercontent.com/63493907/79055713-11b7c580-7c47-11ea-9060-e070ca6c75e3.png)

**Comment by jcoffland** [comment]
It's not the CPU id is the count of CPU cores.  So each of your CPU slots has one core.
