### ISSUE TITLE
Feature request: Android support

### ISSUE THREAD

**Issue by talregev** [FoldingAtHome/fah-issues#1358]
Do you have a plan for android support?

**Comment by shorttack** [comment]
Yes, Android is under consideration. No dates. Android would create a lot of computing-power supply, but right now the project is having difficulties keeping up with recent demand spike.

**Comment by shorttack** [comment]
Duplicate: https://github.com/FoldingAtHome/fah-issues/issues/1321 already logged for the same enhancement request
