### ISSUE TITLE
Causes - influenza and diabetes

### ISSUE THREAD

**Issue by anand-bhat** [FoldingAtHome/fah-issues#1359]
https://api.foldingathome.org/project/cause lists the following causes: ["unspecified","alzheimers","cancer","huntingtons","parkinsons","influenza","diabetes","covid-19"]

However, influenza and diabetes are missing from the Cause preference selector in the web client and advanced client. Considering that addition of these to the client requires a new release, would it be beneficial to add them now if these causes are in use?

**Comment by shorttack** [comment]
Will be fixed in 7.6.x
