### ISSUE TITLE
Bogus IP(s) in WU-servers list

### ISSUE THREAD

**Issue by ChrisTG7411** [FoldingAtHome/fah-issues#1361]
It seems there are a few strange IPs in the list of the WU servers.
I quite often see IPs like this here in the log:

10:27:32:ERROR:WU01:FS01:Exception: Failed to connect to 192.0.2.1:80

192.0.2.x is "reserved list" regarding IANA, so I doubt that there is really a server running on that IP?!

Unfortunately I haven't found a way to force my client to skip this non-responding server w/o deleting all config manually. Is there?

**Comment by Privacywonk** [comment]
I also got this IP assigned on a linux client. I could not get drivers loaded to interact with the GPU.

Correlation != causation but sharing a story that might. Sadly, I could not get the GPU working on that linux client with nvidia drivers. Giant PITA.

**Comment by ipkh** [comment]
According to the experts at the folding forum.
This means your slot in incapable of running a project.
Older and select Current AMD GPUs do not have enough DP capability to run Core 22 projects of which all new Covid-19 are.

**Comment by ChrisTG7411** [comment]
Well, if that's the usecase than this is a security flaw. If the client uses unassigned IPs as a marker for non-supported GPUs they should at least use an IP from a local network range that can not be routed from the internet. IMHO it would be best to set localhost aka 127.0.0.1 in that case.
Otherwise it may be possible for criminals to spread infected binaries by spoofing that unassigned IPs like 192.0.2.1.
A sane solution could be to implement a state system into the handshake with the assignment-servers that informs the client of it's unability to run the cores instead of settings unresponding IPs for the WU-servers.

**Comment by PantherX** [comment]
IP Address 192.0.2.1 can't be routed across the internet: https://ipinfo.io/bogon

**Comment by Yonseca** [comment]
Hi, 

I think this issue is related with #1309. If this IP appears when we have an unsupported GPU, why does my GPU appear in GPUs.txt file? Shouldn't it be blacklisted?

**Comment by PantherX** [comment]
@Yonseca 
Please note that the GPUs.txt file is a shared resource across all OSes (Windows, Linux, macOS) and it is actually a greylist, we blacklist unsupported GPUs and whitelist supported GPUs.

I am closing this issue as this isn't a bug or a security issue.

**Comment by ChrisTG7411** [comment]
> 
> 
> IP Address 192.0.2.1 can't be routed across the internet: https://ipinfo.io/bogon

Sorry to disagree here, but RFC5735 only says "192.0.2.0/24 (...) addresses within this
   block **do not legitimately appear** on the public Internet and can be
   used without any coordination with IANA or an Internet registry."

I still would recommend to be safe and use an IP from the localhost-range 127.0.0.0/8 instead here.

**Comment by bb30994** [comment]
00:22:22:WU01:FS01:Requesting new work unit for slot 01: READY gpu:0:Manhattan [Mobility Radeon HD 5000 Series] from 192.0.2.1
00:22:22:WU01:FS01:Connecting to 192.0.2.1:8080
00:22:25:WU00:FS00:Upload complete
00:22:25:WU00:FS00:Server responded PLEASE_WAIT (464)
00:22:25:WARNING:WU00:FS00:Failed to send results, will try again later

**Comment by ipkh** [comment]
If anything this is a stupid way to indicate gpu not supported.  If there is logic to do this redirect, it should be equally easy to put in a better notice.  It certainly creates a lot if uncertainty and there is no reason to burden the end user with deciphering this ip address message.

**Comment by shorttack** [comment]
1. Duplicate: "related with [#1309"](https://github.com/FoldingAtHome/fah-issues/issues/1309)
2. > this is a stupid way to indicate gpu not supported
I agree and call it a bug.

**Comment by bb30994** [comment]
The easiest way to reproduce this error is to attempt to configure a GPU on Mac_OS.  GPUs are NOT supported on OS-X so whether the GPU happens to be listed in GPUs.txt or not has no bearing on the error.  Intercept this error before it issues the message containing the bogus IP address and generate an appropriate error message.

**Comment by PantherX** [comment]
FYI, I will close this issue as a duplicate of #1309
