### ISSUE TITLE
Attempt direct connection when proxy connection fails

### ISSUE THREAD

**Issue by gabrielschulhof** [FoldingAtHome/fah-issues#1365]
Hello, and thank you for an amazing project!

I switch frequently between having a VPN on and turning it off. When it's on, Web browsing requires a proxy to be set.. Thus, in my system configuration I always have a proxy turned on. Web browsers fall back to direct connection when the proxy is unreachable, after a little delay. I accept this in exchange for the convenience of being able to turn the VPN on and off.

I have noticed that the Folding@Home client stops working when I turn off the VPN and leave the computer for a while, having to be restarted when I return and turn the VPN back on.

Thus, would it be possible to modify the client to attempt a direct connection whenever the proxy is unreachable?

**Comment by shorttack** [comment]
Please try your question at [https://foldingforum.org/index.php](url). They may be able to help you with a workaround. To the best of my knowledge, FAHClient establishes connections to various assignment and work servers and expects those connections to continue, or reestablish with the original route (e.g., not insert/remove a proxy).
_Issues Support Team_
