### ISSUE TITLE
FahClient beta 7.6.6 cannot connect with FahControl on Windows 7

### ISSUE THREAD

**Issue by informatorius** [FoldingAtHome/fah-issues#1368]
FahClient beta 7.6.6 cannot connect with FahControl on Windows 7. WebControl works. FahControl 7.5.1 worked before and can connect to FahClient beta 7.6.6
![grafik](https://user-images.githubusercontent.com/6989214/79268024-5f783c00-7e9a-11ea-83fa-ff578723f4eb.png)

**Comment by jonstacks** [comment]
@informatorius, can you try stopping the services and then start them again?

**Comment by informatorius** [comment]
There are no services running on Windows. Just FahClient and FahControl. Restart does not help same issue.

**Comment by bb30994** [comment]
Go to foldingforum.org and post your question there.  Start a new thread with the same title but leave out the mention of 7.6.6 or beta.  (It's so close to release that I think we can handle it there without causing a ruckus.)  Answer which userID you used when you installed it and did you accept the defaults.  I understand there may be a problem with the shorcuts delivered with this beta version.  I'll help you there in about 9 hours.
Go to %APPDATA%/FAHclient and find log.txt.  Post from ***SYSTEM*** forward a page or two.

**Comment by PantherX** [comment]
Also, have a look at this thread as it seems to be similar issue, FAHControl can't connect but WebControl works fine: https://foldingforum.org/viewtopic.php?f=61&t=34313

**Comment by informatorius** [comment]
Works now with default express installation. Failed with custom install for all users to C:\ProgramData with previous FahClient 7.5.1 installed

**Comment by jcoffland** [comment]
@informatorius only one copy of FAHClient can be running at a time.  It sounds to me like you have your v7.5.1 running with a password set on the command port.  The v7.6.6 FAHControl does not know this password.  But I'm just guessing.

**Comment by informatorius** [comment]
Yes that's it a password is set in FahControl from v7.5.1
