### ISSUE TITLE
Fah 7.6.6 Cannot install over 7.5.1 installation

### ISSUE THREAD

**Issue by ipkh** [FoldingAtHome/fah-issues#1370]
The 7.6.6 installer cannot upgrade 7.5.1 install
It removes files but cannot install the new files claiming they are in use.
I cannot remove the old installation as the uninstaller file is removed and Apps/Programs cannot find it.

**Comment by shorttack** [comment]
See #1369 as duplicate. Looks like a problem.

**Comment by ajacocks** [comment]
When opening these issues, please specify platform and operating system.

**Comment by ipkh** [comment]
Windows 10 Pro Version 1909
It fails the installer but clicking the info tab in FahControl shows 7.6.6

**Comment by ipkh** [comment]
7.6.7 does the same thing, the installer pauses over Extract ssleay32.dll if that helps any.
Info tab reports 7.6.7 as the version number upon relaunch of FAHClient.

**Comment by jcoffland** [comment]
@ipkh, you must have some other application using ``ssleay32.dll`` from the FAHClient install.  This is not normal but Windows will grab DLLs from anywhere.  You will have to stop the offending application.

**Comment by ipkh** [comment]
@jcoffland Any idea how to track that down?
Are all files being copied to the client directory?
I'll look into it tonight if you have any suggestions.
