### ISSUE TITLE
FAHClient does not detect any GPUs in Windows 10

### ISSUE THREAD

**Issue by amandablev** [FoldingAtHome/fah-issues#1372]
gpu.txt is on the system and the 2080 Super is listed. If I try to add a GPU slot, it lets me save, but then the slot does not appear. On the FAHclient startup log it says there are 0 GPUs.

**Comment by shorttack** [comment]
The Folding at Home user support community can assist you at [https://foldingforum.org/index.php](url)
_Issue Support_

**Comment by amandablev** [comment]
I performed more troubleshooting steps and was able to resolve the issue. However, 

Originally I had client version 7.5.1 installed and all was folding well for a month with CPU and GPU. Today I installed the latest Windows Update. After that reboot the 7.5.1 client was reporting my gpu as xxx. I had never seen this before. I tried removing and readding the slot and it still looked the same.

I took this opportunity to download the beta version 7.6.7. After uninstalling 7.5.1 and rebooting Windows, I installed 7.6.7. When I launched the client, it wasn't able to detect any GPUs. I stopped folding and went into my Windows update history. I uninstalled today's Windows update and rebooted. After the reboot the update was still listed. I did this 2 more times, but it never disappeared. However, when I opened the FAHControl 7.6.7 this time, I saw under system info that fahclient detected two GPUs. GPU 0 is the onboard Intel[xxx]. GPU 1 is the GeForce RTX 2080 Super.

I manually set the GPU to GPU 1 through FAHControl Configure and slots. Now the 2080 Super is shown as ready. There aren't any WUs for me to test to see if it works though.

**Comment by amandablev** [comment]
You probably want to reopen this issue as the Windows Update that wouldn't uninstall actually is not detected by Windows. Therefore, as soon as this update applies the next time, I could run into the same problem. Also, many other people will have this issue when they apply their Windows updates today and moving forward.

**Comment by shorttack** [comment]
Reopened, but more information is needed.

@amandablev what Windows update screwed up the working 7.5.1 install? Try reinstalling the graphics card driver.

Please post your issue at foldingforum.org. You will be helping lots of other folders who ran into problems with Patch Tuesday. You'll also get lost of support.

**Comment by amandablev** [comment]
I did reinstall the graphics card driver three times. Even after removing 7.5.1.

**Comment by amandablev** [comment]
4/15/20 Windows Update.
