### ISSUE TITLE
Beta version

### ISSUE THREAD

**Issue by j0taDasFestas** [FoldingAtHome/fah-issues#1376]
Hi there i installed beta version fah-installer_7.6.8_x86.exe but now my gpu isn't showing 
Asus Cerberus Nvidea GTX 1050TI OC 4GB
Thanks

**Comment by PantherX** [comment]
Please note that this is not the area to troubleshoot installation: https://github.com/FoldingAtHome/coronavirus#questions-or-feedback-about-running-foldinghome

Please post your log at the Official Forum: https://foldingforum.org/index.php where the issue can be investigated further.

I will close this issue now and the discussion can be carried at the Forum :)
