### ISSUE TITLE
Beta 7.6.8 Advanced Control cannot connect to local client

### ISSUE THREAD

**Issue by ipkh** [FoldingAtHome/fah-issues#1377]
Uninstalled 7.6.8 and reinstalled
Web control loaded fine but advanced control alternated between Connecting and Updating.
Window 10 Pro x64 1909

**Comment by informatorius** [comment]
Maybe it is this one? https://github.com/FoldingAtHome/fah-issues/issues/1368

**Comment by ajacocks** [comment]
Please verify that your Windows firewall isn't blocking port 36330, assuming that Web Control is running on a different host.

**Comment by informatorius** [comment]
Guess it is no firewall issue when both fahclient and fahcontrol run on the same machine. FahClient should be blocked in firewall if you don't access it through internet or local network.

**Comment by snis** [comment]
Get a similar behaviour, running on Linux.
Can't connect to localhost:36330.
The webpage localhost:7396 shows, but without data.
The log shows:
`16:09:13:ERROR:Socket not open`
`16:09:14:ERROR:Socket not open`
`16:09:17:ERROR:Socket not open`
`16:09:17:ERROR:Socket not open`
`16:09:22:ERROR:Socket not open`
`16:09:27:ERROR:Socket not open`
`16:09:32:ERROR:Socket not open`
`16:09:37:ERROR:Socket not open`
`16:09:40:10:127.0.0.1:New Web session`
`16:09:42:WARNING:14:127.0.0.1:500 HTTP INTERNAL SERVER ERROR /api/updates?_=1587226180452&sid=00c7428bf8ec9a9034f8b7e323941bde: Option 'gpu-index' has no default and is not set.`
`16:09:42:ERROR:HTTP_INTERNAL_SERVER_ERROR: Option 'gpu-index' has no default and is not set.`
`16:09:42:ERROR:Socket not open`
`16:09:44:WARNING:16:127.0.0.1:500 HTTP INTERNAL SERVER ERROR /api/updates?_=1587226180454&sid=00c7428bf8ec9a9034f8b7e323941bde: Option 'gpu-index' has no default and is not set.`
`16:09:44:ERROR:HTTP_INTERNAL_SERVER_ERROR: Option 'gpu-index' has no default and is not set.`
And so on.
I've tried to include my GPU in the config with:
`  <slot id='1' type='GPU'/>`
When I remove that line it works on both port 36330 and 7396

**Comment by shorttack** [comment]
@snis 

> I've tried to include my GPU in the config with:
<slot id='1' type='GPU'/>

Can you add a GPU slot in FAHControl? You have not posted the config.xml file, so I can only guess that your syntax is OK. Note that "advanced control alternated between Connecting and Updating" can happen with a bad config.xml file.

Can you please post your log and config files file in the Official Forum: https://foldingforum.org/index.php for the issue to be diagnosed? GitHub is not used for troubleshooting, the Forum is :)

**Comment by ipkh** [comment]
<config>
  
  <checkpoint v='30'/>

  
  <client-type v='beta'/>

  
  <verbosity v='5'/>

  
  <proxy v=':8080'/>

  
  <pause-on-start v='true'/>
  <power v='full'/>

  
  <passkey v='4ffd83aaf7ec5bdf0065cea5174a6132'/>
  <team v='41608'/>
  <user v='ipkh'/>

  
  <next-unit-percentage v='98'/>

  
  <slot id='2' type='GPU'/>
  <slot id='0' type='CPU'>
    <cpus v='6'/>
  </slot>
</config>

**Comment by shorttack** [comment]
@ipkh Is this still an issue with 7.6.13 or can I close it out?

> Here is my config.xml
Not received in prior post.
