### ISSUE TITLE
v7.6.9 Windows10 only runs as administrator, won't add GPU slots

### ISSUE THREAD

**Issue by ex-nerd** [FoldingAtHome/fah-issues#1380]
This is a continuation of #1369.

Now that 7.6.9 is released, I did a clean reinstall, but both the client and control apps will still only run if I right-click and "run as administrator".  I even manually deleted the FAH config from my local AppData directory because uninstall didn't always completely erase it for me.

I think the lack of GPU slots is due to the client trying and failing to launch automatically, and but setting up enough data for future runs to think there is just an empty list of whitelisted GPUs.

Actually, after running as administrator (and getting a CPU work unit), I still don't see where the data is downloading to, so I suspect there is some data folder somewhere that is not getting deleted, and may be interfering with my ability to do a clean install.

**Comment by PantherX** [comment]
Can you please post your log file in the Official Forum for troubleshooting: https://foldingforum.org/index.php

**Comment by ex-nerd** [comment]
Sure, but where do I find the log file for FAHContro.exel?  I don't even get any output when I try to run it from a command prompt.

FWIW, the client logs aren't helpful -- they show an "Unspecified error" trying to register a system tray icon, but then the service starts up, grabs a CPU work unit and goes to work.  It does seem to eventually grab GPUs.txt (it took about 5 minutes for this to show up, and I hadn't previously been that patient).

**Comment by PantherX** [comment]
Here's information of the log file: https://foldingforum.org/viewtopic.php?f=61&t=26036

**Comment by ex-nerd** [comment]
@PantherX  I don't see anything there about getting logs out of FAHControl.  For now, the client is mostly working fine (after several restarts/partial-uninstalls/reinstalls/manual-config-editing/reinstalls) ... it's FAHControl that won't open (unless I run it as administrator and bypass the warning messages).

**Comment by shorttack** [comment]
@ex-nerd As PantherX says, this is not the place to troubleshoot installations. Please post your information in the Official Forum for troubleshooting: https://foldingforum.org/index.php.

If I had to guess, you're on Windows logged into an account that is not the Administrator account but does have administrative privilages, or FAHcontrol is installed with untypical privileges. Thanks.

**Comment by ex-nerd** [comment]
Honesty, I thought "app does not start but produces no logs or error output" sounded like a bug, not an installation issue.
