### ISSUE TITLE
7.6.10 Beta - FahCore returned: INTERRUPTED (102 = 0x66)

### ISSUE THREAD

**Issue by JanosAudron** [FoldingAtHome/fah-issues#1384]
On 7.6.8 beta version, if you pause a slot which has 2 WU, one running and one downloading, that slot crashes and restart from last checkpoint.

EDIT: wrong information. Here is new log file:
https://github.com/FoldingAtHome/fah-issues/issues/1384#issuecomment-615831122

Expert global configuration

> next-unit-percentage: 90
> max-packet-size: big
> idle: true
> 

Slot expert configuration

> Paused: false
> Idle: false

Log

> 05:58:37:WU00:FS01:0x22:Completed 920000 out of 1000000 steps (92%)
> 06:01:35:WU00:FS01:0x22:Completed 930000 out of 1000000 steps (93%)
> 06:02:06:WU02:FS01:Connecting to 65.254.110.245:80
> 06:02:07:WARNING:WU02:FS01:Failed to get assignment from '65.254.110.245:80': No WUs available for this configuration
> 06:02:07:WU02:FS01:Connecting to 18.218.241.186:80
> 06:02:07:WU02:FS01:Assigned to work server 128.252.203.10
> 06:02:07:WU02:FS01:Requesting new work unit for slot 01: RUNNING gpu:0:GP106 [GeForce GTX 1060 3GB] 3935 from 128.252.203.10
> 06:02:07:WU02:FS01:Connecting to 128.252.203.10:8080
> 06:02:29:WARNING:WU02:FS01:WorkServer connection failed on port 8080 trying 80
> 06:02:29:WU02:FS01:Connecting to 128.252.203.10:80
> 06:02:50:ERROR:WU02:FS01:Exception: Failed to connect to 128.252.203.10:80: Impossibile stabilire la connessione. Risposta non corretta della parte connessa dopo l'intervallo di tempo oppure mancata risposta dall'host collegato.
> 06:04:22:FS01:Paused
> 06:04:22:FS01:Shutting core down
> 06:04:22:WU00:FS01:0x22:WARNING:Console control signal 1 on PID 1368
> 06:04:22:WU00:FS01:0x22:Exiting, please wait. . .
> 06:04:23:WU00:FS01:0x22:Folding@home Core Shutdown: INTERRUPTED
> 06:04:23:WU00:FS01:FahCore returned: INTERRUPTED (102 = 0x66)
> 06:04:25:FS01:Unpaused
> 06:04:25:WU00:FS01:Starting
> 06:04:25:WU00:FS01:Running FahCore: "C:\Program Files (x86)\FAHClient/FAHCoreWrapper.exe" E:\FoldingHome\cores/cores.foldingathome.org/v7/win/64bit/Core_22.fah/FahCore_22.exe -dir 00 -suffix 01 -version 706 -lifeline 15828 -checkpoint 15 -gpu-vendor nvidia -opencl-platform 0 -opencl-device 0 -cuda-device 0 -gpu 0
> 06:04:25:WU00:FS01:Started FahCore on PID 12612
> 06:04:25:WU00:FS01:Core PID:17952
> 06:04:25:WU00:FS01:FahCore 0x22 started
> 06:04:26:WU00:FS01:0x22:*********************** Log Started 2020-04-18T06:04:26Z ***********************
> 06:04:26:WU00:FS01:0x22:*************************** Core22 Folding@home Core ***************************
> 06:04:26:WU00:FS01:0x22:       Type: 0x22
> 06:04:26:WU00:FS01:0x22:       Core: Core22
> 06:04:26:WU00:FS01:0x22:    Website: https://foldingathome.org/
> 06:04:26:WU00:FS01:0x22:  Copyright: (c) 2009-2018 foldingathome.org
> 06:04:26:WU00:FS01:0x22:     Author: John Chodera <john.chodera@choderalab.org> and Rafal Wiewiora
> 06:04:26:WU00:FS01:0x22:             <rafal.wiewiora@choderalab.org>
> 06:04:26:WU00:FS01:0x22:       Args: -dir 00 -suffix 01 -version 706 -lifeline 12612 -checkpoint 15
> 06:04:26:WU00:FS01:0x22:             -gpu-vendor nvidia -opencl-platform 0 -opencl-device 0 -cuda-device
> 06:04:26:WU00:FS01:0x22:             0 -gpu 0
> 06:04:26:WU00:FS01:0x22:     Config: <none>
> 06:04:26:WU00:FS01:0x22:************************************ Build *************************************
> 06:04:26:WU00:FS01:0x22:    Version: 0.0.2
> 06:04:26:WU00:FS01:0x22:       Date: Dec 6 2019
> 06:04:26:WU00:FS01:0x22:       Time: 21:30:31
> 06:04:26:WU00:FS01:0x22: Repository: Git
> 06:04:26:WU00:FS01:0x22:   Revision: abeb39247cc72df5af0f63723edafadb23d5dfbe
> 06:04:26:WU00:FS01:0x22:     Branch: HEAD
> 06:04:26:WU00:FS01:0x22:   Compiler: Visual C++ 2008
> 06:04:26:WU00:FS01:0x22:    Options: /TP /nologo /EHa /wd4297 /wd4103 /Ox /MT
> 06:04:26:WU00:FS01:0x22:   Platform: win32 10
> 06:04:26:WU00:FS01:0x22:       Bits: 64
> 06:04:26:WU00:FS01:0x22:       Mode: Release
> 06:04:26:WU00:FS01:0x22:************************************ System ************************************
> 06:04:26:WU00:FS01:0x22:        CPU: Intel(R) Core(TM) i5-4460 CPU @ 3.20GHz
> 06:04:26:WU00:FS01:0x22:     CPU ID: GenuineIntel Family 6 Model 60 Stepping 3
> 06:04:26:WU00:FS01:0x22:       CPUs: 4
> 06:04:26:WU00:FS01:0x22:     Memory: 7.94GiB
> 06:04:26:WU00:FS01:0x22:Free Memory: 2.38GiB
> 06:04:26:WU00:FS01:0x22:    Threads: WINDOWS_THREADS
> 06:04:26:WU00:FS01:0x22: OS Version: 6.2
> 06:04:26:WU00:FS01:0x22:Has Battery: true
> 06:04:26:WU00:FS01:0x22: On Battery: false
> 06:04:26:WU00:FS01:0x22: UTC Offset: 2
> 06:04:26:WU00:FS01:0x22:        PID: 17952
> 06:04:26:WU00:FS01:0x22:        CWD: E:\FoldingHome\work
> 06:04:26:WU00:FS01:0x22:         OS: Windows 10 Pro
> 06:04:26:WU00:FS01:0x22:    OS Arch: AMD64
> 06:04:26:WU00:FS01:0x22:********************************************************************************
> 06:04:26:WU00:FS01:0x22:Project: 11741 (Run 0, Clone 3707, Gen 35)
> 06:04:26:WU00:FS01:0x22:Unit: 0x000000458ca304f15e695c802389aea5
> 06:04:26:WU00:FS01:0x22:Digital signatures verified
> 06:04:26:WU00:FS01:0x22:Folding@home GPU Core22 Folding@home Core
> 06:04:26:WU00:FS01:0x22:Version 0.0.2
> 06:04:26:WU00:FS01:0x22:  Found a checkpoint file
> 06:04:28:WU02:FS01:Connecting to 65.254.110.245:80
> 06:04:49:WARNING:WU02:FS01:Failed to get assignment from '65.254.110.245:80': No WUs available for this configuration
> 06:04:49:WU02:FS01:Connecting to 18.218.241.186:80
> 06:04:50:WARNING:WU02:FS01:Failed to get assignment from '18.218.241.186:80': No WUs available for this configuration
> 06:04:50:WU02:FS01:Connecting to 65.254.110.245:80
> 06:04:51:WARNING:WU02:FS01:Failed to get assignment from '65.254.110.245:80': No WUs available for this configuration
> 06:04:51:WU02:FS01:Connecting to 18.218.241.186:80
> 06:04:52:WARNING:WU02:FS01:Failed to get assignment from '18.218.241.186:80': No WUs available for this configuration
> 06:04:52:ERROR:WU02:FS01:Exception: Could not get an assignment
> 06:04:52:WU00:FS01:0x22:Completed 900000 out of 1000000 steps (90%)

**Comment by PantherX** [comment]
Is this still an issue with the 7.6.10 beta?

**Comment by JanosAudron** [comment]
I'm sorry, I gave wrong information. It's not related to 2 WU on same slot, but happens every time on GPU slot. Here is the log taken on v7.6.10 beta

> 09:02:39:WU00:FS01:0x22:Completed 410000 out of 1000000 steps (41%)
> 09:04:38:WU00:FS01:0x22:Completed 420000 out of 1000000 steps (42%)
> 09:06:28:WU00:FS01:0x22:Completed 430000 out of 1000000 steps (43%)
> 09:08:17:WU00:FS01:0x22:Completed 440000 out of 1000000 steps (44%)
> 09:10:07:WU00:FS01:0x22:Completed 450000 out of 1000000 steps (45%)
> 09:12:05:WU00:FS01:0x22:Completed 460000 out of 1000000 steps (46%)
> 09:13:57:WU00:FS01:0x22:Completed 470000 out of 1000000 steps (47%)
> 09:15:49:WU00:FS01:0x22:Completed 480000 out of 1000000 steps (48%)
> 09:16:05:FS01:Paused
> 09:16:05:FS01:Shutting core down
> 09:16:05:WU00:FS01:0x22:WARNING:Console control signal 1 on PID 18688
> 09:16:05:WU00:FS01:0x22:Exiting, please wait. . .
> 09:16:05:WU00:FS01:0x22:Folding@home Core Shutdown: INTERRUPTED
> 09:16:06:WU00:FS01:FahCore returned: INTERRUPTED (102 = 0x66)
> 09:16:10:FS01:Unpaused
> 09:16:10:WU00:FS01:Starting
> 09:16:10:WU00:FS01:Running FahCore: "C:\Program Files (x86)\FAHClient/FAHCoreWrapper.exe" E:\FoldingHome\cores/cores.foldingathome.org/v7/win/64bit/Core_22.fah/FahCore_22.exe -dir 00 -suffix 01 -version 706 -lifeline 6468 -checkpoint 15 -gpu-vendor nvidia -opencl-platform 0 -opencl-device 0 -cuda-device 0 -gpu 0
> 09:16:10:WU00:FS01:Started FahCore on PID 3012
> 09:16:10:WU00:FS01:Core PID:7780
> 09:16:10:WU00:FS01:FahCore 0x22 started
> 09:16:11:WU00:FS01:0x22:*********************** Log Started 2020-04-18T09:16:10Z ***********************
> 09:16:11:WU00:FS01:0x22:*************************** Core22 Folding@home Core ***************************
> 09:16:11:WU00:FS01:0x22:       Type: 0x22
> 09:16:11:WU00:FS01:0x22:       Core: Core22
> 09:16:11:WU00:FS01:0x22:    Website: https://foldingathome.org/
> 09:16:11:WU00:FS01:0x22:  Copyright: (c) 2009-2018 foldingathome.org
> 09:16:11:WU00:FS01:0x22:     Author: John Chodera <john.chodera@choderalab.org> and Rafal Wiewiora
> 09:16:11:WU00:FS01:0x22:             <rafal.wiewiora@choderalab.org>
> 09:16:11:WU00:FS01:0x22:       Args: -dir 00 -suffix 01 -version 706 -lifeline 3012 -checkpoint 15
> 09:16:11:WU00:FS01:0x22:             -gpu-vendor nvidia -opencl-platform 0 -opencl-device 0 -cuda-device
> 09:16:11:WU00:FS01:0x22:             0 -gpu 0
> 09:16:11:WU00:FS01:0x22:     Config: <none>
> 09:16:11:WU00:FS01:0x22:************************************ Build *************************************
> 09:16:11:WU00:FS01:0x22:    Version: 0.0.2
> 09:16:11:WU00:FS01:0x22:       Date: Dec 6 2019
> 09:16:11:WU00:FS01:0x22:       Time: 21:30:31
> 09:16:11:WU00:FS01:0x22: Repository: Git
> 09:16:11:WU00:FS01:0x22:   Revision: abeb39247cc72df5af0f63723edafadb23d5dfbe
> 09:16:11:WU00:FS01:0x22:     Branch: HEAD
> 09:16:11:WU00:FS01:0x22:   Compiler: Visual C++ 2008
> 09:16:11:WU00:FS01:0x22:    Options: /TP /nologo /EHa /wd4297 /wd4103 /Ox /MT
> 09:16:11:WU00:FS01:0x22:   Platform: win32 10
> 09:16:11:WU00:FS01:0x22:       Bits: 64
> 09:16:11:WU00:FS01:0x22:       Mode: Release
> 09:16:11:WU00:FS01:0x22:************************************ System ************************************
> 09:16:11:WU00:FS01:0x22:        CPU: Intel(R) Core(TM) i5-4460 CPU @ 3.20GHz
> 09:16:11:WU00:FS01:0x22:     CPU ID: GenuineIntel Family 6 Model 60 Stepping 3
> 09:16:11:WU00:FS01:0x22:       CPUs: 4
> 09:16:11:WU00:FS01:0x22:     Memory: 7.94GiB
> 09:16:11:WU00:FS01:0x22:Free Memory: 1.82GiB
> 09:16:11:WU00:FS01:0x22:    Threads: WINDOWS_THREADS
> 09:16:11:WU00:FS01:0x22: OS Version: 6.2
> 09:16:11:WU00:FS01:0x22:Has Battery: true
> 09:16:11:WU00:FS01:0x22: On Battery: false
> 09:16:11:WU00:FS01:0x22: UTC Offset: 2
> 09:16:11:WU00:FS01:0x22:        PID: 7780
> 09:16:11:WU00:FS01:0x22:        CWD: E:\FoldingHome\work
> 09:16:11:WU00:FS01:0x22:         OS: Windows 10 Pro
> 09:16:11:WU00:FS01:0x22:    OS Arch: AMD64
> 09:16:11:WU00:FS01:0x22:********************************************************************************
> 09:16:11:WU00:FS01:0x22:Project: 11762 (Run 0, Clone 14065, Gen 8)
> 09:16:11:WU00:FS01:0x22:Unit: 0x0000000d80fccb0a5e71138b8701fac0
> 09:16:11:WU00:FS01:0x22:Digital signatures verified
> 09:16:11:WU00:FS01:0x22:Folding@home GPU Core22 Folding@home Core
> 09:16:11:WU00:FS01:0x22:Version 0.0.2
> 09:16:11:WU00:FS01:0x22:  Found a checkpoint file
> 09:16:23:WU00:FS01:0x22:Completed 450000 out of 1000000 steps (45%)
> 09:16:23:WU00:FS01:0x22:Temperature control disabled. Requirements: single Nvidia GPU, tmax must be < 110 and twait >= 900

**Comment by JanosAudron** [comment]
Here is CPU log, where does not happen the error

> 09:01:12:WU01:FS00:0xa7:Completed 212500 out of 250000 steps (85%)
> 09:04:23:WU01:FS00:0xa7:Completed 215000 out of 250000 steps (86%)
> 09:07:05:WU01:FS00:0xa7:Completed 217500 out of 250000 steps (87%)
> 09:09:46:WU01:FS00:0xa7:Completed 220000 out of 250000 steps (88%)
> 09:12:42:WU01:FS00:0xa7:Completed 222500 out of 250000 steps (89%)
> 09:15:34:WU01:FS00:0xa7:Completed 225000 out of 250000 steps (90%)
> 09:15:35:WU02:FS00:Connecting to 65.254.110.245:80
> 09:15:36:WARNING:WU02:FS00:Failed to get assignment from '65.254.110.245:80': No WUs available for this configuration
> 09:15:36:WU02:FS00:Connecting to 18.218.241.186:80
> 09:15:36:WARNING:WU02:FS00:Failed to get assignment from '18.218.241.186:80': No WUs available for this configuration
> 09:15:36:WU02:FS00:Connecting to 65.254.110.245:80
> 09:15:37:WARNING:WU02:FS00:Failed to get assignment from '65.254.110.245:80': No WUs available for this configuration
> 09:15:37:WU02:FS00:Connecting to 18.218.241.186:80
> 09:15:37:WARNING:WU02:FS00:Failed to get assignment from '18.218.241.186:80': No WUs available for this configuration
> 09:15:37:ERROR:WU02:FS00:Exception: Could not get an assignment
> 09:15:37:WU02:FS00:Connecting to 65.254.110.245:80
> 09:15:38:WARNING:WU02:FS00:Failed to get assignment from '65.254.110.245:80': No WUs available for this configuration
> 09:15:38:WU02:FS00:Connecting to 18.218.241.186:80
> 09:15:38:WARNING:WU02:FS00:Failed to get assignment from '18.218.241.186:80': No WUs available for this configuration
> 09:15:38:WU02:FS00:Connecting to 65.254.110.245:80
> 09:15:39:WARNING:WU02:FS00:Failed to get assignment from '65.254.110.245:80': No WUs available for this configuration
> 09:15:39:WU02:FS00:Connecting to 18.218.241.186:80
> 09:15:39:WARNING:WU02:FS00:Failed to get assignment from '18.218.241.186:80': No WUs available for this configuration
> 09:15:39:ERROR:WU02:FS00:Exception: Could not get an assignment
> 09:16:38:WU02:FS00:Connecting to 65.254.110.245:80
> 09:16:38:WU02:FS00:Assigned to work server 150.136.14.110
> 09:16:38:WU02:FS00:Requesting new work unit for slot 00: RUNNING cpu:3 from 150.136.14.110
> 09:16:38:WU02:FS00:Connecting to 150.136.14.110:8080
> 09:16:39:WU02:FS00:Downloading 2.34MiB
> 09:16:45:WU02:FS00:Download 72.11%
> 09:16:47:WU02:FS00:Download complete
> 09:16:47:WU02:FS00:Received Unit: id:02 state:DOWNLOAD error:NO_ERROR project:16417 run:3023 clone:2 gen:71 core:0xa7 unit:0x0000004d96880e6e5e8a5f81a5bc9e1f
> 09:18:10:FS00:Paused
> 09:18:10:FS00:Shutting core down
> 09:18:10:WU01:FS00:0xa7:WARNING:Console control signal 1 on PID 20212
> 09:18:10:WU01:FS00:0xa7:Exiting, please wait. . .
> 09:18:11:WU01:FS00:FahCore returned: INTERRUPTED (102 = 0x66)
> 09:18:15:FS00:Unpaused
> 09:18:15:WU01:FS00:Starting
> 09:18:15:WU01:FS00:Running FahCore: "C:\Program Files (x86)\FAHClient/FAHCoreWrapper.exe" E:\FoldingHome\cores/cores.foldingathome.org/v7/win/64bit/avx/Core_a7.fah/FahCore_a7.exe -dir 01 -suffix 01 -version 706 -lifeline 6468 -checkpoint 15 -np 3
> 09:18:15:WU01:FS00:Started FahCore on PID 16596
> 09:18:16:WU01:FS00:Core PID:7568
> 09:18:16:WU01:FS00:FahCore 0xa7 started
> 09:18:16:WU01:FS00:0xa7:*********************** Log Started 2020-04-18T09:18:16Z ***********************
> 09:18:16:WU01:FS00:0xa7:************************** Gromacs Folding@home Core ***************************
> 09:18:16:WU01:FS00:0xa7:       Type: 0xa7
> 09:18:16:WU01:FS00:0xa7:       Core: Gromacs
> 09:18:16:WU01:FS00:0xa7:       Args: -dir 01 -suffix 01 -version 706 -lifeline 16596 -checkpoint 15 -np
> 09:18:16:WU01:FS00:0xa7:             3
> 09:18:16:WU01:FS00:0xa7:************************************ CBang *************************************
> 09:18:16:WU01:FS00:0xa7:       Date: Oct 26 2019
> 09:18:16:WU01:FS00:0xa7:       Time: 01:38:25
> 09:18:16:WU01:FS00:0xa7:   Revision: c46a1a011a24143739ac7218c5a435f66777f62f
> 09:18:16:WU01:FS00:0xa7:     Branch: master
> 09:18:16:WU01:FS00:0xa7:   Compiler: Visual C++ 2008
> 09:18:16:WU01:FS00:0xa7:    Options: /TP /nologo /EHa /wd4297 /wd4103 /Ox /MT
> 09:18:16:WU01:FS00:0xa7:   Platform: win32 10
> 09:18:16:WU01:FS00:0xa7:       Bits: 64
> 09:18:16:WU01:FS00:0xa7:       Mode: Release
> 09:18:16:WU01:FS00:0xa7:************************************ System ************************************
> 09:18:16:WU01:FS00:0xa7:        CPU: Intel(R) Core(TM) i5-4460 CPU @ 3.20GHz
> 09:18:16:WU01:FS00:0xa7:     CPU ID: GenuineIntel Family 6 Model 60 Stepping 3
> 09:18:16:WU01:FS00:0xa7:       CPUs: 4
> 09:18:16:WU01:FS00:0xa7:     Memory: 7.94GiB
> 09:18:16:WU01:FS00:0xa7:Free Memory: 1.52GiB
> 09:18:16:WU01:FS00:0xa7:    Threads: WINDOWS_THREADS
> 09:18:16:WU01:FS00:0xa7: OS Version: 6.2
> 09:18:16:WU01:FS00:0xa7:Has Battery: true
> 09:18:16:WU01:FS00:0xa7: On Battery: false
> 09:18:16:WU01:FS00:0xa7: UTC Offset: 2
> 09:18:16:WU01:FS00:0xa7:        PID: 7568
> 09:18:16:WU01:FS00:0xa7:        CWD: E:\FoldingHome\work
> 09:18:16:WU01:FS00:0xa7:******************************** Build - libFAH ********************************
> 09:18:16:WU01:FS00:0xa7:    Version: 0.0.18
> 09:18:16:WU01:FS00:0xa7:     Author: Joseph Coffland <joseph@cauldrondevelopment.com>
> 09:18:16:WU01:FS00:0xa7:  Copyright: 2019 foldingathome.org
> 09:18:16:WU01:FS00:0xa7:   Homepage: https://foldingathome.org/
> 09:18:16:WU01:FS00:0xa7:       Date: Oct 26 2019
> 09:18:16:WU01:FS00:0xa7:       Time: 01:52:30
> 09:18:16:WU01:FS00:0xa7:   Revision: c1e3513b1bc0c16013668f2173ee969e5995b38e
> 09:18:16:WU01:FS00:0xa7:     Branch: master
> 09:18:16:WU01:FS00:0xa7:   Compiler: Visual C++ 2008
> 09:18:16:WU01:FS00:0xa7:    Options: /TP /nologo /EHa /wd4297 /wd4103 /Ox /MT
> 09:18:16:WU01:FS00:0xa7:   Platform: win32 10
> 09:18:16:WU01:FS00:0xa7:       Bits: 64
> 09:18:16:WU01:FS00:0xa7:       Mode: Release
> 09:18:16:WU01:FS00:0xa7:************************************ Build *************************************
> 09:18:16:WU01:FS00:0xa7:       SIMD: avx_256
> 09:18:16:WU01:FS00:0xa7:********************************************************************************
> 09:18:16:WU01:FS00:0xa7:Project: 14379 (Run 2082, Clone 4, Gen 6)
> 09:18:16:WU01:FS00:0xa7:Unit: 0x00000006455e42075e932fa97cd04575
> 09:18:16:WU01:FS00:0xa7:Digital signatures verified
> 09:18:16:WU01:FS00:0xa7:Calling: mdrun -s frame6.tpr -o frame6.trr -cpi state.cpt -cpt 15 -nt 3
> 09:18:17:WU01:FS00:0xa7:Steps: first=0 total=250000
> 09:18:18:WU01:FS00:0xa7:Completed 227186 out of 250000 steps (90%)
> 09:18:40:WU01:FS00:0xa7:Completed 227500 out of 250000 steps (91%)
> 09:21:32:WU01:FS00:0xa7:Completed 230000 out of 250000 steps (92%)

**Comment by informatorius** [comment]
I cannot see any crash in these logfiles. You pause the slot so FAHcore gets interrupted. You unpause the slot so FAHcore starts again from last checkpoint. Works as specified.

**Comment by JanosAudron** [comment]
I did not know it, and actually I didn't expected it because I didn't stopped the task but just paused. By the way, if you check in my CPU log there isn't the "Found a checkpoint file" step. At its place, there is "Calling: mdrun -s frame6.tpr -o frame6.trr -cpi state.cpt -cpt 15 -nt 3"

**Comment by JanosAudron** [comment]
In the GPU log there also be the step "Folding@home Core Shutdown: INTERRUPTED" which there isn't in the CPU log.

**Comment by JanosAudron** [comment]
After 2 hours paused, I lost 6% of calculation

> 07:29:21:WU00:FS01:0x22:Completed 1760000 out of 2000000 steps (88%)
> 07:33:39:WU00:FS01:0x22:Completed 1780000 out of 2000000 steps (89%)
> 07:37:56:WU00:FS01:0x22:Completed 1800000 out of 2000000 steps (90%)
> 07:37:58:WU02:FS01:Connecting to 65.254.110.245:80
> 07:37:59:WARNING:WU02:FS01:Failed to get assignment from '65.254.110.245:80': No WUs available for this configuration
> 07:37:59:WU02:FS01:Connecting to 18.218.241.186:80
> 07:37:59:WARNING:WU02:FS01:Failed to get assignment from '18.218.241.186:80': No WUs available for this configuration
> 07:37:59:WU02:FS01:Connecting to 65.254.110.245:80
> 07:38:00:WARNING:WU02:FS01:Failed to get assignment from '65.254.110.245:80': No WUs available for this configuration
> 07:38:00:WU02:FS01:Connecting to 18.218.241.186:80
> 07:38:00:WARNING:WU02:FS01:Failed to get assignment from '18.218.241.186:80': No WUs available for this configuration
> 07:38:00:ERROR:WU02:FS01:Exception: Could not get an assignment
> 07:38:01:WU02:FS01:Connecting to 65.254.110.245:80
> 07:38:01:WARNING:WU02:FS01:Failed to get assignment from '65.254.110.245:80': No WUs available for this configuration
> 07:38:01:WU02:FS01:Connecting to 18.218.241.186:80
> 07:38:02:WARNING:WU02:FS01:Failed to get assignment from '18.218.241.186:80': No WUs available for this configuration
> 07:38:02:WU02:FS01:Connecting to 65.254.110.245:80
> 07:38:02:WARNING:WU02:FS01:Failed to get assignment from '65.254.110.245:80': No WUs available for this configuration
> 07:38:02:WU02:FS01:Connecting to 18.218.241.186:80
> 07:38:03:WARNING:WU02:FS01:Failed to get assignment from '18.218.241.186:80': No WUs available for this configuration
> 07:38:03:ERROR:WU02:FS01:Exception: Could not get an assignment
> 07:39:01:WU02:FS01:Connecting to 65.254.110.245:80
> 07:39:01:WARNING:WU02:FS01:Failed to get assignment from '65.254.110.245:80': No WUs available for this configuration
> 07:39:02:WU02:FS01:Connecting to 18.218.241.186:80
> 07:39:02:WARNING:WU02:FS01:Failed to get assignment from '18.218.241.186:80': No WUs available for this configuration
> 07:39:02:WU02:FS01:Connecting to 65.254.110.245:80
> 07:39:03:WARNING:WU02:FS01:Failed to get assignment from '65.254.110.245:80': No WUs available for this configuration
> 07:39:03:WU02:FS01:Connecting to 18.218.241.186:80
> 07:39:03:WARNING:WU02:FS01:Failed to get assignment from '18.218.241.186:80': No WUs available for this configuration
> 07:39:03:ERROR:WU02:FS01:Exception: Could not get an assignment
> 07:40:38:WU02:FS01:Connecting to 65.254.110.245:80
> 07:40:39:WU02:FS01:Assigned to work server 13.82.98.119
> 07:40:39:WU02:FS01:Requesting new work unit for slot 01: RUNNING gpu:0:GP106 [GeForce GTX 1060 3GB] 3935 from 13.82.98.119
> 07:40:39:WU02:FS01:Connecting to 13.82.98.119:8080
> ******************************* Date: 2020-04-19 *******************************
> 07:41:25:WU02:FS01:Downloading 22.03MiB
> 07:41:31:WU02:FS01:Download 10.50%
> 07:41:37:WU02:FS01:Download 22.98%
> 07:41:43:WU02:FS01:Download 35.75%
> 07:41:49:WU02:FS01:Download 48.24%
> 07:41:55:WU02:FS01:Download 60.72%
> 07:42:01:WU02:FS01:Download 73.49%
> 07:42:07:WU02:FS01:Download 86.26%
> 07:42:13:WU02:FS01:Download 98.75%
> 07:42:13:WU02:FS01:Download complete
> 07:42:13:WU02:FS01:Received Unit: id:02 state:DOWNLOAD error:NO_ERROR project:14545 run:0 clone:653 gen:12 core:0x22 unit:0x000000170d5262775e80e224425749f3
> 07:42:19:WU00:FS01:0x22:Completed 1820000 out of 2000000 steps (91%)
> 07:46:36:WU00:FS01:0x22:Completed 1840000 out of 2000000 steps (92%)
> 07:50:53:WU00:FS01:0x22:Completed 1860000 out of 2000000 steps (93%)
> 07:55:13:WU00:FS01:0x22:Completed 1880000 out of 2000000 steps (94%)
> 07:59:31:WU00:FS01:0x22:Completed 1900000 out of 2000000 steps (95%)
> 08:03:50:WU00:FS01:0x22:Completed 1920000 out of 2000000 steps (96%)
> ### **08:08:18:WU00:FS01:0x22:Completed 1940000 out of 2000000 steps (97%)**
> 08:11:27:FS01:Paused
> 08:11:27:FS01:Shutting core down
> 08:11:28:WU00:FS01:0x22:WARNING:Console control signal 1 on PID 18536
> 08:11:28:WU00:FS01:0x22:Lost lifeline PID 18800, exiting
> 08:11:28:WU00:FS01:0x22:Exiting, please wait. . .
> 08:11:28:WU00:FS01:0x22:Folding@home Core Shutdown: INTERRUPTED
> 08:11:28:WU00:FS01:FahCore returned: INTERRUPTED (102 = 0x66)
> 09:46:04:FS01:Unpaused
> 09:46:04:WU00:FS01:Starting
> 09:46:04:WU00:FS01:Running FahCore: "C:\Program Files (x86)\FAHClient/FAHCoreWrapper.exe" E:\FoldingHome\cores/cores.foldingathome.org/v7/win/64bit/Core_22.fah/FahCore_22.exe -dir 00 -suffix 01 -version 706 -lifeline 6468 -checkpoint 15 -gpu-vendor nvidia -opencl-platform 0 -opencl-device 0 -cuda-device 0 -gpu 0
> 09:46:04:WU00:FS01:Started FahCore on PID 18152
> 09:46:08:WU00:FS01:Core PID:21408
> 09:46:08:WU00:FS01:FahCore 0x22 started
> 09:46:10:WU00:FS01:0x22:*********************** Log Started 2020-04-19T09:46:10Z ***********************
> 09:46:10:WU00:FS01:0x22:*************************** Core22 Folding@home Core ***************************
> 09:46:10:WU00:FS01:0x22:       Type: 0x22
> 09:46:10:WU00:FS01:0x22:       Core: Core22
> 09:46:10:WU00:FS01:0x22:    Website: https://foldingathome.org/
> 09:46:10:WU00:FS01:0x22:  Copyright: (c) 2009-2018 foldingathome.org
> 09:46:10:WU00:FS01:0x22:     Author: John Chodera <john.chodera@choderalab.org> and Rafal Wiewiora
> 09:46:10:WU00:FS01:0x22:             <rafal.wiewiora@choderalab.org>
> 09:46:10:WU00:FS01:0x22:       Args: -dir 00 -suffix 01 -version 706 -lifeline 18152 -checkpoint 15
> 09:46:10:WU00:FS01:0x22:             -gpu-vendor nvidia -opencl-platform 0 -opencl-device 0 -cuda-device
> 09:46:10:WU00:FS01:0x22:             0 -gpu 0
> 09:46:10:WU00:FS01:0x22:     Config: <none>
> 09:46:10:WU00:FS01:0x22:************************************ Build *************************************
> 09:46:10:WU00:FS01:0x22:    Version: 0.0.2
> 09:46:10:WU00:FS01:0x22:       Date: Dec 6 2019
> 09:46:10:WU00:FS01:0x22:       Time: 21:30:31
> 09:46:10:WU00:FS01:0x22: Repository: Git
> 09:46:10:WU00:FS01:0x22:   Revision: abeb39247cc72df5af0f63723edafadb23d5dfbe
> 09:46:10:WU00:FS01:0x22:     Branch: HEAD
> 09:46:10:WU00:FS01:0x22:   Compiler: Visual C++ 2008
> 09:46:10:WU00:FS01:0x22:    Options: /TP /nologo /EHa /wd4297 /wd4103 /Ox /MT
> 09:46:10:WU00:FS01:0x22:   Platform: win32 10
> 09:46:10:WU00:FS01:0x22:       Bits: 64
> 09:46:10:WU00:FS01:0x22:       Mode: Release
> 09:46:10:WU00:FS01:0x22:************************************ System ************************************
> 09:46:10:WU00:FS01:0x22:        CPU: Intel(R) Core(TM) i5-4460 CPU @ 3.20GHz
> 09:46:10:WU00:FS01:0x22:     CPU ID: GenuineIntel Family 6 Model 60 Stepping 3
> 09:46:10:WU00:FS01:0x22:       CPUs: 4
> 09:46:10:WU00:FS01:0x22:     Memory: 7.94GiB
> 09:46:10:WU00:FS01:0x22:Free Memory: 3.08GiB
> 09:46:10:WU00:FS01:0x22:    Threads: WINDOWS_THREADS
> 09:46:10:WU00:FS01:0x22: OS Version: 6.2
> 09:46:10:WU00:FS01:0x22:Has Battery: true
> 09:46:10:WU00:FS01:0x22: On Battery: false
> 09:46:10:WU00:FS01:0x22: UTC Offset: 2
> 09:46:10:WU00:FS01:0x22:        PID: 21408
> 09:46:10:WU00:FS01:0x22:        CWD: E:\FoldingHome\work
> 09:46:10:WU00:FS01:0x22:         OS: Windows 10 Pro
> 09:46:10:WU00:FS01:0x22:    OS Arch: AMD64
> 09:46:10:WU00:FS01:0x22:********************************************************************************
> 09:46:10:WU00:FS01:0x22:Project: 14432 (Run 0, Clone 1394, Gen 11)
> 09:46:10:WU00:FS01:0x22:Unit: 0x0000000e0d5262775e8b4d5706ef330d
> 09:46:10:WU00:FS01:0x22:Digital signatures verified
> 09:46:10:WU00:FS01:0x22:Folding@home GPU Core22 Folding@home Core
> 09:46:10:WU00:FS01:0x22:Version 0.0.2
> 09:46:10:WU00:FS01:0x22:  Found a checkpoint file
> 09:47:23:WARNING:WU00:FS01:Detected clock skew (1 mins 13 secs), I/O delay, laptop hibernation or other slowdown noted, adjusting time estimates
> 09:47:31:WU00:FS01:0x22:Temperature control disabled. Requirements: single Nvidia GPU, tmax must be < 110 and twait >= 900
> ### **09:51:56:WU00:FS01:0x22:Completed 1820000 out of 2000000 steps (91%)**

**Comment by PantherX** [comment]
Can you please post your logs on the Official Forum: https://foldingforum.org/index.php

Reason is GitHub is for having issues which can be reproduced on demand but in your case, we are still troubleshooting and GitHub isn't the place, the Forum is :)
