### ISSUE TITLE
GPU wu processing idles when pc in use, indicates it is still running.

### ISSUE THREAD

**Issue by Kosahn** [FoldingAtHome/fah-issues#1392]
GPU wu processing slows from utilizing near 100% of GPU to an idle level of GPU. This occurs shortly after signing on to an existing Windows session (not logged out, just locked session). FAH still reports the job as running however the ETA steadily climbs. Pressing Pause then Fold restores processing to full power. It happens on a regular basis when signing in and no errors are logged. Web control is set to "While I'm Working" and Medium power.

W10 Pro 1909, I7-4790, ASUS R9 390 Strix, FAH client 7.6.9

**Comment by shorttack** [comment]
@Kosahn Can you please post your log file in the Official Forum: https://foldingforum.org/index.php for the issue to be diagnosed? GitHub is not used for troubleshooting, the Forum is :)
