### ISSUE TITLE
Incomplete fix for Core_Outdated with two slots

### ISSUE THREAD

**Issue by bb30994** [FoldingAtHome/fah-issues#1393]
Core_outdated means FAHClient needs to download a new core.  I have two slots using that core.  One was running and I unpaused the other.  Naturally, the file was is use so the update couldn't proceed.

Pausing the active slot gives me two slots with status Update_Core.  That.s correct ... except that now the download needs to proceed but it doesn't 

Windows 7.6.9

Core had been deleted looking for a fresh copy.  After a long wait, I paused both slots and then unpaused them and something worked.  I'm not sure if that unjammed it or if it just took ~10 minutes to decide to proceed.

**Comment by ajacocks** [comment]
Can you clarify what OS you are using?

**Comment by shorttack** [comment]
Defect: poorly handling update_core condition when multiple slots running the same (outdated) core.

**Comment by jcoffland** [comment]
This has been solved.  All cores now include their version in the download URL.  This makes it possible to have two versions of the same core running on the same client at once.
