### ISSUE TITLE
SmartScreen blocking FAH installer

### ISSUE THREAD

**Issue by stuartsoft** [FoldingAtHome/fah-issues#1395]
Windows SmartScreen stops FAH installer, likely due to the expired signing certificate.
I'm seeing the same issue with both the 7.6.9 release and the 7.6.10 beta.

![image](https://user-images.githubusercontent.com/6208902/79669596-a0b66780-818a-11ea-8abb-2ac0972de4af.png)

![image](https://user-images.githubusercontent.com/6208902/79669544-461d0b80-818a-11ea-963b-c235e5ee048d.png)

**Comment by shorttack** [comment]
@stuartsoft The dev team is aware of this issue, and I will flag this issue. The software download needs an updated certificate. As you are no doubt aware, click "Run Anyway".

**Comment by stuartsoft** [comment]
The latest installer (7.6.11 beta) has a valid signature now, but is still blocked by Windows Defender :(

Also it appears the 7.6.11 beta binary was signed by `Cauldron Development LLC`, not `Stanford UNIVERSITY` as it was on the public release of 7.6.9. Was this intended?

![image](https://user-images.githubusercontent.com/6208902/80171046-66e4c700-85b7-11ea-829b-76b02d4a4017.png)

**Comment by stuartsoft** [comment]
Issue is still present on 7.6.12 beta. Same as the previous comment.

**Comment by jcoffland** [comment]
Stanford is no longer involved in Folding@home.  foldingathome.org is not a legal entity so I cannot purchase a code signing certificate for it.  Cauldron Development LLC is my contracting business.  It is an LLC filed in the state of California.

**Comment by jcoffland** [comment]
> ...a certificate just isn't enough anymore to gain trust... SmartScreen is reputation based, not unlike the way StackOverflow works... SmartScreen trusts installers that don't cause problems. Windows machines send telemetry back to Redmond about installed programs and how much trouble they cause. If you get enough thumbs-up then SmartScreen stops blocking your installer automatically. This takes time and lots of installs to get sufficient thumbs. There is no way to find out how far along you got.

**Comment by PantherX** [comment]
Please note that based on the most recent comments, I will close this issue now.
