### ISSUE TITLE
non-admin installation

### ISSUE THREAD

**Issue by Adiumene** [FoldingAtHome/fah-issues#1398]
There is an issue when a non-admin user attempts to install FAH on Windows 10.
edit: regression from #889 (labelled as critical defect)

## Expected Behavior
- FAH's data folders should be in user's folders by default
- FAH should open at startup if the option was selected
- FAH shorcuts should be created in the user's Start Menu

## Current Behavior
- The installer's default data folder is located inside the _temp_ user directory: `C:\Users\temp\Roaming\FAHClient` , or in another admin account directory :  `C:\Users\admin\Roaming\FAHClient`
- FAH will not open at startup, even if user's own folders are manually selected during the installation process (say `C:\Users\username\Roaming\FAHClient` )
- The admin user account (not used for installation) will have a .lnk in it's startup folder, not the user who installed FAH
- The admin user account (not used for installation) will have Start Menu shortcuts, not the user who installed FAH

## Solutions
- Install FAH for every users: keep admin level and set `SetShellVarContext All`.
- (possibly) Or use the user's directory as default for data, shortcut and startup (not the user running the installation process' folders (an admin)), by not elevating during the installation.

## Steps to Reproduce
1. Create a non admin account on windows
2. v1 run fah-installer_7.6.9_x86.exe or fah-installer_7.5.1_x86.exe with default settings with this non admin account (with or without run as admin)
2. v2 run fah-installer_7.6.9_x86.exe or fah-installer_7.5.1_x86.exe with the user's folder with this non admin account (with or without run as admin)
3. restart the computer

Edit: clarification and spelling
Edit 2: more details

**Comment by M-D-M** [comment]
@Adiumene Were you able to fix the behavior on your install?  Were your steps similar to mine?  

My data directory wasn't in the temp directory -- weird.

**Comment by Adiumene** [comment]
@M-D-M I had to correct this statement after some tests. The _temp_ folders are only used with the default settings. That said, the .lnk is still not inside the current user startup folder so everything else is still valid.

With another computer, I was able to reproduce everything except for the fact that the default folders were located on the _admin_ account, not the _temp_ one.

The workaround was about the same:
- with the non admin account, install in some folder where this same account have every privilege (used thisuser\Roaming\FAHClient and thisuser\Roaming\DataFAH)
- create (or modify after finding the original) a .lnk inside the _admin_ or the _temp_ and move it inside the user's startup folder with `C:\Users\thisuser\AppData\Roaming\FAHClient\HideConsole.exe C:\Users\thisuser\AppData\Roaming\FAHClient\FAHClient.exe` as _target_ and `C:\Users\thisuser\AppData\Roaming\DataFAH` in _start in_ .
- restart

**Comment by bb30994** [comment]
Correction: The installer does not install in the "temp" folder, it installs in the users's Application Data folder, which is an excellent default and recommended by Microsoft.  This is **%APPDATA%\FAHClient.** 0 where (if the user is logged on as bruce), %APPDATA% has been initialized to "C:\Users\bruce\AppData\Roaming" .

**Comment by shorttack** [comment]
Implement with #1409

**Comment by M-D-M** [comment]
> Correction: The installer does not install in the "temp" folder, it installs in the users's Application Data folder, which is an excellent default and recommended by Microsoft. This is **%APPDATA%\FAHClient.** 0 where (if the user is logged on as bruce), %APPDATA% has been initialized to "C:\Users\bruce\AppData\Roaming" .

The original statement needed to be corrected.  

The problem is that the install is happening into the "elevated" %APPDATA% folder, not the %APPDATA% folder of the logged-in user, during non-admin installs.

**Comment by Adiumene** [comment]
@shorttack on #1409 :
> Newbie users are installing client as Administrator and then complaining when they have to right-click to "run as administrator".

Right-clicking on "run as administrator" will not solve this use case: the .lnk will still be created and placed in the admin account startup folder. Thus, when the regular user restart his computer, F@H will not start. Installing F@H with a non-admin, having or not right-click-admin on the installer, thus require manual configuration. I also humbly suggest that we stay zen and we refrain from name calling.

@bb30994 :
> Correction: The installer does not install in the "temp" folder, it installs in the users' Application Data folder, which is an excellent default and recommended by Microsoft. This is **%APPDATA%\FAHClient.** 0 where (if the user is logged on as bruce), %APPDATA% has been initialized to "C:\Users\bruce\AppData\Roaming" .

What @M-D-M said is correct. If bruce is not an admin, installing F@H with the default settings will place it's folders in another admin account, say in "C:\Users\brucesAdmin\AppData\Roaming". If the user knows that the installer is misconfigured and setup the client and folder accordingly, the startup shortcut will still be put in "C:\Users\brucesAdmin\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup" and so F@H will not auto start.

Also: the regular _start menu_ shortcuts won't appear for this user.

I find it a bit weird this is labelled as "enhancement"; I'd say this is simply a small problem that needs a small fix.

**Comment by M-D-M** [comment]
Yeah, I don't appreciate the comment about "newbie users", either -- this has nothing to do with "right-clicking and selecting "run as administrator".

If you're running the installer from a non-admin user account, you don't even _have_ to right-click and select "run as administrator" -- the installer automatically asks for elevation, and you enter admin credentials through the Windows UAC dialog.

**Comment by PantherX** [comment]
Please see this topic too which has additional details: https://foldingforum.org/viewtopic.php?f=61&t=34696

**Comment by ItEndsWithTens** [comment]
Same issue here! I'm not running as admin, just a standard user account, but double clicking the installer requests elevation, and the way Windows accomplishes that is by running under the admin account for which you provide credentials. The %APPDATA% variable is thus expanded to its value for the account **running the process**, which has now switched to an admin account, not the account which originally double clicked the .exe (Process Explorer can quickly tell you who owns which process). I believe this issue is a regression to the problem described in #889, from some years ago. That or a similar issue.

Regarding Microsoft's recommendations, I don't believe
> ... it installs in the users's Application Data folder, which is an excellent default and recommended by Microsoft.

is quite correct. They certainly want per-user data **stored** in the users AppData, but the **install** is not supposed to attempt to put anything there. Per Microsoft's [certification requirements for Windows Desktop applications](https://docs.microsoft.com/en-us/windows/win32/win_cert/certification-requirements-for-windows-desktop-apps?redirectedfrom=MSDN#10-apps-must-install-to-the-correct-folders-by-default):

>10.6 Your app must write user data at first run and not during the installation in per-machine installations
When the app is installed, there is no correct user location in which to store data.

"Per-machine" being any installation that writes to Program Files and thus requires UAC elevation, like this one does. I've never done more than tinker with NSIS (which [Universal Extractor](https://github.com/Bioruebe/UniExtract2) suggests the F@H installer was built with), but I've stumbled over some issues related to the topic, if they're of any interest:

https://stackoverflow.com/a/55537022
https://nsis-dev.github.io/NSIS-Forums/html/t-373468.html

I've managed to struggle past the issue myself by manually moving files around after the install, and manually editing the .lnk to point to the right place, but I'd love to see the installer take care of all that.

**Comment by Adiumene** [comment]
Thanks for this search! I agree: seems to be a regression identical to issue #889. 

Maybe we could invite @jcoffland to comment on this?

**Comment by Adiumene** [comment]
I have included this as a proposed solution in the problem summary, but for the flow of conversation; I suspect that `SetShellVarContext All` in FAHClient.nsi  should do the trick, with an admin elevation and for an all-users installation. I've yet to test it with NSIS, but I don't know much about it either, so it'll take some time.

Getting back to issue #889; this was labelled critical defect. @ajacocks , could you reconsider the enhancement label?

**Comment by Stel2112** [comment]
Please see this topic for relevant information and suggested fix: https://foldingforum.org/viewtopic.php?f=108&t=34839

Comments regarding the suggested fix:
https://foldingforum.org/viewtopic.php?f=106&t=33531&p=330204#p330204

**Comment by Adiumene** [comment]
I have managed to compile and test the `SetShellVarContext All` and keep the admin level: this is working at is should. I might propose a merge, but I'm wondering if this would be any useful since the git version is not up to date.

**Comment by bb30994** [comment]
The installer has generally worked if run by the non-admin user that normally logs on to the computer.  In the past, there has been a choice of installing "just for me" or "for all users" but the latter has not worked well.  Here's what I propose:

Depending on which version of WIndows we're talking about, Microsoft creates several entries in C:\users including
\user1
\user2
\Public
\Admin

I think that c:\users\Public may have rwx permissions for everyone.  If so, why not create the \FAHClient in that directory and use it no matter which user happens to log on.  Inasmuch as only one user at a time can create the desktop, they will be the owner of the GPU(s) and effectively will be able to work on the files in the Public branch.

I have not investigated the question of the shortcuts, but presumably a similar solution would work and they wouldn't have to have different values for "start in"

**Comment by Stel2112** [comment]
Consider using the hidden "%PROGRAMDATA%" folder (it is "C:\ProgramData\" by default). All windows users have read and write access to this folder and it is supported on windows 7 and up. Just make a folder such as "C:\ProgramData\FAH\". The intent of this folder is for shared working program data.

They have read and write to c:\Users\Public as well, however the intent of that folder is really for shared music, pictures, desktop items, etc. ie. files a user would directly interact with or edit.

**Comment by Adiumene** [comment]
`%programdata%` sounds right. Using `SetShellVarContext All` in the .nsi script will create the Startup and Start Menu links in `C:\ProgramData\Microsoft\Windows\Start Menu\Programs` and `C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Startup` respectively, with the program files in `C:\Program Files (x86)\FAHClient` by default. 

The program data, on the contrary, will still be generated in 'C:\users\randomAdmin\AppData\Roaming\FAHClient`. The installer, however, will give all users the rights to read and right in that folder, such that FAH will start at startup or with a double click in the menu without any prompt.

While this is a functional fix for the _working part_ of this issue, it would be better if the data folder could be found in `%programdata%` also.

On a side note: 7.6.13 beta is still concerned by this.

**Comment by PantherX** [comment]
I wonder if we can have the data files in %PROGRAMDATA% and the shortcuts pointing to that location placed in the C:\users\Public\Desktop folder for all users (existing and new) to use it without issues?

**Comment by Adiumene** [comment]
Turns out: another call to `SetShellVarContext All` did the trick again. A function is setting the data folder to `$APPDATA\FAHClient` which now resolve to `PROGRAMDATA` with this option.

But, unfortunately, I've discovered that the uninstallation process fail to delete the data folder on this branch.

**Comment by shorttack** [comment]
Good idea. Note, developers will need to create an automatic conversion path from today's /user/AppData/Roaming/FoldingClient directory path, copying over existing config, work, etc. to the folding %PROGRAMDATA% folder on installs over an existing client. If we don't provide a seamless upgrade/conversion path, the support issues will be off the charts.

**Comment by Adiumene** [comment]
> 
> 
> Good idea. Note, developers will need to create an automatic conversion path from today's /user/AppData/Roaming/FoldingClient directory path, copying over existing config, work, etc. to the folding %PROGRAMDATA% folder on installs over an existing client. If we don't provide a seamless upgrade/conversion path, the support issues will be off the charts.

Good thought, but the installer already does record and (should) retrieve the data folder path on a new installation.

I understood the uninstallation process failure yesterday: the registry reading was not looking inside the 64bit registry for this same registry key. Fixing this fixed this issue. I'll commit this soon.
