### ISSUE TITLE
Feature request: FAH pause on other exclusive apps running

### ISSUE THREAD

**Issue by informatorius** [FoldingAtHome/fah-issues#1407]
Feature request: FAH should have a configurable list of other exclusive apps. When other apps are started then FAH pause automatically. When other apps closed then FAH continues. 

This can be reached currently with user scripts but could be a nice feature for users running 3D games or apps in between folding.

**Comment by shorttack** [comment]
I like the idea. My two cents is have three options: keep folding (default); Pause on start of app; Finish slots on start of app.

I'm not sure how FAHControl is going to create a list of all installed apps on the fly (not to mention the overhead) for the three operating systems supported or else validate the user's specifically-entered app name.

this might be the kind of enhancement that an open source FAHcontrol could tackle...

**Comment by shorttack** [comment]
@informatorius And ... the open-source world comes through for you! FAHControl-Plus is open source. Here's a Helper that does what you want. Please try it and work with that developer to get exactly what you need. [https://github.com/tmontney/FAHControl-Plus](url)

I'm going to close this enhancement request, but if you're not satisfied with Plus, comment here and I'll open it back up.
