### ISSUE TITLE
Windows Install Client for All Users

### ISSUE THREAD

**Issue by shorttack** [FoldingAtHome/fah-issues#1409]
Newbie users are installing client as Administrator and then complaining when they have to right-click to "run as administrator".

Recommend an enhancement that Windows Installer asks "Install for all users?" question, allowing Windows to share access to the client to all users. This will cut down Forum and support issues.

Thanks to #1380 and @bb30994.

**Comment by shorttack** [comment]
Implement with #1398

**Comment by shorttack** [comment]
Implement enhancement with #1409

**Comment by PantherX** [comment]
I am closing this issue since the implementation approach mentioned above would resolve this by having a single location regardless of if it is a single user or shared by multiple users.
