### ISSUE TITLE
  FAHClient 7.6.9 throws exception (Fedora 26)

### ISSUE THREAD

**Issue by FulkoHew** [FoldingAtHome/fah-issues#1411]
I just upgraded to version 7.6.9 (running on Fedora 26)
This new FAHClient constantly emits an exception to its log file and
stdout/stderr every ~2 seconds. 
Example:

17:52:10:ERROR:std::exception: std::bad_cast

a) As soon as I start FAHControl and it connects to FAHClient,
the client starts spewing the exception every ~2 seconds.

 - Stopping FAHClient quiets FAHControl.
 - Restarting FAHControl restarts the exception.

 - There is nothing unusual in the log.
 - The log and the client proceeds normally.

Note that having the browser based controller connected does NOT cause the exceptions.

b) Explicitly starting FAHViewer also causes the client to emit the exception;
  except in groups of 3 exceptions every 5 seconds.

 - FAHViewer also never actually renders the molecule.

 - A Wireshark sniff of the viewer-client connection when the viewer is started shows the following:

```
.[H.[2JWelcome to the FAHClient command server.
> updates add 0 5 $heartbeat
updates add 1 5 $slot-info

>
>
PyON 1 slots
[
  {
    "id": "00",
    "status": "RUNNING",
    "description": "cpu:3",
    "options": {},
    "reason": "",
    "idle": False
  }
]
---
updates add 2 5 $(simulation-info 0)
updates add 3 5 $(trajectory 0)

> 
```

**Comment by abitrolly** [comment]
@FulkoHew Fedora 26 is unsupported for almost 2 years https://en.wikipedia.org/wiki/Fedora_version_history Have you tried to use the fresh version?

**Comment by FulkoHew** [comment]
​No, I haven't.
At this point in time, I can't change.
Perhaps I can try it in a virtual machine.

I can also add that the previous version (7.5.1) worked fine without the exception,
and the viewer worked too.

**Comment by FulkoHew** [comment]
I just tried it on Fedora 30 in a VM, and the exception did not occur,
and the viewer renders the molecule.  Feel free to close this bug report.
