### ISSUE TITLE
Cause filter is not effective, folding other projects

### ISSUE THREAD

**Issue by FlorinAndrei** [FoldingAtHome/fah-issues#1412]
FAHClient 7.6.9 on Linux

```
<config>
  <user value='XXXXXXXXX'/>
  <team value='0'/>
  <passkey value=''/>
  <cause v='COVID_19'/>
  <smp value='false'/>
  <gpu value='true'/>
  <power v='full'/>
  <idle v='false'/>
  <slot id='1' type='GPU'/>
  <allow v='127.0.0.1,X.X.X.X/X'/>
  <web-allow v='127.0.0.1,X.X.X.X/X'/>
  <command-allow-no-pass v='127.0.0.1,X.X.X.X/X'/>
</config>
```

But it's folding this project which is not related to COVID-19:

Project 14434

This project simulates several myosins found in the human body. Myosins are the proteins responsible for most of the force generated by the body, from the contraction of muscles to the movement of materials around the cell. We are interested in understanding the mechanistic basis of drugs that might be used to treat defects in myosin, including hypertrophic and dilated cardiomyopathies as well as heart failure. Myosin was featured as the PDB Molecule of the Month in June 2001.

**Comment by ChrisTG7411** [comment]
Same here w/ 7.6.10 and Windows client.

**Comment by shorttack** [comment]
@FlorinAndrei This is not a bug. The program always follows your request and looks first for available work on your selected cause. However, if there is no work for the selected cause (i.e. COVID-19), the client selects available work compatible with your configuration. When that work unit is completed, it will look again at the input queue of your cause.

@ChrisTG7411 same answer
