### ISSUE TITLE
Cannot add GPU Slot/No GPU Slot generated by default

### ISSUE THREAD

**Issue by westernheld** [FoldingAtHome/fah-issues#1416]
![image](https://user-images.githubusercontent.com/1569381/80012606-d8484b00-84cd-11ea-818a-a209e4482dd8.png)
Freshly installed v 7.6.9 on Windows 10 v1909
Just a CPU Slot was generated, with the old Version i was able to compute also with GPU.
When trying to add the slot the entry for GPU just venishes and nothing happens.
Driver for GPU is latest for AMD R9 280X

**Comment by shorttack** [comment]
@westernheld See #1414  Install 7.6.10 at foldingathome.org/beta, which fixes exactly this bug. This will find the GPU and fold it.

**Comment by westernheld** [comment]
@shorttack Thanks! Didn't see that issue somehow on my first seethrough. I guess we can close this a duplicate.
