### ISSUE TITLE
Problem with parsing daily summary files.

### ISSUE THREAD

**Issue by wilyahm** [FoldingAtHome/fah-issues#1422]
Hello!

I've hit some barriers while trying to parse these files. Nothing i can't work around. But annoying nevertheless.

Both seem to have some "broken lines" like this
team | teamname | score | wu
------------ | ------------- | ------------- | -------------
|260927|JackHorns|10062|14
|81098|vijos|bebiruja|gakma
|<a href="http://ufhqbz3.biz/funny-greeting-cards.html ">chair</a> http://fqwi8vp.biz/boxer-breeders.html [url=http://bpsr9fo.biz|10061|71|

Oh and the daily user summary has duplicate entries? As in name and team not being unique.

Am i doing it wrong or is this intentional?

> [daily_user_summary.txt.bz2](https://apps.foldingathome.org/daily_user_summary.txt.bz2) 
> [daily_team_summary.txt.bz2]( https://apps.foldingathome.org/daily_team_summary.txt.bz2)

**Comment by PantherX** [comment]
AFAIK, usernames are not unique within F@H. Thus, you can have identical usernames without issues. It could be possible that they belong to the same team or different. Thus, I don't think it is an issue.

**Comment by ronnyreinertsen** [comment]
Username and team should be unique? But it's not unique in the summary file. You will find duplicate entries with history data, and that will mess up the reading and parsing of the latest score. So, by reading the latest file once, you cannot get single score for (username+team)

**Comment by PantherX** [comment]
Username and team will not be a unique combination as anyone can use whatever name they want and join any team. There's no restriction on that.

The only thing unique is the passkey. The combination of username/passkey is always unique.

**Comment by shorttack** [comment]
@wilyahm You ask good questions that might have answers at www.foldingforum.org, the official troubleshooting site for folding.

**Comment by PantherX** [comment]
Hiya @ronnyreinertsen 
Based on the fact that having multiple identical username+team combination is a design, I will close this issue.
BTW, you may want to contact EOC Stats (https://folding.extremeoverclocking.com/) to see how they deal with this.
