### ISSUE TITLE
Stats-API for time-series not giving result

### ISSUE THREAD

**Issue by ChristianVirtual** [FoldingAtHome/fah-issues#1423]
When I try the time-series stats for account and any period like this

https://api.foldingathome.org/time-series/account/daily/188510?end=20200423&count=10&sort=credit&descending=1

I get a result like this:
{"error":"Table 'ts.daily_account' doesn't exist","status":500}

**Comment by anand-bhat** [comment]
I'd reported this at https://github.com/FoldingAtHome/fah-issues/issues/1354 and Joseph had indicated the time series queries weren't coping well with the tons of new data pouring in. This can probably remain open until a permanent fix is in place.

**Comment by shorttack** [comment]
Closed: known issue at #1354
