### ISSUE TITLE
Address waisted computational idle time of network

### ISSUE THREAD

**Issue by wesleyolis** [FoldingAtHome/fah-issues#1425]
Hi,

Basically, as you can see below, I see there is now high priority, in which case
I would imagine that across all projects that have available work, you dish out work units.
Can we decided the priority and every there is nothing left if your preferences, then
pick the next best work unit from any other category, maybe this is an optional checkboxes feature.

Because waisting computational resource at your disposal slows progress obviously, especially if there work units in other major projects, that on is not supporting, but would like to determine there specific ordering of supported projects.

Imagion High has COVID-19 is top of the list.

Can some on also explain the progress of the project on the projects stats page.

Then I guess the other thing hopefully in work units, I don't know the details, is that machine that has six sigma reliability of returning and doing work, at highest computation rates are first assigned workloads of high priority, followed by those lower. Ideally, you looking to reduce and optimize the finishing time of all the workloads, you don't want 1 client to have a workload, that results in taking an additional 8 days to complete, so if faster clients can finish the workloads faster statistically, can work off a set of work units in the expected time of 4days processing 8 work units, then there is no point giving a work unit to someone that would take 8days, just means you going to be waisting computation and slowing down the rate at which the project is completed.

Guess have optimization algorithm, running the permutations, set of all clients and configurations, which then be simplified into common aggregations buckets of WU, sigma, work rate, work rate reliability, work rate min, max, avg, std. Then of all WU units available, assign them into the different work-rate aggregations' buckets, or assigned basically maximum slowest work-rate unit bucket, due to anything less than this just be wasting resource and creating additional waiting time as explained above. Every time new projects are added, then have to re-run this permutations algorithm, to update the distribution of the project of units, across work-rate aggregation buckets for assignment, when wu are requested. Basically match resources based on how reliable and efficient they are to complete the project in the least amount of time.

Obviously, you only updated the clients into add common aggregation buckets of WU, at a slower rate or incrementally as required promotion and de-promotion.

To take this further, each client for should report the typically maximum, avg, min power consumption of there chip average across the cores they were using, that is also then taken into account for the aggregation buckets. In which now you can compute to optimization dimensions max horsepower and measure the power consumption of the network, or have a balance between 
max horsepower and power consumption, to where the curve flattens out, less CO2 emissions you saving the world.

To improve this further, ideally client on the machine, should be able to run the computations and then PWM idle cycles, or so to reduce power consumption, then measure system at different loads at the granularity of 1% which then also gets submitted and maintained by there client with re-benchmark/sample, which checks randomly from time to time as well.

Having this information about your client machines and the computation WU rate/ power consumption you can then basically find the sweet spot of balancing power and performance of the network.

In the long run, what this results in is naturally old slow and computation power inefficient clients, will no longer get work, as they can no longer make the baseline of WUrate/power consumption rate WU, which means just be doing the environmental damage. 

If you would like to take this further, then that would be having the geographic location of the client and statistics as detail as you can get of there power source, in which cases as this information that would be obtained from national power operators changes for wind extra availability, then you can re-run section of the distribution of WU to aggregation WU clients, based on how clean there power is.

You could also associate each client with the geographic power rate in that country, which would allow you to in ways know which would be the cheapest to run, but balancing at between cheap and CO2.

The other is for the client indicate that they are off grid, and solar, in which case probably don't care as long its runoff solar permantely.

Eventually this turns into a nice little AI problem.

3:39:53:WU00:FS00:Upload 65.46%
03:39:59:WU00:FS00:Upload 68.19%
03:40:05:WU00:FS00:Upload 70.66%
03:40:11:WU00:FS00:Upload 73.25%
03:40:17:WU00:FS00:Upload 75.85%
03:40:23:WU00:FS00:Upload 78.71%
03:40:29:WU00:FS00:Upload 81.57%
03:40:35:WU00:FS00:Upload 83.39%
03:40:41:WU00:FS00:Upload 85.46%
03:40:47:WU00:FS00:Upload 88.19%
03:40:53:WU00:FS00:Upload 91.18%
03:40:59:WU00:FS00:Upload 94.04%
03:41:05:WU00:FS00:Upload 96.63%
03:41:11:WU00:FS00:Upload 99.23%
03:41:13:WU00:FS00:Upload complete
03:41:13:WU00:FS00:Server responded WORK_ACK (400)
03:41:13:WU00:FS00:Final credit estimate, 128670.00 points
03:41:14:WU00:FS00:Cleaning up
05:58:14:WU00:FS00:Connecting to 65.254.110.245:80
05:58:15:WU00:FS00:Assigned to work server 13.82.98.119
05:58:15:WU00:FS00:Requesting new work unit for slot 00: READY gpu:0:TU116-250 [GeForce GTX 1650 SUPER] from 13.82.98.119
05:58:15:WU00:FS00:Connecting to 13.82.98.119:8080
05:58:36:WARNING:WU00:FS00:WorkServer connection failed on port 8080 trying 80
05:58:36:WU00:FS00:Connecting to 13.82.98.119:80
05:58:57:ERROR:WU00:FS00:Exception: Failed to connect to 13.82.98.119:80: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
05:58:57:WU00:FS00:Connecting to 65.254.110.245:80
05:58:58:WARNING:WU00:FS00:Failed to get assignment from '65.254.110.245:80': No WUs available for this configuration
05:58:58:WU00:FS00:Connecting to 18.218.241.186:80
05:58:59:WARNING:WU00:FS00:Failed to get assignment from '18.218.241.186:80': No WUs available for this configuration
05:58:59:WU00:FS00:Connecting to 65.254.110.245:80
05:59:00:WU00:FS00:Assigned to work server 13.82.98.119
05:59:00:WU00:FS00:Requesting new work unit for slot 00: READY gpu:0:TU116-250 [GeForce GTX 1650 SUPER] from 13.82.98.119
05:59:00:WU00:FS00:Connecting to 13.82.98.119:8080
05:59:53:ERROR:WU00:FS00:Exception: 10002: Received short response, expected 512 bytes, got 0
05:59:57:WU00:FS00:Connecting to 65.254.110.245:80
05:59:58:WARNING:WU00:FS00:Failed to get assignment from '65.254.110.245:80': No WUs available for this configuration
05:59:58:WU00:FS00:Connecting to 18.218.241.186:80
05:59:59:WARNING:WU00:FS00:Failed to get assignment from '18.218.241.186:80': No WUs available for this configuration
05:59:59:WU00:FS00:Connecting to 65.254.110.245:80
06:00:00:WARNING:WU00:FS00:Failed to get assignment from '65.254.110.245:80': No WUs available for this configuration
06:00:00:WU00:FS00:Connecting to 18.218.241.186:80
06:00:01:WARNING:WU00:FS00:Failed to get assignment from '18.218.241.186:80': No WUs available for this configuration
06:00:01:ERROR:WU00:FS00:Exception: Could not get an assignment
06:01:34:WU00:FS00:Connecting to 65.254.110.245:80
06:01:35:WARNING:WU00:FS00:Failed to get assignment from '65.254.110.245:80': No WUs available for this configuration
06:01:35:WU00:FS00:Connecting to 18.218.241.186:80
06:01:36:WARNING:WU00:FS00:Failed to get assignment from '18.218.241.186:80': No WUs available for this configuration
06:01:36:WU00:FS00:Connecting to 65.254.110.245:80
06:01:37:WARNING:WU00:FS00:Failed to get assignment from '65.254.110.245:80': No WUs available for this configuration
06:01:37:WU00:FS00:Connecting to 18.218.241.186:80
06:01:37:WARNING:WU00:FS00:Failed to get assignment from '18.218.241.186:80': No WUs available for this configuration
06:01:37:ERROR:WU00:FS00:Exception: Could not get an assignment
06:04:12:WU00:FS00:Connecting to 65.254.110.245:80
06:04:12:WARNING:WU00:FS00:Failed to get assignment from '65.254.110.245:80': No WUs available for this configuration
06:04:12:WU00:FS00:Connecting to 18.218.241.186:80
06:04:13:WARNING:WU00:FS00:Failed to get assignment from '18.218.241.186:80': No WUs available for this configuration
06:04:13:WU00:FS00:Connecting to 65.254.110.245:80
06:04:14:WARNING:WU00:FS00:Failed to get assignment from '65.254.110.245:80': No WUs available for this configuration
06:04:14:WU00:FS00:Connecting to 18.218.241.186:80
06:04:15:WU00:FS00:Assigned to work server 13.82.98.119
06:04:15:WU00:FS00:Requesting new work unit for slot 00: READY gpu:0:TU116-250 [GeForce GTX 1650 SUPER] from 13.82.98.119
06:04:15:WU00:FS00:Connecting to 13.82.98.119:8080
06:04:47:ERROR:WU00:FS00:Exception: Server did not assign work unit

**Comment by PantherX** [comment]
Please note that GitHub is for tracking issues that the development team can reproduce and fix. Unfortunately, you haven't posted an issue, just a suggestion. We encourage you to have discussions at the Official Forum https://foldingforum.org/index.php where you may find answers to some of your suggestions :)

Regarding your idea of having a "next priority Project" do note that the current stable version allows you to set a preference of disease type. If there's no WU available for that disease, you will be assigned a WU that's suitable to your hardware and is "next in line" priority wise.

I will now close this issue but you're welcomed to discuss your ideas at the Official Forum.

**Comment by wesleyolis** [comment]
@PantherX Shall do ;-)
