### ISSUE TITLE
Client auto update request

### ISSUE THREAD

**Issue by Asteliks** [FoldingAtHome/fah-issues#1428]
This is more of a feature request than a bug report. We at the Poznan University of technology have more than 500 computers running F@H. An auto update feature would be of much use. Reinstalling all those clients to get the latest security fixes is a real struggle.
What we could use is for the client to update by itself without requiring any human input.

**Comment by edumorlom** [comment]
Yes, please! This is a must

**Comment by shorttack** [comment]
Label: FAHControl
FAHControl is the logical place to do the auto-update check, although FAHControl auto-update would be elegant.

**Comment by shorttack** [comment]
Closed Duplicate #1404
