### ISSUE TITLE
Certain GPU projects show up having been completed on CPU slots in the cpu stats

### ISSUE THREAD

**Issue by anand-bhat** [FoldingAtHome/fah-issues#1442]
Certain GPU projects (for instance, 14437, 14549, 16433 and possibly others) show up having been completed on CPU slots in the cpu stats.

Here is an example from a user's report (all entries highlighted in green are GPU projects but some show as CPU slots).

![image](https://user-images.githubusercontent.com/7332442/80780105-1110b000-8bb1-11ea-824a-18579392e046.png)

I'm not certain if this is also misreporting active CPU/ GPU count to os stats.

**Comment by PantherX** [comment]
IIRC, it might be when the Project was created, the incorrect fields were copied and hence, the macOS GPU issue and this one too?

**Comment by anand-bhat** [comment]
Yeah, I suspect it's something with the project configuration. The same slots show up correctly as GPU slots when working on other projects so it's unlikely to be a client issue.

**Comment by anand-bhat** [comment]
Closing this as there have been no new cases for the past 6 months.
