### ISSUE TITLE
7.6.9: Gatekeeper issues

### ISSUE THREAD

**Issue by vonorlow** [FoldingAtHome/fah-issues#1457]
The current version is unable to install on macOS systems (without using the bypass button in System Preferences - Security & Privacy - General) due to not being notarised by Apple.

**Comment by shorttack** [comment]
@vonorlow Apple has software app store requirements that Folding at Home is unable to meet. This is unlikely to change. As you have discovered, the bypass button is going to be standard practice for the foreseeable future.
-Issue Support-

**Comment by shochberg** [comment]
You can notarize without meeting the app store requirements, as long as you are not using the app store to distribute. That would avoid this issue.

**Comment by macblazer** [comment]
I don't know the build process used for the Mac client, but notarization of a Developer ID signed application is usually straightforward.  This would let you distribute the apps and installer outside of the App Store as you currently do, but still participate in Apple's security system for macOS 10.15+

As @shochberg mentioned, you do not need to follow App Store requirements for notarization.  The main requirement that maybe could be some work is that you have enabled the hardened runtime for your app.  https://developer.apple.com/documentation/security/hardened_runtime

All the official notarization information is available here: https://developer.apple.com/documentation/xcode/notarizing_macos_software_before_distribution

If you use fastlane to help coordinate the Mac build, they have a notarization action you can use.  More info on that here:
https://docs.fastlane.tools/actions/notarize/

**Comment by shorttack** [comment]
@macblazer Thanks very much for these links.

**Comment by kbernhagen** [comment]
Thanks. This has been fixed.
