### ISSUE TITLE
7.6.13 on Ubuntu 20.04 pauses on idle

### ISSUE THREAD

**Issue by ipkh** [FoldingAtHome/fah-issues#1461]
I'm running Xubuntu 20.04 and when I leave the computer and cone back, fahclient says Paused:user request.  It is set to Full and Fold while working in Fahcontrol and web control.

**Comment by shorttack** [comment]
@ipkh Please note that we tend to use GitHub for development issues that are reproducible. For troubleshooting, heading over to the Official Forum is the best option: [https://foldingforum.org/index.php](url) where there are lots of Donors who are happy to help out Let's see if others are seeing this problem. :)

Report to the forum you Sleep and screensaver settings, please.
