### ISSUE TITLE
Completed a long task but no points reward.

### ISSUE THREAD

**Issue by Federico-Caraffi** [FoldingAtHome/fah-issues#1466]
Windows 10, version 7.6.13
Username: Federico_Caraffi

Have just completed a big task that required a lot of hours to do (10 more or less). But then no points were given. I don't remember the WU number and if there is a history i'm unaware of it's existence. 
I don't know if the WU has been completely correctly or not. hope this bug report helps

**Comment by ffissore** [comment]
Please take a look at [this faq entry](https://foldingathome.org/support/faq/points/#when-will-my-points-username-or-team-appear-in-the-folding-statistics): your points should show up in at most an hour. Please consider giving the servers some more time, due to the high load they are handing during these covid times

**Comment by Federico-Caraffi** [comment]
> Please take a look at [this faq entry](https://foldingathome.org/support/faq/points/#when-will-my-points-username-or-team-appear-in-the-folding-statistics): your points should show up in at most an hour. Please consider giving the servers some more time, due to the high load they are handling during these covid times


Took 2 hours but it appeared now. Sorry for the waste of time. 
Grazie Federico :)

**Comment by chordlines** [comment]
I have the same problem. No points. But i have waited over 12 hrs. I have completed many tasks already but no Points..

**Comment by PantherX** [comment]
@chordlines 
Please note that there's a known cosmetic issue with the Stats: https://foldingforum.org/viewtopic.php?f=16&t=35430
If that isn't your issue, please head over to the Official Forum and post with all the details. We prefer to use GitHub for documented issues and ask Donors to head to the Forum for troubleshooting.
