### ISSUE TITLE
fahclient 7.6.x ignore <power value="*"/> - fahcontrol  overwrite item on config.xml

### ISSUE THREAD

**Issue by PeterGarlic** [FoldingAtHome/fah-issues#1467]
Hello
we are testing inside our labs for a massive deployment of fah clients based on centos7/fedora32 4 cpu VMs on a KVM cluster. 

The problem we found is that on /etc/fahclient/config.xml the tag <power value> is ignored with any value from faclient and then the program start using 100% of all vCpu generating warnings on the cluster infrastructure.

```
  <!-- Slot Control
       Options: light, medium or full
       Watch out for high load -->
  <power v='medium'/>
```

Using FAHcontrol as alternative configuration approach any configuration change made inside the GUI overwrite the config.xml and remove the tag  <power> if inserted manually.

This problem has been tested on a KVM cluster, Virtualbox (on windows host) with Centos 7.7, 7.8, Fedora31 and Fedora32 as clients.

**Comment by shorttack** [comment]
@PeterGarlic 
1. We upgraded the public beta yesterday from 7.6.9 to 7.6.13.
2. Please take this code to the community at [https://foldingforum.org/index.php](url) for diagnosis where there are lots of Donors who are happy to help out :) We cannot diagnose here.
3. Why not have FAHControl generate a config.xml file that contains the Power Level settings you desire, and then migrating that file as part of your rollout to each client? I can assure you that in my experience a config.xml file generated by FAHControl will be accepted the next time FAHClient starts up.

**Comment by shorttack** [comment]
Note:  Linux VM Centos7

**Comment by ffissore** [comment]
@PeterGarlic side note: config.xml changes won't be loaded by a running FAHClient. You need to either provide the desired xml file before the service is started, or restart the service once config.xml is modified, or start FAHClient manually providing all options as command line params (and disabling the service)

**Comment by PeterGarlic** [comment]
Hi @shorttack 
Thanks for you fast feedback.  Here some reply:
1. We tested both 7.6.9 and 7.6.13. Same issue.
2. There are some problem with account creation and this is why I have created one issue here.
3. The problem can be easily reproduced and if this can help the development I can post all required steps for that.

**Comment by shorttack** [comment]
> The problem can be easily reproduced and if this can help the development I can post all required steps for that.

@PeterGarlic Yes, please post steps to reproduce and I will flag the defect.
Also. note ffissore comment above about when config.xml is loaded.

**Comment by PeterGarlic** [comment]
> 
> 
> @PeterGarlic side note: config.xml changes won't be loaded by a running FAHClient. You need to either provide the desired xml file before the service is started, or restart the service once config.xml is modified, or start FAHClient manually providing all options as command line params (and disabling the service)

We tested also this procedure on our lab

**Comment by PeterGarlic** [comment]
Excuse me for the late feedback. I tested the process also on ubuntu 18.04LTS to be sure that is not one OS/Distro related issue:

Steps to reproduce the problem:

00) Create a vm with 4 cpu
01) install fahclient, fahcontrol, faviewer and dependencies on your linux (Centos, Fedora, Ubuntu)
02) backup and review you /etc/fahclient/config.xml
03) start fahclient with /etc/init.d/FAHclient start 
04) Start FAHcontrol,  check credentials and that you have 1 cpu slot available 
05) start resource monitor to keep under control cpu usage
06) test start/pause folding from FAH - from resource monitor you can see that "Power Slide" have no effects on cpu utilization

10) stop all
11) edit you /etc/fahcontrol/config.xml  and add the tag power control

```
<config>
  <!-- Client Control -->
  <fold-anon v='true'/>

  <!-- Folding Slot Configuration -->
  <gpu v='false'/>

  <!-- Slot Control -->
  <power v='light'/>

  <!-- Remote Command Server -->
  <password v='mypass'/>

  <!-- User Information -->
  <passkey v='mypassword'/>
  <user v='myusername'/>

  <!-- Folding Slots -->
  <slot id='0' type='CPU'>  </slot>
  <slot id='1' type='CPU'>  </slot>
</config>

```
12) Restart FAHclient
13) Open FAHcontrol & resource monitor
14) Check that job are running
15) check the resource monitor and you will have again 2 cpu at 100% despite the <power> tag

The expected effect of the FAHcontrol "Power slide" and/or config.xml <power> tag is a different CPU load for the 2 available settings.

Will also be really nice that to see the load not always be on the same core.

**Comment by shorttack** [comment]
@PeterGarlic I repeat: please take this problem to foldingforum.org and post under Linux. I am not a diagnostician. What you are trying to do is not documented at https://foldingathome.org/support/faq/installation-guides/linux/command-line-options/.

My personal opinion is you are are running all cores, TWICE, by having two slots for cpu. See the Threads option in FAHControl when you add a cpu slot.  That would explain excessive cpu load.

As I suggested, having FAHCcontrol build a working config.xml file is a very good idea.

Back off to one cpu slot. Try it. Then go to foldingforum.org. Good luck. No more assistance here. I’m slowing you down.

**Comment by PantherX** [comment]
Please note that this is not an issue so I will be closing this issue.

However, assuming you have issues with Forum registration (I haven't heard any issues), I can help you out while you register at the forum.

You created a VM with 4 CPUs. If you want 50% usage of the VM, then this configuration will work:
```
  ...
  <!-- Slot Control -->
  <power v='full'/>
...
  <!-- Folding Slots -->
  <slot id='0' type='CPU'>
    <cpus v='2'/>
  </slot>
...
```
If you have 8 CPUs, and require 50% usage then the value is 4. Just note that you can control the CPU usage based on the CPUs assigned to the CPU Slot.
