### ISSUE TITLE
Add usage, purpose instructions at GitHub.com/foldingathome/FAH-issues

### ISSUE THREAD

**Issue by shorttack** [FoldingAtHome/fah-issues#1478]
Place instructions in <Code> tab that explains what the GitHub site’s purpose is and how to use it. Emphasize the availability and purpose of foldingforum.org, our sister site.

**Comment by PantherX** [comment]
Please note that I tried to address it in the Pull Request by having the information in various places to ensure that regardless of how the "workflow" is started, the donor gets to view that information :)
https://github.com/FoldingAtHome/fah-issues/pull/1481

**Comment by PantherX** [comment]
I have done the following which I believes covers your request:
https://github.com/FoldingAtHome/fah-issues/pull/1481
https://github.com/FoldingAtHome/fah-issues/pull/1493
https://github.com/FoldingAtHome/fah-issues/pull/1494
https://github.com/FoldingAtHome/fah-issues/pull/1495
https://github.com/FoldingAtHome/fah-issues/pull/1496
https://github.com/FoldingAtHome/fah-issues/pull/1500
https://github.com/FoldingAtHome/fah-issues/pull/1506

I will close this now. However, if you think that I have missed something, please re-open it with the details and we can address it :)
