### ISSUE TITLE
public and beta flags for projects aren't accurate

### ISSUE THREAD

**Issue by anand-bhat** [FoldingAtHome/fah-issues#1482]
[psummary ](https://apps.foldingathome.org/psummary)uses https://apps.foldingathome.org/psummary.json which contains two flags -- public and beta. These flags are used in two place that I'm aware of:

1. These are used to control what projects are displayed in psummary - [all](https://apps.foldingathome.org/psummary?visibility=ALL), [beta](https://apps.foldingathome.org/psummary?visibility=BETA) or [public](https://apps.foldingathome.org/psummary?visibility=PUBLIC)

2. These flags are used to aggregate the public and beta WU counts on [serverstats](https://apps.foldingathome.org/serverstats)

However, it appears the flags do not accurately represent the states of the project. For instance, none of the projects on 37.187.12.48 are available outside of the pre-release environment but are flagged as public=true & beta=true. The counts in serverstats against this server are therefore not truly public or beta WUs and the projects shouldn't be listed in the public and beta psummary pages.

There are also a number of projects that are released to FAH but have the beta flag set, inflating the beta WU counts in serverstats.

**Comment by shorttack** [comment]
Defect is beta and public flags should be mutually exclusive. If Public=True, then Beta must = False, and vice versa.

**Comment by anand-bhat** [comment]
This appears to have been fixed when seen on 2020-08-05. psummary with the Beta filter is now showing the correct beta projects and the counts in serverstats are correct.

Note: There are two projects with both public and beta set to true. These are the COVID-19 Moonshot.

![image](https://user-images.githubusercontent.com/7332442/89360840-f64c5b00-d70c-11ea-9f20-e89ed5d7dd75.png)
![image](https://user-images.githubusercontent.com/7332442/89360871-0e23df00-d70d-11ea-9593-b09bd3b40a75.png)
