### ISSUE TITLE
Pause FAH automatically when an exclusive app is running

### ISSUE THREAD

**Issue by informatorius** [FoldingAtHome/fah-issues#1485]
I wish a feature for FAH that it pause automatically when an exclusive app is running. User could configure in FAHcontrol or config a list of exclusive apps which is just the process name or path. FAHclient monitors  running processes and when a process is contained in exclusive apps then FAHclient pause. If no exclusive app is running anymore then FAHclient unpause.

**Comment by TunaErtemalp** [comment]
I think this is the same as #1480 I had opened up a few days back.

**Comment by shorttack** [comment]
Closed: duplicate enhancement.
