### ISSUE TITLE
The F@H Screen Saver (Fahscreensaver) for Win 10 does not work properly

### ISSUE THREAD

**Issue by ejoepan1** [FoldingAtHome/fah-issues#1486]
While trying to figure out the F@H Work Only When Idle setting works, I discovered in Github F@H issue 1483 that the idle state was when the computer, not the user, was idle and that an example of this state was when a screensaver was active.  I decided to add a screensaver to see the Work Only When Idle setting in action and discovered there was a F@H Screen Saver (Fahscreensaver in the dropdown of screen savers that could be used).  I decided to try it as I thought seeing the protein being modeled would be neat.  However, after waiting for the appropriate amount of idle time set the screen saver settings, the Fahscreensaver pops up and immediately closes.  Other screensavers will pop up and stay up until the keyboard or mouse is touched.

**Comment by TunaErtemalp** [comment]
Just as a note: the FAH screen saver does work on my Win10 machine. So, this might be an issue with the version of Win10 or some other hardware/software config/setting.

**Comment by ejoepan1** [comment]
###
