### ISSUE TITLE
Dialog Box opened from FahCore22.exe, entry point clReleaseDevice could not be located

### ISSUE THREAD

**Issue by lurklad** [FoldingAtHome/fah-issues#1491]
## Environment
See Defect report #1490 
* OS:
* FAH version:

**Comment by PantherX** [comment]
Hiya @lurklad 
Please note that I will close this as a duplicate and respond to you in the original ticket :) In future, please refrain from creating duplicate tickets to reduce unnecessary overhead and for clarity sake too :)
