### ISSUE TITLE
Please provide ppc64le Linux client/cores

### ISSUE THREAD

**Issue by esyr** [FoldingAtHome/fah-issues#1499]
It's a shame that F@H client is closed-source _and_ provides _only_ x86_64 binaries, leaving out other capable architectures. Having a (mosly) idling 5700XT on a ppc64le machine, I'd like to request ppc64le client/core builds as a way to utilise it.

**Comment by PantherX** [comment]
Please note that the development for a new architecture isn't possible at this stage. The development team is focused on supporting the existing infrastructure and have a lot on their plate.

I will close this issue now. If you would like further discussion, please head over to the official Forum (https://foldingforum.org/index.php). Thanks for your suggestion :)
