### ISSUE TITLE
failed to get new WU at system startup - fails to retry.

### ISSUE THREAD

**Issue by madtom1999** [FoldingAtHome/fah-issues#1503]
Your issue may already be reported!
Please search on the [issue tracker](./) before creating one.
## Your Environment

* **F@H Software version**: 7.5.1
* **Operating System**: Xubuntu 18,04
* **Browser**: 

----
## Expected Behavior

----
## Current Behavior

----
## Possible Solution (Optional)

----
## Steps To Reproduce

1.
2.
3.
I have not been able to manually reproduce the problem It seems to occur when the system is shutdown and restarted around the time a new WU is collected and the old one finished automatically. I have tried to reproduce the problem by getting f@h to stop at the end of a WU and then rebooting the system but that seems to restart happily.

----
## Context

----

**Comment by PantherX** [comment]
Hiya @madtom1999 

May I please suggest that you start with troubleshooting at the Official Forum (https://foldingforum.org/index.php) where there are lots of members who would be happy to investigate and help you resolve this issue.

For now, I will close this issue as it can't be replicated by the development team. However, if you're able to recreate it with the help of Forum members, you can edit this issue and would be more than happy to reopen it :)
