### ISSUE TITLE
Points are not updating

### ISSUE THREAD

**Issue by ritualrain10** [FoldingAtHome/fah-issues#1514]
Our points have not updated for my TEAM since last night....completed over 50 work units but still stuck. Is there an issue? This is across multiple computers.

**Comment by PantherX** [comment]
Hiya @ritualrain10 
Please note that this is a known issue: https://foldingforum.org/viewtopic.php?f=16&t=35430

I will close your issue now. If you need further assistance, please head over to the Forums.

P.S. In future, please use the template provided as it makes triaging the issues a lot easier for the volunteers. Having consistency in the issues makes it really easy for the development team to analyze.
