### ISSUE TITLE
Occasional "Work Quit (404)" and dumping successful finished WUs on upload.

### ISSUE THREAD

**Issue by unf** [FoldingAtHome/fah-issues#1520]
Your issue may already be reported!
Please search on the [issue tracker](./) before creating one.

## Your Environment

* **F@H Software version**: 7.6.13
* **Operating System**: Ubuntu LTS 20.04
* **Browser**: Firefox 77 (not used, machine is controled remotly by FAHControl)
* **Hardware**: MSI B450 A Pro Max, Ryzen 7 2700, 2x 8GB DDR4-3000, WD 256GB NVMe, GTX 1660 Super & GTX 950
* **Internet connection**: 250MBit/s

----
## Expected Behavior

After error free folding, a WU should be upload flawless and successful.

----
## Current Behavior

Occasionally successful folded WUs are not uploaded successful. They seem to be fully uploaded, but FAHClient get's a "Work Quit (404)" and the correct results get dumped.

It's not a big deal on a fast GPU, a small WU folded in a short time, but frustrating if the gear folded XX hours on it successfully and is then dumped without running into any timeout ...

Please see this example, it's a rather fast GTX 1660 Super, folding succesful a WU under 2 hours, but upload failed:

**[log.txt](https://github.com/FoldingAtHome/fah-issues/files/4754705/log.txt)**
----
## Possible Solution (Optional)

No suggestion, but looks like an issue on the work servers ...

----
## Steps To Reproduce

1. Nothing to provide to reproduce it ... just let the gear run and check logs from time to time.

----
## Context

Well, at the end my gear doesn't get it's credits, but that's not the point. Any successfully finished job should be received flawless, otherwise it's a waste of valuable computing time and power ...

----

**Comment by bb30994** [comment]
The client is supposed to get confirmation from the server that the WU was successfully received before discarding the local copy of the data.  It's interesting that the error code is 404, which doesn't confirm that anything was received.

My question would be to ask the server's owner to inspect the servers log and what it says about the upload at this particular time/date.

**Comment by unf** [comment]
@bb30994 All information is in the appended "log.txt" above.

But that thing happens occasionally on different of my machines and different FAH work servers. No pattern visable, just, it doesn't happen twice after another.

**Comment by PantherX** [comment]
Hiya @unf 
Please note that it seems that one potential cause of this issue is when the WS is out of space. That has been documented here #1522 so I will mark this issue as a duplicate and close it 😃
