### ISSUE TITLE
Domain decomposition error

### ISSUE THREAD

**Issue by bb30994** [FoldingAtHome/fah-issues#1521]
Your issue may already be reported!
Please search on the [issue tracker](./) before creating one.

## Your Environment
https://foldingforum.org/viewtopic.php?f=19&t=35537 and
https://foldingforum.org/viewtopic.php?f=19&t=35488

----
## Expected Behavior
When confronted with a prime number of threads, FAHCore_a7 attempts to reduce that number to a workable number.

e.g. 11 > 10 
followed by 
10 > 9

Reducing the number of threads from 11 to 10 should actually reduce it to 9.

Reducing the number of threads from 15 to 14 should actually reduce it to 12.

----
## Current Behavior

Domain decomposition fails.

----
## Possible Solution (Optional)

----
## Steps To Reproduce

1.  Set a slot for 11 threads.
2. Some projects work with 10, some do not.  Choose one which fails with 10.
3. (See example in linked report)

----
## Context

----

**Comment by informatorius** [comment]
Maybe that would be a workaround for the problem in some work units if fahcore would itself downscale the number of threads when this error occurs?

**Comment by jakewilkins** [comment]
I've had a WU stuck in this loop for 5 days now 😢 Is there a known workaround?

**Comment by janhalt** [comment]
Manually reduce the number of cores available.

If using FAHControl, see this guide.  https://foldingathome.org/support/faq/installation-guides/configuration-guide/#customize-one-slot-local-setting

For instance, my client defaulted to 15 cores, this caused the work unit to fail per this bug, manually changing the CPU slot to 12 cores allows the stuck work unit to start and complete.

**Comment by ejoepan1** [comment]
F@H has a problem dealing with the number of cores being a prime number.  The table shown here has the numbers that work.  https://foldingforum.org/viewtopic.php?f=38&t=35286#p335183

**Comment by janhalt** [comment]
There are also work units that fail when the number of cores is decomposed into larger prime numbers.  (eg 2^x generally always works, as will 3^z, or (3^z+2^x), but including the prime 5 eg (5^w) sometimes fails like it did with the work units I reported.

The bug here is that the FAH client is expected to automatically reduce the number of cores when this error is encountered, but there are multiple examples posted where this automatic core count reduction failed.

**Comment by PantherX** [comment]
FYI, the update on this is that there's a new FahCore_a8 in development and the idea is that it will be designed to intelligently handle such errors in a transparent manner. Thus, the folding experience for donors should be much better 😃

**Comment by bb30994** [comment]
FAHCore_a8 is now released and production is growing.  The problem will not be fixed in FAHCore_a7 and in with the current work-around in FAH's server code.  As FAHCore_a8 gradually replaces _a7 the problem will dissapear.
