### ISSUE TITLE
Website "Contact Us" page links to web.archive.org instead of Discord, forum, GitHub and email addresses

### ISSUE THREAD

**Issue by remocrevo** [FoldingAtHome/fah-issues#1530]
Your issue may already be reported!
Please search on the [issue tracker](./) before creating one.

## Your Environment

* **F@H Software version**: None
* **Operating System**: Windows 10
* **Browser**: Firefox

----
## Expected Behavior

This web page should have normal web links, not links to archived pages in the Internet Archive:
https://foldingathome.org/contact-us/

----
## Current Behavior

Links on this page go to archived pages:
https://foldingathome.org/contact-us/

For example, the GitHub link goes to:
https://web.archive.org/web/20200522200753/https://github.com/FoldingAtHome/fah-issues/issues

----
## Possible Solution (Optional)

----
## Steps To Reproduce

1. Go to the contact us page
2. Click any link in the main content of the page (not including social media links)
3. You end up at the Internet Archive

----
## Context

----

**Comment by anand-bhat** [comment]
All links now point to the correct locations.
