### ISSUE TITLE
Raspberry Pi / ARM Version

### ISSUE THREAD

**Issue by Niwla23** [FoldingAtHome/fah-issues#1534]
----
## Describe the Feature
Add an ARM Version

----
## Context
Use it on the Raspberry Pi 4

**Comment by bb30994** [comment]
Development work has been going on but FAH has not announced an ARM client or supporting software yet.  That means that there are still unresolved issues that await developmental solutions.  

FAH does not pre-announce anything that isn't ready for production nor suggest specific dates when announcements may be expected.

**Comment by anand-bhat** [comment]
The [v7.6.21 release](https://foldingathome.org/2020/11/24/new-client-with-arm-support/) of the client includes ARM 64-bit support. Projects that use the A8 science core (FAHCore_A8) will be available  to these clients.
