### ISSUE TITLE
I changed my name (identity) and lost my points and WU’s.

### ISSUE THREAD

**Issue by MARF-123** [FoldingAtHome/fah-issues#1538]
Good morning, I am part of the AVAST team (team 236,798).

I work with 3 computers and, on one of them, I just changed my name (from M.A.R.F.-1. to M.A.R.F.-1-Core2Duo.2.00GHz.) and, when I saved the change, I lost all my 21,794 points and 22 or 23 WUs.  I returned my name to M.A.R.F.-1., but I still couldn't recover my points, nor my WU’s.  Wouldn't it be possible for punctuation and WU’s to be linked to the IP Address, instead of being linked to the name (identity)?

Likewise, before perfecting my name (from M.A.R.F. to M.A.R.F.-1), I ended up leaving some points and WU’s along the way, which were not used to compose my total score.  Is there no way to take advantage of these points by adding them all to my IP Address?

My computer (M.A.R.F.-1) took several days to complete a 5000 point WU.  But, I don't know why, these points were not counted for my score.  Can't you add them to it?

My other 2 computers, on the other hand, presented a great difference in the speed of processing WUs. I had named the one with the highest capacity of M.A.R.F.-2.;  and the one with the lowest capacity of M.A.R.F.-3.  But I noticed that, strangely, M.A.R.F.-3. processed WU’s much faster than M.A.R.F.-2.  So I decided to invert their names, so that the fastest name (3) was ahead of the slowest (2).  However, both names and scores and WU’s have also been reversed.  I understand that it would be better if the points and WU’s were tied to the IP addresses, and not to the names we give to our computers.

**Comment by ChristianVirtual** [comment]
Hello, that sound more a support issue and not a software bug or enhancement. Could you head over to foldingforum.org and raise your issue there ? I’m sure you get better response there.

**Comment by MARF-123** [comment]
Hello, thanks for the answer.  Please, send-me the eletronic adress.
________________________________
De: Christian Lohmann <notifications@github.com>
Enviado: quinta-feira, 9 de julho de 2020 07:08
Para: FoldingAtHome/fah-issues <fah-issues@noreply.github.com>
Cc: MARF-123 <winchester44wcf@hotmail.com>; Author <author@noreply.github.com>
Assunto: Re: [FoldingAtHome/fah-issues] I changed my name (identity) and lost my points and WU’s. (#1538)


Hello, that sound more a support issue and not a software bug or enhancement. Could you head over to foldingforum.org and raise your issue there ? I’m sure you get better response there.

**Comment by PantherX** [comment]
Hiya @MARF-123 
Please note that once a WU has been credited with a particular combination of username/passkey/team, it will be virtually immutable. They can't be transferred to any other account or username.

Your points are not lost, instead, if you search on the official stats (https://stats.foldingathome.org/donor) with the correct details, you will find them there. If you would like to discuss this further, please head over to the Official Forum (https://foldingforum.org/index.php) for troubleshooting. There are many members there to help you out and suggest various options for you to make an informed decision.

We tend to use GitHub for documented issues for the development team to resolve. I will close this issue now as it isn't an issue. :smiley:
