### ISSUE TITLE
Cannot install fahcontrol in Linux Mint 20

### ISSUE THREAD

**Issue by holmesrichards** [FoldingAtHome/fah-issues#1539]
Your issue may already be reported!
Please search on the [issue tracker](./) before creating one.

## Your Environment

* **fahcontrol_7.6.13-1**
* **Linux Mint 20**

----
## Expected Behavior

Should have been able to install

----
## Current Behavior

Could not install

----
## Possible Solution (Optional)

----
## Steps To Reproduce

1. Download fahcontrol_7.6.13-1_all.deb
2. Double click on icon 
3. Window has error message: "Error: Dependency is not satisfiable: python"

----
## Context

----

**Comment by ChristianVirtual** [comment]
Have you seen this posting in the support forum ?
https://foldingforum.org/viewtopic.php?f=108&t=35707

**Comment by ffissore** [comment]
Duplicate of #858
