### ISSUE TITLE
Download stalls, client never errors out, requires machine restart to clear fault

### ISSUE THREAD

**Issue by rhavern** [FoldingAtHome/fah-issues#1542]
18:41:47:WU00:FS01:Connecting to assign1.foldingathome.org:80
18:41:48:WU00:FS01:Assigned to work server 155.247.166.220
18:41:48:WU00:FS01:Requesting new work unit for slot 01: RUNNING gpu:0:TU104 [GeForce RTX 2060] from 155.247.166.220
18:41:48:WU00:FS01:Connecting to 155.247.166.220:8080
18:41:48:WU00:FS01:Downloading 4.28MiB
18:42:32:WU01:FS01:0x22:Completed 495000 out of 500000 steps (99%)
18:43:12:WU00:FS01:Download 2.92%
18:43:19:WU01:FS01:0x22:Completed 500000 out of 500000 steps (100%)
18:43:19:WU01:FS01:0x22:Average performance: 14.8326 ns/day
18:43:23:WU01:FS01:0x22:Saving result file ../logfile_01.txt
18:43:23:WU01:FS01:0x22:Saving result file checkpointState.xml
18:43:24:WU00:FS01:Download 4.39%
18:43:26:WU01:FS01:0x22:Saving result file positions.xtc
18:43:26:WU01:FS01:0x22:Saving result file science.log
18:43:26:WU01:FS01:0x22:Folding@home Core Shutdown: FINISHED_UNIT
18:43:26:WU01:FS01:FahCore returned: FINISHED_UNIT (100 = 0x64)
18:43:26:WU01:FS01:Sending unit results: id:01 state:SEND error:NO_ERROR project:16600 run:0 clone:1343 gen:37 core:0x22 unit:0x0000002a8f59f36f5ec369119006d84d
18:43:26:WU01:FS01:Uploading 19.08MiB to 143.89.243.111
18:43:26:WU01:FS01:Connecting to 143.89.243.111:8080
18:43:32:WU01:FS01:Upload 3.93%
18:43:38:WU01:FS01:Upload 7.21%
18:43:44:WU01:FS01:Upload 10.48%
18:43:50:WU01:FS01:Upload 13.43%
18:43:57:WU01:FS01:Upload 16.70%
18:44:03:WU01:FS01:Upload 19.65%
18:44:09:WU01:FS01:Upload 22.93%
18:44:11:WU00:FS01:Download 5.85%
18:44:13:ERROR:WU00:FS01:Exception: Transfer failed
18:44:13:WU00:FS01:Connecting to assign1.foldingathome.org:80
18:44:15:WU01:FS01:Upload 25.87%
18:44:15:WU00:FS01:Assigned to work server 155.247.166.220
18:44:15:WU00:FS01:Requesting new work unit for slot 01: READY gpu:0:TU104 [GeForce RTX 2060] from 155.247.166.220
18:44:15:WU00:FS01:Connecting to 155.247.166.220:8080
18:44:17:WU00:FS01:Downloading 4.83MiB
18:44:22:WU01:FS01:Upload 29.15%
18:44:24:WU00:FS01:Download 2.59%
18:44:28:WU01:FS01:Upload 32.43%
18:44:34:WU01:FS01:Upload 35.37%
18:44:36:WU00:FS01:Download 3.88%
18:44:40:WU01:FS01:Upload 38.65%
18:44:43:WU00:FS01:Download 5.18%
18:44:46:WU01:FS01:Upload 41.60%
18:44:52:WU01:FS01:Upload 44.87%
18:44:53:WU00:FS01:Download 6.47%
18:44:59:WU01:FS01:Upload 48.15%
18:45:03:WU00:FS01:Download 7.76%
18:45:05:WU01:FS01:Upload 51.09%
18:45:11:WU01:FS01:Upload 54.37%
18:45:14:WU00:FS01:Download 9.06%
18:45:17:WU01:FS01:Upload 57.32%
18:45:23:WU01:FS01:Upload 60.59%
18:45:23:WU00:FS01:Download 10.35%
18:45:29:WU01:FS01:Upload 63.54%
18:45:31:WU00:FS01:Download 11.65%
18:45:35:WU01:FS01:Upload 66.82%
18:45:41:WU01:FS01:Upload 70.09%
18:45:42:WU00:FS01:Download 12.94%
18:45:48:WU01:FS01:Upload 73.04%
18:45:49:WU00:FS01:Download 14.24%
18:45:54:WU01:FS01:Upload 76.31%
18:45:58:WU00:FS01:Download 16.82%
18:46:00:WU01:FS01:Upload 79.26%
18:46:06:WU01:FS01:Upload 82.54%
18:46:08:WU00:FS01:Download 18.12%
18:46:12:WU01:FS01:Upload 85.81%
18:46:14:WU00:FS01:Download 19.41%
18:46:18:WU01:FS01:Upload 88.76%
18:46:22:WU00:FS01:Download 20.71%
18:46:24:WU01:FS01:Upload 92.04%
18:46:30:WU01:FS01:Upload 94.98%
18:46:36:WU01:FS01:Upload 98.26%
18:46:43:WU01:FS01:Upload complete
18:46:43:WU01:FS01:Server responded WORK_ACK (400)
18:46:43:WU01:FS01:Final credit estimate, 78071.00 points
18:46:43:WU01:FS01:Cleaning up
18:46:53:WU00:FS01:Download 22.00%
18:47:00:WU00:FS01:Download 23.29%
18:47:06:WU00:FS01:Download 25.88%
18:47:27:WU00:FS01:Download 28.47%
18:47:37:WU00:FS01:Download 31.06%
18:47:44:WU00:FS01:Download 33.65%
18:47:50:WU00:FS01:Download 36.23%
18:48:01:WU00:FS01:Download 38.82%
18:48:07:WU00:FS01:Download 41.41%
18:48:16:WU00:FS01:Download 44.00%
18:48:23:WU00:FS01:Download 46.59%
18:48:29:WU00:FS01:Download 49.18%
18:48:37:WU00:FS01:Download 54.35%
18:48:43:WU00:FS01:Download 59.53%
18:48:51:WU00:FS01:Download 66.00%
18:48:57:WU00:FS01:Download 68.59%
18:49:05:WU00:FS01:Download 72.47%
18:49:15:WU00:FS01:Download 75.06%
18:49:24:WU00:FS01:Download 77.65%
<it is now 0836 the following day and the client is stalled, restart required>

## Your Environment
08:44:32:****************************** FAHClient ******************************
08:44:32:        Version: 7.6.13
08:44:32:         Author: Joseph Coffland <joseph@cauldrondevelopment.com>
08:44:32:      Copyright: 2020 foldingathome.org
08:44:32:       Homepage: https://foldingathome.org/
08:44:32:           Date: Apr 28 2020
08:44:32:           Time: 04:20:16
08:44:32:       Revision: 5a652817f46116b6e135503af97f18e094414e3b
08:44:32:         Branch: master
08:44:32:       Compiler: GNU 8.3.0
08:44:32:        Options: -std=c++11 -ffunction-sections -fdata-sections -O3
08:44:32:                 -funroll-loops -fno-pie
08:44:32:       Platform: linux2 4.19.0-5-amd64
08:44:32:           Bits: 64
08:44:32:           Mode: Release
08:44:32:           Args: --child /etc/fahclient/config.xml --run-as fahclient
08:44:32:                 --pid-file=/var/run/fahclient.pid --daemon
08:44:32:         Config: /etc/fahclient/config.xml
08:44:32:******************************** CBang ********************************
08:44:32:           Date: Apr 25 2020
08:44:32:           Time: 00:07:53
08:44:32:       Revision: ea081a3b3b0f4a37c4d0440b4f1bc184197c7797
08:44:32:         Branch: master
08:44:32:       Compiler: GNU 8.3.0
08:44:32:        Options: -std=c++11 -ffunction-sections -fdata-sections -O3
08:44:32:                 -funroll-loops -fno-pie -fPIC
08:44:32:       Platform: linux2 4.19.0-5-amd64
08:44:32:           Bits: 64
08:44:32:           Mode: Release
08:44:32:******************************* System ********************************
08:44:32:            CPU: Intel(R) Core(TM) i3-9100F CPU @ 3.60GHz
08:44:32:         CPU ID: GenuineIntel Family 6 Model 158 Stepping 11
08:44:32:           CPUs: 4
08:44:32:         Memory: 7.71GiB
08:44:32:    Free Memory: 6.79GiB
08:44:32:        Threads: POSIX_THREADS
08:44:32:     OS Version: 5.3
08:44:32:    Has Battery: false
08:44:32:     On Battery: false
08:44:32:     UTC Offset: 1
08:44:32:            PID: 1281
08:44:32:            CWD: /var/lib/fahclient
08:44:32:             OS: Linux 5.3.0-62-generic x86_64
08:44:32:        OS Arch: AMD64
08:44:32:           GPUs: 1
08:44:32:          GPU 0: Bus:1 Slot:0 Func:0 NVIDIA:7 TU104 [GeForce RTX 2060]
08:44:32:  CUDA Device 0: Platform:0 Device:0 Bus:1 Slot:0 Compute:7.5 Driver:10.2
08:44:32:OpenCL Device 0: Platform:0 Device:0 Bus:1 Slot:0 Compute:1.2 Driver:440.100
08:44:32:******************************* libFAH ********************************
08:44:32:           Date: Apr 15 2020
08:44:32:           Time: 21:43:24
08:44:32:       Revision: 216968bc7025029c841ed6e36e81a03a316890d3
08:44:32:         Branch: master
08:44:32:       Compiler: GNU 8.3.0
08:44:32:        Options: -std=c++11 -ffunction-sections -fdata-sections -O3
08:44:32:                 -funroll-loops -fno-pie
08:44:32:       Platform: linux2 4.19.0-5-amd64
08:44:32:           Bits: 64
08:44:32:           Mode: Release
08:44:32:***********************************************************************
08:44:32:<config>
08:44:32:  
08:44:32:  <fold-anon v='true'/>
08:44:32:
08:44:32:  
08:44:32:  <gpu v='false'/>
08:44:32:
08:44:32:  
08:44:32:  <allow v='127.0.0.1 192.168.1.0/24'/>
08:44:32:
08:44:32:  
08:44:32:  <proxy v=':8080'/>
08:44:32:
08:44:32:  
08:44:32:  <command-allow-no-pass v='127.0.0.1 192.168.1.0/24'/>
08:44:32:
08:44:32:  
08:44:32:  <power v='full'/>
08:44:32:
08:44:32:  
08:44:32:  <passkey v='*****'/>
08:44:32:  <team v='224497'/>
08:44:32:  <user v='rhavern_ALL_1KcgKzs2VkwqZcoiFuqttzh2u1snJxGHhh'/>
08:44:32:
08:44:32:  
08:44:32:  <slot id='0' type='CPU'>
08:44:32:    <cpus v='2'/>
08:44:32:    <paused v='True'/>
08:44:32:  </slot>
08:44:32:  <slot id='1' type='GPU'>
08:44:32:    <client-type v='internal'/>
08:44:32:    <next-unit-percentage v='98'/>
08:44:32:    <paused v='False'/>
08:44:32:    <project-key v='169171111'/>
08:44:32:  </slot>
08:44:32:</config>

----
## Expected Behavior
New WU should complete download

----
## Current Behavior
Download stalls, client does not error, only way to recover is to restart the machine; pause/unpause has no effect.

----
## Possible Solution (Optional)
Set a watchdog on the download to error out after no progress for a period of time

----
## Steps To Reproduce
I wish there was a way to easily reproduce this, it is random.  There do seem to be certain servers that exhibit the behaviour more frequently than others, 155.247.166.220 for example.

----
## Context
Slots remain idle until manual intervention and no errors are generated.  Users that don't check frequently could be idle for long periods of time.

----

**Comment by joe-h-fah** [comment]
This appears to be another instance of the network connection problems covered by Issue #983 - https://github.com/FoldingAtHome/fah-issues/issues/983

**Comment by PantherX** [comment]
Hiya @rhavern 
I will close this issue as a duplicate. However, to reproduce the issue, you can yank the LAN cable while it is downloading and notice the issue. Also, instead of rebooting the machine, you can restart FAHClient too to achieve the same result.
