### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by hamirmahal** [FoldingAtHome/fah-issues#1546]
Your issue may already be reported!
Please search on the [issue tracker](./) before creating one.

## Your Environment

* **F@H Software version**:  N/A
* **Operating System**:  Windows 10 Pro Version 1909 OS build 18363.959
* **Browser**:  Chromium-based Microsoft Edge Version 84.0.522.52 (Official build) (64-bit)
I also replicated the issue by visiting [the fah-issues page](https://github.com/FoldingAtHome/fah-issues) in private browsing windows on both Firefox and Chrome on the same device, and viewing the same page in a private browsing session in Safari on an iPhone 6 running some version of iOS 12.
![Edge Folding at Home Logo not Rendering 2020-08-04 125507](https://user-images.githubusercontent.com/43425812/89339360-e1ab8c80-d652-11ea-81ef-56155f081e96.jpg)
![FireFox Folding at Home Logo not Rendering 2020-08-04 125507](https://user-images.githubusercontent.com/43425812/89339170-91342f00-d652-11ea-86a3-ce484edb2347.jpg)
![Chrome Folding at Home Logo not Rendering 2020-08-04 125507](https://user-images.githubusercontent.com/43425812/89339230-ac9f3a00-d652-11ea-9ed4-8390a0be5533.jpg)

----
## Expected Behavior

The Folding at Home logo should have rendered when viewing [the fah-issues repository homepage on GitHub](https://github.com/FoldingAtHome/fah-issues).

----
## Current Behavior

The image fails to render, although the anchor tag still works and the unrendered image is clickable.

----
## Possible Solution (Optional)

My guess is that the domain blocks viewing the image on different servers. The [source url](https://foldingathome.org/wp-content/uploads/2016/10/cropped-foldingathome-logo.png) displays the image just fine.

----
## Steps To Reproduce

1. View the README on the project page: https://github.com/FoldingAtHome/fah-issues.

----
## Context

It would just be nice to see the logo.

----

**Comment by jcoffland** [comment]
Fixed.  Thanks!
