### ISSUE TITLE
CPU and/or GPU stuck at Ready, or only complete 1 WU and then get stuck at ready

### ISSUE THREAD

**Issue by ero1996** [FoldingAtHome/fah-issues#1551]
I've been using FAH for a few months now, and until a few weeks ago had no issues; both the CPU and GPU would smoothly transition to a new WU after completing one. More recently, the CPU and/or GPU will finish a WU and just sit at ready. Even if I stop folding and restart, that does not help. I've searched through the issues here and cannot find a similar one. I've updated my GPU driver to the most recent one (as suggested by one issue thread), but that has not helped. Usually, the only way to get a new WU to start is to restart the computer, which is obviously not ideal. 

My CPU is an AMD Ryzen 5 2600X and my GPU is a NVIDIA GeForce GTX 1050 TI.

How can I fix this? Is there any other info I should provide to help?

Thanks!

**Comment by PantherX** [comment]
Hiya @ero1996 
May I please suggest that you head over to the Official Forum (https://foldingforum.org/index.php) for troubleshooting. There are many members there to help you investigate. I do know that it is possible to fold continuously on your CPU/GPU without issues and there isn't any known widespread Server issue.

We tend to use GitHub for documented issues for the development team to resolve. I will close this issue now as it needs to be investigated first :smiley:

**Comment by ejoepan1** [comment]
@PantherX

You are getting a lot of these because of this:
[cid:image001.png@01D67DFF.EE308CE0]

By removing the link to GitHub from the help in the Web Control, you and the other admins would not get this kind of issue to deal with and could let the community help as you want it to.

Joe

**Comment by PantherX** [comment]
@ejoepan1 
Thanks for pointing that out 😄 I have already raised an issue here #1518 so hopefully, this will be sorted out soon 🤞
