### ISSUE TITLE
My slot configuration does not persist after computer restart/shutdown

### ISSUE THREAD

**Issue by allen-learning** [FoldingAtHome/fah-issues#1552]
My PC has 2 GPU's and I've configured my fah to use only one GPU.
GPU 1: GTX 1050
GPU 2: GTX 1070 (being used by fah)

----
## Expected Behavior
FAH is configured to use GPU2 only...
When i restart or turn off&on my PC, i should be able to continue folding with my GPU2

----
## Current Behavior
FAH is configured to use GPU2 only...
When i restart or turn off&on my PC. my configuration is set to GPU1 and previous work of GPU2; if unfinished, will be void.

----
## Possible Solution (Optional)
Check how fah client chooses slots on startup??

I'm guessing fah chooses my GPU in first slot of motherboard on startup and does not check if it was the configured slot. Will try to confirm when i get home by switching them in my motherboard.

----
## Steps To Reproduce
1. Get two GPU, and corresponding motherboard
2. Configure fah to use GPU in the second slot of motherboard ONLY
3. Fold for some time, do not finish folding
4. Stop folding and restart pc
5. FAH configured GPU slot will return to GPU first slot of motherboard 

----

**Comment by PantherX** [comment]
Hiya @allen-learning 
Thanks for using the template! May I please suggest that you head over to the Official Forum (https://foldingforum.org/index.php) for troubleshooting. There are many members there to help you investigate. I do know that it is possible to only fold on 1 GPU without using other GPUs on the system.

We tend to use GitHub for documented issues for the development team to resolve. I will close this issue now as it needs to be investigated first :smiley:

P.S. If you're encountering this issue using a Beta client, then please use the stable release which is V7.6.13
