### ISSUE TITLE
Cannot process work unit - FAH crashing?  Mac Pro Early 2008

### ISSUE THREAD

**Issue by hadfiiw** [FoldingAtHome/fah-issues#1565]
Hello,

I have 3 Early 2008 Mac Pros that all seem to be suck.  

In Web Control, they all show Yellow/Ready but if I watch it long enough, it will go Green/Running for about a second then go back to Yellow/Ready.

All 3 computers are trying to work on Project 16810

From the logs of one of the F@H clients, I see the below "INTERRUPTED" and the PID changes.  Is the F@H app crashing?  Is there a problem with the WU they have picked up?  These old machine have been folding for months without a problem.

Any ideas on how to fix this?

Thanks

13:37:25:WU00:FS00:Starting
13:37:25:WU00:FS00:Running FahCore: /usr/local/bin/FAHCoreWrapper "/Library/Application Support/FAHClient/cores/cores.foldingathome.org/osx/64bit-sse2/a8-0.0.7/Core_a8.fah/FahCore_a8" -dir 00 -suffix 01 -version 706 -lifeline 251 -checkpoint 15 -np 8
13:37:25:WU00:FS00:Started FahCore on PID 21158
13:37:25:WU00:FS00:Core PID:21159
13:37:25:WU00:FS00:FahCore 0xa8 started
13:37:26:WU00:FS00:FahCore returned: INTERRUPTED (102 = 0x66)
13:38:25:WU00:FS00:Starting
13:38:25:WU00:FS00:Running FahCore: /usr/local/bin/FAHCoreWrapper "/Library/Application Support/FAHClient/cores/cores.foldingathome.org/osx/64bit-sse2/a8-0.0.7/Core_a8.fah/FahCore_a8" -dir 00 -suffix 01 -version 706 -lifeline 251 -checkpoint 15 -np 8
13:38:25:WU00:FS00:Started FahCore on PID 21161
13:38:25:WU00:FS00:Core PID:21162
13:38:25:WU00:FS00:FahCore 0xa8 started
13:38:26:WU00:FS00:FahCore returned: INTERRUPTED (102 = 0x66)
13:39:26:WU00:FS00:Starting
13:39:26:WU00:FS00:Running FahCore: /usr/local/bin/FAHCoreWrapper "/Library/Application Support/FAHClient/cores/cores.foldingathome.org/osx/64bit-sse2/a8-0.0.7/Core_a8.fah/FahCore_a8" -dir 00 -suffix 01 -version 706 -lifeline 251 -checkpoint 15 -np 8
13:39:26:WU00:FS00:Started FahCore on PID 21164
13:39:26:WU00:FS00:Core PID:21165
13:39:26:WU00:FS00:FahCore 0xa8 started
13:39:26:WU00:FS00:FahCore returned: INTERRUPTED (102 = 0x66)
13:40:26:WU00:FS00:Starting
13:40:26:WU00:FS00:Running FahCore: /usr/local/bin/FAHCoreWrapper "/Library/Application Support/FAHClient/cores/cores.foldingathome.org/osx/64bit-sse2/a8-0.0.7/Core_a8.fah/FahCore_a8" -dir 00 -suffix 01 -version 706 -lifeline 251 -checkpoint 15 -np 8
13:40:26:WU00:FS00:Started FahCore on PID 21167
13:40:26:WU00:FS00:Core PID:21168
13:40:26:WU00:FS00:FahCore 0xa8 started
13:40:27:WU00:FS00:FahCore returned: INTERRUPTED (102 = 0x66)
13:41:26:WU00:FS00:Starting
13:41:26:WU00:FS00:Running FahCore: /usr/local/bin/FAHCoreWrapper "/Library/Application Support/FAHClient/cores/cores.foldingathome.org/osx/64bit-sse2/a8-0.0.7/Core_a8.fah/FahCore_a8" -dir 00 -suffix 01 -version 706 -lifeline 251 -checkpoint 15 -np 8
13:41:26:WU00:FS00:Started FahCore on PID 21170
13:41:26:WU00:FS00:Core PID:21171
13:41:26:WU00:FS00:FahCore 0xa8 started
13:41:27:WU00:FS00:FahCore returned: INTERRUPTED (102 = 0x66)

**Comment by hadfiiw** [comment]
I think I found the issue in the Forum...

[https://foldingforum.org/viewtopic.php?f=105&t=36147&start=30](https://foldingforum.org/viewtopic.php?f=105&t=36147&start=30)

**Comment by PantherX** [comment]
Hiya @hadfiiw 
Apologies for the issue where a dev build was accidentally released. It should have been resolved in 0.0.8.

I will close this issue now 😄
