### ISSUE TITLE
CUDA FILE not found ERROR 301

### ISSUE THREAD

**Issue by TyHuffman** [FoldingAtHome/fah-issues#1568]
Your issue may already be reported!
Please search on the [issue tracker](./) before creating one.

## Your Environment

* **F@H Software version**: 7.5.1
* **Operating System**: Windows 10, latest update.
* **Browser**: Chrome

----
## Expected Behavior
Expected to load and run. Is running but I'm not sure if on 0.0.13 with CUDA updates

----
## Current Behavior
Error loading CUDA module: CUDA_ERROR_FILE_NOT_FOUND (301)

----
## Possible Solution (Optional)

----
## Steps To Reproduce

21:49:39:WU01:FS01:0x22:Version 0.0.13
21:49:39:WU01:FS01:0x22:  Checkpoint write interval: 25000 steps (2%) [50 total]
21:49:39:WU01:FS01:0x22:  JSON viewer frame write interval: 12500 steps (1%) [100 total]
21:49:39:WU01:FS01:0x22:  XTC frame write interval: 10000 steps (0.8%) [125 total]
21:49:39:WU01:FS01:0x22:  Global context and integrator variables write interval: disabled
21:49:39:WU01:FS01:0x22:There are 4 platforms available.
21:49:39:WU01:FS01:0x22:Platform 0: Reference
21:49:39:WU01:FS01:0x22:Platform 1: CPU
21:49:39:WU01:FS01:0x22:Platform 2: OpenCL
21:49:39:WU01:FS01:0x22:  opencl-device 0 specified
21:49:39:WU01:FS01:0x22:Platform 3: CUDA
21:49:39:WU01:FS01:0x22:  cuda-device 0 specified
21:49:44:WU00:FS01:Upload 27.65%
21:49:50:WU00:FS01:Upload 55.64%
21:49:56:WU00:FS01:Upload 83.97%
21:49:56:WU01:FS01:0x22:Attempting to create CUDA context:
21:49:56:WU01:FS01:0x22:  Configuring platform CUDA
21:49:56:WU01:FS01:0x22:Failed to create CUDA context:
21:49:56:WU01:FS01:0x22:Error loading CUDA module: CUDA_ERROR_FILE_NOT_FOUND (301)
21:49:56:WU01:FS01:0x22:Attempting to create OpenCL context:
21:49:56:WU01:FS01:0x22:  Configuring platform OpenCL
21:50:00:WU00:FS01:Upload complete
21:50:00:WU00:FS01:Server responded WORK_ACK (400)
21:50:00:WU00:FS01:Final credit estimate, 142664.00 points
21:50:00:WU00:FS01:Cleaning up
21:50:06:WU01:FS01:0x22:  Using OpenCL on platformId 0 and gpu 0

----
## Context

----

**Comment by PantherX** [comment]
Hiya @TyHuffman 

May I suggest that you post this in the Official Forum https://foldingforum.org/index.php to troubleshoot? Once we identify if this is a reproducible issue or not, we can fully document it in this issue. In the meantime, I will close this but would be happy to re-open in future if needed 😄
