### ISSUE TITLE
Jetson Nano Docker container fails

### ISSUE THREAD

**Issue by tgrrr** [FoldingAtHome/fah-issues#1571]
Also reported here: https://github.com/FoldingAtHome/containers/issues/11

## Your Environment

* **F@H Software version**: https://github.com/FoldingAtHome/containers image 7.6.13
* **Operating System**: Ubuntu 18.04.4 LTS
* **Browser**: N/A

----
## Expected Behavior

fah docker container to run on Jetson Nano

----
## Current Behavior

`standard_init_linux.go:211: exec user process caused "exec format error"`

----
## Steps To Reproduce

Steps:

1. Config
```
# fah/config.xml
<config>
  <!-- Set with your user, passkey, team-->
  <user value="REDACTED"/>
  <passkey value="REDACTED"/>
  <team value="0"/>

  <power value="full"/>
  <exit-when-done v='true'/>

  <web-enable v='false'/>
  <disable-viz v='true'/>
  <gui-enabled v='false'/>

  <!-- 1 slots for GPUs -->
  <slot id='0' type='GPU'> </slot>

  <!-- 16-1 = 15 = 3*5 for decomposition -->
  <slot id='1' type='SMP'> <cpus v='15'/> </slot>

</config>
```

2. Run docker
```zsh
$ docker run --gpus all --name fah0 -d --user "$(id -u):$(id -g)"   --volume $HOME/fah:/fah foldingathome/fah-gpu:latest
08a13874aba9145efd6b729c2b543f90e6fd250c0a880eb6721dc577816a950b
```
works

3. Then I run:
```zsh
$ docker start fah0
fah0
```

4. Error log

```zsh
~$ docker logs fah0
standard_init_linux.go:211: exec user process caused "exec format error"
standard_init_linux.go:211: exec user process caused "exec format error"
```

----

**Comment by ffissore** [comment]
Hi @tgrrr you already reported this issue in the [right repository](https://github.com/FoldingAtHome/containers/issues/11), where folks working on containers for folding@home will take care of it. No reason to create a duplicate here. Closing
