### ISSUE TITLE
X-Plane conflict

### ISSUE THREAD

**Issue by xmitr** [FoldingAtHome/fah-issues#1572]
With FAH in the background or foreground, when I start X-Plane 11.5 flight simulator my screens start to flash on and off rapidly.
Your issue may already be reported!
Please search on the [issue tracker](./) before creating one.

## Your Environment

* **F@H Software version**: newest
* **Operating System**: Win 10 Home 10.0.19041
* **Browser**: Chrome Version 85.0.4183.121 (Official Build) (64-bit)

Ryzen 7 3700X processor, Asus TUF Gaming X570 Plus WiFi motherboard
32GB memory
Nvidia GTX670, driver 456.55
Radeon HD6850, driver 15.8

----
## Expected Behavior
Should be able to run X-Plane 11.5 flight simulator concurrently with FAH.

----
## Current Behavior
With FAH in the background or foreground in Light, Medium or Full mode, when I start X-Plane 11.5 flight simulator my screens start to flash on and off rapidly.

----
## Possible Solution (Optional)

----
## Steps To Reproduce

1.
2.
3.

----
## Context

----

**Comment by PantherX** [comment]
Hiya @xmitr 

At this stage, I would suggest that you start a discussion at our Official Forum (https://foldingforum.org/index.php) who would be able to troubleshoot this issue. If it is indeed a bug report, it can be reopened with additional information 😄
