### ISSUE TITLE
CPU temperatures suddenly very high

### ISSUE THREAD

**Issue by wingandstache** [FoldingAtHome/fah-issues#1573]
I have been running FAH on my PC for about a month now, and in just the last few days, it started to make my CPU run around 80C at 60% load, whereas before it could easily run at 100% load and be doing fine on thermals. To see if it was an issue with my computer, I have run several benchmarking softwares. With all of them, I am getting 100% load and powerdraw, but the temperature of the CPU is staying around 65C. This is very concerning as I do not want my computer running very hot for extended periods of time.

**Comment by UofM-MartinK** [comment]
Newer "cores" might be able to use different CPU instruction sets, more threads or other resources better for more performance. For example the relatively new "a8" core now uses AVX2, while the previous and also still widely used "a7" core only uses AVX. On a Ryzen 3900X, for example, that can make a difference of 5C and 10W power draw.

Also, the "a8" core seems to more often (or always?) use exactly the number of threads the slot is configured for, for example all 23 threads on a Ryzen 3900X (e.g., slider on "medium"), while "a7" was only using 21 to avoid domain-decomposition issues.

**Comment by PantherX** [comment]
Hiya @wingandstache 

Please note that it seems to be related to your system's cooling configuration which can be addressed to a certain degree by tweaking the client settings as mentioned by @UofM-MartinK. This is best done on our Official Forum (https://foldingforum.org/index.php) where there are plenty of experienced members within the Community who would be more than happy to help out 😄
