### ISSUE TITLE
FAH, hei, jeg har brukt fah i flere år og det ser ut til å være en glitch som gjentar seg hele tiden og som dere ikke har fikset. Når man har latt datamaskinen folde i noen dager vil den låse seg, den laster ikke opp produktet som er ferdig foldet, den vil ikke laste inn ny data... (Jeg bruker MAC book pro) det som ser ut til å løse utfordringen er å vente ut tiden vi har på folde hele stykket.

### ISSUE THREAD

**Issue by Sfof98** [FoldingAtHome/fah-issues#1575]
Your issue may already be reported!
Please search on the [issue tracker](./) before creating one.

## Your Environment

* **F@H Software version**: 
* **Operating System**: 
* **Browser**: 

----
## Expected Behavior

----
## Current Behavior

----
## Possible Solution (Optional)

----
## Steps To Reproduce

1.
2.
3.

----
## Context

----

**Comment by jcoffland** [comment]
Issues must follow the guide and be in English.

**Comment by PantherX** [comment]
@Sfof98 

Hiya,

Please note that you can use our official Forum (https://foldingforum.org/index.php) to help you fix the issue. If you have a bug, a report can be created by someone else in English :)

Hei,

Vær oppmerksom på at du kan bruke vårt offisielle forum (https://foldingforum.org/index.php) for å hjelpe deg med å løse problemet. Hvis du har en feil, kan en rapport opprettes av noen andre på engelsk :)
