### ISSUE TITLE
FAHControl not starting up

### ISSUE THREAD

**Issue by gvmelle** [FoldingAtHome/fah-issues#1576]
Your issue may already be reported!
Please search on the [issue tracker](./) before creating one.

## Your Environment

* **F@H Software version**: 7.6.20
* **Operating System**: MacOS 10.15.7 (19H2)
* **Browser**: Chrome

----
## Expected Behavior

FAHControl should open

----
## Current Behavior
nothing happens (only one jump up)

----
## Possible Solution (Optional)

----
## Steps To Reproduce

1. Go to Applications directory
2. click on FAHControl icon

----
## Context
have to use Web Control.url to see what happens in the background

----

**Comment by pasteusernamehere** [comment]
Same thing here after upgrade to new version.

**Comment by pasteusernamehere** [comment]
Console reports the following:


default	08:04:49.080646-0400	FAHControl	  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/py2app/apptemplate/lib/site.py", line 22, in <module>
default	08:04:49.080665-0400	FAHControl	zipimport.ZipImportError: can't decompress data; zlib not available

**Comment by joe-h-fah** [comment]
As reported on the forum, FAHControl does not work on either macOS 10.14 or 10.15, does work on 10.13.  7.6.21 has same problem, 7.6.13 FAHControl is reported to work.

**Comment by bb30994** [comment]
Enhancement request:
1) Add a FAHControl option for open-fah-control = TRUE.
2) If open-web-control fails, fallback to open-fah-control

**Comment by joe-h-fah** [comment]
Early adopter of macOS 11 - Big Sur - reports same problem with 7.6.21 FAHControl, 7.6.13 does work

**Comment by kbernhagen** [comment]
I found an article with the answer

A python app signed with hardened runtime needs entitlement com.apple.security.cs.allow-unsigned-executable-memory. Bundled libraries also need to be individually signed. Deep signing the app is not sufficient. 

https://glyph.twistedmatrix.com/2018/01/shipping-pygame-mac-app.html

Unlike in the article, both codesign need —timestamp, and the library codesign does not need —deep or —entitlements. Might want to add a signing prefix for the libs.

I will make appropriate PRs.

**Comment by kbernhagen** [comment]
> Enhancement requests:
> 
> 1. Add a FAHControl option for open-fah-control = TRUE.
> 2. If open-web-control fails, fallback to open-fah-control

The client does not have permission to open an app in the user’s login context. So this enhancement is not possible.

**Comment by unbeatable-101** [comment]
Has a version with the fix been released yet? Because I'm having the problem.

**Comment by kbernhagen** [comment]
It has not been released yet. No eta. Sorry.

**Comment by kbernhagen** [comment]
If you are a developer, you can make FAHControl 7.6.21 work by force re-signing it without the hardened runtime option using your own Dev id. 

If you don’t know what that means, you’ll have to wait for 7.6.22.

**Comment by kbernhagen** [comment]
Just for historical interest...
A v7.6.22 was never released.
Instead, v7.6.21 was re-signed and re-packaged, replacing the old download.

Anyone having trouble with FAHControl on macOS 11 or later should see

[FAHControl is not connecting to my client - macOS11](https://foldingforum.org/viewtopic.php?t=37513)
