### ISSUE TITLE
Core Settings are ignored with 7.6.20

### ISSUE THREAD

**Issue by IzzySoft** [FoldingAtHome/fah-issues#1577]
## Your Environment
* **F@H Software version**: 7.6.20
* **Operating System**: Linux Mint 18.3; Debian 9.13
* **Browser**: n/a

----
## Expected Behavior
I've set the CPU slider to "light", the config reflects that. With previous versions, this meant:

* use 1 core of 4 present
* use .5 cores of 2 present

I expected this behavior not to change with the upgrade from 7.6.13 (performed via the `.deb` packages provided at the F@H website).

----
## Current Behavior
"Light" is no longer "light" but rather what one would expect from "medium". Behavior at "light" changed to:

* use 2 cores of 4
* use 1 core of 2

Verified this on 3 machines so far: Mint w/ 4 cores, Mint w/ 2 cores, Debian w/ 2 cores.

This means I've got to shut down the FAHClient on some machines as they get to sluggish. This behaviour of the client is not acceptable; we need a real "minimum" setting, even if it were "1 core" (which would at least work for 4+ core machines).

----
## Possible Solution (Optional)
The slider is fine for raw adjustment – if it would head what it suggests:

* use 1 of 4 cores (25%) at "light"
* use 2 of 4 cores (50%) at "medium" (was and still is 75%)
* use all cores (100%) if "free" at "full"

OTOH it would be fine if one could apply more fine-grained settings – like directly specifying either the number of cores one would like to dedicate (in decimals with 1 digit, so machines with 2 cores could e.g. dedicate .5 cores) – which the client, if needed, would round to the next possible value. Also possible: a percentage of processing power one wants to specify (e.g. "25" for 25%) – which then could also easily be applied to GPUs.

----
## Steps To Reproduce
1. install 7.6.13 or earlier
2. set "Folding power" to "light" and watch how much CPU power it takes
3. update to 7.6.20, restart the client, and check the CPU again.

----
## Context
The 2 core machine gets pretty sluggish. The 4 core machine as well for certain tasks. Didn't check the other machines yet. Energy consumption went up (so it costs **my** money – I gladly contribute, but please reasonably; I must still be able to use my machines and pay the bills :wink:).

----

**Comment by bb30994** [comment]
Question:  Do you fold with a GPU or just CPUs?

Sluggish responses can be caused by either by FAJ on your CPU or on your GPU.  Visit foldingforum.org for additional help.

**Comment by IzzySoft** [comment]
@bb30994 as my GPU is not supported, only with CPU. And I worked around the issue for now by setting vCPU directly – but that means the "power slider" has become useless. So I've stopped "cranking up power" for times I wouldn't use the machine myself for a while, and simply leave F@H on the "back burner" (i.e. on "minimal power"). It's a pity; but not even a response after 3 weeks doesn't make me hopeful someone is looking into the issue anytime soon. The update to v7.6.21 didn't solve this either (not that I had expected that, considered the "activity" on this issue here).

So to answer your question: Just CPU, and behavior is "back to normal" after setting vCPU to a "digital value" (e.g. via FAHControl: *Settings › Slots*, mark the CPU, hit the *Edit* button, set "CPU" to some "natural number" (i.e. "positive integer", not "-1")). Seeing the number of steps involved you certainly understand why, once set, I rarely (read: never) touch this now – as opposed to the slider in plain view which I used at times before.

> Visit foldingforum.org for additional help.

Well, I rather consider this a bug, so I've opened a bug report. The forum I'd use if I wanted to ask the algorithm behind points' calculation, which always amazes me: for similar configurations I get tasks requiring 2 days processing earning me, say, 900 points – or ones needing just 20h but earning 3k base rep… Though that would be best placed in some FAQ :zany_face:

**Comment by PantherX** [comment]
@IzzySoft 

Can you please provide log files from V7.6.13 and V7.6.21 so we can see what the client is detecting and how it's configuring your system when using Light Folding Power.

BTW, most aspect of support (Forum, Discord, GitHub) is managed by volunteers with a dedicated developer (who isn't a FTE for F@H but works on other projects too) so apologies for the delay in responding... there's only 24 hours in most people's day... unless you have the [time stone](https://marvelcinematicuniverse.fandom.com/wiki/Time_Stone) and/or a [time turner](https://harrypotter.fandom.com/wiki/Time-Turner) 🤓

**Comment by IzzySoft** [comment]
@PantherX thanks – and sure, I'm aware of that (hence I tried being patient :wink:) I've attached you some logs. One from before, and two more recent, from the 4-core machine. If you need them from the smaller ones (2-core) as well, let me know.

[fahlogs.zip](https://github.com/FoldingAtHome/fah-issues/files/5543173/fahlogs.zip)

Btw, speaking of calculation: another puzzling thing is to see that some WUs I get are with long runtimes and very few points (like, ~500 points for 2 days), and other times getting short runtimes with good points (say, 2k+ for 12h). Base points, I mean. Not complaining, mind you, just wondering…

**Comment by PantherX** [comment]
Thanks for the log file. I can see that:

- V7.6.13 uses 1 CPU out of 4 CPUs
- V7.6.21 uses 2 CPUs out of 4 CPUs

Either there was an issue in the initial configuration of V7.6.13 or there's a bug in V7.6.21. I don't know yet but have asked so let's see what happens.

Regarding your observation, it would be best suited for our official Forum (https://foldingforum.org/index.php) were you might be able to learn more about it by our enthusiastic community 😄

**Comment by IzzySoft** [comment]
Thanks @PantherX – similarly it's for 2-cores (0.5 CPUs => 1 CPU – I assume that would mach vCPU=0 vs vCPU=1). On the 4-core, I've currently set vCPU=1 explicitly (which makes the slider useless, but at least I can keep on folding while working on the machine at the same time). I could try setting vCPU=0 on the 2-cores to see if that brings the previous behavior back there as well, but somehow "0" looks wrong to me so I'm not sure.

As for the "points observation": I just wanted to mention it. I don't feel it important enough (to me) going to register another account and starting a discussion. Enough other tasks at hand – and the important thing is getting things done. It's nice to be rewarded points and by that seeing the contribution's worth, though :smile:

**Comment by IzzySoft** [comment]
Any news on this meanwhile, @PantherX? The longer it takes, the harder a dev remembers what might have been changed and caused this behavior. Had to take down some of the clients already. Would like to bring them online again, but without this being fixed it's not likely.

**Comment by PantherX** [comment]
@IzzySoft Apologies, but I don't have any update for you 😞  The only suggestion that I have is a fresh installation of V7.6.21 and then if you have issues, post at the [Official Forum](https://foldingforum.org/index.php) to see if anyone else in the community can reproduce it and/or help you out 😄

**Comment by IzzySoft** [comment]
Thanks for answering, @PantherX – but I lack the time to play with that now. I've nailed the core to a single CPU now on all affected machines (sorry for that, but no choice left except for that or shutting it down entirely – which I might have to do on the 2-core machines at least unless this issue gets fixed and I can run on .5 cores again as before; as only integer values are available, I cannot do this now).

Apart from that: the very same behavior on multiple machines would be a strange coincidence, don't you agree? Affected machines even run different distros: Debian Buster, Mint 18, Mint 19 … And all show the very same issue since being upgraded to 7.6.20 – while none of them had it before.

If you tell me you tested this on a 2-core and, set the ruler to the far left FAH is using .5 cores or less (or 1 core with a 4-core machine) I'd be surprised. Can you? And did you get an answer on [your question in November](https://github.com/FoldingAtHome/fah-issues/issues/1577#issuecomment-727800465)? I do not think a re-install will solve the issue (for the reasons given) – at least not until you swear you see the behavior described in this paragraph with v7.6.21 on dual- and quad-cores.

**Comment by IzzySoft** [comment]
Am I the only one having this issue? It's two years now, and still no indication the culprit was found and addressed. Probably not much machines around anymore with 4 or less cores…

**Comment by jcoffland** [comment]
The change in behavior mentioned at the beginning of this issue was intentional.  I'm sorry it doesn't fit with with your usage of F@H but you can set the number of CPUs to anything you like using FAHControl.  Is this issue just that you don't agree with the power slider CPU settings or is there something else here that I'm missing?  If so feel free to reopen this issue.

**Comment by IzzySoft** [comment]
Thanks for the clear words, @jcoffland – that's an answer to my question, though it complicates things for machines with 4 cores or less (e.g. on a 2 core machine, it makes it impossible to dedicate 25% of CPU power; I have a few 2-core VMs spread around in different locations where I was doing exactly that, on all but one I meanwhile shut down the F@H client due to this as I couldn't afford spending 50%).

You will have your reasons for your decision, so I will have to accept it. At least by now I know it was done with some reasoning behind it – and admittedly, this 1) is not affecting too many current clients and 2) ¼ CPU of such a small VM is not really contributing much anyway. So I leave it to you whether you consider it worthwhile. Thanks for having the client available! (btw: will it be open-sourced finally one day? I vaguely remember that was said/planned a few years ago. I'm making the DEB variant available [in my repo here](https://apt.izzysoft.de/ubuntu/dists/generic/) and would really like to attach a FOSS license to it :smile:)

**Comment by jcoffland** [comment]
Part of the problem is that the simulation cores no longer support utilization of less then a whole CPU.  So there's currently no way to use 0.5 CPU.

The new v8 client is 100% Open-Source.  You can find it here: https://github.com/FoldingAtHome/fah-client-bastet.  It's mostly functional but is lacking documentation.  Public beta testing will start in the next few months.

**Comment by IzzySoft** [comment]
> Part of the problem is that the simulation cores no longer support utilization of less then a whole CPU. So there's currently no way to use 0.5 CPU.

OK, then I retract my request: the effort needed to change that would not be worth it IMHO.

> The new v8 client is 100% Open-Source. You can find it here

Cool! Be welcome to give me a ping once you consider it stable enough for wider distribution, and want it to be in my repo (until it can hit an official Debian repo). All I'd need for that would be the `*.deb`. Oh, and I also could take the `*.rpm` into my YUM repo if you'd like that. As it's not there, it could even be introduced as beta – which would make it easier to your testers to not miss updates.

Mind if I already spread the word that the new FOSS client is entering public beta soon, and link to the repo?
