### ISSUE TITLE
Installing 7.6.20 while 7.6.13 is running causes TWO "HideConsole"s running at next reboot, thus TWO "FAHClient"s, possibly causing database locks and FAHCore_xx crashes

### ISSUE THREAD

**Issue by TunaErtemalp** [FoldingAtHome/fah-issues#1578]
I have 9 hosts, all on latest Win10 except for one that is still on Win7 for various reasons, all running CUDA cards.

Just updated all from 7.6.13 to 7.6.20, while 7.6.13 was running, since that worked in the past: The new setup would stop the running processes, keep the data, update the program files, and pick the calculations up from where they were left before the update.

This time, the same action resulted in TWO HideConsole.EXEs being launched at next OS restart on all hosts!

Using https://live.sysinternals.com/autoruns.exe from Microsoft, and filtering for HideConsole:

![HideConsole](https://user-images.githubusercontent.com/64696922/96621123-17a8f600-12bd-11eb-92ff-646e3897da60.jpg)

The dates seem to indicate that 7.6.13 installed the Folding@home.lnk shortcut to HideConsole.exe into **C:\Users\master\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup** on 9/2/2020, and 7.6.20 installed another shortcut to HideConsole into **C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Startup** today. So, HideConsole gets launched twice during a reboot, both launch FAHClient, somehow the second FAHClient doesn't quit after realizing there already is a running instance (race condition?), they both stay running, Task Manager's **Startup** tab shows TWO HideConsoles, and **Details** tab shows TWO FAHClients. This later results in some database locks, or in two hosts' case, possibly FahCore_22 crashes.

This has happened across all 9 hosts, so it is not a fluke.

Obviously, the expected behavior would be for this to **not** happen. 7.6.20 should have either not changed where Folding@home.lnk	is placed, or (assuming there was a good reason for that) it should have removed the one in the old location.

DISABLEing one of these either in Win10's Task Manager's Startup tab, or using the above AutoRuns.exe and unchecking the older one, or just deleting the old link using File Manager would be the possible workarounds for now.

Tuna

**Comment by jcoffland** [comment]
We are testing a fix for this in v7.6.21 now.

**Comment by TunaErtemalp** [comment]
I'm sure you are doing the right fix in setup, but I also found it curious as to why the 2nd insurance of FAHClient didn't shut down after detecting the 1st one. A fix in setup would certainly be nice, but the main problem in FAHClient not detecting other running instances with 100% accuracy might come back to bite the user in other situations...

**Comment by jcoffland** [comment]
I'm  not sure why that happens.  Can you test the new beta client to see if them original problem is fixed?  https://foldingathome.org/beta/

**Comment by TunaErtemalp** [comment]
Will do Wednesday morning Seattle time...

**Comment by TunaErtemalp** [comment]
I tried out https://download.foldingathome.org/releases/beta/release/fah-installer/windows-10-32bit/v7.6/fah-installer_7.6.21_x86.exe.

Yes, it works. I had 7.6.20 running, removed my workarounds to make sure both Autorun links were present & active (using TaskManager/Startup tab & AutoRuns.exe), rebooted, made sure I had two FAHClient.exe in the process list, started the 7.6.21 install, chose CUSTOM, answered everything with defaults, watched Task Manager during install to see all FAH processes get shutdown including BOTH FAHClient.exe (nice!). Once the Setup was complete, I let it start FAH, it picked up all WUs from where they were left, there was only one FAHClient.exe running, there was only one HideConsole in TaskManager/Startup tab, and AutoRuns.exe found only one link that was properly under C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Startup and active. And, rebooting the host preserved all this goodness.

Thank you! It passed my scrutiny... :)

**Comment by TunaErtemalp** [comment]
As for Setup issue, this seems releasable.

If you would like me to test out the race condition, feel free to give me a 7.6.21-based instrumented/verbose/debug version of FAHClient.exe that will create enough logs for you to figure out the problem, and I'd be happy to add back the extra autorun link and reboot and send you the resulting logs, assuming the time spent in the extra logging activity won't affect the race condition. Needless to say, make sure the two FAHclient.EXEs don't try to write to the same log file... ;)

**Comment by jcoffland** [comment]
The race condition when two FAHClients start is another issue.  I believe there is already an issue open for this.  I don't have time to work on this right now.  Thanks for you help.
