### ISSUE TITLE
BSOD "Unexpected Kernal Mode Trap"

### ISSUE THREAD

**Issue by improviz** [FoldingAtHome/fah-issues#1579]
1 day after installing the latest FAH client on my new (May 2020, Ryzen 3950 16 core Threadripper/Win10/nVidia RTX 2080 Super Ventus/64GB RAM) desktop, I got a BSOD and the above error. I ran the online repair (DISM.exe /Online /Cleanup-image /Restorehealth) after running a CMD Line sfc /scannow and discovering corrupted files. Subsequent sfc /scannow post-repair found no corrupt files. Then, on my OLD desktop (Core i7 6 core/Win10/nVidia 980 Ti/32GB RAM, installed FAH same day) when I booted up this morning CHKDISK ran at boot and performed a repair to THAT machine. This is a little too coincidental. I've NEVER had a BSOD on either machine, ever. Just thought I'd mention this here. Thanks.

**Comment by PantherX** [comment]
Hiya @improviz 

Please note that at this point, there's very little information on how to reproduce this bug in a consistent and reliable manner. Thus, I would suggest that you post in our official Forum (https://foldingforum.org/index.php) where this can be investigated further. If needed, a proper bug report can be opened in the future 😄 

Thanks for your report!
