### ISSUE TITLE
F@H Client fails to detect OpenCL AMD GPU on fresh install of Windows 10

### ISSUE THREAD

**Issue by TheRealPenDragon** [FoldingAtHome/fah-issues#1580]
Your issue may already be reported!
Please search on the [issue tracker](./) before creating one.

## Your Environment

* **F@H Software version**: 7.6.13 & 7.6.20 & 7.6.21
* **Operating System**: Windows 10 Pro - Version 2004 - Build 19041.572  -  Feature experience pack 120.2212.31.0
* **Browser**:  Chrome 86.0.4240.111 (Official Build) (64-bit)

----
## Expected Behavior

----
## Current Behavior

----
## Possible Solution (Optional)

----
## Steps To Reproduce

1. Clean vanilla install of windows - onto new machine - no previous OS
2. Fresh clean install of AMD GPU drivers downloaded from AMD directly - the full driver package.
3. Fresh install of F@H 7.6.21 (or 7.6.20 or 7.6.13)
4. Bang - not worky :(

[log.txt](https://github.com/FoldingAtHome/fah-issues/files/5421686/log.txt)
[clinfo.txt](https://github.com/FoldingAtHome/fah-issues/files/5421705/clinfo.txt)

----
## Context

----

**Comment by TheRealPenDragon** [comment]
Please let me know if there are any other logs that would be helpful. 
Or troubleshooting steps you would like me to perform - and capture logs and upload. 
I suspect this is something relatively simple with linkages missing. but I dont have the knowledge of how to troubleshoot F@H's usage of OpenCL to be able to find and fix myself.
Thanks  Steve

**Comment by TheRealPenDragon** [comment]
Installed motherboard drivers from motherboard manufacturer (msi) and issue with F@H client went away. 
I'll now study my system logs to see if there is some change that I can identify - that has enabled F@H to now work for GPU. 
Also attaching an output of a run from AIDA64 - 'before' I installed motherboard drivers , where OPENCL was working ... but F@H was not - just for reference - so you don't think i'm mad :)

**Comment by TheRealPenDragon** [comment]
![gpgpu](https://user-images.githubusercontent.com/73280564/97085229-186ebe80-1614-11eb-84fd-aa7013a619d4.png)

**Comment by anand-bhat** [comment]
In my laptop with the Adrenalin 2020 Edition 20.10.1 drivers, I see an additional line in the startup section of the FAH log indicating the FAH client was able to see the OpenCL capability of the card.

Your log:
```
08:47:31:      OS Arch: AMD64
08:47:31:         GPUs: 1
08:47:31:        GPU 0: Bus:45 Slot:0 Func:0 AMD:6 Navi 10 [Radeon RX 5600 OEM/5600 XT /
08:47:31:               5700/5700 XT]
08:47:31:         CUDA: Not detected: Failed to open dynamic library 'nvcuda.dll': The
08:47:31:               specified module could not be found.
08:47:31:
08:47:31:***********************************************************************
08:47:31:<config>
```

```
15:02:51:        OS Arch: AMD64
15:02:51:           GPUs: 1
15:02:51:          GPU 0: Bus:3 Slot:0 Func:0 AMD:5 Renoir [Ryzen 4900HS mobile]
15:02:51:           CUDA: Not detected: Failed to open dynamic library 'nvcuda.dll': The
15:02:51:                 specified module could not be found.
15:02:51:
15:02:51:OpenCL Device 0: Platform:0 Device:0 Bus:3 Slot:0 Compute:1.2 Driver:3110.7 <------
15:02:51:***********************************************************************
15:02:51:<config>
```

Can you compare the clinfo output now with the one you had previously? When comparing it to mine, I see that yours said

Driver version:                                3110.7 (PAL,LC)
while mine had
Driver version:                                3110.7 (PAL,HSAIL)

and yours had the following extensions missing:
cl_amd_fp64 cl_amd_vec3cl_amd_printf cl_amd_popcnt

**Comment by TheRealPenDragon** [comment]
Indeed - log from F@H now shows the OpenCL
20:53:27:        OS Arch: AMD64
20:53:27:           GPUs: 1
20:53:27:          GPU 0: Bus:45 Slot:0 Func:0 AMD:6 Navi 10 [Radeon RX 5600 OEM/5600 XT
20:53:27:                 / 5700/5700 XT]
20:53:27:           CUDA: Not detected: Failed to open dynamic library 'nvcuda.dll': The
20:53:27:                 specified module could not be found.
20:53:27:
20:53:27:OpenCL Device 0: Platform:0 Device:0 Bus:45 Slot:0 Compute:1.2 Driver:3110.7
20:53:27:***********************************************************************
20:53:27:<config>

Looking at driver version - I'm still listed showing 
Driver version: 3110.7 (PAL,LC)

And those 3 extensions are still missing from clinfo output. 

Full clinfo-working is uploaded. 

BUT - I am now fully working  - and the GPU is behaving as it should.... 
So really must have been the motherboard drivers  - 
Strange thing is - other opencl and opengl software was working...
So I'm still struggling to understand, what library the windows 10 default (& update) were not installing. But that the proprietary MSI drivers have 'fixed' 
I have no unknown devices showing in Device manager - or any devices that were looking for a 'better' driver from windows update.
   
[clinfo-working.txt](https://github.com/FoldingAtHome/fah-issues/files/5435745/clinfo-working.txt)

**Comment by bb30994** [comment]
This is a WInodws issue.  I know that when WindowsUpdate decides I need an updated driver for my GPU (which happens to be an nVidia) windows will update the driver and fail to reinstall the OpenCL that I previously installed.  Why should it be any different for AMD?

Neither version of OpenCL is "supported" by Windows or Linux or MacOS so I guess removing it is intentional.  I don't understand the inconsistency of Microsoft providing an OpenCL driver as part of the default driver package that supports an Intel iGPU.

**Comment by anand-bhat** [comment]
Closing this as I've opened a meta issue to track and troubleshoot this
