### ISSUE TITLE
Unable to Install - Versions 7.6.20 and 7.6.21

### ISSUE THREAD

**Issue by cab26715** [FoldingAtHome/fah-issues#1581]
Your issue may already be reported!
Please search on the [issue tracker](./) before creating one.

## Your Environment

* **F@H Software version**: 7.6.21
* **Operating System**: Windows 10 (Version 2004, 19041.572)
* **Browser**: Firefox 82.0 (64-bit)

----
## Expected Behavior

Should be able to install the program.

----
## Current Behavior

Unable to install Versions 7.6.20 and 7.6.21.  During installation on [Extract: ssleay32.dll] get error = "Failed to install files.  Most likely some software, possibly Folding@home is currently using one or more files that the installer is trying to upgrade.  Please stop all running Folding@home software and quit any applications that are using files from the Folding@home installation.  Note, complete shutdown can take a little while after the application has closed."

I tried completely closing the program using the Web Interface; Desktop App; and looking for running instances in Task Manager.  Still unable to install.  Normally, the installation program is supposed to close down the program and regain access to the files it is trying to update.

----
## Possible Solution (Optional)

Update the installation program code.  Did not have this problem on version 7.6.13.

----
## Steps To Reproduce

1. Try installing the program using Express setup and version 7.6.20 or 7.6.21.
2.
3.

----
## Context

Unable to update the program to 7.6.21.  Still works though without the upgrade.

----

**Comment by cab26715** [comment]
![Folding At Home - Bug 1](https://user-images.githubusercontent.com/73396999/97086211-e51a3880-15ef-11eb-85fa-ece90c5d007b.png)
![Folding At Home - Bug 2](https://user-images.githubusercontent.com/73396999/97086212-e51a3880-15ef-11eb-95bf-4b1055f0dcaf.png)

**Comment by cab26715** [comment]
I tried to remove 7.6.13 and do a fresh reinstall of 7.6.21 but on "Apps & Features" Windows returns "Windows cannot find 'C:\Program Files (x86)\FAHClient\Uninstall.exe.'  Make sure you typed the name correctly, and then try again."
![Folding At Home - Bug 3](https://user-images.githubusercontent.com/73396999/97086363-c8cacb80-15f0-11eb-95de-72b50eb102d2.png)

**Comment by jcoffland** [comment]
Some software on your system is locking a file F@H needs to write.  Maybe try rebooting first.  The uninstaller was likely removed during the incomplete install.

**Comment by cab26715** [comment]
Changed my Norton Security Firewall Settings on "FAHClient" to "Allow" from "Auto" then did a Custom Install with default settings.  It worked!
