### ISSUE TITLE
FAHclient/cores logging does use UTC time instead of local time

### ISSUE THREAD

**Issue by informatorius** [FoldingAtHome/fah-issues#1582]
FAHclient 7.6.20 and previous (and FAHcores) use UTC time for logging instead of local time. The operating system should be able to tell the local time to the app logging component, so this should be a low hanging fruit for the FAH developer. This would help users to identify issues at what time they happened.

**Comment by jcoffland** [comment]
This is intentional.  It's so we can easily cross reference times with those in our server logs.

**Comment by UofM-MartinK** [comment]
Using UTC time also helps the community in the forum or on discord to help others debug issues and relate them to global events, like trouble with certain servers at certain times etc.

**Comment by bb30994** [comment]
Logs do get posted as bug reports on servers where they might be parsed from several timezones or they get posted on FAHForum or Discord or ... where your local timezone means nothing.  We have to figure out when something happened without the benefit of knowing your timezone.  

You can benefit from one person learning to convert to/from UTC (you) a lot easier that having everybody else in the world learning to convert to/from your local timezone.

**Comment by PantherX** [comment]
Please note that I am closing this in favor of a potential feature request reference above 😄
