### ISSUE TITLE
Suspicious points earned

### ISSUE THREAD

**Issue by fdrobnic** [FoldingAtHome/fah-issues#1585]
Your issue may already be reported!
Please search on the [issue tracker](./) before creating one.

## Your Environment

* **F@H Software version**: 7.6.21
* **Operating System**: Windows 10 Pro
* **Browser**: any

----
## Expected Behavior

Although the exact points earned can not be determined by myself, I would expect the "Estimated Points" count (on the Web Control) to stop changing after the WU has been done (progress bar shows 100 %).

----
## Current Behavior

The "Estimated Points" count (on the Web Control) continues to change (it decreases gradually) after the WU has been done (progress bar shows 100 %).

----
## Possible Solution (Optional)

----
## Steps To Reproduce

1.
2.
3.

----
## Context

----

**Comment by jcoffland** [comment]
You get more points by returning the WU early.  Estimates points are expected to go down over time until the WU is returned.  I think this is normal.  Either way this is just an estimate and not the actual points which are determined by F@H when the WU is received.

**Comment by PantherX** [comment]
Hiya @fdrobnic 

If you still have further questions, feel free to hope over to our Official Forum (https://foldingforum.org/index.php) where many experienced members are there to help you out 😄
