### ISSUE TITLE
"Points earned" inconsistent with the Stats page

### ISSUE THREAD

**Issue by JSPerko** [FoldingAtHome/fah-issues#1586]
Your issue may already be reported!
Please search on the [issue tracker](./) before creating one.

## Your Environment

F@H Version 7.16.21 
Windows 10 Pro 
Chrome

----
## Expected Behavior

----
## Current Behavior

----
## Possible Solution (Optional)

----
## Steps To Reproduce

1.  Stop folding on the first computer (choose the option where it finishes the current unit, and then stops, although I'm not sure that it actually does stop--it seems as if it got another WU).  
2.  Install F@H on another computer.
3.  Request your passkey to be emailed to you.
4.  Enter that passkey on the new computer, and see if the correct "Points earned" from the previous computer shows up instead of zero.

----
## Context

----

**Comment by PantherX** [comment]
Hiya @JSPerko 

Please note that first glace, it doesn't seem to be a bug, but a design feature. Allow me to explain and if you still have further questions, we would be happy to help out you at our Official Forum (https://foldingforum.org/index.php) 😄 

Usernames are not unique within F@H. Thus, multiple donors can use the same username.
Passkeys are unique to the email/username so if you enter the same details, you get the same passkey,
The Client will display either the total points for the username or username/passkey combination depending on what the client is using.
Currently, all WUs are supported with passkeys but prior to that, there were many WUs that didn't support passkey to they are not counted in the points when searching with username/passkey but will show up when using only username.

**Comment by JSPerko** [comment]
I moved F@H to the new computer with both the same username and passkey as the old one.  So there's no reason that the program can't pick up the real number of "Points earned", unless you're saying that the username/password combination is not unique.  This seems especially true since the Stats page opened by clicking the "(See stats)" link shows the correct Points earned of over 9,000,000.  The main web page shows only 231,586.

**Comment by PantherX** [comment]
@JSPerko 

Please note that this isn't a bug but a "feature":

- Stats: It will show you all the points for that Username and will group points per team.
- Web Control: If you enter a passkey and username, it will only show points that have been assigned to that specific combination of username/passkey.

Historically, there have been non-bonus WUs which wouldn't have used any passkey so would not show up in Web Control but would show up in the Stats page.

**Comment by JSPerko** [comment]
Ridiculously and needlessly complicated.
