### ISSUE TITLE
FAHClient does not detect "on battery" state correctly (mac)

### ISSUE THREAD

**Issue by benfranklin79** [FoldingAtHome/fah-issues#1590]
I think this might be related to: https://github.com/FoldingAtHome/fah-issues/issues/1583

Below is a silent screencast where I show that the setting "Pause work while on battery power" is turned off, 
yet I'm unable to get folding to start via the control application or via the web interface.

After turning off the setting I would have expected to be able to resume folding when I manually tell the application to fold, even if my laptop is not connected.

https://www.screencast.com/t/QtU8vlUZVbrb

## Your Environment
* **F@H Software version**: 7.6.13
* **Operating System**: MacOSX 10.15.7
* **Browser**: Brave 1.16.75

**Comment by kbernhagen** [comment]
This is more a documentation error.

When folding on “light” power level, pause on battery is always considered true.

FAHControl should probably dim the option and show selected when power is light. 

Solution is to use a different power level, and manually set desired cpu count for slot.
