### ISSUE TITLE
fah control .deb not installable on Debian testing/unstable

### ISSUE THREAD

**Issue by smoe** [FoldingAtHome/fah-issues#1595]
## Your Environment ##

* **F@H Software version**:
7.6.21
* **Operating System**: 
Debian sid/unstable, also Debian testing/bullseye
* **Browser**: 
Firefox

----
## Expected Behavior ##

The package was attempted to be installed via the following command which should not have any output:

```
sudo dpkg -i fahcontrol_7.6.21-1_all.deb
```

----
## Current Behavior

```$ sudo dpkg -i fahcontrol_7.6.21-1_all.deb
Selecting previously unselected package fahcontrol.
(Reading database ... 286621 files and directories currently installed.)
Preparing to unpack fahcontrol_7.6.21-1_all.deb ...
Unpacking fahcontrol (7.6.21-1) ...
dpkg: dependency problems prevent configuration of fahcontrol:
 fahcontrol depends on python; however:
  Package python is not installed.
 fahcontrol depends on python-gtk2 | python-gnome2; however:
  Package python-gtk2 is not installed.
  Package python-gnome2 is not installed.

dpkg: error processing package fahcontrol (--install):
 dependency problems - leaving unconfigured
Processing triggers for mailcap (3.67) ...
Errors were encountered while processing:
 fahcontrol
```
----
## Possible Solution

Update dependency to Python2 (preferably Python3) and change the dependency on gtk2 to PyGObject https://pygobject.readthedocs.io/en/latest/getting_started.html

PyGObject is already available for the stable version of Debian. Would you be accepting patches to make the transition?

**Comment by shorttack** [comment]
Foldingathome will not install in a pure Python 3 environment like yours. There is a Github project to fix this. It is a high priority but no completion date yet. 7.6.13 installs on older (last year) versions of Linux (and I'm not a Linux numerologist). If you can help, seek out the FAH Python 3 team. Thanks.

**Comment by smoe** [comment]
The immediate fix would be with the individual maintaining the .deb file to also allow the [Python2](https://packages.debian.org/unstable/python2) package and to not solely insist on the python package.
Please kindly try to find the Python3 transition team's URL for me. I just failed to locate them. Many thanks!

**Comment by PantherX** [comment]
> 
> Please kindly try to find the Python3 transition team's URL for me. I just failed to locate them. Many thanks!

Assuming you're looking for the progress, this is what I have found: https://github.com/FoldingAtHome/fah-control/pull/70 within that Repo, there are other Pull Requests and discussion too
