### ISSUE TITLE
Why does it keep crashing my PC - especially on "Full" mode?

### ISSUE THREAD

**Issue by Uralrider** [FoldingAtHome/fah-issues#1596]
AMD FX600 Black, GTX 970 with 16Gb RAM.

----

**Comment by Uralrider** [comment]
Sorry, FX6300 Black.

**Comment by Nexus76it** [comment]
Check the Temperature with HWMonitor
Hi

**Comment by Uralrider** [comment]
Temps are good, CPU is liquid cooled stable at 24 degrees under load!  GPU air cooled stable at 65 degrees under load.  I don't think it's that.
Crashes are random, the worst kind.  It's been on 2 days without crashing (to date).

**Comment by PantherX** [comment]
Hiya @Uralrider 

Please note that at this point, there's very little information on how to reproduce this bug in a consistent and reliable manner. Thus, I would suggest that you post in our Official Forum (https://foldingforum.org/index.php) where this can be investigated further. If needed, a proper bug report can be opened in the future 😄

Thanks for your report!
