### ISSUE TITLE
serious network problems caused by the client fah-installer_7.6.21_x86.exe

### ISSUE THREAD

**Issue by Nexus76it** [FoldingAtHome/fah-issues#1597]
I have encountered serious network problems caused by the client fah-installer_7.6.21_x86.exe (Winbdows 10 + Nvidia 1060) I could not understand if it generates too much traffic to the internet or what is blocking the network.
When the fah-installer_7.6.21_x86.exe client is running, the pings to google.com go from 43ms to 1500ms and beyond, blocking my internet connection.
Removing everything and returning to the old client fah-installer_7.6.13_x86.exe there is no longer any network problem and the ping to google.com returns to 43ms.
What can it be ?
thanks
regards

**Comment by Nexus76it** [comment]
I'm an active user on folding@home
-------------------------------------
Nexus76
Total score   121,074,171
Total WUs     1,246
Overall rank  11,605 of 2,770,460

**Comment by PantherX** [comment]
Hiya @Nexus76it 

Please note that at this point, there's very little information on how to reproduce this bug in a consistent and reliable manner. Thus, I would suggest that you post in our Official Forum (https://foldingforum.org/index.php) where this can be investigated further. If needed, a proper bug report can be opened in the future 😄

Thanks for your report!
