### ISSUE TITLE
Failure to send results - Collection Server 0.0.0.0

### ISSUE THREAD

**Issue by castalite** [FoldingAtHome/fah-issues#1598]
I have a task on its 41st send attempt 
so a GPU sat idle
Project is 17426

**Comment by PantherX** [comment]
Hiya @castalite 

Please note that at this point, there's very little information on how to reproduce this bug in a consistent and reliable manner. Thus, I would suggest that you post in our Official Forum (https://foldingforum.org/index.php) where this can be investigated further. If needed, a proper bug report can be opened in the future 😄

Thanks for your report!
