### ISSUE TITLE
Theta Edge Nodes not folding

### ISSUE THREAD

**Issue by kdmyhre88** [FoldingAtHome/fah-issues#1599]
Your issue may already be reported!
Please search on the [issue tracker](./) before creating one.

## Your Environment

* **F@H Software version**: 
* **Operating System**: 
* **Browser**: 

----
## Expected Behavior

----
## Current Behavior

----
## Possible Solution (Optional)

----
## Steps To Reproduce

1.
2.
3.

----
## Context

----

**Comment by kdmyhre88** [comment]
Two of my four nodes will not fold.
I think I interupted the dialog box that would have allowed.
How can it be initiated?

**Comment by PantherX** [comment]
Hiya @kdmyhre88 

Please note that at this point, there's very little information on how to reproduce this bug in a consistent and reliable manner. Thus, I would suggest that you post in our Official Forum (https://foldingforum.org/index.php) where this can be investigated further. If needed, a proper bug report can be opened in the future 😄

Thanks for your report!
