### ISSUE TITLE
Mac M1 Silicon cant install app

### ISSUE THREAD

**Issue by snakeys** [FoldingAtHome/fah-issues#1600]
If i try to install fah on my Macbook Air M1 then i get the following error message.
ah-installer_7.6.21_x86_64.pkg “cannot be opened because Apple cannot search for malware in it.

maybe solved instead of double click i have started isnatllation with right klich and open with.

But it dont start crunching. after testing. Command Line over terminal seems to work. all cores up under load.

**Comment by smiba** [comment]
If you go to your security settings on OS 11 you should be able to approve the package to run without verification

**Comment by PantherX** [comment]
Hiya @snakeys 

Please see https://github.com/FoldingAtHome/fah-issues/issues/1576 for the workaround until V7.6.22 (or higher) is released. There's no ETA for that.

I will close this issue now as a duplicate 😄
