### ISSUE TITLE
FAH not acessing Ryzen 5000 correctly

### ISSUE THREAD

**Issue by GitHub-source-42** [FoldingAtHome/fah-issues#1603]
## Your Environment

* 7.6.21_x86: 
* Windows: 
* Firefox: 

----
## Expected Behavior

The CPU should only be using about 20% to 50% of the CPU

----
## Current Behavior

It is presently using around 95% of my CPU on the light setting.

----
## Possible Solution (Optional)

A tailorable CPU load creation tool allowing the cores to individually be used within set limits.

----
## Steps To Reproduce

Install a 5950X in an AM4 motherboard Run F@h and see the load usage in Ryzen master or Task Manager

----
## Context

This has meant I am constantly running at really high temperatures due to the excessive loads.

**Comment by PantherX** [comment]
Hiya @GitHub-source-42 

Please note that at this point, I would suggest that you post in our Official Forum (https://foldingforum.org/index.php) where you can seek configuration help 😄

Thanks for your report!
