### ISSUE TITLE
created team & passkey, not working... 	https://apps.foldingathome.org/teamstats/team268531.html

### ISSUE THREAD

**Issue by OpenNewFolder** [FoldingAtHome/fah-issues#1617]
Your issue may already be reported!
Please search on the [issue tracker](./) before creating one.

## Your Environment

* **F@H Software version**: 
* **Operating System**: 
* **Browser**: 

----
## Expected Behavior

----
## Current Behavior

----
## Possible Solution (Optional)

----
## Steps To Reproduce

1.
2.
3.

----
## Context

----

**Comment by PantherX** [comment]
Hiya @OpenNewFolder 

Please note that our [Forum](https://foldingforum.org/index.php) would be the best place to continue this discussion further 😄 

However, I did have a quick look and there's already a team 26853 which has a single donor: https://stats.foldingathome.org/team/268531 so I assume that's the correct team you're after.

**Comment by OpenNewFolder** [comment]
thank you, still learning all this, figuring out forum, there is another donor named K2SGSTEAM....not finding him
________________________________

**Comment by PantherX** [comment]
@OpenNewFolder I am able to find the donor here: https://stats.foldingathome.org/donor/447931140

Just note that new donors can take up to 72 hours to show up in the stats system depending on how much load there is on the system.
