### ISSUE TITLE
Completed WU for project 16927 not counted

### ISSUE THREAD

**Issue by sergeydeg** [FoldingAtHome/fah-issues#1621]
Your issue may already be reported!
Please search on the [issue tracker](./) before creating one.

## Your Environment

* **F@H Software version**: 7.6.21
* **Operating System**: Win10
* **Browser**: 

----
## Expected Behavior
Points to completed WU assigned in time

----
## Current Behavior
WU completed 15.01
```
00:40:39:WU00:FS00:FahCore returned: FINISHED_UNIT (100 = 0x64)
00:40:39:WU00:FS00:Sending unit results: id:00 state:SEND error:NO_ERROR project:16927 run:17 clone:813 gen:62 core:0xa7 unit:0x0000032d0000003e0000421f00000011
00:40:39:WU00:FS00:Uploading 6.30MiB to 129.32.209.201
00:40:39:WU00:FS00:Connecting to 129.32.209.201:8080
00:40:45:WU00:FS00:Upload 42.67%
00:40:51:WU00:FS00:Upload 91.29%
00:40:52:WU00:FS00:Upload complete
00:40:52:WU00:FS00:Server responded WORK_ACK (400)
```

[https://apps.foldingathome.org/wu#project=16927&run=17&clone=813&gen=62](https://apps.foldingathome.org/wu#project=16927&run=17&clone=813&gen=62)
says not found.

----
Today another WU from this project finished, not counted yet.

```
05:52:02:WU00:FS00:FahCore returned: FINISHED_UNIT (100 = 0x64)
05:52:02:WU00:FS00:Sending unit results: id:00 state:SEND error:NO_ERROR project:16927 run:13 clone:774 gen:61 core:0xa7 unit:0x000003060000003d0000421f0000000d
05:52:03:WU00:FS00:Uploading 6.30MiB to 129.32.209.201
05:52:03:WU00:FS00:Connecting to 129.32.209.201:8080
05:52:09:WU00:FS00:Upload 46.64%
05:52:15:WU00:FS00:Upload 85.35%
05:52:18:WU00:FS00:Upload complete
05:52:18:WU00:FS00:Server responded WORK_ACK (400)
```

**Comment by jcoffland** [comment]
We've identified the problem and fixed it.  No simulation data was lost.  The points information is also available but not easy sort out.
