### ISSUE TITLE
trouble

### ISSUE THREAD

**Issue by valen94** [FoldingAtHome/fah-issues#1629]
Your issue may already be reported!
Please search on the [issue tracker](./) before creating one.

## Your Environment

* **F@H Software version**: 
* **Operating System**: 
* **Browser**: 

----
## Expected Behavior

Hello, yesterday February 20 I started mining and I left it for 20% more or less and today February 21 the counter was reset. This should not happen because that way I will never reach 100% and therefore I will not charge
This happens in the local Folding @ home.

----

**Comment by gwildperson** [comment]
Folding@home is not mining.

When a WU is assigned, it may not be completed before you shutdown your computer.  F@H writes checkpoints periodically and can restart from the last checkpoint depending on how you start/restart FAHClient and where it was storing the checkpoint.  Is F@H starting automatically when you reboot?  Have you altered the default settings for where F@H was installed?

**Comment by PantherX** [comment]
Hiya @valen94 

Please note that F@H doesn't officially support Cryptocurrency ([Folding@home policy on cryptocurrencies](https://foldingathome.org/2019/01/14/foldinghome-policy-on-cryptocurrencies/)). Thus, I will be closing this issue now. If you would like to have a discussion, feel free to join our [Official Forum](https://foldingforum.org/index.php) 😃
