### ISSUE TITLE
Exception: Failed to send results to work server: Transfer failed

### ISSUE THREAD

**Issue by bedge117** [FoldingAtHome/fah-issues#1631]
I have a back log of WUs that need to be sent.  There is no way, that I can see, to force a reattempt.  I have pinged the collection server and I get a response.  My network if working normally.  This issue has only been happening the last 24 hours.  It is happening on multiple devices.

**Comment by bedge117** [comment]
03:42:54:ERROR:WU09:FS01:Exception: Transfer failed
03:49:26:WARNING:WU11:FS01:Exception: Failed to send results to work server: Transfer failed
03:49:42:WARNING:WU00:FS00:Exception: Failed to send results to work server: Transfer failed
03:50:14:ERROR:WU00:FS00:Exception: Transfer failed
03:56:53:ERROR:WU11:FS01:Exception: Transfer failed
******************************* Date: 2021-02-28 *******************************
04:01:55:WU12:FS01:0x22:ERROR:98: Attempting to restart from last good checkpoint by restarting core.
04:01:58:WARNING:WU12:FS01:FahCore returned an unknown error code which probably indicates that it crashed
04:01:58:WARNING:WU12:FS01:FahCore returned: UNKNOWN_ENUM (-1073740791 = 0xc0000409)
04:03:37:WARNING:WU08:FS01:Exception: Failed to send results to work server: Transfer failed
04:05:25:WARNING:WU02:FS00:Exception: Failed to send results to work server: Transfer failed
04:07:12:ERROR:WU08:FS01:Exception: Transfer failed
04:09:14:ERROR:WU02:FS00:Exception: Transfer failed
04:14:30:WARNING:WU04:FS01:Exception: Failed to send results to work server: Transfer failed
04:15:08:WARNING:WU05:FS00:Exception: Failed to send results to work server: Transfer failed
04:21:59:ERROR:WU04:FS01:Exception: Transfer failed
04:23:34:WARNING:WU07:FS01:Exception: Failed to send results to work server: Transfer failed
04:25:21:ERROR:WU07:FS01:Exception: Transfer failed
04:27:27:ERROR:WU05:FS00:Exception: Transfer failed
04:31:06:WARNING:WU01:FS01:Exception: Failed to send results to work server: Transfer failed
04:31:45:ERROR:WU01:FS01:Exception: Transfer failed
04:33:19:WARNING:WU03:FS01:Exception: Failed to send results to work server: Transfer failed
04:36:40:ERROR:WU03:FS01:Exception: Transfer failed
04:39:08:WARNING:WU09:FS01:Exception: Failed to send results to work server: Transfer failed
04:44:42:ERROR:WU09:FS01:Exception: Transfer failed
04:49:41:WARNING:WU11:FS01:Exception: Failed to send results to work server: Transfer failed
04:50:14:WARNING:WU08:FS01:Exception: Failed to send results to work server: Transfer failed
04:50:14:ERROR:WU11:FS01:Exception: Transfer failed
04:50:31:WARNING:WU00:FS00:Exception: Failed to send results to work server: Transfer failed
04:51:06:ERROR:WU08:FS01:Exception: Transfer failed
04:54:40:ERROR:WU00:FS00:Exception: Transfer failed
05:05:10:WARNING:WU02:FS00:Exception: Failed to send results to work server: Transfer failed
05:05:58:ERROR:WU02:FS00:Exception: Transfer failed
05:13:11:WARNING:WU04:FS01:Exception: Failed to send results to work server: Transfer failed
05:15:09:ERROR:WU04:FS01:Exception: Transfer failed
05:16:25:WARNING:WU05:FS00:Exception: Failed to send results to work server: Transfer failed
05:16:52:ERROR:WU05:FS00:Exception: Transfer failed
05:24:22:WARNING:WU07:FS01:Exception: Failed to send results to work server: Transfer failed
05:29:18:WARNING:WU01:FS01:Exception: Failed to send results to work server: Transfer failed
05:31:42:WARNING:WU12:FS01:Exception: Failed to send results to work server: Transfer failed
05:31:45:ERROR:WU01:FS01:Exception: Transfer failed
05:32:00:WARNING:WU03:FS01:Exception: Failed to send results to work server: Transfer failed
05:32:01:ERROR:WU07:FS01:Exception: Transfer failed
05:33:54:ERROR:WU03:FS01:Exception: Transfer failed
05:35:27:ERROR:WU12:FS01:Exception: Transfer failed
05:38:07:WARNING:WU12:FS01:Exception: Failed to send results to work server: Transfer failed
05:39:07:WARNING:WU09:FS01:Exception: Failed to send results to work server: Transfer failed
05:40:28:ERROR:WU09:FS01:Exception: Transfer failed
05:41:43:WU06:FS01:0x22:WARNING:Console control signal 1 on PID 21096
05:41:43:WU10:FS00:0xa8:WARNING:Console control signal 1 on PID 10216
05:42:23:ERROR:WU12:FS01:Exception: Transfer failed
05:44:01:WARNING:WU12:FS01:Exception: Failed to send results to work server: Transfer failed
05:44:40:WARNING:WU05:FS00:Exception: Failed to send results to work server: Transfer failed
05:45:00:WARNING:WU03:FS01:Exception: Failed to send results to work server: Transfer failed
05:45:20:WARNING:WU04:FS01:Exception: Failed to send results to work server: Transfer failed
05:45:25:ERROR:WU12:FS01:Exception: Transfer failed
05:45:32:ERROR:WU05:FS00:Exception: Transfer failed
05:46:28:WARNING:WU07:FS01:Exception: Failed to send results to work server: Transfer failed
05:47:00:ERROR:WU03:FS01:Exception: Transfer failed
05:47:08:ERROR:WU04:FS01:Exception: Transfer failed
05:47:48:WARNING:WU01:FS01:Exception: Failed to send results to work server: Transfer failed
05:47:58:WARNING:WU02:FS00:Exception: Failed to send results to work server: Transfer failed
05:48:14:ERROR:WU01:FS01:Exception: Transfer failed
05:48:39:WARNING:WU05:FS00:Exception: Failed to send results to work server: Transfer failed
05:48:56:WARNING:WU04:FS01:Exception: Failed to send results to work server: Transfer failed
05:49:05:WARNING:WU09:FS01:Exception: Failed to send results to work server: Transfer failed
05:49:26:ERROR:WU02:FS00:Exception: Transfer failed
05:49:27:ERROR:WU07:FS01:Exception: Transfer failed
05:50:03:WARNING:WU11:FS01:Exception: Failed to send results to work server: Transfer failed
05:50:11:WARNING:WU00:FS00:Exception: Failed to send results to work server: Transfer failed
05:51:00:ERROR:WU04:FS01:Exception: Transfer failed
05:51:27:ERROR:WU00:FS00:Exception: Transfer failed
05:51:28:WARNING:WU10:FS00:Detected clock skew (2 mins 01 secs), I/O delay, laptop hibernation or other slowdown noted, adjusting time estimates
05:52:59:ERROR:WU11:FS01:Exception: Transfer failed
05:52:59:WARNING:WU10:FS00:Detected clock skew (1 mins 31 secs), I/O delay, laptop hibernation or other slowdown noted, adjusting time estimates
05:52:59:WARNING:WU06:FS01:Detected clock skew (7 mins 34 secs), I/O delay, laptop hibernation or other slowdown noted, adjusting time estimates

**Comment by gwildperson** [comment]
Let's assume the designated server has run out of disk space or is off-line temporally. (Yes, such things do happen)  It obviously cannot receive your results.  FAHClient will AUTIOMATICALLY resend the file until it succeeds or until the result expires.  Deadlines are very important to F@H so somebody is likely to fix the server's problem promptly.  Manually trying to re-send is not a useful activity.

**Comment by PantherX** [comment]
Hiya @bedge117 

Based on the comments above, there's not much that can be done in this situation for you. However, if you would like to have a discussion, feel free to join our [Official Forum](https://foldingforum.org/index.php) 😃
