### ISSUE TITLE
Ideas 

### ISSUE THREAD

**Issue by eliagiacomelli** [FoldingAtHome/fah-issues#1634]

**Comment by eliagiacomelli** [comment]
Do we turn folding @ home into an eth blockchain project via an ERC20 token that is released when someone donates the computing power?

**Comment by PantherX** [comment]
Hiya @eliagiacomelli 

Please note that F@H doesn't officially support Cryptocurrency ([Folding@home policy on cryptocurrencies](https://foldingathome.org/2019/01/14/foldinghome-policy-on-cryptocurrencies/)). Thus, I will be closing this issue now. If you would like to have a discussion, feel free to join our [Official Forum](https://foldingforum.org/index.php) 😃
