### ISSUE TITLE
Total of units completed no longer displays

### ISSUE THREAD

**Issue by SueBoyde** [FoldingAtHome/fah-issues#1638]
I was close to 10,000,000 units. The next morning the running total of work units did not display and it hasn't been visible since. Can I fix it? Or how else can I see my units?
NB other users have said the total has stopped displaying for them. We suspect it's a server issue.

**Comment by anand-bhat** [comment]
The web client attempts to get project details from `apps.foldingathome.org/stats.py?user=X&team=Y&passkey=Z` (e.g., https://apps.foldingathome.org/stats.py?callback=jQuery11020844434884399677_1618233160677&user=AnandBhat&team=41494&passkey=12345&version=7.6.21&_=1618233160678), which redirects to `stats.foldingathome.org/user?user=X&team=Y&passkey=Z` (e.g., https://stats.foldingathome.org/user?callback=jQuery11020844434884399677_1618233160677&user=AnandBhat&team=41494&passkey=12345&version=7.6.21&_=1618233160678). After the new stats pages were rolled out, these URLs do not return the values expected by the web client.

The original content of the requests can be found by replacing stats with stasclassic i.e., `statsclassic.foldingathome.org/user?user=X&team=Y&passkey=Z` (e.g., https://statsclassic.foldingathome.org/user?callback=jQuery11020844434884399677_1618233160677&user=AnandBhat&team=41494&passkey=12345&version=7.6.21&_=1618233160678). After the new stats pages were rolled out, these URLs do not return the values expected by the web client.

**Comment by anand-bhat** [comment]
[at]ReadyPlayerEmma fixed by configuring cloudflare. Future client would use the API instead of stats domain jquery callback
