### ISSUE TITLE
Team Stats link on Web Control page not working--just continually displays "Loading..."

### ISSUE THREAD

**Issue by pjcaldwell7** [FoldingAtHome/fah-issues#1639]
Your issue may already be reported!
Please search on the [issue tracker](./) before creating one.

## Your Environment

* **F@H Software version**: 
* **Operating System**: 
* **Browser**: 

----
## Expected Behavior

----
## Current Behavior

----
## Possible Solution (Optional)

----
## Steps To Reproduce

1.
2.
3.

----
## Context

----

**Comment by TAWASHId2** [comment]
> Your issue may already be reported!
> Please search on the [issue tracker](./) before creating one.
> 
> ## Your Environment
> * **F@H Software version**:
> * **Operating System**:
> * **Browser**:
> 
> ## Expected Behavior
> ## Current Behavior
> ## Possible Solution (Optional)
> ## Steps To Reproduce
> 
> ## Context

#

1.

**Comment by anand-bhat** [comment]
The web client attempts to get project details from `stats.foldingathome.org/project?id=XXXXX` (e.g., https://stats.foldingathome.org/project?callback=jQuery11020844434884399677_1618233160677&id=17411&version=7.6.21). After the new stats pages were rolled out, these URLs do not return the values expected by the web client.

The original content of the requests can be found by replacing `stats` with `stasclassic` i.e., `stats.foldingathome.org/project?id=XXXXX` (e.g., https://statsclassic.foldingathome.org/project?callback=jQuery11020844434884399677_1618233160677&id=17411&version=7.6.21)

**Comment by anand-bhat** [comment]
[at]ReadyPlayerEmma fixed by configuring cloudflare. Future client would use the API instead of stats domain jquery callback
