### ISSUE TITLE
Running two different nodes, but ended up same user and team when opened

### ISSUE THREAD

**Issue by yhca** [FoldingAtHome/fah-issues#1641]
Hi, I am running one FAH for Bananos coins and another FAH for Tfuel coins. However, when I open the system to run for Tfuel coins, the username and team is the same as my bananos coin app. Ended up I did not receive my bananos coin as I would daily do and my Tfuel is the one going up. So I can only run one FAH and decide which coins I want to fold for? I can't get both coins?

**Comment by bb30994** [comment]
Folding@home is NOT a cybercoin organization, it is a scientific research organization.  As far as FAH is concerned, you're donating computer resources to biochemical research.  Please contact Bnanaos and TFuel about your concerns associated with cyber coins..

FAHClient is designed to use all of the unused resources and credit them to your FAH account.  You cannot run two different copies of FAHClient to earn double the FAH points unless they are on different computers.
