### ISSUE TITLE
Since receiving a pass code none of my stats are showing up.

### ISSUE THREAD

**Issue by mac2941** [FoldingAtHome/fah-issues#1642]
Your issue may already be reported!
Please search on the [issue tracker](./) before creating one.

## Your Environment

* **F@H Software version**: 
* **Operating System**: 
* **Browser**: 

----
## Expected Behavior

----
## Current Behavior

----
## Possible Solution (Optional)

----
## Steps To Reproduce

1.
2.
3.

----
## Context

----

**Comment by PantherX** [comment]
Hiya @mac2941 

Please head over to the [Official Forum](https://foldingforum.org/index.php) if you still need help 😄
