### ISSUE TITLE
Windows 10 (20H2) crashing and giving Blue Screen using SSD NVME M.2

### ISSUE THREAD

**Issue by jonataskts** [FoldingAtHome/fah-issues#1645]
I'm using the FHA for a while, but until yesterday a new NVME M.2 ssd arrived from NETAC of 1tb, I did the entire system installation process, but when I install and start the FHA after a few minutes the computer freezes and the screen blue, I have tried several alternatives to get around this but so far I have not had a solution, could you help me solve this? (windows 10 20H2)

**Comment by muziqaz** [comment]
I do not believe this is related to FAH. Also these type of issues can be dealt with in foldingforum.org or foldingathome discord

Regards

**Comment by PantherX** [comment]
Hiya @jonataskts 

Please note that there's too may variables involved so isn't a valid issue. As suggested by @muziqaz you may head over to our [Official Forum](https://foldingforum.org/index.php) to get help if you still need it 😃
