### ISSUE TITLE
Estou fechando blocos, mais não recebo

### ISSUE THREAD

**Issue by Brito84** [FoldingAtHome/fah-issues#1646]
Estou minerando  e fechando blocos diariamente.
Porém estou sem receber desde o dia 19/04.
O que está ocorrendo?
Desde á agradeço pela atenção e agurdo um retorno. 
Att; 

ban_1yr4othafpugcckddsyoo7q481338fzw9xnb1iwzpbnxb9ndc3jmmyjsqnu4

**Comment by muziqaz** [comment]
This is not mining github. FAH does not give any coins or money for folding. If you are not receiving something someone promised to you, ask those who promised something to you.

**Comment by Brito84** [comment]
OK. Shutting down mining. I thought the dots ae turned into bananas( BAN).
It's good to know this team at Folding @ home. thanks.

Em sex, 23 de abr de 2021 16:29, muziqaz ***@***.***>
escreveu:

**Comment by PantherX** [comment]
Hiya @Brito84 

Please note that F@H doesn't officially support Cryptocurrency ([Folding@home policy on cryptocurrencies](https://foldingathome.org/2019/01/14/foldinghome-policy-on-cryptocurrencies/)). Thus, I will be closing this issue now. If you would like to have a discussion, feel free to join our [Official Forum](https://foldingforum.org/index.php) 😃
