### ISSUE TITLE
Where to report issue about banano vault wallets please? 

### ISSUE THREAD

**Issue by curious209** [FoldingAtHome/fah-issues#1648]
Your issue may already be reported!
Please search on the [issue tracker](./) before creating one.

## Your Environment

* **F@H Software version**: 
* **Operating System**: 
* **Browser**: 

----
## Expected Behavior

----
## Current Behavior

----
## Possible Solution (Optional)

----
## Steps To Reproduce

1.
2.
3.

----
## Context

----

**Comment by curious209** [comment]
Folding is fine, got 2k no but no bananos as some glitch with the vault? Not showing up the original account, then logged in and theres another ban_ account details in its place, which I have never seen before.  

I checked the explorer, says the original account exists but not showing up at all in my vault - just a different address, copied them all down though. Logged out then in again and now says needs to configure wallet (after it as already successfully configured). So lots of glitches happening.

No idea, not a techie. 

The folding itself is fine but having a difficult time to know where to go and who to see about these glitches. I have my user ID, team number and my passkey for folding but I dont know where bananos have gone. Been folding now for approx. 2 months. 

Thank you in advance for anything to direct me to the correct place/department/peeps to fix this issue.

**Comment by muziqaz** [comment]
Folding at Home has no association with any crypto outfits. Please address your issues with any crypto related problems to people/companies who are promising you payouts. FAH does not do that.

**Comment by Luca-Ziesler** [comment]
I'm closing this

**Comment by Luca-Ziesler** [comment]
I'm closing this

**Comment by Luca-Ziesler** [comment]
or let's say I would

**Comment by PantherX** [comment]
Hiya @curious209 

Please note that F@H doesn't officially support Cryptocurrency ([Folding@home policy on cryptocurrencies](https://foldingathome.org/2019/01/14/foldinghome-policy-on-cryptocurrencies/)). Thus, I will be closing this issue now. If you would like to have a discussion, feel free to join our [Official Forum](https://foldingforum.org/index.php) 😃
