### ISSUE TITLE
Folding for a specific task was completed but points were not credited 

### ISSUE THREAD

**Issue by nayanjha16** [FoldingAtHome/fah-issues#1649]
Hi , Even after completion of the cntire folding process for the tasks , the points were not credited for me !

**Comment by muziqaz** [comment]
Points take some time to show up for first time folders.
For this type of queries please create a thread in foldingforum.org

**Comment by PantherX** [comment]
Hiya @nayanjha16 

Please note that there isn't any known stats issues. As suggested by @muziqaz you may head over to our [Official Forum](https://foldingforum.org/index.php) to get help if you still need it 😃
