### ISSUE TITLE
WU and points not showing up

### ISSUE THREAD

**Issue by Commie9713** [FoldingAtHome/fah-issues#1650]
I watched my WU compete and I allowed my pc to run overnight (a work unit is about an hour for me) and my points score has not changed. This is obviously a problem somewhere so just in case anyone else has this I'd like to report it.

**Comment by muziqaz** [comment]
Visit foldingforum.org and create a thread over there in relevant section.

**Comment by PantherX** [comment]
Hiya @Commie9713 

Please note that there isn't any known stats issues. As suggested by @muziqaz you may head over to our [Official Forum](https://foldingforum.org/index.php) to get help if you still need it 😃
