### ISSUE TITLE
I have folded for several weeks and also I completed some projects but my point is steel 0 ?? what is the problem? could you please help me?

### ISSUE THREAD

**Issue by PooryaMir** [FoldingAtHome/fah-issues#1653]
Your issue may already be reported!
Please search on the [issue tracker](./) before creating one.

## Your Environment

* **F@H Software version**: 
* **Operating System**: 
* **Browser**: 

----
## Expected Behavior

----
## Current Behavior

----
## Possible Solution (Optional)

----
## Steps To Reproduce

1.
2.
3.

----
## Context

----

**Comment by muziqaz** [comment]
This is not a support forum. Please visit foldingforum.org and create a thread over there in relevant section, and PLEASE provide more information, like your username, which you chose to fold with.

**Comment by PantherX** [comment]
Hiya @PooryaMir 

Please note that there isn't any known stats issues. As suggested by @muziqaz you may head over to our [Official Forum](https://foldingforum.org/index.php) to get help if you still need it 😃
