### ISSUE TITLE
Running 24/7 not getting paid tfuel for finishing multible jobs

### ISSUE THREAD

**Issue by LionNL** [FoldingAtHome/fah-issues#1654]
Hi, Im running multible Theta nodes on different networks, different pc's, different account in the Netherland. I read storys about earning 1 tfuel each day. My pc's are running 24/7 for about a month now. I completed manny jobs but didnt earn a single tfuel... <-- talking about pending earnings. Edge compute finishes one job after another. but doenst ad tfuel after the job is finshed. Sometimes edgecompute flickers. (disappears and comeback). Edge cache doesnt do much most of the time.  My question is how come i cant see the jobs that i finshed and the paymed that i should earn for these jobs...
On some pc's its worked a litle but of the 25 computers that run it on different networks only 2 pc earnt a 4 tfuel total....

Your issue may already be reported!
Please search on the [issue tracker](./) before creating one.

## Your Environment

* **F@H Software version**: 
* **Operating System**: 
* **Browser**: 

----
## Expected Behavior

----
## Current Behavior

----
## Possible Solution (Optional)

----
## Steps To Reproduce

1.
2.
3.

----
## Context

----

**Comment by muziqaz** [comment]
Folding@Home has nothing to do with any payments. Please seek information from those who promise the payments. FAH does not pay anyone anything for folding

**Comment by PantherX** [comment]
Hiya @LionNL 

Please note that F@H doesn't officially support Cryptocurrency ([Folding@home policy on cryptocurrencies](https://foldingathome.org/2019/01/14/foldinghome-policy-on-cryptocurrencies/)). Thus, I will be closing this issue now. If you would like to have a discussion, feel free to join our [Official Forum](https://foldingforum.org/index.php) 😃
