### ISSUE TITLE
Failed to get assignment - Client starts no WUs

### ISSUE THREAD

**Issue by Radon8472** [FoldingAtHome/fah-issues#1655]
## Your Environment

* **F@H Software version**: 7.6.9_x86 / 7.6.21_x86
* **Operating System**: Windows 10
* **Browser**:  irelevant

----
## Expected Behavior

client should start, download WUs and start working

----
## Current Behavior

Client starts, but is not able to download and start WU.

----
## Possible Solution (Optional)

----
## Steps To Reproduce

1. Start client software

----
## Context

I use version 7.6.9 a long time, and it was working each day.
since 2 days the client was no longer able to download new WUs.
I tried to update my client to the latest version 7.6.21, but still the same problem.
( My Internet Connection is checked, I dont use proxies or other special confuguration)

The logfile gives following error-messages:

> 06:19:49:WARNING:WU00:FS00:Failed to get assignment from 'assign1.foldingathome.org:80': No WUs available for this configuration
> 06:19:50:WARNING:WU00:FS00:Failed to get assignment from 'assign2.foldingathome.org:80': No WUs available for this configuration
> 06:19:50:WARNING:WU00:FS00:Failed to get assignment from 'assign3.foldingathome.org:80': No WUs available for this configuration
> 06:19:51:WARNING:WU00:FS00:Failed to get assignment from 'assign4.foldingathome.org:80': No WUs available for this configuration
> 06:19:51:ERROR:WU00:FS00:Exception: Could not get an assignment

----

**Comment by muziqaz** [comment]
This is not an issue with the client. This means, that there are no work units for you available at that given moment. It happens from time to time

**Comment by Radon8472** [comment]
But is that normal, that there are no work units for over 3 days in all projects ??

**Comment by muziqaz** [comment]
Yes, when there are no WUs it is normal.
P.S. Future similar questions like that please post them in foldingforum.org.
GitHub is geared more towards technical bug reporting and solving.

Regards

**Comment by PantherX** [comment]
Hiya @Radon8472 

As stated by @muziqaz that occasionally, we may run out of WUs to provide to the client. We do not provide "busy work" so it can happen every now and then. Best is to visit the [Official Forum](https://foldingforum.org/) to see what the situation is.

Since this is not classified as a bug, I will be closing this issue 😸
