### ISSUE TITLE
[FR] Select hours when to fold

### ISSUE THREAD

**Issue by iamdoubz** [FoldingAtHome/fah-issues#1656]
## Is your feature request related to a problem?
This FR is not related to any existing problem.

----
## Describe the Feature
It would be really nice to have an option to be able to configure hours in which the client is allowed to fold.

----
## Context
This feature would be beneficial if a client can only fold during certain time frames/hours of the day. For me specifically, I really only want to fold at nights, but am not always am around or forget to remember to "unpause" my folding clients. So, in theory, I could set a start time of 7pm and an end time of 7am and the client would fold its heart heart out between those two times. It also helps save time, energy, and manually intervention of the people behind these systems. My vision of the configuration would be a check box that enables the Start and End values. If the box isn't checked, it should default to the other configuration options such as Low, Medium, High and/or While I'm Working and When I'm Idle.

----
Thank you in advanced.

**Comment by iamdoubz** [comment]
Although I would still like this to be implemented in the GUI, this is how you would do it using a crontab in a *nix environment:

```
22 00 * * * /usr/bin/FAHClient --send-unpause >/dev/null
00 07 * * * /usr/bin/FAHClient --send-pause >/dev/null
```

Tell FAHClient to "Start Folding" at 10PM. Followed by tell FAHClient to "Stop Folding" at 7am.

On Windows, you can set up a Task Schedule to start the program `C:\Program Files (x86)\FAHClient\FAHClient.exe --send-unpause` and another to stop it `C:\Program Files (x86)\FAHClient\FAHClient.exe --send-pause`.

If you'd rather "Finish" your jobs, substitute `--send-pause` with `--send-finish`.

**Comment by PantherX** [comment]
Hiya @iamdoubz 

It seems that your feature request has been covered by these two:
https://github.com/FoldingAtHome/fah-issues/issues/300
https://github.com/FoldingAtHome/fah-issues/issues/1507

Thus will close this on as a duplicate 😄
