### ISSUE TITLE
exit-when-done and max-units settings don't work as expected

### ISSUE THREAD

**Issue by ouhman** [FoldingAtHome/fah-issues#1660]
Hello,

I am trying to use both settings exit-when-done set to true and max-units set to 1 but the client doesn't exit properly after the WU is complete.

Here is a screenshot of the issue. I tried to set max-units to one and manually set the flag exit-when-done to true. As seen on the screenshot the client exists but starts again.
![image](https://user-images.githubusercontent.com/39566/124507310-d5cdca80-ddcd-11eb-9437-37190fe6dae1.png)

Here is a screenshot of the configuration:
![folding-at-home-config](https://user-images.githubusercontent.com/39566/124507652-80de8400-ddce-11eb-95f5-7eaa9a6bcd2f.png)

Is there anything I can do to make that work?

Many thanks.

## Your Environment

* **F@H Software version**: 7.6.21
* **Operating System**:  Ubuntu 18.04

----
## Expected Behavior

----
## Current Behavior

----

**Comment by kbernhagen** [comment]
I believe your issue is that the client is started with a command line option like --respawn, but you want it to run on-demand only.

I'm not a linux expert, so I don't know what file you you have to tweak.

With ubuntu 18, you might start by looking at /etc/init.d/FAHClient

**Comment by ouhman** [comment]
> I believe your issue is that the client is started with a command line option like --respawn, but you want it to run on-demand only.
> 
> I'm not a linux expert, so I don't know what file you have to tweak.
> 
> With ubuntu 18, you might start by looking at /etc/init.d/FAHClient

Thank you for your reply. The client is started with the following command, there is no --respawn added to it.
`/etc/init.d/FAHClient start`

**Comment by kbernhagen** [comment]
`/etc/init.d/FAHClient` is a script which starts the client with several options.
Included would usually be --daemon, which I believe implies --respawn.

To see what it was started with, try command
`ps auxww | grep FAH`

**Comment by ouhman** [comment]
Thank you you are right. I looked at the script and it seems to be starting with a default daemon option. It doesn't look like there is a way to override this option or am I missing something?

![image](https://user-images.githubusercontent.com/39566/131298999-7a0e3a48-18ee-4d2c-b59e-e8430ec6caf2.png)

**Comment by kbernhagen** [comment]
I think you’d need to sudo edit the file to comment out the daemon line with a #

**Comment by ouhman** [comment]
Thank you
