### ISSUE TITLE
Portable Client for Windows

### ISSUE THREAD

**Issue by digitalblossom** [FoldingAtHome/fah-issues#1661]
## Is your feature request related to a problem?
No.

----
## Describe the Feature
It would be very handy if there was a portable version of the windows client, as an archive which just needs to be extracted and can be run on demand and put on a stick/portable drive.

----
## Context
 It would also simplify getting started as some users prefer not having to install.

Reference: https://portableapps.com/apps/utilities/folding-at-home-portable

The issue with the above fork/modification is that its version lacks behind

----

**Comment by anand-bhat** [comment]
The [PortableApps.com version](https://portableapps.com/apps/utilities/folding-at-home-portable) is the only official portable version of the app that I'm aware of. It has the current version of the client software (v7.6.21) (appears to have been updated on 2021-08-30)
