### ISSUE TITLE
English FAQ is in Dutch

### ISSUE THREAD

**Issue by DHSimonson** [FoldingAtHome/fah-issues#1662]
THe English language FAQ at foldingathome.org/faq/?lng=en-US is in Dutch.
![English_FAQ_In_Dutch](https://user-images.githubusercontent.com/50890892/128943889-b3515936-b25d-4c8b-b1d0-ab7988e9ef47.png)

**Comment by anand-bhat** [comment]
Appears to have been fixed when checked on 2021-12-09.
![image](https://user-images.githubusercontent.com/7332442/145322835-dc0097b8-ebe8-4fcd-ba3e-4522547fd7fc.png)
