### ISSUE TITLE
Web client "See stats" link leads to empty stats page

### ISSUE THREAD

**Issue by prehensilecode** [FoldingAtHome/fah-issues#1664]
## Your Environment

* **F@H Software version**: 7.6.21
* **Operating System**: Windows 10, macOS 10.15
* **Browser**: Chrome

----
## Expected Behavior

In the Web UI (http://client.foldingathome.org), next to the "Points earned" display in the top right, there is a link "See stats". Clicking that "See stats" link, expect to go to the user's stats page.

----
## Current Behavior

 Clicking that leads to `https://stats.foldingathome.org/_username_` which is empty. 

Going to `https://stats.foldingathome.org/donor` and searching on that username, then clicking the result, leads to `https://stats.foldingathome.org/donor/[some_digits]` which does display the user stats.

----
## Possible Solution (Optional)

Fix the web UI to link to the user numeric ID?

----
## Steps To Reproduce

1. Launch web browser.
2. Visit http://client.foldingathome.org/
3. Click the "See stats" link

----
## Context

Trying to look at the user stats page.

----

**Comment by anand-bhat** [comment]
This is being worked via https://github.com/FoldingCommunity/fah-stats-front-end/issues/65
