### ISSUE TITLE
Incorrect link to forum in Contact us page

### ISSUE THREAD

**Issue by anand-bhat** [FoldingAtHome/fah-issues#1669]
## Your Environment
* **F@H Software version**: N/A
* **Operating System**: N/A
* **Browser**: Google Chrome Version 92.0.4515.159 (Official Build) (64-bit)

----
## Expected Behavior
Link to forum should point to https://foldingforum.org/

----
## Current Behavior
Link to forum points to http://foldingathome.org/

![image](https://user-images.githubusercontent.com/7332442/131250927-9f74ada7-c96a-4cc0-9e84-90dd13eeeaee.png)

----
## Possible Solution (Optional)

----
## Steps To Reproduce
1. Open the Contact Us page -- https://foldingathome.org/contact-us/
2. Observe that the link to FoldingForum.org leads to http://foldingathome.org/

----
## Context
----

**Comment by meatball133** [comment]
Fixed
