### ISSUE TITLE
Allow for scheduling or multiple triggers

### ISSUE THREAD

**Issue by Phenix51** [FoldingAtHome/fah-issues#1683]
I would love to have the ability to schedule when I would love to have the ability to fold lightly during the day (work hours) and at medium over night.

Being able to set multiple triggers such as running lightly while I'm active on my desktop, but run at medium while the system is idle would also be great. I have noticed that my systems will not fold when I step away from my system if I have a video, say a YouTube video for example, paused on my system when I step away from the system. If I close the video and leave the other applications and browser windows open, the application will run when idle.

**Comment by jcoffland** [comment]
This is already covered in #300.  Please add to the discussion of that issue.
