### ISSUE TITLE
The web client just shows loading where earned points would be

### ISSUE THREAD

**Issue by julerobb1** [FoldingAtHome/fah-issues#1686]
Hello, the spot on the client page shows loading... where the points that i've earned so far would be. Not sure if this a bug or not. 
![image](https://user-images.githubusercontent.com/25588072/165201577-d6f643b2-bc7f-4a53-a300-dcf5892f9401.png)

I am running on windows 10 pro, build 20h2. (19042 1645)

**Comment by julerobb1** [comment]
Still having this issue, if anyone could assist me with this it would be appreciated. I've tried chrome, edge. firefox, internet explorer and opera browser all with the same issue.

**Comment by shreyashah1903** [comment]
This should be fixed by [the issue](https://github.com/FoldingCommunity/fah-stats-front-end/issues/77)
