### ISSUE TITLE
when folding@home is running, it repeatedly corrupts the creative cloud software

### ISSUE THREAD

**Issue by jmferraro** [FoldingAtHome/fah-issues#1697]
Your issue may already be reported!
Please search on the [issue tracker](./) before creating one.

## Your Environment

* **F@H Software version**: 
* **Operating System**: 
* **Browser**: 

----
## Expected Behavior

----
## Current Behavior

----
## Possible Solution (Optional)

----
## Steps To Reproduce

1.
2.
3.

----
## Context

----

**Comment by jmferraro** [comment]
I've noticed that the Creative Cloud  software is corrupt when folding@home is active.
Perhaps the CPU cycles interfere with its ability to either asses it's state or update itself

**Comment by jcoffland** [comment]
This is not something we can help with.
