### ISSUE TITLE
AMD Radeon RX 6700 XT power settings (light medium full) incorrect

### ISSUE THREAD

**Issue by SpringfieldMH** [FoldingAtHome/fah-issues#1701]
Power setting of Medium maxes out the GPU (-gpu-usage 100).
Presumably should be less than 100.
Also, not sure if bug or intentional, setting of Low discontinues the GPU (-gpu-usage 0).
Naive assumption is would be low but greater than 0.

Bug? AMD Radeon limitation? Manual workaround?

Thanks.

AMD Radeon info
GPU - AMD Radeon RX 6700 XT - Primary/Discrete
VRAM - 12272 MB - GDDR6 2000 MHz
Driver Version - 22.20.29.10-221130a-387206C-AMD-Software-Adrenalin-Edition
AMD Windows Driver Version - 31.0.12029.10015
Direct3D API Version - 12.1
Vulkan™ API Version - 1.3.217
OpenCL™ API Version - 2.0
OpenGL® API Version - 4.6
Direct3D® Driver Version - 9.14.10.01523
Vulkan™ Driver Version - 2.0.233
OpenCL® Driver Version - 31.0.12029.10015
OpenGL® Driver Version - 22.11.221102_65bb9ce
2D Driver Version - 8.1.1.1634
2D Driver File Path - /REGISTRY/MACHINE/SYSTEM/CurrentControlSet/Control/Class/{4d36e968-e325-11ce-bfc1-08002be10318}/0001
UI Version - 2022.1130.1413.1936
AMD Audio Driver Version - 10.0.1.24
Driver Provider - Advanced Micro Devices, Inc.
Windows Edition - Windows 10 Professional (64 bit)
Windows Version - 22H2

Folding log

*********************** Log Started 2023-01-30T17:35:10Z ***********************
17:35:10:******************************* libFAH ********************************
17:35:10:           Date: Oct 20 2020
17:35:10:           Time: 13:36:55
17:35:10:       Revision: 5ca109d295a6245e2a2f590b3d0085ad5e567aeb
17:35:10:         Branch: master
17:35:10:       Compiler: Visual C++ 2015
17:35:10:        Options: /TP /nologo /EHa /wd4297 /wd4103 /O2 /Zc:throwingNew /MT
17:35:10:       Platform: win32 10
17:35:10:           Bits: 32
17:35:10:           Mode: Release
17:35:10:****************************** FAHClient ******************************
17:35:10:        Version: 7.6.21
17:35:10:         Author: Joseph Coffland <joseph@cauldrondevelopment.com>
17:35:10:      Copyright: 2020 foldingathome.org
17:35:10:       Homepage: https://foldingathome.org/
17:35:10:           Date: Oct 20 2020
17:35:10:           Time: 13:41:04
17:35:10:       Revision: 6efbf0e138e22d3963e6a291f78dcb9c6422a278
17:35:10:         Branch: master
17:35:10:       Compiler: Visual C++ 2015
17:35:10:        Options: /TP /nologo /EHa /wd4297 /wd4103 /O2 /Zc:throwingNew /MT
17:35:10:       Platform: win32 10
17:35:10:           Bits: 32
17:35:10:           Mode: Release
17:35:10:         Config: C:\Users\Mike\AppData\Roaming\FAHClient\config.xml
17:35:10:******************************** CBang ********************************
17:35:10:           Date: Oct 20 2020
17:35:10:           Time: 11:36:18
17:35:10:       Revision: 7e4ce85225d7eaeb775e87c31740181ca603de60
17:35:10:         Branch: master
17:35:10:       Compiler: Visual C++ 2015
17:35:10:        Options: /TP /nologo /EHa /wd4297 /wd4103 /O2 /Zc:throwingNew /MT
17:35:10:       Platform: win32 10
17:35:10:           Bits: 32
17:35:10:           Mode: Release
17:35:10:******************************* System ********************************
17:35:10:            CPU: AMD Ryzen 7 3700X 8-Core Processor
17:35:10:         CPU ID: AuthenticAMD Family 23 Model 113 Stepping 0
17:35:10:           CPUs: 16
17:35:10:         Memory: 31.91GiB
17:35:10:    Free Memory: 19.97GiB
17:35:10:        Threads: WINDOWS_THREADS
17:35:10:     OS Version: 6.2
17:35:10:    Has Battery: false
17:35:10:     On Battery: false
17:35:10:     UTC Offset: -6
17:35:10:            PID: 15512
17:35:10:            CWD: C:\Users\Mike\AppData\Roaming\FAHClient
17:35:10:  Win32 Service: false
17:35:10:             OS: Windows 10 Enterprise
17:35:10:        OS Arch: AMD64
17:35:10:           GPUs: 1
17:35:10:          GPU 0: Bus:8 Slot:0 Func:0 AMD:6 Navi 22 XT-XL [Radeon RX
17:35:10:                 6700/6700XT/6800M]
17:35:10:           CUDA: Not detected: cuInit() returned 100
17:35:10:OpenCL Device 0: Platform:0 Device:0 Bus:8 Slot:0 Compute:1.2 Driver:3444.0
17:35:10:***********************************************************************
17:35:10:<config>
17:35:10:  
17:35:10:  <cause v='CANCER'/>
17:35:10:
17:35:10:  
17:35:10:  <proxy v=':8080'/>
17:35:10:
17:35:10:  
17:35:10:  <pause-on-battery v='false'/>
17:35:10:  <power v='LIGHT'/>
17:35:10:
17:35:10:  
17:35:10:  <slot id='1' type='GPU'>
17:35:10:    <pci-bus v='8'/>
17:35:10:    <pci-slot v='0'/>
17:35:10:  </slot>
17:35:10:</config>
17:35:10:Trying to access database...
17:35:10:Successfully acquired database lock
17:35:10:FS01:Initialized folding slot 01: gpu:8:0 Navi 22 XT-XL [Radeon RX 6700/6700XT/6800M]
17:36:08:17:127.0.0.1:New Web session
17:36:12:WU01:FS01:Starting
17:36:12:WU01:FS01:Running FahCore: "C:\Program Files (x86)\FAHClient/FAHCoreWrapper.exe" C:\Users\Mike\AppData\Roaming\FAHClient\cores/cores.foldingathome.org/win/64bit/22-0.0.20/Core_22.fah/FahCore_22.exe -dir 01 -suffix 01 -version 706 -lifeline 15512 -checkpoint 15 -opencl-platform 0 -opencl-device 0 -gpu-vendor amd -gpu 0 -gpu-usage 100
17:36:12:WU01:FS01:Started FahCore on PID 5764
17:36:12:WU01:FS01:Core PID:15776
17:36:12:WU01:FS01:FahCore 0x22 started
17:36:12:WU01:FS01:0x22:*********************** Log Started 2023-01-30T17:36:12Z ***********************
17:36:12:WU01:FS01:0x22:*************************** Core22 Folding@home Core ***************************
17:36:12:WU01:FS01:0x22:       Core: Core22
17:36:12:WU01:FS01:0x22:       Type: 0x22
17:36:12:WU01:FS01:0x22:    Version: 0.0.20
17:36:12:WU01:FS01:0x22:     Author: Joseph Coffland <joseph@cauldrondevelopment.com>
17:36:12:WU01:FS01:0x22:  Copyright: 2020 foldingathome.org
17:36:12:WU01:FS01:0x22:   Homepage: https://foldingathome.org/
17:36:12:WU01:FS01:0x22:       Date: Jan 20 2022
17:36:12:WU01:FS01:0x22:       Time: 01:15:36
17:36:12:WU01:FS01:0x22:   Revision: 3f211b8a4346514edbff34e3cb1c0e0ec951373c
17:36:12:WU01:FS01:0x22:     Branch: HEAD
17:36:12:WU01:FS01:0x22:   Compiler: Visual C++
17:36:12:WU01:FS01:0x22:    Options: /TP /nologo /EHa /wd4297 /wd4103 /O2 /Zc:throwingNew /MT
17:36:12:WU01:FS01:0x22:             -DOPENMM_VERSION="\"7.7.0\""
17:36:12:WU01:FS01:0x22:   Platform: win32 10
17:36:12:WU01:FS01:0x22:       Bits: 64
17:36:12:WU01:FS01:0x22:       Mode: Release
17:36:12:WU01:FS01:0x22:Maintainers: John Chodera <john.chodera@choderalab.org> and Peter Eastman
17:36:12:WU01:FS01:0x22:             <peastman@stanford.edu>
17:36:12:WU01:FS01:0x22:       Args: -dir 01 -suffix 01 -version 706 -lifeline 5764 -checkpoint 15
17:36:12:WU01:FS01:0x22:             -opencl-platform 0 -opencl-device 0 -gpu-vendor amd -gpu 0
17:36:12:WU01:FS01:0x22:             -gpu-usage 100
17:36:12:WU01:FS01:0x22:************************************ libFAH ************************************
17:36:12:WU01:FS01:0x22:       Date: Jan 20 2022
17:36:12:WU01:FS01:0x22:       Time: 01:14:17
17:36:12:WU01:FS01:0x22:   Revision: 9f4ad694e75c2350d4bb6b8b5b769ba27e483a2f
17:36:12:WU01:FS01:0x22:     Branch: HEAD
17:36:12:WU01:FS01:0x22:   Compiler: Visual C++
17:36:12:WU01:FS01:0x22:    Options: /TP /nologo /EHa /wd4297 /wd4103 /O2 /Zc:throwingNew /MT
17:36:12:WU01:FS01:0x22:   Platform: win32 10
17:36:12:WU01:FS01:0x22:       Bits: 64
17:36:12:WU01:FS01:0x22:       Mode: Release
17:36:12:WU01:FS01:0x22:************************************ CBang *************************************
17:36:12:WU01:FS01:0x22:       Date: Jan 20 2022
17:36:12:WU01:FS01:0x22:       Time: 01:13:20
17:36:12:WU01:FS01:0x22:   Revision: ab023d155b446906d55b0f6c9a1eedeea04f7a1a
17:36:12:WU01:FS01:0x22:     Branch: HEAD
17:36:12:WU01:FS01:0x22:   Compiler: Visual C++
17:36:12:WU01:FS01:0x22:    Options: /TP /nologo /EHa /wd4297 /wd4103 /O2 /Zc:throwingNew /MT
17:36:12:WU01:FS01:0x22:   Platform: win32 10
17:36:12:WU01:FS01:0x22:       Bits: 64
17:36:12:WU01:FS01:0x22:       Mode: Release
17:36:12:WU01:FS01:0x22:************************************ System ************************************
17:36:12:WU01:FS01:0x22:        CPU: AMD Ryzen 7 3700X 8-Core Processor
17:36:12:WU01:FS01:0x22:     CPU ID: AuthenticAMD Family 23 Model 113 Stepping 0
17:36:12:WU01:FS01:0x22:       CPUs: 16
17:36:12:WU01:FS01:0x22:     Memory: 31.91GiB
17:36:12:WU01:FS01:0x22:Free Memory: 19.48GiB
17:36:12:WU01:FS01:0x22:    Threads: WINDOWS_THREADS
17:36:12:WU01:FS01:0x22: OS Version: 6.2
17:36:12:WU01:FS01:0x22:Has Battery: false
17:36:12:WU01:FS01:0x22: On Battery: false
17:36:12:WU01:FS01:0x22: UTC Offset: -6
17:36:12:WU01:FS01:0x22:        PID: 15776
17:36:12:WU01:FS01:0x22:        CWD: C:\Users\Mike\AppData\Roaming\FAHClient\work
17:36:12:WU01:FS01:0x22:************************************ OpenMM ************************************
17:36:12:WU01:FS01:0x22:    Version: 7.7.0
17:36:12:WU01:FS01:0x22:********************************************************************************
17:36:12:WU01:FS01:0x22:Project: 18448 (Run 8, Clone 116, Gen 127)
17:36:12:WU01:FS01:0x22:Digital signatures verified
17:36:12:WU01:FS01:0x22:Folding@home GPU Core22 Folding@home Core
17:36:12:WU01:FS01:0x22:Version 0.0.20
17:36:12:WU01:FS01:0x22:  Checkpoint write interval: 50000 steps (2%) [50 total]
17:36:12:WU01:FS01:0x22:  JSON viewer frame write interval: 25000 steps (1%) [100 total]
17:36:12:WU01:FS01:0x22:  XTC frame write interval: 2500000 steps (1e+02%) [1 total]
17:36:12:WU01:FS01:0x22:  Global context and integrator variables write interval: disabled
17:36:12:WU01:FS01:0x22:There are 3 platforms available.
17:36:12:WU01:FS01:0x22:Platform 0: Reference
17:36:12:WU01:FS01:0x22:Platform 1: CPU
17:36:12:WU01:FS01:0x22:Platform 2: OpenCL
17:36:12:WU01:FS01:0x22:  opencl-device 0 specified
17:36:20:WU01:FS01:0x22:Attempting to create OpenCL context:
17:36:20:WU01:FS01:0x22:  Configuring platform OpenCL
17:36:28:WU01:FS01:0x22:  Using OpenCL on platformId 0 and gpu 0
17:36:28:WU01:FS01:0x22:Completed 200000 out of 2500000 steps (8%)
17:37:09:47:127.0.0.1:New Web session
17:37:12:Removing old file 'configs/config-20230128-085911.xml'
17:37:12:Saving configuration to config.xml
17:37:12:<config>
17:37:12:  
17:37:12:  <cause v='CANCER'/>
17:37:12:
17:37:12:  
17:37:12:  <proxy v=':8080'/>
17:37:12:
17:37:12:  
17:37:12:  <pause-on-battery v='false'/>
17:37:12:  <power v='MEDIUM'/>
17:37:12:
17:37:12:  
17:37:12:  <slot id='1' type='GPU'>
17:37:12:    <pci-bus v='8'/>
17:37:12:    <pci-slot v='0'/>
17:37:12:  </slot>
17:37:12:</config>
17:37:13:FS01:Shutting core down
17:37:13:WU01:FS01:0x22:WARNING:Console control signal 1 on PID 15776
17:37:13:WU01:FS01:0x22:Exiting, please wait. . .
17:37:13:WU01:FS01:0x22:Folding@home Core Shutdown: INTERRUPTED
17:37:13:WU01:FS01:FahCore returned: INTERRUPTED (102 = 0x66)

**Comment by joe-h-fah** [comment]
Not a bug, but a setting (-gpu-usage 100) left over from an older GPU folding core that tested setting power levels through the client.  It failed to work well.  Current folding cores do not have support for this setting, I am surprised it had any effect.

The slider setting is not for setting the amount of utilization of a GPU.  Light by default pauses GPU folding, but otherwise it mostly effects the number of CPU threads used.  Light uses half the available threads, Medium all but one, Full uses all.

To set GPU power usage you need to use some utility to set power limits while F@h is running.

**Comment by SpringfieldMH** [comment]
Seemed to work with previous Nvidia Geforce RT 1660 TI.
Perhaps Radeon vs. Geforce difference...
I will see if I can use Radeon utility to throttle.
Thanks.

**Comment by joe-h-fah** [comment]
Possibly different code paths available in the drivers.  But by not working well, when tested years ago this option just cycled the GPU on and off, going between 0 and 100% utilization.  This power cycling was not considered desirable by users as it thermally stressed GPU components.
