### ISSUE TITLE
Web Control page not showing accumulated points

### ISSUE THREAD

**Issue by pcar75** [FoldingAtHome/fah-issues#1713]
Your issue may already be reported!
Please search on the [issue tracker](./) before creating one.

## Your Environment

* **PC tower, i7-6700 @ 3.40 GHz, 16GB RAM, Windows SSD 256GB, Ubuntu SSD 256GB, HW 1TB,**: 
* **FAHClient 7.6.21**: 
* **Windows 10, regularly auto-updated**: 
* **Firefox 117.0.1**: 

----
## Expected Behavior

Web Control page should display total accumulated points when linked to internet

----
## Current Behavior

Since beginning of week (2023-09-11) Web Control page does not display total accumulated points , only caption "Loading ..."
Other elements in page are OK

----
## Possible Solution (Optional)

----
## Steps To Reproduce

1.
2.
3.

----
## Context

No changes have happened this week to my computer except for some Windows automated update and a few reboot (i.e. dual boot pc). FAH runs only in Windows.
This is not a big problem as long as the main processing occurs and the results are handled properly but I'd rather know how to resolve the problem (yours or mine ?) than add another software to bypass the problem (e.g. HFM utility, ref.: https://foldingforum.org/viewtopic.php?t=39617&hilit=not+showing+points ).
I have not found in the FAHControl app my accumulated points either (should be ± 50 G ).  My ID is pcar20201107.
Thanks for any info.

----

**Comment by jcoffland** [comment]
Should be fixed now.

**Comment by pcar75** [comment]
It is.  Thanks.

________________________________
