### ISSUE TITLE
Malware alert (false positive)

### ISSUE THREAD

**Issue by wright-david** [FoldingAtHome/fah-issues#1714]
## Environment
* **F@H Software version**:  7.6.21
* **Operating System**:  Windows 11
* **Browser**:  n/a full client

----
## Current Behavior
Started new folding session and the download triggered Bitdefender malware alert (see attached image)

----
## Context
Unable to run folding session

----

<img width="274" alt="image" src="https://github.com/FoldingAtHome/fah-issues/assets/14233575/8bd47ad7-53e6-4bf0-b26e-ee52a940471b">

Is this a false positive?

**Comment by joe-h-fah** [comment]
Yes, this is a false positive.  Generally we recommend excluding downloads by the FAHClient process and the data directory from scanning.  The files may contain binary information that happens to match some signature being looked for.
