### ISSUE TITLE
Typo in GPU disabled help link

### ISSUE THREAD

**Issue by askiiart** [FoldingAtHome/fah-issues#1717]
## Your Environment

* Irrelevant

----
## Expected Behavior

The help link on [client.foldingathome.org](https://client.foldingathome.org) for when the GPU is disabled should point to [https://foldingforum.org/](https://foldingforum.org/).

----
## Current Behavior

The help link on [client.foldingathome.org](https://client.foldingathome.org) for when the GPU is disabled points to [https:://foldingforum.org/](https:://foldingforum.org/). **Note the double colons.**`

----
## Possible Solution (Optional)

Just fix the typo in [client.foldingathome.org](https://client.foldingathome.org)

----
## Steps To Reproduce

1. Run FAHClient without CUDA/OpenCL installed
2. Go to client.foldingathome.org
3. Go to GPU tab.

----
## Context

Irrelevant.

----

**Comment by jcoffland** [comment]
This is a duplicate of #1584.  It was fixed in the source code but a new release of the v7 client is not planned.  Development efforts are focusing on the new v8.x.x client release.

**Comment by askiiart** [comment]
> This is a duplicate of #1584. It was fixed in the source code but a new release of the v7 client is not planned. Development efforts are focusing on the new v8.x.x client release.

Ah, sorry about that, I wasn't able to find #1584 . Thanks!
