### ISSUE TITLE
[API] Team with special characters can't be retrieved

### ISSUE THREAD

**Issue by blakegearin** [FoldingAtHome/fah-issues#1722]
Hi, I've found [a team](https://stats.foldingathome.org/team/182116) with special characters in their name that doesn't appear to be retrievable via the stats API.

----
## Expected Behavior

[This team](https://stats.foldingathome.org/team/182116) can be fetched from the API.

----
## Current Behavior

The team cannot be fetched from the API.

----
## Possible Solution (Optional)

I've tested a number of other teams to try and isolate this issue, but have come up short. I'm able to successfully fetch team names with the similar characters, which are listed below.

Ampersand and spaces 
- ID: [241449](https://stats.foldingathome.org/team/241449), Name: `Tim & The Boys`
- ID: [35947](https://stats.foldingathome.org/team/35947), Name: `Custom PC & bit-tech`

Comma and spaces
- ID: [86926](https://stats.foldingathome.org/team/86926), Name: `Rutgers, The State University of New Jersey`

Hyphen and spaces
- ID: [225605](https://stats.foldingathome.org/team/225605), Name: `PC Master Race - PCMR`

----
## Steps To Reproduce

Search for `Atheists, Skeptics, & Humanists - ASH Folding` on https://stats.foldingathome.org/team 

Or make a similar `curl`

```bash
curl -G https://api.foldingathome.org/team/find -d name="Atheists%2C%20Skeptics%2C%20%26%20Humanists%20-%20ASH%20Folding"

curl -G https://api.foldingathome.org/team -d q="Atheists%2C%20Skeptics%2C%20%26%20Humanists%20-%20ASH%20Folding"
```

----
## Context

I'm making a Ruby client and happened to discover this during testing.

----

**Comment by anand-bhat** [comment]
Inspecting the response from https://api2.foldingathome.org/team/182116 reveals two consecutive spaces, before and after the hyphen.
![image](https://github.com/FoldingAtHome/fah-issues/assets/7332442/bb8a890e-7cb4-456e-9f73-9276eb226b08)

Using this as the search string works when looking up the team by name.
![image](https://github.com/FoldingAtHome/fah-issues/assets/7332442/031eaad1-74d0-4a01-9dc0-8a3527d2da68)

Search API call - https://api2.foldingathome.org/team/find?name=Atheists%2C%20Skeptics%2C%20%26%20Humanists%20%20-%20%20ASH%20Folding
![image](https://github.com/FoldingAtHome/fah-issues/assets/7332442/e20da483-48e6-4cec-a2bf-65b96a9cac62)

**Comment by jcoffland** [comment]
As @anand-bhat pointed out this looks to be working correctly, you just need to match the exact number of spaces.
