### ISSUE TITLE
On Idle not very accurate

### ISSUE THREAD

**Issue by theking2** [FoldingAtHome/fah-issues#1726]
Your issue may already be reported!
Please search on the [issue tracker](./) before creating one.

## Your Environment

* 7.6.21
* Windows 10
* LibreWolfe
* i9-13900 13th 

----
## Expected Behavior
Low CPU usage causes initiating calculating

----
## Current Behavior
With CPU under 3% fah never starts computing

----
## Possible Solution (Optional)

----
## Steps To Reproduce

1.install fah
2.set to on idle
3.wait

----
## Context

----

**Comment by jcoffland** [comment]
That's not how the feature is supposed to work.  The client starts to fold when you've not moved the mouse or touched the keyboard for a long enough period.

**Comment by theking2** [comment]
Ok. Then the feature doesn't work. My wireless keyboard with integrated mouse was turned of but still FaH doesn't continue
