### ISSUE TITLE
Display default Protein in FAHViewer when no other data is available

### ISSUE THREAD

**Issue by jcoffland** [FoldingAtHome/fah-issues#377]
| Trac | Data |
| --: | :-- |
| Ticket | 377 |
| Reported by | @PantherX |
| Status | closed |
| Component | FAHViewer |
| Priority | 7 (minor) |
| Milestone | v7.1.8 |
| Version | 7.1 |

How about including these two status messages to make it more user friendly:

1) "Please wait while snapshot is being generated." -> The reason is that it can take up-to 2 minutes (maybe longer) to generate the snapshot and the Donor may think that it isn't working or is broken, etc.

2) "Snapshot can't be generated as the FahCore being used isn't supported." -> I had to wait a full 5 minutes before I realized that the snapshots won't be generated. If you can display this, the donor will understand and will simply close it.

**Comment by bb30994** [comment]
The message in the lower left corner gives the name as
**Protein: Demo**
