### ISSUE TITLE
Add button to open log in an external editor

### ISSUE THREAD

**Issue by jcoffland** [FoldingAtHome/fah-issues#687]
| Trac | Data |
| --: | :-- |
| Ticket | 687 |
| Reported by | @bb30994 |
| Status | accepted |
| Component | FAHClient |
| Priority | 6 |

The log window in FAHControl is difficult to use.  It lacks the capability to manually search for strings and it can be difficult to use, as evidenced by this comment:

> When trying to review the log in FAH control on a system with 2 GPU's and Bigadv, I find it nearly impossible to browse the log's contents. Every time one of the three clients commits a new entry to the log, the log screen jumps down to the last line entered, so every 20-40 seconds no matter where I am in the log, it jumps back down to the bottom and I lose my place.

One solution to this problem is to start an external utility to view a copy of the current log.  (That will solve this issue because no updates will be seen.  Instead, the standard features of the external viewer will be available to the Donor.)  For example, in windows, open Notepad by default, but provide an editable field to specify what program to use.

The alternative is to provide a satisfactory set of viewer tools expected on each independent platform.

**Comment by bb30994** [comment]
I renew my request for an external log viewer equivalent to the one in FAHControl.  I just spent over an hour searching for significant events in a complex log (3 slots, several uploads/downloads, several failed uploads/downloads, etc.  I dare anybody to attempt it without the benefits of the filters provided in FAHControl.  

**Log:** https://foldingforum.org/viewtopic.php?f=108&t=34988&p=331817#p331487
**Analysis:** https://foldingforum.org/viewtopic.php?f=108&t=34988&p=331817#p331813

I'll bet the log viewer could be extracted, prefixed by a simple file opening routine, and published as a stand-alone program in less time than I spend manually searching the log.

**Comment by bb30994** [comment]
> Trac	Data
> Ticket	687
> Reported by	@bb30994
> Status	accepted
> Component	FAHClient
> Priority	6
> The log window in FAHControl is difficult to use. It lacks the capability to manually search for strings and it can be difficult to use, as evidenced by this comment:
> 
> > When trying to review the log in FAH control on a system with 2 GPU's and Bigadv, I find it nearly impossible to browse the log's contents. Every time one of the three clients commits a new entry to the log, the log screen jumps down to the last line entered, so every 20-40 seconds no matter where I am in the log, it jumps back down to the bottom and I lose my place.
> 
> One solution to this problem is to start an external utility to view a copy of the current log. (That will solve this issue because no updates will be seen. Instead, the standard features of the external viewer will be available to the Donor.) For example, in windows, open Notepad by default, but provide an editable field to specify what program to use.
> 
> The alternative is to provide a satisfactory set of viewer tools expected on each independent platform.

**Comment by bb30994** [comment]
I can't change the title, but scratch the "button" portion and publish the existing viewer as a stand-lone log viewer.  In other words, merge this enhancement with #1272

**Comment by shorttack** [comment]
> merge this enhancement #687 with #1272
Result is ssue #1448

**Comment by shorttack** [comment]
Closed: merged with #1272 to create #1448
