### ISSUE TITLE
Changing gpu-index in FAHControl does not cause the client to reload the GPU info

### ISSUE THREAD

**Issue by jcoffland** [FoldingAtHome/fah-issues#706]
| Trac | Data |
| --: | :-- |
| Ticket | 706 |
| Reported by | @jcoffland |
| Status | closed |
| Component | FAHClient |
| Priority | 4 |

A change in gpu-index should cause the client reload the GPU system info.

**Comment by informatorius** [comment]
I see the same issue in FahControl 7.5.1 on Windows 7. When changing the gpu slots gpu index then the value is not used. After closing FahClient and restart FahClient the new gpu index is used.
