### ISSUE TITLE
slot and queue highlights can get out of sync

### ISSUE THREAD

**Issue by jcoffland** [FoldingAtHome/fah-issues#844]
| Trac | Data |
| --: | :-- |
| Ticket | 844 |
| Reported by | @jcoffland |
| Status | accepted |
| Component | FAHControl |
| Priority | 8 |

Just a very minor FahControl display problem, for the record.

I have two slots (SMP and GPU) on one PC. When I highlight one of the queue entries, the relevant slot is highlighted (not particularly well, but that is not the point here).
I found that the two were out of sync (wrong slot highlighted), which was confusing when checking PPD -- sorry no screenshot.
I think it happened because the highlighted queue entry had completed and been cleared, so the queue entry highlight transferred to the next entry, which was associated with the other slot. However the slot highlight was not updated. Re-selecting the queue entry moved the slot highlight.

I will try to check what happens if the slot is selected when a unit completes.

David

**Comment by informatorius** [comment]
Same as solved issue https://github.com/FoldingAtHome/fah-issues/issues/1181. Can be closed.
