### ISSUE TITLE
Theme selection isn't restored

### ISSUE THREAD

**Issue by jcoffland** [FoldingAtHome/fah-issues#902]
| Trac | Data |
| --: | :-- |
| Ticket | 902 |
| Reported by | @PantherX |
| Status | accepted |
| Component | FAHControl |
| Priority | 7 (minor) |

If I select a theme but hit cancel, the next time i open the preferences window, the "canceled" theme is displayed instead of the current one.

**Comment by informatorius** [comment]
Tried on Windows 7 with latest FahControl build with Glade Gtk+2 and issue is not reproducable.
