### ISSUE TITLE
Detect OS idle in addition to using screensaver signal

### ISSUE THREAD

**Issue by jcoffland** [FoldingAtHome/fah-issues#945]
| Trac | Data |
| --: | :-- |
| Ticket | 945 |
| Reported by | @kbernhagen |
| Status | closed |
| Component | FAHClient |
| Priority | 5 |
| Milestone | v7.2.14 |

For all platforms, optionally detect idle or low load system state, and use that as another pause/unpause criteria.

Would be helpful if disable system sleep were implemented. See ticket #822

This is explicitly different than screensaver and display off modes.

**Comment by dcorking** [comment]
Can you link the code that implements this on Linux please? My Ubuntu system has not folded for 2 weeks, since I set it to 'only when idle', even at night with both users logged out and the screen idle. Possibly something has changed in Ubuntu that stopped this code working.
